<a href="https://colab.research.google.com/github/stephanie465337/Data-Science-Portfolio-C21/blob/main/NotebookLM/Module%205/2b_Text_Representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%%capture output
#Install Wikipedia API
!pip3 install wikipedia-api

In [ ]:
import numpy as np
import pandas as pd
from textblob import TextBlob
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

pd.options.display.max_columns = 100

import nltk
# nltk.download('omw-1.4')
nltk.download('punkt_tab')
# nltk.download('averaged_perceptron_tagger_eng')

import wikipediaapi

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [ ]:
%%capture
!python -m textblob.download_corpora

In [ ]:
sentence_1 = 'Jen is a good student.'
sentence_2 = 'Jen is also a great guitarist.'
sentence_3 = 'Good students can sometimes be good guitarists'

# Data Cleaning
We want to singularize guitarists and students.

In [ ]:
sentence_3_tb = TextBlob(sentence_3) # Make a textblob so that we can singularize the word
sentence_3_singular = [x.singularize() for x in sentence_3_tb.words] # Singularize each word in the text
sentence_3_clean = ' '.join(sentence_3_singular) # Join it together into a single string
sentence_3_clean

'Good student can sometime be good guitarist'

## Bag of Words Using CountVectorizer

In [ ]:
#Perform the count transformation
vectorizer = CountVectorizer(stop_words='english')
bow_vec = vectorizer.fit_transform([sentence_1, sentence_2, sentence_3_clean])
bow_vec

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 9 stored elements and shape (3, 5)>

In [ ]:
bow_vec.toarray()

array([[1, 0, 0, 1, 1],
       [0, 1, 1, 1, 0],
       [2, 0, 1, 0, 1]])

In [ ]:
#Print out results in a data frame
sent_df = pd.DataFrame(bow_vec.toarray(), columns = vectorizer.get_feature_names_out())
sent_df

   good  great  guitarist  jen  student
0     1      0          0    1        1
1     0      1          1    1        0
2     2      0          1    0        1

In [ ]:
[sentence_1, sentence_2, sentence_3_clean]

['Jen is a good student.',
 'Jen is also a great guitarist.',
 'Good student can sometime be good guitarist']

### Your Turn
1. Write 4 sentences of your choice.
2. Run the `CountVectorizer` on your sentences.
3. Print the results in a data frame.

In [ ]:
# Solution 1

In [ ]:
# Solution 2

In [ ]:
# Solution 3

## TF-IDF

In [ ]:
#Perform the TF-IDF transformation - Option 1 (TfidfVectorizer)
tf_idf_vec = TfidfVectorizer(stop_words = 'english')
tf_idf_jen = tf_idf_vec.fit_transform([sentence_1, sentence_2, sentence_3_clean])
tf_idf_jen

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 9 stored elements and shape (3, 5)>

In [ ]:
print(sentence_1)
print(sentence_2)
print(sentence_3_clean)

Jen is a good student.
Jen is also a great guitarist.
Good student can sometime be good guitarist

In [ ]:
#Print out results in a dataframe
tf_df = pd.DataFrame(tf_idf_jen.toarray(), columns = tf_idf_vec.get_feature_names_out())
tf_df.shape

(3, 5)

In [ ]:
tf_df

       good     great  guitarist       jen   student
0  0.577350  0.000000   0.000000  0.577350  0.577350
1  0.000000  0.680919   0.517856  0.517856  0.000000
2  0.816497  0.000000   0.408248  0.000000  0.408248

In [ ]:
#Perform the TF-IDF transformation - Option 2 (CountVectorizer + TfidfTransformer - better for large datasets)
tf_idf_tran = TfidfTransformer()
tf_idf_jen = tf_idf_tran.fit_transform(bow_vec)
tf_idf_jen

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 9 stored elements and shape (3, 5)>

In [ ]:
#Print out results in a dataframe
tf_df = pd.DataFrame(tf_idf_jen.toarray(), columns = vectorizer.get_feature_names_out())
tf_df

       good     great  guitarist       jen   student
0  0.577350  0.000000   0.000000  0.577350  0.577350
1  0.000000  0.680919   0.517856  0.517856  0.000000
2  0.816497  0.000000   0.408248  0.000000  0.408248

In [ ]:
#Get a data frame with the TF-IDF values sorted for document 0
df = pd.DataFrame(tf_idf_jen[0].T.todense(), index=tf_idf_vec.get_feature_names_out(), columns=["TF-IDF"])
df = df.sort_values('TF-IDF', ascending=False)
df

            TF-IDF
good       0.57735
student    0.57735
jen        0.57735
guitarist  0.00000
great      0.00000

In [ ]:
tf_df.transpose()[0].sort_values(ascending = False)

good         0.57735
student      0.57735
jen          0.57735
guitarist    0.00000
great        0.00000
Name: 0, dtype: float64

### Your Turn
1. Use the `TfidfTransformer` to transform the bag of words matrix you created above to TF-IDF.
2. Print out the results in a data frame.

These settings might be helpful.

```python
np.set_printoptions(linewidth=200)
np.set_printoptions(precision=6, formatter={'all': lambda x: f'{x:.4f}'})
my_bow_vec.toarray()
```

In [ ]:
# Solution 1

In [ ]:
# Solution 2

# Another Example - Using Wikipedia API

In [ ]:
#Pull out the popcorn page from wikipedia - https://en.wikipedia.org/wiki/Popcorn
topic = 'popcorn'
wikip = wikipediaapi.Wikipedia(user_agent = 'foobar')
page_ex = wikip.page(topic)
wiki_text = page_ex.text
wiki_text

'Popcorn (also called popped corn, popcorns, or pop-corn) is a variety of corn kernel which expands and puffs up when heated. The term also refers to the snack food produced by the expansion. It is one of the oldest snacks, with evidence of popcorn dating back thousands of years in the Americas. It is commonly eaten salted, buttered, sweetened, or with artificial flavorings.\nA popcorn kernel\'s strong hull contains the seed\'s hard, starchy shell endosperm with 14–20% moisture, which turns to steam as the kernel is heated. Pressure from the steam continues to build until the hull ruptures, allowing the kernel to forcefully expand, to 20 to 50 times its original size, and then cool.\nSome strains of corn (taxonomized as Zea mays) are cultivated specifically as popping corns. The Zea mays variety everta, a special kind of flint corn, is the most common of these. Popcorn is one of six major types of corn, alongside dent corn, flint corn, pod corn, flour corn, and sweet corn.\n\nHistory\nCorn was domesticated about 9,000  years ago, in what is now the Balsas River Valley of Central Mexico. Archaeologists discovered that people have known about popcorn for millennia. Fossil evidence from Peru suggests that corn was present there as early as 4,700 BCE, and popped there over 1,000 years ago. Between 2007 and 2011, evidence as early as 4,700 BCE for popping corn was discovered as macrofossil cobs at the Paredones and Huaca Prieta archaeological sites on the northern coast of Peru. Corn cultivation was present in Amazon basin  farming practices as evidenced by cultivation of corn in the Amazon basin 6,000 years ago \nIn 1948 and 1950, evidence as early as 3600 BCE for popping corn as ears of popcorn were discovered by Harvard anthropology graduate student Herbert W. Dick and Harvard botany graduate student Claude Earle Smith, Junior (1922–1987), in a complex of rock shelters, dubbed the "Bat Cave", in Catron County, west-central New Mexico, and attributed to the Ancestral Puebloan peoples, who maintained trade networks with peoples in tropical Mexico.\nThrough the 19th century, popping of the kernels was achieved by hand, on stove tops over flame. Kernels were sold on the East Coast of the United States under names such as Pearls or Nonpareil. The term popped corn first appeared in John Russell Bartlett\'s 1848 Dictionary of Americanisms. Popcorn is an ingredient in Cracker Jack and, in the early years of the product, it was popped by hand.\n\nPopcorn\'s accessibility increased rapidly in the 1890s with Charles Cretors\' invention of the popcorn maker. Cretors, a Chicago candy store owner, had created a number of steam-powered machines for roasting nuts and applied the technology to the corn kernels.\n\nBy the turn of the century, Cretors had created and deployed street carts equipped with steam-powered popcorn makers. During the Great Depression, popcorn was fairly inexpensive at 5–10 cents a bag and became popular. Thus, while other businesses failed, the popcorn business thrived and became a source of income for many struggling farmers and entrepreneurs, including the Redenbacher family, namesake of the Orville Redenbacher\'s popcorn brand. During World War II, sugar rations diminished candy production, and Americans compensated by eating three times as much popcorn as they had before. The snack was popular at theaters, much to the initial displeasure of many of the theater owners, who thought it distracted from the films. Their minds eventually changed, however, and in 1938 a Midwestern theater owner named Glen W. Dickinson Sr. installed popcorn machines in the lobbies of his Dickinson theaters. Popcorn was more profitable than theater tickets, and at the suggestion of his production consultant, R. Ray Aden, Dickinson purchased popcorn farms and was able to keep ticket prices down. The venture was a success, and popcorn soon spread. The rise of television in the 1940s brought lower popcorn consumption as theater attendance fell. The Popcorn Institute, a trade association of popcorn processors, promoted popcorn consumption at home, bringing it back to previous levels.\n In 1970, Orville Redenbacher\'s namesake brand of popcorn was launched. In 1981, General Mills received the first patent for a microwave oven popcorn bag; popcorn consumption saw an increase.\nAt least six localities (all in the Midwestern United States) claim to be the "Popcorn Capital of the World;": Ridgway, Illinois; Valparaiso, Indiana; Van Buren, Indiana; Schaller, Iowa; Marion, Ohio;  and North Loup, Nebraska.  According to the USDA, specific corn for popcorn is grown mostly in Nebraska and Indiana, and increasingly in Texas. As the result of an elementary school project, popcorn became the official state snack food of Illinois.\n\nPopping mechanism\nEach kernel of popcorn contains moisture and oil. Unlike most other grains, the outer hull of the popcorn kernel is strong and impervious to moisture, and the starch inside consists almost entirely of a hard type.\n\nAs the oil and water in the kernel are heated, they turn into steam. Under these conditions, the starch inside the kernel gelatinizes and softens. The steam pressure increases until the breaking point of the hull is reached: a pressure of approximately 930 kPa (135 psi) and a temperature of 180 °C (356 °F). The hull ruptures, causing a sudden drop in pressure inside the kernel and a corresponding rapid expansion of the steam, which expands the starch and proteins of the endosperm into an airy foam. As the foam rapidly cools, the starch and protein polymers set into the familiar crispy puff.\nSpecial varieties are grown to improve popping yield. Though the kernels of some other types will pop, the cultivated strain for popcorn is Zea mays everta, which is a variety of flint corn.\n\nCooking methods\nPopcorn can be cooked with butter or oil. Although small quantities can be popped in a stove-top kettle or pot in a home kitchen, commercial sale employs specially designed popcorn machines, which were invented in Chicago, Illinois, by Charles Cretors in 1885. Cretors introduced his invention at the Columbian Exposition in 1893. At that fair, F.\u200dW.\u2009Rueckheim introduced a molasses-flavored "Candied Popcorn", the first caramel corn; his brother, Louis Ruekheim, slightly altered the recipe and introduced it as Cracker Jack in 1896.\n\nCretors\'s invention was the first patented steam-driven machine that popped corn in oil. Previously, vendors popped corn by holding a wire basket over an open flame. At best, the result was hot, dry, and unevenly cooked. Cretors\'s machine popped corn in a mixture of one-third clarified butter, two-thirds lard, and salt. This mixture can withstand the 232 °C (450 °F) temperature needed to pop corn and produces little smoke. A fire under a boiler created steam that drove a small engine to drive gears, shaft, and the agitator that stirred the corn, and also powered a small puppet, "The Toasty Roasty Man", an attention-getting amusement to attract business. A wire connected to the top of the cooking pan allowed the operator to disengage the drive mechanism, lift the cover, and dump popped corn into the storage bin beneath. Exhaust from the steam engine was piped to a pan below the corn storage bin and kept freshly popped corn warm. Excess steam was also used to operate a small, shrill whistle to attract attention.\nA different method of popcorn-making involves the "popcorn hammer", a large cast-iron canister that is sealed with a heavy lid and slowly turned over a fire in rotisserie fashion.\n\nExpansion and yield\nPopping results are sensitive to the rate at which the kernels are heated. If heated too quickly, the steam in the outer layers of the kernel can reach high pressures and rupture the hull before the starch in the center of the kernel can fully gelatinize, leading to partially popped kernels with hard centers. Heating too slowly leads to entirely unpopped kernels: the tip of the kernel, where it attached to the cob, is not entirely moisture-proof, and when heated slowly, the steam can leak out of the tip fast enough to keep the pressure from rising sufficiently to break the hull and cause the pop.\nProducers and sellers of popcorn consider two major factors in evaluating the quality of popcorn: what percentage of the kernels will pop, and how much each popped kernel expands. Expansion is an important factor to both the consumer and vendor. For the consumer, larger pieces of popcorn tend to be more tender and are associated with higher quality. For the grower, distributor and vendor, expansion is closely correlated with profit: vendors such as theaters buy popcorn by weight and sell it by volume. For these reasons, higher-expansion popcorn fetches a higher profit per unit weight.\nPopcorn will pop when freshly harvested, but not well; its high moisture content leads to poor expansion and chewy pieces of popcorn. Kernels with a high moisture content are also susceptible to mold when stored. For these reasons, popcorn growers and distributors dry the kernels until they reach the moisture level at which they expand the most. This differs by variety and conditions, but is generally in the range of 14–15% moisture by weight. If the kernels are over-dried, the expansion rate will suffer and the percentage of kernels that pop will decline.  Old popcorn tends to dry out, lowering the yield.\nWhen the popcorn has finished popping, sometimes unpopped kernels remain. Known in the popcorn industry as "old maids", these kernels fail to pop because they do not have enough moisture to create enough steam for an explosion. Re-hydrating prior to popping usually results in eliminating the unpopped kernels.\nPopcorn varieties are broadly categorized by the shape of the kernels, the color of the kernels, or the shape of the popped corn. While the kernels may come in a variety of colors, the popped corn is always off-yellow or white as it is only the hull (or pericarp) that is colored. "Rice" type popcorn have a long kernel pointed at both ends; "pearl" type kernels are rounded at the top. Commercial popcorn production has moved mostly to pearl types. Historically, pearl popcorn were usually yellow and rice popcorn usually white. Today both shapes are available in both colors, as well as others including black, red, mauve,  purple, and variegated. Mauve and purple popcorn usually have smaller and nutty kernels. Commercial production is dominated by white and yellow.\n\nTerminology\nIn the popcorn industry, a popped kernel of corn is known as a "flake". Two shapes of flakes are commercially important. "Butterfly" (or "snowflake") flakes are irregular in shape and have a number of protruding "wings". "Mushroom" flakes are largely ball-shaped, with few wings. Butterfly flakes are regarded as having better mouthfeel, with greater tenderness and less noticeable hulls. Mushroom flakes are less fragile than butterfly flakes and are therefore often used for packaged popcorn or confectionery, such as caramel corn. The kernels from a single cob of popcorn may form both butterfly and mushroom flakes; hybrids that produce 100% butterfly flakes or 100% mushroom flakes exist, the latter developed only as recently as 1998.\n\nConsumption\nPopcorn is a popular snack food at sporting events and in movie theaters, where it has been served since the 1930s. Cinemas have come under fire due to their high markup on popcorn; Stuart Hanson, a film historian at De Montfort University in Leicester, once said, "One of the great jokes in the industry is that popcorn is second only to cocaine or heroin in terms of profit."\nTraditions differ as to whether popcorn is consumed as a hearty snack food with salt (predominating in the United States) or as a sweet snack food with caramelized sugar (predominating in Germany).\nPopcorn customs around savory, salty, and sweet flavors vary by region and demographic, but in the U.S., preferences are diverse and evolving:\n\nPopcorn smell has an unusually attractive quality for human beings. This is largely because it contains high levels of the chemicals 6-acetyl-2,3,4,5-tetrahydropyridine and 2-acetyl-1-pyrroline, very powerful aroma compounds that are also used by food and other industries either to make products that smell like popcorn, bread, or other foods containing the compound in nature, or for other purposes.\n\nPopcorn as a breakfast cereal was consumed by Americans in the 1800s and generally consisted of popcorn with milk and a sweetener.\n\nPopcorn balls (popped kernels stuck together with a sugary "glue") were hugely popular around the turn of the 20th century, but their popularity has since waned.  Popcorn balls are still served in some places as a traditional Halloween treat.\nCracker Jack is a popular, commercially produced candy that consists of peanuts mixed in with caramel-covered popcorn. Kettle corn is a variation of normal popcorn, cooked with white sugar and salt, traditionally in a large copper kettle.  Once reserved for specialty shops and county fairs, kettle corn has recently become popular, especially in the microwave popcorn market.  The popcorn maker is a relatively new home appliance, and its popularity is increasing because it offers the opportunity to add flavors of the consumer\'s own choice and to choose healthy-eating popcorn styles.\nPopped sorghum is popular as a snack in India. The popped sorghum is similar to popcorn, but the puffs are smaller. Recipes for popping sorghum by microwave, in a pot, etc., are readily available online.\n\nNutritional value\nAir-popped popcorn (no salt or other additives) is 4% water, 78% carbohydrates (including 15% dietary fiber), 12% protein, and 4% fat (table). In a 100 gram reference amount, popcorn provides 382 calories and is a rich source (20% or more of the Daily Value, DV) of riboflavin (25% DV) and several dietary minerals, particularly manganese, phosphorus, and zinc (36–45% DV). B vitamins and other minerals are in appreciable amounts (table).\n\nSaturated fat\nMovie theaters commonly use coconut oil to pop the corn, and then top it with butter or margarine.  Movie theater popcorn contains large amounts of saturated fats and sodium due to its method of preparation.\n\nPhytochemicals\nSorghum grains can be popped to form popcorn. All sorghums contain phenolic acids, and most contain flavonoids. Sorghum grains are one of the highest food sources of the flavonoid proanthocyanidin.\n\nHealth risks\nPopcorn is included on the list of foods that the American Academy of Pediatrics recommends not serving to children under four, because of the risk of choking.\nMicrowaveable popcorn represents a special case, since it is designed to be cooked along with its various flavoring agents. One of these formerly common artificial-butter flavorants, diacetyl, has been implicated in causing respiratory illnesses in microwave popcorn factory workers, also known as "popcorn lung". Major manufacturers in the United States have stopped using this chemical, including Orville Redenbacher\'s, Act II, Pop Secret and Jolly Time.\n\nOther uses\nPopcorn, threaded onto a string, is used as a wall or Christmas tree decoration in some parts of North America, as well as on the Balkan peninsula.\nSome shipping companies have experimented with using popcorn as a biodegradable replacement for expanded polystyrene packing material. However, popcorn has numerous undesirable properties as a packing material, including attractiveness to pests, flammability, and a higher cost and greater density than expanded polystyrene. A more processed form of expanded corn foam has been developed to overcome some of these limitations, forming starch-based foam peanuts.\n\nSee also\nReferences\nNotes\n\nFurther reading\n\nHallauer, Arnel R. (2001). Specialty Corns. CRC Press. ISBN 978-0-8493-2377-5.\nLusas, Edmund W.; Rooney, Lloyd W. (2001). Snack Foods Processing. CRC Press. ISBN 978-1-56676-932-7.\nSmith, Andrew F. (1999). Popped Culture: The Social History of Popcorn in America. University of South Carolina Press. ISBN 978-1-57003-300-1.'

In [ ]:
print(wiki_text[:4000])

Popcorn (also called popped corn, popcorns, or pop-corn) is a variety of corn kernel which expands and puffs up when heated. The term also refers to the snack food produced by the expansion. It is one of the oldest snacks, with evidence of popcorn dating back thousands of years in the Americas. It is commonly eaten salted, buttered, sweetened, or with artificial flavorings.
A popcorn kernel's strong hull contains the seed's hard, starchy shell endosperm with 14–20% moisture, which turns to steam as the kernel is heated. Pressure from the steam continues to build until the hull ruptures, allowing the kernel to forcefully expand, to 20 to 50 times its original size, and then cool.
Some strains of corn (taxonomized as Zea mays) are cultivated specifically as popping corns. The Zea mays variety everta, a special kind of flint corn, is the most common of these. Popcorn is one of six major types of corn, alongside dent corn, flint corn, pod corn, flour corn, and sweet corn.

History
Corn was domesticated about 9,000  years ago, in what is now the Balsas River Valley of Central Mexico. Archaeologists discovered that people have known about popcorn for millennia. Fossil evidence from Peru suggests that corn was present there as early as 4,700 BCE, and popped there over 1,000 years ago. Between 2007 and 2011, evidence as early as 4,700 BCE for popping corn was discovered as macrofossil cobs at the Paredones and Huaca Prieta archaeological sites on the northern coast of Peru. Corn cultivation was present in Amazon basin  farming practices as evidenced by cultivation of corn in the Amazon basin 6,000 years ago
In 1948 and 1950, evidence as early as 3600 BCE for popping corn as ears of popcorn were discovered by Harvard anthropology graduate student Herbert W. Dick and Harvard botany graduate student Claude Earle Smith, Junior (1922–1987), in a complex of rock shelters, dubbed the "Bat Cave", in Catron County, west-central New Mexico, and attributed to the Ancestral Puebloan peoples, who maintained trade networks with peoples in tropical Mexico.
Through the 19th century, popping of the kernels was achieved by hand, on stove tops over flame. Kernels were sold on the East Coast of the United States under names such as Pearls or Nonpareil. The term popped corn first appeared in John Russell Bartlett's 1848 Dictionary of Americanisms. Popcorn is an ingredient in Cracker Jack and, in the early years of the product, it was popped by hand.

Popcorn's accessibility increased rapidly in the 1890s with Charles Cretors' invention of the popcorn maker. Cretors, a Chicago candy store owner, had created a number of steam-powered machines for roasting nuts and applied the technology to the corn kernels.

By the turn of the century, Cretors had created and deployed street carts equipped with steam-powered popcorn makers. During the Great Depression, popcorn was fairly inexpensive at 5–10 cents a bag and became popular. Thus, while other businesses failed, the popcorn business thrived and became a source of income for many struggling farmers and entrepreneurs, including the Redenbacher family, namesake of the Orville Redenbacher's popcorn brand. During World War II, sugar rations diminished candy production, and Americans compensated by eating three times as much popcorn as they had before. The snack was popular at theaters, much to the initial displeasure of many of the theater owners, who thought it distracted from the films. Their minds eventually changed, however, and in 1938 a Midwestern theater owner named Glen W. Dickinson Sr. installed popcorn machines in the lobbies of his Dickinson theaters. Popcorn was more profitable than theater tickets, and at the suggestion of his production consultant, R. Ray Aden, Dickinson purchased popcorn farms and was able to keep ticket prices down. The venture was a success, and popcorn soon spread. The rise of television in the 1940s brought lower popcorn consumption as theater attendance fell. The Popcorn Institu

### Clean the text - version 1

Using string replace.

In [ ]:
#Replace newline chars with spaces before doing any processing. Strip the ' and "s" from possessives
wiki_text_clean = (
    wiki_text
    .lower()
    .replace("\n"," ")
    .replace("'s",'')
    .replace("'",'')
)

wiki_text_clean

'popcorn (also called popped corn, popcorns, or pop-corn) is a variety of corn kernel which expands and puffs up when heated. the term also refers to the snack food produced by the expansion. it is one of the oldest snacks, with evidence of popcorn dating back thousands of years in the americas. it is commonly eaten salted, buttered, sweetened, or with artificial flavorings. a popcorn kernel strong hull contains the seed hard, starchy shell endosperm with 14–20% moisture, which turns to steam as the kernel is heated. pressure from the steam continues to build until the hull ruptures, allowing the kernel to forcefully expand, to 20 to 50 times its original size, and then cool. some strains of corn (taxonomized as zea mays) are cultivated specifically as popping corns. the zea mays variety everta, a special kind of flint corn, is the most common of these. popcorn is one of six major types of corn, alongside dent corn, flint corn, pod corn, flour corn, and sweet corn.  history corn was domesticated about 9,000  years ago, in what is now the balsas river valley of central mexico. archaeologists discovered that people have known about popcorn for millennia. fossil evidence from peru suggests that corn was present there as early as 4,700 bce, and popped there over 1,000 years ago. between 2007 and 2011, evidence as early as 4,700 bce for popping corn was discovered as macrofossil cobs at the paredones and huaca prieta archaeological sites on the northern coast of peru. corn cultivation was present in amazon basin  farming practices as evidenced by cultivation of corn in the amazon basin 6,000 years ago  in 1948 and 1950, evidence as early as 3600 bce for popping corn as ears of popcorn were discovered by harvard anthropology graduate student herbert w. dick and harvard botany graduate student claude earle smith, junior (1922–1987), in a complex of rock shelters, dubbed the "bat cave", in catron county, west-central new mexico, and attributed to the ancestral puebloan peoples, who maintained trade networks with peoples in tropical mexico. through the 19th century, popping of the kernels was achieved by hand, on stove tops over flame. kernels were sold on the east coast of the united states under names such as pearls or nonpareil. the term popped corn first appeared in john russell bartlett 1848 dictionary of americanisms. popcorn is an ingredient in cracker jack and, in the early years of the product, it was popped by hand.  popcorn accessibility increased rapidly in the 1890s with charles cretors invention of the popcorn maker. cretors, a chicago candy store owner, had created a number of steam-powered machines for roasting nuts and applied the technology to the corn kernels.  by the turn of the century, cretors had created and deployed street carts equipped with steam-powered popcorn makers. during the great depression, popcorn was fairly inexpensive at 5–10 cents a bag and became popular. thus, while other businesses failed, the popcorn business thrived and became a source of income for many struggling farmers and entrepreneurs, including the redenbacher family, namesake of the orville redenbacher popcorn brand. during world war ii, sugar rations diminished candy production, and americans compensated by eating three times as much popcorn as they had before. the snack was popular at theaters, much to the initial displeasure of many of the theater owners, who thought it distracted from the films. their minds eventually changed, however, and in 1938 a midwestern theater owner named glen w. dickinson sr. installed popcorn machines in the lobbies of his dickinson theaters. popcorn was more profitable than theater tickets, and at the suggestion of his production consultant, r. ray aden, dickinson purchased popcorn farms and was able to keep ticket prices down. the venture was a success, and popcorn soon spread. the rise of television in the 1940s brought lower popcorn consumption as theater attendance fell. the popcorn institute, a trade association of popcorn processors, promoted popcorn consumption at home, bringing it back to previous levels.  in 1970, orville redenbacher namesake brand of popcorn was launched. in 1981, general mills received the first patent for a microwave oven popcorn bag; popcorn consumption saw an increase. at least six localities (all in the midwestern united states) claim to be the "popcorn capital of the world;": ridgway, illinois; valparaiso, indiana; van buren, indiana; schaller, iowa; marion, ohio;  and north loup, nebraska.  according to the usda, specific corn for popcorn is grown mostly in nebraska and indiana, and increasingly in texas. as the result of an elementary school project, popcorn became the official state snack food of illinois.  popping mechanism each kernel of popcorn contains moisture and oil. unlike most other grains, the outer hull of the popcorn kernel is strong and impervious to moisture, and the starch inside consists almost entirely of a hard type.  as the oil and water in the kernel are heated, they turn into steam. under these conditions, the starch inside the kernel gelatinizes and softens. the steam pressure increases until the breaking point of the hull is reached: a pressure of approximately 930 kpa (135 psi) and a temperature of 180 °c (356 °f). the hull ruptures, causing a sudden drop in pressure inside the kernel and a corresponding rapid expansion of the steam, which expands the starch and proteins of the endosperm into an airy foam. as the foam rapidly cools, the starch and protein polymers set into the familiar crispy puff. special varieties are grown to improve popping yield. though the kernels of some other types will pop, the cultivated strain for popcorn is zea mays everta, which is a variety of flint corn.  cooking methods popcorn can be cooked with butter or oil. although small quantities can be popped in a stove-top kettle or pot in a home kitchen, commercial sale employs specially designed popcorn machines, which were invented in chicago, illinois, by charles cretors in 1885. cretors introduced his invention at the columbian exposition in 1893. at that fair, f.\u200dw.\u2009rueckheim introduced a molasses-flavored "candied popcorn", the first caramel corn; his brother, louis ruekheim, slightly altered the recipe and introduced it as cracker jack in 1896.  cretors invention was the first patented steam-driven machine that popped corn in oil. previously, vendors popped corn by holding a wire basket over an open flame. at best, the result was hot, dry, and unevenly cooked. cretors machine popped corn in a mixture of one-third clarified butter, two-thirds lard, and salt. this mixture can withstand the 232 °c (450 °f) temperature needed to pop corn and produces little smoke. a fire under a boiler created steam that drove a small engine to drive gears, shaft, and the agitator that stirred the corn, and also powered a small puppet, "the toasty roasty man", an attention-getting amusement to attract business. a wire connected to the top of the cooking pan allowed the operator to disengage the drive mechanism, lift the cover, and dump popped corn into the storage bin beneath. exhaust from the steam engine was piped to a pan below the corn storage bin and kept freshly popped corn warm. excess steam was also used to operate a small, shrill whistle to attract attention. a different method of popcorn-making involves the "popcorn hammer", a large cast-iron canister that is sealed with a heavy lid and slowly turned over a fire in rotisserie fashion.  expansion and yield popping results are sensitive to the rate at which the kernels are heated. if heated too quickly, the steam in the outer layers of the kernel can reach high pressures and rupture the hull before the starch in the center of the kernel can fully gelatinize, leading to partially popped kernels with hard centers. heating too slowly leads to entirely unpopped kernels: the tip of the kernel, where it attached to the cob, is not entirely moisture-proof, and when heated slowly, the steam can leak out of the tip fast enough to keep the pressure from rising sufficiently to break the hull and cause the pop. producers and sellers of popcorn consider two major factors in evaluating the quality of popcorn: what percentage of the kernels will pop, and how much each popped kernel expands. expansion is an important factor to both the consumer and vendor. for the consumer, larger pieces of popcorn tend to be more tender and are associated with higher quality. for the grower, distributor and vendor, expansion is closely correlated with profit: vendors such as theaters buy popcorn by weight and sell it by volume. for these reasons, higher-expansion popcorn fetches a higher profit per unit weight. popcorn will pop when freshly harvested, but not well; its high moisture content leads to poor expansion and chewy pieces of popcorn. kernels with a high moisture content are also susceptible to mold when stored. for these reasons, popcorn growers and distributors dry the kernels until they reach the moisture level at which they expand the most. this differs by variety and conditions, but is generally in the range of 14–15% moisture by weight. if the kernels are over-dried, the expansion rate will suffer and the percentage of kernels that pop will decline.  old popcorn tends to dry out, lowering the yield. when the popcorn has finished popping, sometimes unpopped kernels remain. known in the popcorn industry as "old maids", these kernels fail to pop because they do not have enough moisture to create enough steam for an explosion. re-hydrating prior to popping usually results in eliminating the unpopped kernels. popcorn varieties are broadly categorized by the shape of the kernels, the color of the kernels, or the shape of the popped corn. while the kernels may come in a variety of colors, the popped corn is always off-yellow or white as it is only the hull (or pericarp) that is colored. "rice" type popcorn have a long kernel pointed at both ends; "pearl" type kernels are rounded at the top. commercial popcorn production has moved mostly to pearl types. historically, pearl popcorn were usually yellow and rice popcorn usually white. today both shapes are available in both colors, as well as others including black, red, mauve,  purple, and variegated. mauve and purple popcorn usually have smaller and nutty kernels. commercial production is dominated by white and yellow.  terminology in the popcorn industry, a popped kernel of corn is known as a "flake". two shapes of flakes are commercially important. "butterfly" (or "snowflake") flakes are irregular in shape and have a number of protruding "wings". "mushroom" flakes are largely ball-shaped, with few wings. butterfly flakes are regarded as having better mouthfeel, with greater tenderness and less noticeable hulls. mushroom flakes are less fragile than butterfly flakes and are therefore often used for packaged popcorn or confectionery, such as caramel corn. the kernels from a single cob of popcorn may form both butterfly and mushroom flakes; hybrids that produce 100% butterfly flakes or 100% mushroom flakes exist, the latter developed only as recently as 1998.  consumption popcorn is a popular snack food at sporting events and in movie theaters, where it has been served since the 1930s. cinemas have come under fire due to their high markup on popcorn; stuart hanson, a film historian at de montfort university in leicester, once said, "one of the great jokes in the industry is that popcorn is second only to cocaine or heroin in terms of profit." traditions differ as to whether popcorn is consumed as a hearty snack food with salt (predominating in the united states) or as a sweet snack food with caramelized sugar (predominating in germany). popcorn customs around savory, salty, and sweet flavors vary by region and demographic, but in the u.s., preferences are diverse and evolving:  popcorn smell has an unusually attractive quality for human beings. this is largely because it contains high levels of the chemicals 6-acetyl-2,3,4,5-tetrahydropyridine and 2-acetyl-1-pyrroline, very powerful aroma compounds that are also used by food and other industries either to make products that smell like popcorn, bread, or other foods containing the compound in nature, or for other purposes.  popcorn as a breakfast cereal was consumed by americans in the 1800s and generally consisted of popcorn with milk and a sweetener.  popcorn balls (popped kernels stuck together with a sugary "glue") were hugely popular around the turn of the 20th century, but their popularity has since waned.  popcorn balls are still served in some places as a traditional halloween treat. cracker jack is a popular, commercially produced candy that consists of peanuts mixed in with caramel-covered popcorn. kettle corn is a variation of normal popcorn, cooked with white sugar and salt, traditionally in a large copper kettle.  once reserved for specialty shops and county fairs, kettle corn has recently become popular, especially in the microwave popcorn market.  the popcorn maker is a relatively new home appliance, and its popularity is increasing because it offers the opportunity to add flavors of the consumer own choice and to choose healthy-eating popcorn styles. popped sorghum is popular as a snack in india. the popped sorghum is similar to popcorn, but the puffs are smaller. recipes for popping sorghum by microwave, in a pot, etc., are readily available online.  nutritional value air-popped popcorn (no salt or other additives) is 4% water, 78% carbohydrates (including 15% dietary fiber), 12% protein, and 4% fat (table). in a 100 gram reference amount, popcorn provides 382 calories and is a rich source (20% or more of the daily value, dv) of riboflavin (25% dv) and several dietary minerals, particularly manganese, phosphorus, and zinc (36–45% dv). b vitamins and other minerals are in appreciable amounts (table).  saturated fat movie theaters commonly use coconut oil to pop the corn, and then top it with butter or margarine.  movie theater popcorn contains large amounts of saturated fats and sodium due to its method of preparation.  phytochemicals sorghum grains can be popped to form popcorn. all sorghums contain phenolic acids, and most contain flavonoids. sorghum grains are one of the highest food sources of the flavonoid proanthocyanidin.  health risks popcorn is included on the list of foods that the american academy of pediatrics recommends not serving to children under four, because of the risk of choking. microwaveable popcorn represents a special case, since it is designed to be cooked along with its various flavoring agents. one of these formerly common artificial-butter flavorants, diacetyl, has been implicated in causing respiratory illnesses in microwave popcorn factory workers, also known as "popcorn lung". major manufacturers in the united states have stopped using this chemical, including orville redenbacher, act ii, pop secret and jolly time.  other uses popcorn, threaded onto a string, is used as a wall or christmas tree decoration in some parts of north america, as well as on the balkan peninsula. some shipping companies have experimented with using popcorn as a biodegradable replacement for expanded polystyrene packing material. however, popcorn has numerous undesirable properties as a packing material, including attractiveness to pests, flammability, and a higher cost and greater density than expanded polystyrene. a more processed form of expanded corn foam has been developed to overcome some of these limitations, forming starch-based foam peanuts.  see also references notes  further reading  hallauer, arnel r. (2001). specialty corns. crc press. isbn 978-0-8493-2377-5. lusas, edmund w.; rooney, lloyd w. (2001). snack foods processing. crc press. isbn 978-1-56676-932-7. smith, andrew f. (1999). popped culture: the social history of popcorn in america. university of south carolina press. isbn 978-1-57003-300-1.'

In [ ]:
print(wiki_text_clean[:4000])

popcorn (also called popped corn, popcorns, or pop-corn) is a variety of corn kernel which expands and puffs up when heated. the term also refers to the snack food produced by the expansion. it is one of the oldest snacks, with evidence of popcorn dating back thousands of years in the americas. it is commonly eaten salted, buttered, sweetened, or with artificial flavorings. a popcorn kernel strong hull contains the seed hard, starchy shell endosperm with 14–20% moisture, which turns to steam as the kernel is heated. pressure from the steam continues to build until the hull ruptures, allowing the kernel to forcefully expand, to 20 to 50 times its original size, and then cool. some strains of corn (taxonomized as zea mays) are cultivated specifically as popping corns. the zea mays variety everta, a special kind of flint corn, is the most common of these. popcorn is one of six major types of corn, alongside dent corn, flint corn, pod corn, flour corn, and sweet corn.  history corn was domesticated about 9,000  years ago, in what is now the balsas river valley of central mexico. archaeologists discovered that people have known about popcorn for millennia. fossil evidence from peru suggests that corn was present there as early as 4,700 bce, and popped there over 1,000 years ago. between 2007 and 2011, evidence as early as 4,700 bce for popping corn was discovered as macrofossil cobs at the paredones and huaca prieta archaeological sites on the northern coast of peru. corn cultivation was present in amazon basin  farming practices as evidenced by cultivation of corn in the amazon basin 6,000 years ago  in 1948 and 1950, evidence as early as 3600 bce for popping corn as ears of popcorn were discovered by harvard anthropology graduate student herbert w. dick and harvard botany graduate student claude earle smith, junior (1922–1987), in a complex of rock shelters, dubbed the "bat cave", in catron county, west-central new mexico, and attributed to the ancestral puebloan peoples, who maintained trade networks with peoples in tropical mexico. through the 19th century, popping of the kernels was achieved by hand, on stove tops over flame. kernels were sold on the east coast of the united states under names such as pearls or nonpareil. the term popped corn first appeared in john russell bartlett 1848 dictionary of americanisms. popcorn is an ingredient in cracker jack and, in the early years of the product, it was popped by hand.  popcorn accessibility increased rapidly in the 1890s with charles cretors invention of the popcorn maker. cretors, a chicago candy store owner, had created a number of steam-powered machines for roasting nuts and applied the technology to the corn kernels.  by the turn of the century, cretors had created and deployed street carts equipped with steam-powered popcorn makers. during the great depression, popcorn was fairly inexpensive at 5–10 cents a bag and became popular. thus, while other businesses failed, the popcorn business thrived and became a source of income for many struggling farmers and entrepreneurs, including the redenbacher family, namesake of the orville redenbacher popcorn brand. during world war ii, sugar rations diminished candy production, and americans compensated by eating three times as much popcorn as they had before. the snack was popular at theaters, much to the initial displeasure of many of the theater owners, who thought it distracted from the films. their minds eventually changed, however, and in 1938 a midwestern theater owner named glen w. dickinson sr. installed popcorn machines in the lobbies of his dickinson theaters. popcorn was more profitable than theater tickets, and at the suggestion of his production consultant, r. ray aden, dickinson purchased popcorn farms and was able to keep ticket prices down. the venture was a success, and popcorn soon spread. the rise of television in the 1940s brought lower popcorn consumption as theater attendance fell. the popcorn institute, a trade

### Clean the text - version 2

Using a for..loop and string replace.

In [ ]:
wiki_text_clean = wiki_text.lower()
for c in ["\n", "'s", "'", "  "]:
  wiki_text_clean = wiki_text_clean.replace(c," ")

wiki_text_clean

'popcorn (also called popped corn, popcorns, or pop-corn) is a variety of corn kernel which expands and puffs up when heated. the term also refers to the snack food produced by the expansion. it is one of the oldest snacks, with evidence of popcorn dating back thousands of years in the americas. it is commonly eaten salted, buttered, sweetened, or with artificial flavorings. a popcorn kernel strong hull contains the seed hard, starchy shell endosperm with 14–20% moisture, which turns to steam as the kernel is heated. pressure from the steam continues to build until the hull ruptures, allowing the kernel to forcefully expand, to 20 to 50 times its original size, and then cool. some strains of corn (taxonomized as zea mays) are cultivated specifically as popping corns. the zea mays variety everta, a special kind of flint corn, is the most common of these. popcorn is one of six major types of corn, alongside dent corn, flint corn, pod corn, flour corn, and sweet corn. history corn was domesticated about 9,000 years ago, in what is now the balsas river valley of central mexico. archaeologists discovered that people have known about popcorn for millennia. fossil evidence from peru suggests that corn was present there as early as 4,700 bce, and popped there over 1,000 years ago. between 2007 and 2011, evidence as early as 4,700 bce for popping corn was discovered as macrofossil cobs at the paredones and huaca prieta archaeological sites on the northern coast of peru. corn cultivation was present in amazon basin farming practices as evidenced by cultivation of corn in the amazon basin 6,000 years ago in 1948 and 1950, evidence as early as 3600 bce for popping corn as ears of popcorn were discovered by harvard anthropology graduate student herbert w. dick and harvard botany graduate student claude earle smith, junior (1922–1987), in a complex of rock shelters, dubbed the "bat cave", in catron county, west-central new mexico, and attributed to the ancestral puebloan peoples, who maintained trade networks with peoples in tropical mexico. through the 19th century, popping of the kernels was achieved by hand, on stove tops over flame. kernels were sold on the east coast of the united states under names such as pearls or nonpareil. the term popped corn first appeared in john russell bartlett 1848 dictionary of americanisms. popcorn is an ingredient in cracker jack and, in the early years of the product, it was popped by hand. popcorn accessibility increased rapidly in the 1890s with charles cretors invention of the popcorn maker. cretors, a chicago candy store owner, had created a number of steam-powered machines for roasting nuts and applied the technology to the corn kernels. by the turn of the century, cretors had created and deployed street carts equipped with steam-powered popcorn makers. during the great depression, popcorn was fairly inexpensive at 5–10 cents a bag and became popular. thus, while other businesses failed, the popcorn business thrived and became a source of income for many struggling farmers and entrepreneurs, including the redenbacher family, namesake of the orville redenbacher popcorn brand. during world war ii, sugar rations diminished candy production, and americans compensated by eating three times as much popcorn as they had before. the snack was popular at theaters, much to the initial displeasure of many of the theater owners, who thought it distracted from the films. their minds eventually changed, however, and in 1938 a midwestern theater owner named glen w. dickinson sr. installed popcorn machines in the lobbies of his dickinson theaters. popcorn was more profitable than theater tickets, and at the suggestion of his production consultant, r. ray aden, dickinson purchased popcorn farms and was able to keep ticket prices down. the venture was a success, and popcorn soon spread. the rise of television in the 1940s brought lower popcorn consumption as theater attendance fell. the popcorn institute, a trade association of popcorn processors, promoted popcorn consumption at home, bringing it back to previous levels. in 1970, orville redenbacher namesake brand of popcorn was launched. in 1981, general mills received the first patent for a microwave oven popcorn bag; popcorn consumption saw an increase. at least six localities (all in the midwestern united states) claim to be the "popcorn capital of the world;": ridgway, illinois; valparaiso, indiana; van buren, indiana; schaller, iowa; marion, ohio; and north loup, nebraska. according to the usda, specific corn for popcorn is grown mostly in nebraska and indiana, and increasingly in texas. as the result of an elementary school project, popcorn became the official state snack food of illinois. popping mechanism each kernel of popcorn contains moisture and oil. unlike most other grains, the outer hull of the popcorn kernel is strong and impervious to moisture, and the starch inside consists almost entirely of a hard type. as the oil and water in the kernel are heated, they turn into steam. under these conditions, the starch inside the kernel gelatinizes and softens. the steam pressure increases until the breaking point of the hull is reached: a pressure of approximately 930 kpa (135 psi) and a temperature of 180 °c (356 °f). the hull ruptures, causing a sudden drop in pressure inside the kernel and a corresponding rapid expansion of the steam, which expands the starch and proteins of the endosperm into an airy foam. as the foam rapidly cools, the starch and protein polymers set into the familiar crispy puff. special varieties are grown to improve popping yield. though the kernels of some other types will pop, the cultivated strain for popcorn is zea mays everta, which is a variety of flint corn. cooking methods popcorn can be cooked with butter or oil. although small quantities can be popped in a stove-top kettle or pot in a home kitchen, commercial sale employs specially designed popcorn machines, which were invented in chicago, illinois, by charles cretors in 1885. cretors introduced his invention at the columbian exposition in 1893. at that fair, f.\u200dw.\u2009rueckheim introduced a molasses-flavored "candied popcorn", the first caramel corn; his brother, louis ruekheim, slightly altered the recipe and introduced it as cracker jack in 1896. cretors invention was the first patented steam-driven machine that popped corn in oil. previously, vendors popped corn by holding a wire basket over an open flame. at best, the result was hot, dry, and unevenly cooked. cretors machine popped corn in a mixture of one-third clarified butter, two-thirds lard, and salt. this mixture can withstand the 232 °c (450 °f) temperature needed to pop corn and produces little smoke. a fire under a boiler created steam that drove a small engine to drive gears, shaft, and the agitator that stirred the corn, and also powered a small puppet, "the toasty roasty man", an attention-getting amusement to attract business. a wire connected to the top of the cooking pan allowed the operator to disengage the drive mechanism, lift the cover, and dump popped corn into the storage bin beneath. exhaust from the steam engine was piped to a pan below the corn storage bin and kept freshly popped corn warm. excess steam was also used to operate a small, shrill whistle to attract attention. a different method of popcorn-making involves the "popcorn hammer", a large cast-iron canister that is sealed with a heavy lid and slowly turned over a fire in rotisserie fashion. expansion and yield popping results are sensitive to the rate at which the kernels are heated. if heated too quickly, the steam in the outer layers of the kernel can reach high pressures and rupture the hull before the starch in the center of the kernel can fully gelatinize, leading to partially popped kernels with hard centers. heating too slowly leads to entirely unpopped kernels: the tip of the kernel, where it attached to the cob, is not entirely moisture-proof, and when heated slowly, the steam can leak out of the tip fast enough to keep the pressure from rising sufficiently to break the hull and cause the pop. producers and sellers of popcorn consider two major factors in evaluating the quality of popcorn: what percentage of the kernels will pop, and how much each popped kernel expands. expansion is an important factor to both the consumer and vendor. for the consumer, larger pieces of popcorn tend to be more tender and are associated with higher quality. for the grower, distributor and vendor, expansion is closely correlated with profit: vendors such as theaters buy popcorn by weight and sell it by volume. for these reasons, higher-expansion popcorn fetches a higher profit per unit weight. popcorn will pop when freshly harvested, but not well; its high moisture content leads to poor expansion and chewy pieces of popcorn. kernels with a high moisture content are also susceptible to mold when stored. for these reasons, popcorn growers and distributors dry the kernels until they reach the moisture level at which they expand the most. this differs by variety and conditions, but is generally in the range of 14–15% moisture by weight. if the kernels are over-dried, the expansion rate will suffer and the percentage of kernels that pop will decline. old popcorn tends to dry out, lowering the yield. when the popcorn has finished popping, sometimes unpopped kernels remain. known in the popcorn industry as "old maids", these kernels fail to pop because they do not have enough moisture to create enough steam for an explosion. re-hydrating prior to popping usually results in eliminating the unpopped kernels. popcorn varieties are broadly categorized by the shape of the kernels, the color of the kernels, or the shape of the popped corn. while the kernels may come in a variety of colors, the popped corn is always off-yellow or white as it is only the hull (or pericarp) that is colored. "rice" type popcorn have a long kernel pointed at both ends; "pearl" type kernels are rounded at the top. commercial popcorn production has moved mostly to pearl types. historically, pearl popcorn were usually yellow and rice popcorn usually white. today both shapes are available in both colors, as well as others including black, red, mauve, purple, and variegated. mauve and purple popcorn usually have smaller and nutty kernels. commercial production is dominated by white and yellow. terminology in the popcorn industry, a popped kernel of corn is known as a "flake". two shapes of flakes are commercially important. "butterfly" (or "snowflake") flakes are irregular in shape and have a number of protruding "wings". "mushroom" flakes are largely ball-shaped, with few wings. butterfly flakes are regarded as having better mouthfeel, with greater tenderness and less noticeable hulls. mushroom flakes are less fragile than butterfly flakes and are therefore often used for packaged popcorn or confectionery, such as caramel corn. the kernels from a single cob of popcorn may form both butterfly and mushroom flakes; hybrids that produce 100% butterfly flakes or 100% mushroom flakes exist, the latter developed only as recently as 1998. consumption popcorn is a popular snack food at sporting events and in movie theaters, where it has been served since the 1930s. cinemas have come under fire due to their high markup on popcorn; stuart hanson, a film historian at de montfort university in leicester, once said, "one of the great jokes in the industry is that popcorn is second only to cocaine or heroin in terms of profit." traditions differ as to whether popcorn is consumed as a hearty snack food with salt (predominating in the united states) or as a sweet snack food with caramelized sugar (predominating in germany). popcorn customs around savory, salty, and sweet flavors vary by region and demographic, but in the u.s., preferences are diverse and evolving: popcorn smell has an unusually attractive quality for human beings. this is largely because it contains high levels of the chemicals 6-acetyl-2,3,4,5-tetrahydropyridine and 2-acetyl-1-pyrroline, very powerful aroma compounds that are also used by food and other industries either to make products that smell like popcorn, bread, or other foods containing the compound in nature, or for other purposes. popcorn as a breakfast cereal was consumed by americans in the 1800s and generally consisted of popcorn with milk and a sweetener. popcorn balls (popped kernels stuck together with a sugary "glue") were hugely popular around the turn of the 20th century, but their popularity has since waned. popcorn balls are still served in some places as a traditional halloween treat. cracker jack is a popular, commercially produced candy that consists of peanuts mixed in with caramel-covered popcorn. kettle corn is a variation of normal popcorn, cooked with white sugar and salt, traditionally in a large copper kettle. once reserved for specialty shops and county fairs, kettle corn has recently become popular, especially in the microwave popcorn market. the popcorn maker is a relatively new home appliance, and its popularity is increasing because it offers the opportunity to add flavors of the consumer own choice and to choose healthy-eating popcorn styles. popped sorghum is popular as a snack in india. the popped sorghum is similar to popcorn, but the puffs are smaller. recipes for popping sorghum by microwave, in a pot, etc., are readily available online. nutritional value air-popped popcorn (no salt or other additives) is 4% water, 78% carbohydrates (including 15% dietary fiber), 12% protein, and 4% fat (table). in a 100 gram reference amount, popcorn provides 382 calories and is a rich source (20% or more of the daily value, dv) of riboflavin (25% dv) and several dietary minerals, particularly manganese, phosphorus, and zinc (36–45% dv). b vitamins and other minerals are in appreciable amounts (table). saturated fat movie theaters commonly use coconut oil to pop the corn, and then top it with butter or margarine. movie theater popcorn contains large amounts of saturated fats and sodium due to its method of preparation. phytochemicals sorghum grains can be popped to form popcorn. all sorghums contain phenolic acids, and most contain flavonoids. sorghum grains are one of the highest food sources of the flavonoid proanthocyanidin. health risks popcorn is included on the list of foods that the american academy of pediatrics recommends not serving to children under four, because of the risk of choking. microwaveable popcorn represents a special case, since it is designed to be cooked along with its various flavoring agents. one of these formerly common artificial-butter flavorants, diacetyl, has been implicated in causing respiratory illnesses in microwave popcorn factory workers, also known as "popcorn lung". major manufacturers in the united states have stopped using this chemical, including orville redenbacher , act ii, pop secret and jolly time. other uses popcorn, threaded onto a string, is used as a wall or christmas tree decoration in some parts of north america, as well as on the balkan peninsula. some shipping companies have experimented with using popcorn as a biodegradable replacement for expanded polystyrene packing material. however, popcorn has numerous undesirable properties as a packing material, including attractiveness to pests, flammability, and a higher cost and greater density than expanded polystyrene. a more processed form of expanded corn foam has been developed to overcome some of these limitations, forming starch-based foam peanuts. see also references notes further reading hallauer, arnel r. (2001). specialty corns. crc press. isbn 978-0-8493-2377-5. lusas, edmund w.; rooney, lloyd w. (2001). snack foods processing. crc press. isbn 978-1-56676-932-7. smith, andrew f. (1999). popped culture: the social history of popcorn in america. university of south carolina press. isbn 978-1-57003-300-1.'

### Clean the text - version 3

Using a regular expression.

In [ ]:
import re

pat = re.compile(r"(\n|'s|'| )+")
wiki_text_clean = re.sub(pat,' ', wiki_text.lower())
wiki_text_clean

'popcorn (also called popped corn, popcorns, or pop-corn) is a variety of corn kernel which expands and puffs up when heated. the term also refers to the snack food produced by the expansion. it is one of the oldest snacks, with evidence of popcorn dating back thousands of years in the americas. it is commonly eaten salted, buttered, sweetened, or with artificial flavorings. a popcorn kernel strong hull contains the seed hard, starchy shell endosperm with 14–20% moisture, which turns to steam as the kernel is heated. pressure from the steam continues to build until the hull ruptures, allowing the kernel to forcefully expand, to 20 to 50 times its original size, and then cool. some strains of corn (taxonomized as zea mays) are cultivated specifically as popping corns. the zea mays variety everta, a special kind of flint corn, is the most common of these. popcorn is one of six major types of corn, alongside dent corn, flint corn, pod corn, flour corn, and sweet corn. history corn was domesticated about 9,000 years ago, in what is now the balsas river valley of central mexico. archaeologists discovered that people have known about popcorn for millennia. fossil evidence from peru suggests that corn was present there as early as 4,700 bce, and popped there over 1,000 years ago. between 2007 and 2011, evidence as early as 4,700 bce for popping corn was discovered as macrofossil cobs at the paredones and huaca prieta archaeological sites on the northern coast of peru. corn cultivation was present in amazon basin farming practices as evidenced by cultivation of corn in the amazon basin 6,000 years ago in 1948 and 1950, evidence as early as 3600 bce for popping corn as ears of popcorn were discovered by harvard anthropology graduate student herbert w. dick and harvard botany graduate student claude earle smith, junior (1922–1987), in a complex of rock shelters, dubbed the "bat cave", in catron county, west-central new mexico, and attributed to the ancestral puebloan peoples, who maintained trade networks with peoples in tropical mexico. through the 19th century, popping of the kernels was achieved by hand, on stove tops over flame. kernels were sold on the east coast of the united states under names such as pearls or nonpareil. the term popped corn first appeared in john russell bartlett 1848 dictionary of americanisms. popcorn is an ingredient in cracker jack and, in the early years of the product, it was popped by hand. popcorn accessibility increased rapidly in the 1890s with charles cretors invention of the popcorn maker. cretors, a chicago candy store owner, had created a number of steam-powered machines for roasting nuts and applied the technology to the corn kernels. by the turn of the century, cretors had created and deployed street carts equipped with steam-powered popcorn makers. during the great depression, popcorn was fairly inexpensive at 5–10 cents a bag and became popular. thus, while other businesses failed, the popcorn business thrived and became a source of income for many struggling farmers and entrepreneurs, including the redenbacher family, namesake of the orville redenbacher popcorn brand. during world war ii, sugar rations diminished candy production, and americans compensated by eating three times as much popcorn as they had before. the snack was popular at theaters, much to the initial displeasure of many of the theater owners, who thought it distracted from the films. their minds eventually changed, however, and in 1938 a midwestern theater owner named glen w. dickinson sr. installed popcorn machines in the lobbies of his dickinson theaters. popcorn was more profitable than theater tickets, and at the suggestion of his production consultant, r. ray aden, dickinson purchased popcorn farms and was able to keep ticket prices down. the venture was a success, and popcorn soon spread. the rise of television in the 1940s brought lower popcorn consumption as theater attendance fell. the popcorn institute, a trade association of popcorn processors, promoted popcorn consumption at home, bringing it back to previous levels. in 1970, orville redenbacher namesake brand of popcorn was launched. in 1981, general mills received the first patent for a microwave oven popcorn bag; popcorn consumption saw an increase. at least six localities (all in the midwestern united states) claim to be the "popcorn capital of the world;": ridgway, illinois; valparaiso, indiana; van buren, indiana; schaller, iowa; marion, ohio; and north loup, nebraska. according to the usda, specific corn for popcorn is grown mostly in nebraska and indiana, and increasingly in texas. as the result of an elementary school project, popcorn became the official state snack food of illinois. popping mechanism each kernel of popcorn contains moisture and oil. unlike most other grains, the outer hull of the popcorn kernel is strong and impervious to moisture, and the starch inside consists almost entirely of a hard type. as the oil and water in the kernel are heated, they turn into steam. under these conditions, the starch inside the kernel gelatinizes and softens. the steam pressure increases until the breaking point of the hull is reached: a pressure of approximately 930 kpa (135 psi) and a temperature of 180 °c (356 °f). the hull ruptures, causing a sudden drop in pressure inside the kernel and a corresponding rapid expansion of the steam, which expands the starch and proteins of the endosperm into an airy foam. as the foam rapidly cools, the starch and protein polymers set into the familiar crispy puff. special varieties are grown to improve popping yield. though the kernels of some other types will pop, the cultivated strain for popcorn is zea mays everta, which is a variety of flint corn. cooking methods popcorn can be cooked with butter or oil. although small quantities can be popped in a stove-top kettle or pot in a home kitchen, commercial sale employs specially designed popcorn machines, which were invented in chicago, illinois, by charles cretors in 1885. cretors introduced his invention at the columbian exposition in 1893. at that fair, f.\u200dw.\u2009rueckheim introduced a molasses-flavored "candied popcorn", the first caramel corn; his brother, louis ruekheim, slightly altered the recipe and introduced it as cracker jack in 1896. cretors invention was the first patented steam-driven machine that popped corn in oil. previously, vendors popped corn by holding a wire basket over an open flame. at best, the result was hot, dry, and unevenly cooked. cretors machine popped corn in a mixture of one-third clarified butter, two-thirds lard, and salt. this mixture can withstand the 232 °c (450 °f) temperature needed to pop corn and produces little smoke. a fire under a boiler created steam that drove a small engine to drive gears, shaft, and the agitator that stirred the corn, and also powered a small puppet, "the toasty roasty man", an attention-getting amusement to attract business. a wire connected to the top of the cooking pan allowed the operator to disengage the drive mechanism, lift the cover, and dump popped corn into the storage bin beneath. exhaust from the steam engine was piped to a pan below the corn storage bin and kept freshly popped corn warm. excess steam was also used to operate a small, shrill whistle to attract attention. a different method of popcorn-making involves the "popcorn hammer", a large cast-iron canister that is sealed with a heavy lid and slowly turned over a fire in rotisserie fashion. expansion and yield popping results are sensitive to the rate at which the kernels are heated. if heated too quickly, the steam in the outer layers of the kernel can reach high pressures and rupture the hull before the starch in the center of the kernel can fully gelatinize, leading to partially popped kernels with hard centers. heating too slowly leads to entirely unpopped kernels: the tip of the kernel, where it attached to the cob, is not entirely moisture-proof, and when heated slowly, the steam can leak out of the tip fast enough to keep the pressure from rising sufficiently to break the hull and cause the pop. producers and sellers of popcorn consider two major factors in evaluating the quality of popcorn: what percentage of the kernels will pop, and how much each popped kernel expands. expansion is an important factor to both the consumer and vendor. for the consumer, larger pieces of popcorn tend to be more tender and are associated with higher quality. for the grower, distributor and vendor, expansion is closely correlated with profit: vendors such as theaters buy popcorn by weight and sell it by volume. for these reasons, higher-expansion popcorn fetches a higher profit per unit weight. popcorn will pop when freshly harvested, but not well; its high moisture content leads to poor expansion and chewy pieces of popcorn. kernels with a high moisture content are also susceptible to mold when stored. for these reasons, popcorn growers and distributors dry the kernels until they reach the moisture level at which they expand the most. this differs by variety and conditions, but is generally in the range of 14–15% moisture by weight. if the kernels are over-dried, the expansion rate will suffer and the percentage of kernels that pop will decline. old popcorn tends to dry out, lowering the yield. when the popcorn has finished popping, sometimes unpopped kernels remain. known in the popcorn industry as "old maids", these kernels fail to pop because they do not have enough moisture to create enough steam for an explosion. re-hydrating prior to popping usually results in eliminating the unpopped kernels. popcorn varieties are broadly categorized by the shape of the kernels, the color of the kernels, or the shape of the popped corn. while the kernels may come in a variety of colors, the popped corn is always off-yellow or white as it is only the hull (or pericarp) that is colored. "rice" type popcorn have a long kernel pointed at both ends; "pearl" type kernels are rounded at the top. commercial popcorn production has moved mostly to pearl types. historically, pearl popcorn were usually yellow and rice popcorn usually white. today both shapes are available in both colors, as well as others including black, red, mauve, purple, and variegated. mauve and purple popcorn usually have smaller and nutty kernels. commercial production is dominated by white and yellow. terminology in the popcorn industry, a popped kernel of corn is known as a "flake". two shapes of flakes are commercially important. "butterfly" (or "snowflake") flakes are irregular in shape and have a number of protruding "wings". "mushroom" flakes are largely ball-shaped, with few wings. butterfly flakes are regarded as having better mouthfeel, with greater tenderness and less noticeable hulls. mushroom flakes are less fragile than butterfly flakes and are therefore often used for packaged popcorn or confectionery, such as caramel corn. the kernels from a single cob of popcorn may form both butterfly and mushroom flakes; hybrids that produce 100% butterfly flakes or 100% mushroom flakes exist, the latter developed only as recently as 1998. consumption popcorn is a popular snack food at sporting events and in movie theaters, where it has been served since the 1930s. cinemas have come under fire due to their high markup on popcorn; stuart hanson, a film historian at de montfort university in leicester, once said, "one of the great jokes in the industry is that popcorn is second only to cocaine or heroin in terms of profit." traditions differ as to whether popcorn is consumed as a hearty snack food with salt (predominating in the united states) or as a sweet snack food with caramelized sugar (predominating in germany). popcorn customs around savory, salty, and sweet flavors vary by region and demographic, but in the u.s., preferences are diverse and evolving: popcorn smell has an unusually attractive quality for human beings. this is largely because it contains high levels of the chemicals 6-acetyl-2,3,4,5-tetrahydropyridine and 2-acetyl-1-pyrroline, very powerful aroma compounds that are also used by food and other industries either to make products that smell like popcorn, bread, or other foods containing the compound in nature, or for other purposes. popcorn as a breakfast cereal was consumed by americans in the 1800s and generally consisted of popcorn with milk and a sweetener. popcorn balls (popped kernels stuck together with a sugary "glue") were hugely popular around the turn of the 20th century, but their popularity has since waned. popcorn balls are still served in some places as a traditional halloween treat. cracker jack is a popular, commercially produced candy that consists of peanuts mixed in with caramel-covered popcorn. kettle corn is a variation of normal popcorn, cooked with white sugar and salt, traditionally in a large copper kettle. once reserved for specialty shops and county fairs, kettle corn has recently become popular, especially in the microwave popcorn market. the popcorn maker is a relatively new home appliance, and its popularity is increasing because it offers the opportunity to add flavors of the consumer own choice and to choose healthy-eating popcorn styles. popped sorghum is popular as a snack in india. the popped sorghum is similar to popcorn, but the puffs are smaller. recipes for popping sorghum by microwave, in a pot, etc., are readily available online. nutritional value air-popped popcorn (no salt or other additives) is 4% water, 78% carbohydrates (including 15% dietary fiber), 12% protein, and 4% fat (table). in a 100 gram reference amount, popcorn provides 382 calories and is a rich source (20% or more of the daily value, dv) of riboflavin (25% dv) and several dietary minerals, particularly manganese, phosphorus, and zinc (36–45% dv). b vitamins and other minerals are in appreciable amounts (table). saturated fat movie theaters commonly use coconut oil to pop the corn, and then top it with butter or margarine. movie theater popcorn contains large amounts of saturated fats and sodium due to its method of preparation. phytochemicals sorghum grains can be popped to form popcorn. all sorghums contain phenolic acids, and most contain flavonoids. sorghum grains are one of the highest food sources of the flavonoid proanthocyanidin. health risks popcorn is included on the list of foods that the american academy of pediatrics recommends not serving to children under four, because of the risk of choking. microwaveable popcorn represents a special case, since it is designed to be cooked along with its various flavoring agents. one of these formerly common artificial-butter flavorants, diacetyl, has been implicated in causing respiratory illnesses in microwave popcorn factory workers, also known as "popcorn lung". major manufacturers in the united states have stopped using this chemical, including orville redenbacher , act ii, pop secret and jolly time. other uses popcorn, threaded onto a string, is used as a wall or christmas tree decoration in some parts of north america, as well as on the balkan peninsula. some shipping companies have experimented with using popcorn as a biodegradable replacement for expanded polystyrene packing material. however, popcorn has numerous undesirable properties as a packing material, including attractiveness to pests, flammability, and a higher cost and greater density than expanded polystyrene. a more processed form of expanded corn foam has been developed to overcome some of these limitations, forming starch-based foam peanuts. see also references notes further reading hallauer, arnel r. (2001). specialty corns. crc press. isbn 978-0-8493-2377-5. lusas, edmund w.; rooney, lloyd w. (2001). snack foods processing. crc press. isbn 978-1-56676-932-7. smith, andrew f. (1999). popped culture: the social history of popcorn in america. university of south carolina press. isbn 978-1-57003-300-1.'

### Moving on ...

In [ ]:
#Break up single string into separate sentences
wiki_blob = TextBlob(wiki_text_clean)
len(wiki_blob.sentences)

128

In [ ]:
#Only look at first 20 sentences
my_sentences = wiki_blob.sentences
my_sentences

[Sentence("popcorn (also called popped corn, popcorns, or pop-corn) is a variety of corn kernel which expands and puffs up when heated."),
 Sentence("the term also refers to the snack food produced by the expansion."),
 Sentence("it is one of the oldest snacks, with evidence of popcorn dating back thousands of years in the americas."),
 Sentence("it is commonly eaten salted, buttered, sweetened, or with artificial flavorings."),
 Sentence("a popcorn kernel strong hull contains the seed hard, starchy shell endosperm with 14–20% moisture, which turns to steam as the kernel is heated."),
 Sentence("pressure from the steam continues to build until the hull ruptures, allowing the kernel to forcefully expand, to 20 to 50 times its original size, and then cool."),
 Sentence("some strains of corn (taxonomized as zea mays) are cultivated specifically as popping corns."),
 Sentence("the zea mays variety everta, a special kind of flint corn, is the most common of these."),
 Sentence("popcorn is one of six major types of corn, alongside dent corn, flint corn, pod corn, flour corn, and sweet corn."),
 Sentence("history corn was domesticated about 9,000 years ago, in what is now the balsas river valley of central mexico."),
 Sentence("archaeologists discovered that people have known about popcorn for millennia."),
 Sentence("fossil evidence from peru suggests that corn was present there as early as 4,700 bce, and popped there over 1,000 years ago."),
 Sentence("between 2007 and 2011, evidence as early as 4,700 bce for popping corn was discovered as macrofossil cobs at the paredones and huaca prieta archaeological sites on the northern coast of peru."),
 Sentence("corn cultivation was present in amazon basin farming practices as evidenced by cultivation of corn in the amazon basin 6,000 years ago in 1948 and 1950, evidence as early as 3600 bce for popping corn as ears of popcorn were discovered by harvard anthropology graduate student herbert w. dick and harvard botany graduate student claude earle smith, junior (1922–1987), in a complex of rock shelters, dubbed the "bat cave", in catron county, west-central new mexico, and attributed to the ancestral puebloan peoples, who maintained trade networks with peoples in tropical mexico."),
 Sentence("through the 19th century, popping of the kernels was achieved by hand, on stove tops over flame."),
 Sentence("kernels were sold on the east coast of the united states under names such as pearls or nonpareil."),
 Sentence("the term popped corn first appeared in john russell bartlett 1848 dictionary of americanisms."),
 Sentence("popcorn is an ingredient in cracker jack and, in the early years of the product, it was popped by hand."),
 Sentence("popcorn accessibility increased rapidly in the 1890s with charles cretors invention of the popcorn maker."),
 Sentence("cretors, a chicago candy store owner, had created a number of steam-powered machines for roasting nuts and applied the technology to the corn kernels."),
 Sentence("by the turn of the century, cretors had created and deployed street carts equipped with steam-powered popcorn makers."),
 Sentence("during the great depression, popcorn was fairly inexpensive at 5–10 cents a bag and became popular."),
 Sentence("thus, while other businesses failed, the popcorn business thrived and became a source of income for many struggling farmers and entrepreneurs, including the redenbacher family, namesake of the orville redenbacher popcorn brand."),
 Sentence("during world war ii, sugar rations diminished candy production, and americans compensated by eating three times as much popcorn as they had before."),
 Sentence("the snack was popular at theaters, much to the initial displeasure of many of the theater owners, who thought it distracted from the films."),
 Sentence("their minds eventually changed, however, and in 1938 a midwestern theater owner named glen w. dickinson sr. installed popcorn machines in the lobbies of his dickinson theaters."),
 Sentence("popcorn was more profitable than theater tickets, and at the suggestion of his production consultant, r. ray aden, dickinson purchased popcorn farms and was able to keep ticket prices down."),
 Sentence("the venture was a success, and popcorn soon spread."),
 Sentence("the rise of television in the 1940s brought lower popcorn consumption as theater attendance fell."),
 Sentence("the popcorn institute, a trade association of popcorn processors, promoted popcorn consumption at home, bringing it back to previous levels."),
 Sentence("in 1970, orville redenbacher namesake brand of popcorn was launched."),
 Sentence("in 1981, general mills received the first patent for a microwave oven popcorn bag; popcorn consumption saw an increase."),
 Sentence("at least six localities (all in the midwestern united states) claim to be the "popcorn capital of the world;": ridgway, illinois; valparaiso, indiana; van buren, indiana; schaller, iowa; marion, ohio; and north loup, nebraska."),
 Sentence("according to the usda, specific corn for popcorn is grown mostly in nebraska and indiana, and increasingly in texas."),
 Sentence("as the result of an elementary school project, popcorn became the official state snack food of illinois."),
 Sentence("popping mechanism each kernel of popcorn contains moisture and oil."),
 Sentence("unlike most other grains, the outer hull of the popcorn kernel is strong and impervious to moisture, and the starch inside consists almost entirely of a hard type."),
 Sentence("as the oil and water in the kernel are heated, they turn into steam."),
 Sentence("under these conditions, the starch inside the kernel gelatinizes and softens."),
 Sentence("the steam pressure increases until the breaking point of the hull is reached: a pressure of approximately 930 kpa (135 psi) and a temperature of 180 °c (356 °f)."),
 Sentence("the hull ruptures, causing a sudden drop in pressure inside the kernel and a corresponding rapid expansion of the steam, which expands the starch and proteins of the endosperm into an airy foam."),
 Sentence("as the foam rapidly cools, the starch and protein polymers set into the familiar crispy puff."),
 Sentence("special varieties are grown to improve popping yield."),
 Sentence("though the kernels of some other types will pop, the cultivated strain for popcorn is zea mays everta, which is a variety of flint corn."),
 Sentence("cooking methods popcorn can be cooked with butter or oil."),
 Sentence("although small quantities can be popped in a stove-top kettle or pot in a home kitchen, commercial sale employs specially designed popcorn machines, which were invented in chicago, illinois, by charles cretors in 1885. cretors introduced his invention at the columbian exposition in 1893. at that fair, f.‍w."),
 Sentence("rueckheim introduced a molasses-flavored "candied popcorn", the first caramel corn; his brother, louis ruekheim, slightly altered the recipe and introduced it as cracker jack in 1896. cretors invention was the first patented steam-driven machine that popped corn in oil."),
 Sentence("previously, vendors popped corn by holding a wire basket over an open flame."),
 Sentence("at best, the result was hot, dry, and unevenly cooked."),
 Sentence("cretors machine popped corn in a mixture of one-third clarified butter, two-thirds lard, and salt."),
 Sentence("this mixture can withstand the 232 °c (450 °f) temperature needed to pop corn and produces little smoke."),
 Sentence("a fire under a boiler created steam that drove a small engine to drive gears, shaft, and the agitator that stirred the corn, and also powered a small puppet, "the toasty roasty man", an attention-getting amusement to attract business."),
 Sentence("a wire connected to the top of the cooking pan allowed the operator to disengage the drive mechanism, lift the cover, and dump popped corn into the storage bin beneath."),
 Sentence("exhaust from the steam engine was piped to a pan below the corn storage bin and kept freshly popped corn warm."),
 Sentence("excess steam was also used to operate a small, shrill whistle to attract attention."),
 Sentence("a different method of popcorn-making involves the "popcorn hammer", a large cast-iron canister that is sealed with a heavy lid and slowly turned over a fire in rotisserie fashion."),
 Sentence("expansion and yield popping results are sensitive to the rate at which the kernels are heated."),
 Sentence("if heated too quickly, the steam in the outer layers of the kernel can reach high pressures and rupture the hull before the starch in the center of the kernel can fully gelatinize, leading to partially popped kernels with hard centers."),
 Sentence("heating too slowly leads to entirely unpopped kernels: the tip of the kernel, where it attached to the cob, is not entirely moisture-proof, and when heated slowly, the steam can leak out of the tip fast enough to keep the pressure from rising sufficiently to break the hull and cause the pop."),
 Sentence("producers and sellers of popcorn consider two major factors in evaluating the quality of popcorn: what percentage of the kernels will pop, and how much each popped kernel expands."),
 Sentence("expansion is an important factor to both the consumer and vendor."),
 Sentence("for the consumer, larger pieces of popcorn tend to be more tender and are associated with higher quality."),
 Sentence("for the grower, distributor and vendor, expansion is closely correlated with profit: vendors such as theaters buy popcorn by weight and sell it by volume."),
 Sentence("for these reasons, higher-expansion popcorn fetches a higher profit per unit weight."),
 Sentence("popcorn will pop when freshly harvested, but not well; its high moisture content leads to poor expansion and chewy pieces of popcorn."),
 Sentence("kernels with a high moisture content are also susceptible to mold when stored."),
 Sentence("for these reasons, popcorn growers and distributors dry the kernels until they reach the moisture level at which they expand the most."),
 Sentence("this differs by variety and conditions, but is generally in the range of 14–15% moisture by weight."),
 Sentence("if the kernels are over-dried, the expansion rate will suffer and the percentage of kernels that pop will decline."),
 Sentence("old popcorn tends to dry out, lowering the yield."),
 Sentence("when the popcorn has finished popping, sometimes unpopped kernels remain."),
 Sentence("known in the popcorn industry as "old maids", these kernels fail to pop because they do not have enough moisture to create enough steam for an explosion."),
 Sentence("re-hydrating prior to popping usually results in eliminating the unpopped kernels."),
 Sentence("popcorn varieties are broadly categorized by the shape of the kernels, the color of the kernels, or the shape of the popped corn."),
 Sentence("while the kernels may come in a variety of colors, the popped corn is always off-yellow or white as it is only the hull (or pericarp) that is colored."),
 Sentence(""rice" type popcorn have a long kernel pointed at both ends; "pearl" type kernels are rounded at the top."),
 Sentence("commercial popcorn production has moved mostly to pearl types."),
 Sentence("historically, pearl popcorn were usually yellow and rice popcorn usually white."),
 Sentence("today both shapes are available in both colors, as well as others including black, red, mauve, purple, and variegated."),
 Sentence("mauve and purple popcorn usually have smaller and nutty kernels."),
 Sentence("commercial production is dominated by white and yellow."),
 Sentence("terminology in the popcorn industry, a popped kernel of corn is known as a "flake"."),
 Sentence("two shapes of flakes are commercially important."),
 Sentence(""butterfly" (or "snowflake") flakes are irregular in shape and have a number of protruding "wings"."),
 Sentence(""mushroom" flakes are largely ball-shaped, with few wings."),
 Sentence("butterfly flakes are regarded as having better mouthfeel, with greater tenderness and less noticeable hulls."),
 Sentence("mushroom flakes are less fragile than butterfly flakes and are therefore often used for packaged popcorn or confectionery, such as caramel corn."),
 Sentence("the kernels from a single cob of popcorn may form both butterfly and mushroom flakes; hybrids that produce 100% butterfly flakes or 100% mushroom flakes exist, the latter developed only as recently as 1998. consumption popcorn is a popular snack food at sporting events and in movie theaters, where it has been served since the 1930s."),
 Sentence("cinemas have come under fire due to their high markup on popcorn; stuart hanson, a film historian at de montfort university in leicester, once said, "one of the great jokes in the industry is that popcorn is second only to cocaine or heroin in terms of profit.""),
 Sentence("traditions differ as to whether popcorn is consumed as a hearty snack food with salt (predominating in the united states) or as a sweet snack food with caramelized sugar (predominating in germany)."),
 Sentence("popcorn customs around savory, salty, and sweet flavors vary by region and demographic, but in the u.s., preferences are diverse and evolving: popcorn smell has an unusually attractive quality for human beings."),
 Sentence("this is largely because it contains high levels of the chemicals 6-acetyl-2,3,4,5-tetrahydropyridine and 2-acetyl-1-pyrroline, very powerful aroma compounds that are also used by food and other industries either to make products that smell like popcorn, bread, or other foods containing the compound in nature, or for other purposes."),
 Sentence("popcorn as a breakfast cereal was consumed by americans in the 1800s and generally consisted of popcorn with milk and a sweetener."),
 Sentence("popcorn balls (popped kernels stuck together with a sugary "glue") were hugely popular around the turn of the 20th century, but their popularity has since waned."),
 Sentence("popcorn balls are still served in some places as a traditional halloween treat."),
 Sentence("cracker jack is a popular, commercially produced candy that consists of peanuts mixed in with caramel-covered popcorn."),
 Sentence("kettle corn is a variation of normal popcorn, cooked with white sugar and salt, traditionally in a large copper kettle."),
 Sentence("once reserved for specialty shops and county fairs, kettle corn has recently become popular, especially in the microwave popcorn market."),
 Sentence("the popcorn maker is a relatively new home appliance, and its popularity is increasing because it offers the opportunity to add flavors of the consumer own choice and to choose healthy-eating popcorn styles."),
 Sentence("popped sorghum is popular as a snack in india."),
 Sentence("the popped sorghum is similar to popcorn, but the puffs are smaller."),
 Sentence("recipes for popping sorghum by microwave, in a pot, etc., are readily available online."),
 Sentence("nutritional value air-popped popcorn (no salt or other additives) is 4% water, 78% carbohydrates (including 15% dietary fiber), 12% protein, and 4% fat (table)."),
 Sentence("in a 100 gram reference amount, popcorn provides 382 calories and is a rich source (20% or more of the daily value, dv) of riboflavin (25% dv) and several dietary minerals, particularly manganese, phosphorus, and zinc (36–45% dv)."),
 Sentence("b vitamins and other minerals are in appreciable amounts (table)."),
 Sentence("saturated fat movie theaters commonly use coconut oil to pop the corn, and then top it with butter or margarine."),
 Sentence("movie theater popcorn contains large amounts of saturated fats and sodium due to its method of preparation."),
 Sentence("phytochemicals sorghum grains can be popped to form popcorn."),
 Sentence("all sorghums contain phenolic acids, and most contain flavonoids."),
 Sentence("sorghum grains are one of the highest food sources of the flavonoid proanthocyanidin."),
 Sentence("health risks popcorn is included on the list of foods that the american academy of pediatrics recommends not serving to children under four, because of the risk of choking."),
 Sentence("microwaveable popcorn represents a special case, since it is designed to be cooked along with its various flavoring agents."),
 Sentence("one of these formerly common artificial-butter flavorants, diacetyl, has been implicated in causing respiratory illnesses in microwave popcorn factory workers, also known as "popcorn lung"."),
 Sentence("major manufacturers in the united states have stopped using this chemical, including orville redenbacher , act ii, pop secret and jolly time."),
 Sentence("other uses popcorn, threaded onto a string, is used as a wall or christmas tree decoration in some parts of north america, as well as on the balkan peninsula."),
 Sentence("some shipping companies have experimented with using popcorn as a biodegradable replacement for expanded polystyrene packing material."),
 Sentence("however, popcorn has numerous undesirable properties as a packing material, including attractiveness to pests, flammability, and a higher cost and greater density than expanded polystyrene."),
 Sentence("a more processed form of expanded corn foam has been developed to overcome some of these limitations, forming starch-based foam peanuts."),
 Sentence("see also references notes further reading hallauer, arnel r. (2001)."),
 Sentence("specialty corns."),
 Sentence("crc press."),
 Sentence("isbn 978-0-8493-2377-5. lusas, edmund w.; rooney, lloyd w. (2001)."),
 Sentence("snack foods processing."),
 Sentence("crc press."),
 Sentence("isbn 978-1-56676-932-7. smith, andrew f. (1999)."),
 Sentence("popped culture: the social history of popcorn in america."),
 Sentence("university of south carolina press."),
 Sentence("isbn 978-1-57003-300-1.")]

In [ ]:
#Convert text blob sentences to strings
my_sentences_str = [ str(x) for x in my_sentences ]
my_sentences_str

['popcorn (also called popped corn, popcorns, or pop-corn) is a variety of corn kernel which expands and puffs up when heated.',
 'the term also refers to the snack food produced by the expansion.',
 'it is one of the oldest snacks, with evidence of popcorn dating back thousands of years in the americas.',
 'it is commonly eaten salted, buttered, sweetened, or with artificial flavorings.',
 'a popcorn kernel strong hull contains the seed hard, starchy shell endosperm with 14–20% moisture, which turns to steam as the kernel is heated.',
 'pressure from the steam continues to build until the hull ruptures, allowing the kernel to forcefully expand, to 20 to 50 times its original size, and then cool.',
 'some strains of corn (taxonomized as zea mays) are cultivated specifically as popping corns.',
 'the zea mays variety everta, a special kind of flint corn, is the most common of these.',
 'popcorn is one of six major types of corn, alongside dent corn, flint corn, pod corn, flour corn, and sweet corn.',
 'history corn was domesticated about 9,000 years ago, in what is now the balsas river valley of central mexico.',
 'archaeologists discovered that people have known about popcorn for millennia.',
 'fossil evidence from peru suggests that corn was present there as early as 4,700 bce, and popped there over 1,000 years ago.',
 'between 2007 and 2011, evidence as early as 4,700 bce for popping corn was discovered as macrofossil cobs at the paredones and huaca prieta archaeological sites on the northern coast of peru.',
 'corn cultivation was present in amazon basin farming practices as evidenced by cultivation of corn in the amazon basin 6,000 years ago in 1948 and 1950, evidence as early as 3600 bce for popping corn as ears of popcorn were discovered by harvard anthropology graduate student herbert w. dick and harvard botany graduate student claude earle smith, junior (1922–1987), in a complex of rock shelters, dubbed the "bat cave", in catron county, west-central new mexico, and attributed to the ancestral puebloan peoples, who maintained trade networks with peoples in tropical mexico.',
 'through the 19th century, popping of the kernels was achieved by hand, on stove tops over flame.',
 'kernels were sold on the east coast of the united states under names such as pearls or nonpareil.',
 'the term popped corn first appeared in john russell bartlett 1848 dictionary of americanisms.',
 'popcorn is an ingredient in cracker jack and, in the early years of the product, it was popped by hand.',
 'popcorn accessibility increased rapidly in the 1890s with charles cretors invention of the popcorn maker.',
 'cretors, a chicago candy store owner, had created a number of steam-powered machines for roasting nuts and applied the technology to the corn kernels.',
 'by the turn of the century, cretors had created and deployed street carts equipped with steam-powered popcorn makers.',
 'during the great depression, popcorn was fairly inexpensive at 5–10 cents a bag and became popular.',
 'thus, while other businesses failed, the popcorn business thrived and became a source of income for many struggling farmers and entrepreneurs, including the redenbacher family, namesake of the orville redenbacher popcorn brand.',
 'during world war ii, sugar rations diminished candy production, and americans compensated by eating three times as much popcorn as they had before.',
 'the snack was popular at theaters, much to the initial displeasure of many of the theater owners, who thought it distracted from the films.',
 'their minds eventually changed, however, and in 1938 a midwestern theater owner named glen w. dickinson sr. installed popcorn machines in the lobbies of his dickinson theaters.',
 'popcorn was more profitable than theater tickets, and at the suggestion of his production consultant, r. ray aden, dickinson purchased popcorn farms and was able to keep ticket prices down.',
 'the venture was a success, and popcorn soon spread.',
 'the rise of television in the 1940s brought lower popcorn consumption as theater attendance fell.',
 'the popcorn institute, a trade association of popcorn processors, promoted popcorn consumption at home, bringing it back to previous levels.',
 'in 1970, orville redenbacher namesake brand of popcorn was launched.',
 'in 1981, general mills received the first patent for a microwave oven popcorn bag; popcorn consumption saw an increase.',
 'at least six localities (all in the midwestern united states) claim to be the "popcorn capital of the world;": ridgway, illinois; valparaiso, indiana; van buren, indiana; schaller, iowa; marion, ohio; and north loup, nebraska.',
 'according to the usda, specific corn for popcorn is grown mostly in nebraska and indiana, and increasingly in texas.',
 'as the result of an elementary school project, popcorn became the official state snack food of illinois.',
 'popping mechanism each kernel of popcorn contains moisture and oil.',
 'unlike most other grains, the outer hull of the popcorn kernel is strong and impervious to moisture, and the starch inside consists almost entirely of a hard type.',
 'as the oil and water in the kernel are heated, they turn into steam.',
 'under these conditions, the starch inside the kernel gelatinizes and softens.',
 'the steam pressure increases until the breaking point of the hull is reached: a pressure of approximately 930 kpa (135 psi) and a temperature of 180 °c (356 °f).',
 'the hull ruptures, causing a sudden drop in pressure inside the kernel and a corresponding rapid expansion of the steam, which expands the starch and proteins of the endosperm into an airy foam.',
 'as the foam rapidly cools, the starch and protein polymers set into the familiar crispy puff.',
 'special varieties are grown to improve popping yield.',
 'though the kernels of some other types will pop, the cultivated strain for popcorn is zea mays everta, which is a variety of flint corn.',
 'cooking methods popcorn can be cooked with butter or oil.',
 'although small quantities can be popped in a stove-top kettle or pot in a home kitchen, commercial sale employs specially designed popcorn machines, which were invented in chicago, illinois, by charles cretors in 1885. cretors introduced his invention at the columbian exposition in 1893. at that fair, f.\u200dw.',
 'rueckheim introduced a molasses-flavored "candied popcorn", the first caramel corn; his brother, louis ruekheim, slightly altered the recipe and introduced it as cracker jack in 1896. cretors invention was the first patented steam-driven machine that popped corn in oil.',
 'previously, vendors popped corn by holding a wire basket over an open flame.',
 'at best, the result was hot, dry, and unevenly cooked.',
 'cretors machine popped corn in a mixture of one-third clarified butter, two-thirds lard, and salt.',
 'this mixture can withstand the 232 °c (450 °f) temperature needed to pop corn and produces little smoke.',
 'a fire under a boiler created steam that drove a small engine to drive gears, shaft, and the agitator that stirred the corn, and also powered a small puppet, "the toasty roasty man", an attention-getting amusement to attract business.',
 'a wire connected to the top of the cooking pan allowed the operator to disengage the drive mechanism, lift the cover, and dump popped corn into the storage bin beneath.',
 'exhaust from the steam engine was piped to a pan below the corn storage bin and kept freshly popped corn warm.',
 'excess steam was also used to operate a small, shrill whistle to attract attention.',
 'a different method of popcorn-making involves the "popcorn hammer", a large cast-iron canister that is sealed with a heavy lid and slowly turned over a fire in rotisserie fashion.',
 'expansion and yield popping results are sensitive to the rate at which the kernels are heated.',
 'if heated too quickly, the steam in the outer layers of the kernel can reach high pressures and rupture the hull before the starch in the center of the kernel can fully gelatinize, leading to partially popped kernels with hard centers.',
 'heating too slowly leads to entirely unpopped kernels: the tip of the kernel, where it attached to the cob, is not entirely moisture-proof, and when heated slowly, the steam can leak out of the tip fast enough to keep the pressure from rising sufficiently to break the hull and cause the pop.',
 'producers and sellers of popcorn consider two major factors in evaluating the quality of popcorn: what percentage of the kernels will pop, and how much each popped kernel expands.',
 'expansion is an important factor to both the consumer and vendor.',
 'for the consumer, larger pieces of popcorn tend to be more tender and are associated with higher quality.',
 'for the grower, distributor and vendor, expansion is closely correlated with profit: vendors such as theaters buy popcorn by weight and sell it by volume.',
 'for these reasons, higher-expansion popcorn fetches a higher profit per unit weight.',
 'popcorn will pop when freshly harvested, but not well; its high moisture content leads to poor expansion and chewy pieces of popcorn.',
 'kernels with a high moisture content are also susceptible to mold when stored.',
 'for these reasons, popcorn growers and distributors dry the kernels until they reach the moisture level at which they expand the most.',
 'this differs by variety and conditions, but is generally in the range of 14–15% moisture by weight.',
 'if the kernels are over-dried, the expansion rate will suffer and the percentage of kernels that pop will decline.',
 'old popcorn tends to dry out, lowering the yield.',
 'when the popcorn has finished popping, sometimes unpopped kernels remain.',
 'known in the popcorn industry as "old maids", these kernels fail to pop because they do not have enough moisture to create enough steam for an explosion.',
 're-hydrating prior to popping usually results in eliminating the unpopped kernels.',
 'popcorn varieties are broadly categorized by the shape of the kernels, the color of the kernels, or the shape of the popped corn.',
 'while the kernels may come in a variety of colors, the popped corn is always off-yellow or white as it is only the hull (or pericarp) that is colored.',
 '"rice" type popcorn have a long kernel pointed at both ends; "pearl" type kernels are rounded at the top.',
 'commercial popcorn production has moved mostly to pearl types.',
 'historically, pearl popcorn were usually yellow and rice popcorn usually white.',
 'today both shapes are available in both colors, as well as others including black, red, mauve, purple, and variegated.',
 'mauve and purple popcorn usually have smaller and nutty kernels.',
 'commercial production is dominated by white and yellow.',
 'terminology in the popcorn industry, a popped kernel of corn is known as a "flake".',
 'two shapes of flakes are commercially important.',
 '"butterfly" (or "snowflake") flakes are irregular in shape and have a number of protruding "wings".',
 '"mushroom" flakes are largely ball-shaped, with few wings.',
 'butterfly flakes are regarded as having better mouthfeel, with greater tenderness and less noticeable hulls.',
 'mushroom flakes are less fragile than butterfly flakes and are therefore often used for packaged popcorn or confectionery, such as caramel corn.',
 'the kernels from a single cob of popcorn may form both butterfly and mushroom flakes; hybrids that produce 100% butterfly flakes or 100% mushroom flakes exist, the latter developed only as recently as 1998. consumption popcorn is a popular snack food at sporting events and in movie theaters, where it has been served since the 1930s.',
 'cinemas have come under fire due to their high markup on popcorn; stuart hanson, a film historian at de montfort university in leicester, once said, "one of the great jokes in the industry is that popcorn is second only to cocaine or heroin in terms of profit."',
 'traditions differ as to whether popcorn is consumed as a hearty snack food with salt (predominating in the united states) or as a sweet snack food with caramelized sugar (predominating in germany).',
 'popcorn customs around savory, salty, and sweet flavors vary by region and demographic, but in the u.s., preferences are diverse and evolving: popcorn smell has an unusually attractive quality for human beings.',
 'this is largely because it contains high levels of the chemicals 6-acetyl-2,3,4,5-tetrahydropyridine and 2-acetyl-1-pyrroline, very powerful aroma compounds that are also used by food and other industries either to make products that smell like popcorn, bread, or other foods containing the compound in nature, or for other purposes.',
 'popcorn as a breakfast cereal was consumed by americans in the 1800s and generally consisted of popcorn with milk and a sweetener.',
 'popcorn balls (popped kernels stuck together with a sugary "glue") were hugely popular around the turn of the 20th century, but their popularity has since waned.',
 'popcorn balls are still served in some places as a traditional halloween treat.',
 'cracker jack is a popular, commercially produced candy that consists of peanuts mixed in with caramel-covered popcorn.',
 'kettle corn is a variation of normal popcorn, cooked with white sugar and salt, traditionally in a large copper kettle.',
 'once reserved for specialty shops and county fairs, kettle corn has recently become popular, especially in the microwave popcorn market.',
 'the popcorn maker is a relatively new home appliance, and its popularity is increasing because it offers the opportunity to add flavors of the consumer own choice and to choose healthy-eating popcorn styles.',
 'popped sorghum is popular as a snack in india.',
 'the popped sorghum is similar to popcorn, but the puffs are smaller.',
 'recipes for popping sorghum by microwave, in a pot, etc., are readily available online.',
 'nutritional value air-popped popcorn (no salt or other additives) is 4% water, 78% carbohydrates (including 15% dietary fiber), 12% protein, and 4% fat (table).',
 'in a 100 gram reference amount, popcorn provides 382 calories and is a rich source (20% or more of the daily value, dv) of riboflavin (25% dv) and several dietary minerals, particularly manganese, phosphorus, and zinc (36–45% dv).',
 'b vitamins and other minerals are in appreciable amounts (table).',
 'saturated fat movie theaters commonly use coconut oil to pop the corn, and then top it with butter or margarine.',
 'movie theater popcorn contains large amounts of saturated fats and sodium due to its method of preparation.',
 'phytochemicals sorghum grains can be popped to form popcorn.',
 'all sorghums contain phenolic acids, and most contain flavonoids.',
 'sorghum grains are one of the highest food sources of the flavonoid proanthocyanidin.',
 'health risks popcorn is included on the list of foods that the american academy of pediatrics recommends not serving to children under four, because of the risk of choking.',
 'microwaveable popcorn represents a special case, since it is designed to be cooked along with its various flavoring agents.',
 'one of these formerly common artificial-butter flavorants, diacetyl, has been implicated in causing respiratory illnesses in microwave popcorn factory workers, also known as "popcorn lung".',
 'major manufacturers in the united states have stopped using this chemical, including orville redenbacher , act ii, pop secret and jolly time.',
 'other uses popcorn, threaded onto a string, is used as a wall or christmas tree decoration in some parts of north america, as well as on the balkan peninsula.',
 'some shipping companies have experimented with using popcorn as a biodegradable replacement for expanded polystyrene packing material.',
 'however, popcorn has numerous undesirable properties as a packing material, including attractiveness to pests, flammability, and a higher cost and greater density than expanded polystyrene.',
 'a more processed form of expanded corn foam has been developed to overcome some of these limitations, forming starch-based foam peanuts.',
 'see also references notes further reading hallauer, arnel r. (2001).',
 'specialty corns.',
 'crc press.',
 'isbn 978-0-8493-2377-5. lusas, edmund w.; rooney, lloyd w. (2001).',
 'snack foods processing.',
 'crc press.',
 'isbn 978-1-56676-932-7. smith, andrew f. (1999).',
 'popped culture: the social history of popcorn in america.',
 'university of south carolina press.',
 'isbn 978-1-57003-300-1.']

In [ ]:
#Perform the TF-IDF Vectorization
tf_idf_vec = TfidfVectorizer(stop_words = 'english')
tf_idf_pop = tf_idf_vec.fit_transform(my_sentences_str)
tf_idf_pop.shape

(128, 878)

In [ ]:
128*878

112384

In [ ]:
tf_idf_pop

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1440 stored elements and shape (128, 878)>

In [ ]:
tf_idf_pop.transpose().shape

(878, 128)

In [ ]:
np.set_printoptions(precision=6, formatter=None)
tf_idf_vec.get_feature_names_out()

array(['000', '10', '100', '12', '135', '14', '15', '180', '1800s',
       '1848', '1885', '1890s', '1893', '1896', '1922', '1930s', '1938',
       '1940s', '1948', '1950', '1970', '1981', '1987', '1998', '1999',
       '19th', '20', '2001', '2007', '2011', '20th', '232', '2377', '25',
       '300', '356', '36', '3600', '382', '45', '450', '50', '56676',
       '57003', '700', '78', '8493', '930', '932', '978', 'able',
       'academy', 'accessibility', 'according', 'acetyl', 'achieved',
       'acids', 'act', 'add', 'additives', 'aden', 'agents', 'agitator',
       'ago', 'air', 'airy', 'allowed', 'allowing', 'alongside',
       'altered', 'amazon', 'america', 'american', 'americanisms',
       'americans', 'americas', 'amounts', 'amusement', 'ancestral',
       'andrew', 'anthropology', 'appeared', 'appliance', 'applied',
       'appreciable', 'approximately', 'archaeological', 'archaeologists',
       'arnel', 'aroma', 'artificial', 'associated', 'association',
       'attached', 'attendance', 'attention', 'attract', 'attractive',
       'attractiveness', 'attributed', 'available', 'bag', 'balkan',
       'ball', 'balls', 'balsas', 'bartlett', 'based', 'basin', 'basket',
       'bat', 'bce', 'beings', 'beneath', 'best', 'better', 'bin',
       'biodegradable', 'black', 'boiler', 'botany', 'brand', 'bread',
       'break', 'breakfast', 'breaking', 'bringing', 'broadly', 'brother',
       'brought', 'build', 'buren', 'business', 'businesses', 'butter',
       'buttered', 'butterfly', 'buy', 'called', 'calories', 'candied',
       'candy', 'canister', 'capital', 'caramel', 'caramelized',
       'carbohydrates', 'carolina', 'carts', 'case', 'cast',
       'categorized', 'catron', 'cause', 'causing', 'cave', 'center',
       'centers', 'central', 'cents', 'century', 'cereal', 'changed',
       'charles', 'chemical', 'chemicals', 'chewy', 'chicago', 'children',
       'choice', 'choking', 'choose', 'christmas', 'cinemas', 'claim',
       'clarified', 'claude', 'closely', 'coast', 'cob', 'cobs',
       'cocaine', 'coconut', 'color', 'colored', 'colors', 'columbian',
       'come', 'commercial', 'commercially', 'common', 'commonly',
       'companies', 'compensated', 'complex', 'compound', 'compounds',
       'conditions', 'confectionery', 'connected', 'consider',
       'consisted', 'consists', 'consultant', 'consumed', 'consumer',
       'consumption', 'contain', 'containing', 'contains', 'content',
       'continues', 'cooked', 'cooking', 'cool', 'cools', 'copper',
       'corn', 'corns', 'correlated', 'corresponding', 'cost', 'county',
       'cover', 'covered', 'cracker', 'crc', 'create', 'created',
       'cretors', 'crispy', 'cultivated', 'cultivation', 'culture',
       'customs', 'daily', 'dating', 'decline', 'decoration',
       'demographic', 'density', 'dent', 'deployed', 'depression',
       'designed', 'developed', 'diacetyl', 'dick', 'dickinson',
       'dictionary', 'dietary', 'differ', 'different', 'differs',
       'diminished', 'discovered', 'disengage', 'displeasure',
       'distracted', 'distributor', 'distributors', 'diverse',
       'domesticated', 'dominated', 'dried', 'drive', 'driven', 'drop',
       'drove', 'dry', 'dubbed', 'dump', 'dv', 'earle', 'early', 'ears',
       'east', 'eaten', 'eating', 'edmund', 'elementary', 'eliminating',
       'employs', 'endosperm', 'ends', 'engine', 'entirely',
       'entrepreneurs', 'equipped', 'especially', 'evaluating', 'events',
       'eventually', 'everta', 'evidence', 'evidenced', 'evolving',
       'excess', 'exhaust', 'exist', 'expand', 'expanded', 'expands',
       'expansion', 'experimented', 'explosion', 'exposition', 'factor',
       'factors', 'factory', 'fail', 'failed', 'fair', 'fairly', 'fairs',
       'familiar', 'family', 'farmers', 'farming', 'farms', 'fashion',
       'fast', 'fat', 'fats', 'fell', 'fetches', 'fiber', 'film', 'films',
       'finished', 'flake', 'flakes', 'flame', 'flammability',
       'flavonoid', 'flavonoids', 'flavorants', 'flavored', 'flavoring',
       'flavorings', 'flavors', 'flint', 'flour', 'foam', 'food', 'foods',
       'forcefully', 'form', 'forming', 'fossil', 'fragile', 'freshly',
       'fully', 'gears', 'gelatinize', 'gelatinizes', 'general',
       'generally', 'germany', 'getting', 'glen', 'glue', 'graduate',
       'grains', 'gram', 'great', 'greater', 'grower', 'growers', 'grown',
       'hallauer', 'halloween', 'hammer', 'hand', 'hanson', 'hard',
       'harvard', 'harvested', 'having', 'health', 'healthy', 'hearty',
       'heated', 'heating', 'heavy', 'herbert', 'heroin', 'high',
       'higher', 'highest', 'historian', 'historically', 'history',
       'holding', 'home', 'hot', 'huaca', 'hugely', 'hull', 'hulls',
       'human', 'hybrids', 'hydrating', 'ii', 'illinois', 'illnesses',
       'impervious', 'implicated', 'important', 'improve', 'included',
       'including', 'income', 'increase', 'increased', 'increases',
       'increasing', 'increasingly', 'india', 'indiana', 'industries',
       'industry', 'inexpensive', 'ingredient', 'initial', 'inside',
       'installed', 'institute', 'introduced', 'invented', 'invention',
       'involves', 'iowa', 'iron', 'irregular', 'isbn', 'jack', 'john',
       'jokes', 'jolly', 'junior', 'kept', 'kernel', 'kernels', 'kettle',
       'kind', 'kitchen', 'known', 'kpa', 'lard', 'large', 'largely',
       'larger', 'launched', 'layers', 'leading', 'leads', 'leak',
       'leicester', 'level', 'levels', 'lid', 'lift', 'like',
       'limitations', 'list', 'little', 'lloyd', 'lobbies', 'localities',
       'long', 'louis', 'loup', 'lower', 'lowering', 'lung', 'lusas',
       'machine', 'machines', 'macrofossil', 'maids', 'maintained',
       'major', 'make', 'maker', 'makers', 'making', 'man', 'manganese',
       'manufacturers', 'margarine', 'marion', 'market', 'markup',
       'material', 'mauve', 'mays', 'mechanism', 'method', 'methods',
       'mexico', 'microwave', 'microwaveable', 'midwestern', 'milk',
       'millennia', 'mills', 'minds', 'minerals', 'mixed', 'mixture',
       'moisture', 'molasses', 'mold', 'montfort', 'mouthfeel', 'moved',
       'movie', 'mushroom', 'named', 'names', 'namesake', 'nature',
       'nebraska', 'needed', 'networks', 'new', 'nonpareil', 'normal',
       'north', 'northern', 'notes', 'noticeable', 'number', 'numerous',
       'nutritional', 'nuts', 'nutty', 'offers', 'official', 'ohio',
       'oil', 'old', 'oldest', 'online', 'open', 'operate', 'operator',
       'opportunity', 'original', 'orville', 'outer', 'oven', 'overcome',
       'owner', 'owners', 'packaged', 'packing', 'pan', 'paredones',
       'partially', 'particularly', 'parts', 'patent', 'patented',
       'peanuts', 'pearl', 'pearls', 'pediatrics', 'peninsula', 'people',
       'peoples', 'percentage', 'pericarp', 'peru', 'pests', 'phenolic',
       'phosphorus', 'phytochemicals', 'pieces', 'piped', 'places', 'pod',
       'point', 'pointed', 'polymers', 'polystyrene', 'poor', 'pop',
       'popcorn', 'popcorns', 'popped', 'popping', 'popular',
       'popularity', 'pot', 'powered', 'powerful', 'practices',
       'predominating', 'preferences', 'preparation', 'present', 'press',
       'pressure', 'pressures', 'previous', 'previously', 'prices',
       'prieta', 'prior', 'proanthocyanidin', 'processed', 'processing',
       'processors', 'produce', 'produced', 'producers', 'produces',
       'product', 'production', 'products', 'profit', 'profitable',
       'project', 'promoted', 'proof', 'properties', 'protein',
       'proteins', 'protruding', 'provides', 'psi', 'puebloan', 'puff',
       'puffs', 'puppet', 'purchased', 'purple', 'purposes', 'pyrroline',
       'quality', 'quantities', 'quickly', 'range', 'rapid', 'rapidly',
       'rate', 'rations', 'ray', 'reach', 'reached', 'readily', 'reading',
       'reasons', 'received', 'recently', 'recipe', 'recipes',
       'recommends', 'red', 'redenbacher', 'reference', 'references',
       'refers', 'regarded', 'region', 'relatively', 'remain',
       'replacement', 'represents', 'reserved', 'respiratory', 'result',
       'results', 'riboflavin', 'rice', 'rich', 'ridgway', 'rise',
       'rising', 'risk', 'risks', 'river', 'roasting', 'roasty', 'rock',
       'rooney', 'rotisserie', 'rounded', 'rueckheim', 'ruekheim',
       'rupture', 'ruptures', 'russell', 'said', 'sale', 'salt', 'salted',
       'salty', 'saturated', 'savory', 'saw', 'schaller', 'school',
       'sealed', 'second', 'secret', 'seed', 'sell', 'sellers',
       'sensitive', 'served', 'serving', 'set', 'shaft', 'shape',
       'shaped', 'shapes', 'shell', 'shelters', 'shipping', 'shops',
       'shrill', 'similar', 'single', 'sites', 'size', 'slightly',
       'slowly', 'small', 'smaller', 'smell', 'smith', 'smoke', 'snack',
       'snacks', 'snowflake', 'social', 'sodium', 'softens', 'sold',
       'soon', 'sorghum', 'sorghums', 'source', 'sources', 'south',
       'special', 'specially', 'specialty', 'specific', 'specifically',
       'sporting', 'spread', 'sr', 'starch', 'starchy', 'state', 'states',
       'steam', 'stirred', 'stopped', 'storage', 'store', 'stored',
       'stove', 'strain', 'strains', 'street', 'string', 'strong',
       'struggling', 'stuart', 'stuck', 'student', 'styles', 'success',
       'sudden', 'suffer', 'sufficiently', 'sugar', 'sugary',
       'suggestion', 'suggests', 'susceptible', 'sweet', 'sweetened',
       'sweetener', 'table', 'taxonomized', 'technology', 'television',
       'temperature', 'tend', 'tender', 'tenderness', 'tends', 'term',
       'terminology', 'terms', 'tetrahydropyridine', 'texas', 'theater',
       'theaters', 'thirds', 'thought', 'thousands', 'threaded',
       'thrived', 'ticket', 'tickets', 'time', 'times', 'tip', 'toasty',
       'today', 'tops', 'trade', 'traditional', 'traditionally',
       'traditions', 'treat', 'tree', 'tropical', 'turn', 'turned',
       'turns', 'type', 'types', 'undesirable', 'unevenly', 'unit',
       'united', 'university', 'unlike', 'unpopped', 'unusually', 'usda',
       'use', 'used', 'uses', 'using', 'usually', 'valley', 'valparaiso',
       'value', 'van', 'variation', 'variegated', 'varieties', 'variety',
       'various', 'vary', 'vendor', 'vendors', 'venture', 'vitamins',
       'volume', 'wall', 'waned', 'war', 'warm', 'water', 'weight',
       'west', 'whistle', 'white', 'wings', 'wire', 'withstand',
       'workers', 'world', 'years', 'yellow', 'yield', 'zea', 'zinc'],
      dtype=object)

In [ ]:
for w in ['use', 'used', 'uses', 'using']:
  print(f"stem: {w} -> {TextBlob(w).words[0].stem()}")

for w in ['use', 'used', 'uses', 'using']:
  print(f"lemmatize: {w} -> {TextBlob(w).words[0].lemmatize()}")

for w in ['use', 'used', 'uses', 'using']:
  print(f"singularize: {w} -> {TextBlob(w).words[0].singularize()}")

stem: use -> use
stem: used -> use
stem: uses -> use
stem: using -> use
lemmatize: use -> use
lemmatize: used -> used
lemmatize: uses -> us
lemmatize: using -> using
singularize: use -> use
singularize: used -> used
singularize: uses -> use
singularize: using -> using

In [ ]:
#Print out results in a dataframe
tf_df = pd.DataFrame(tf_idf_pop.toarray(), columns = tf_idf_vec.get_feature_names_out())
tf_df.transpose()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,...,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127
000,0.0,0.0,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.290129,0.0,0.283972,0.0,0.100540,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.369332,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100,0.0,0.0,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.332144,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.170849,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.261483,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
135,0.0,0.0,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.254568,0.0,0.0,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
years,0.0,0.0,0.31138,0.0,0.0,0.0,0.000000,0.000000,0.0,0.263833,0.0,0.258234,0.0,0.091428,0.0,0.0,0.0,0.320648,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
yellow,0.0,0.0,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.441109,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
yield,0.0,0.0,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.401666,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
zea,0.0,0.0,0.00000,0.0,0.0,0.0,0.329954,0.338147,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.3183,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
zinc,0.0,0.0,0.00000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.185398,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
#Get a data frame with the TF-IDF values sorted for document 0
df = pd.DataFrame(tf_idf_pop[0].T.todense(), index=tf_idf_vec.get_feature_names_out(), columns=["TF-IDF"])
df = df.sort_values('TF-IDF', ascending=False)
df[:5]

            TF-IDF
corn      0.513506
called    0.349884
popcorns  0.349884
puffs     0.322426
expands   0.302945

In [ ]:
tf_df.T[[0]].sort_values([0], ascending=False)[:5]

                 0
corn      0.513506
called    0.349884
popcorns  0.349884
puffs     0.322426
expands   0.302945

In [ ]:
(tf_idf_pop[0].T.todense())

matrix([[0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.349884],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.513506],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.302945],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.265048],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.218108],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.23444 ],
        [0.109118],
        [0.349884],
        [0.1875  ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.322426],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.275487],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ],
        [0.      ]])