<a href="https://colab.research.google.com/github/stephanie465337/Data-Science-Portfolio-C21/blob/main/NotebookLM/Module%205/3c_K_Nearest_Neighbors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

from textblob import TextBlob
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors

pd.options.display.max_columns = 100

import nltk
# nltk.download('omw-1.4')
nltk.download('punkt_tab')
# nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

### Gary Example

In [ ]:
my_df = pd.DataFrame()
my_df["names"] = ['Amantha', 'Brendon', 'Nate', 'Sam', 'Betty', 'Christine', 'Gin', 'Ken', 'Susy']
my_df["ages"] = [ 19, 23, 24, 30, 16, 18, 22, 18, 15 ]
my_df["genders_txt"] = "female male male male female female female male female".split()
my_df["genders"] = [ 1, 0, 0, 0, 1, 1, 1, 0, 1 ]
my_df["music_band_txt"] = "Coldplay Coldplay LinkinPark LinkinPark Coldplay LinkinPark LinkinPark Coldplay Coldplay".split()

my_df

       names  ages genders_txt  genders music_band_txt
0    Amantha    19      female        1       Coldplay
1    Brendon    23        male        0       Coldplay
2       Nate    24        male        0     LinkinPark
3        Sam    30        male        0     LinkinPark
4      Betty    16      female        1       Coldplay
5  Christine    18      female        1     LinkinPark
6        Gin    22      female        1     LinkinPark
7        Ken    18        male        0       Coldplay
8       Susy    15      female        1       Coldplay

In [ ]:
my_df.select_dtypes("int")

   ages  genders
0    19        1
1    23        0
2    24        0
3    30        0
4    16        1
5    18        1
6    22        1
7    18        0
8    15        1

Fit nearest neighbors

In [ ]:
nn = NearestNeighbors().fit(my_df.select_dtypes("int"))

Get nearest neighbors distances

In [ ]:
gary = pd.DataFrame({"ages":[23], "genders":[0]})
gary

   ages  genders
0    23        0

In [ ]:
distances, indices = nn.kneighbors(
  X = gary,
  n_neighbors = 3,
)

In [ ]:
distances[0]**2

array([0., 1., 2.])

In [ ]:
indices[0]

array([1, 2, 6])

Get people matching index

In [ ]:
my_df.iloc[indices[0]]

     names  ages genders_txt  genders music_band_txt
1  Brendon    23        male        0       Coldplay
2     Nate    24        male        0     LinkinPark
6      Gin    22      female        1     LinkinPark

Vote

In [ ]:
my_df.iloc[indices[0]]["music_band_txt"].mode()[0]

'LinkinPark'

Repeat with K = all rows

In [ ]:
d_i = nn.kneighbors(gary, n_neighbors = my_df.shape[0])
distances, indices = np.array(d_i).reshape(2,9)
distances**2, indices

(array([ 0.,  1.,  2., 17., 25., 26., 49., 50., 65.]),
 array([1., 2., 6., 0., 7., 5., 3., 4., 8.]))

In [ ]:
(
  my_df
    .iloc[indices]
    .join(pd.DataFrame({"distances^2": distances**2}, index = indices))
)

         names  ages genders_txt  genders music_band_txt  distances^2
1.0    Brendon    23        male        0       Coldplay          0.0
2.0       Nate    24        male        0     LinkinPark          1.0
6.0        Gin    22      female        1     LinkinPark          2.0
0.0    Amantha    19      female        1       Coldplay         17.0
7.0        Ken    18        male        0       Coldplay         25.0
5.0  Christine    18      female        1     LinkinPark         26.0
3.0        Sam    30        male        0     LinkinPark         49.0
4.0      Betty    16      female        1       Coldplay         50.0
8.0       Susy    15      female        1       Coldplay         65.0

Display vote for various values of K $\epsilon$ { 1, 3, 5, 7, 9 }

In [ ]:
for k in range(1,10,2):
  vote = my_df.iloc[indices]["music_band_txt"][:k].mode()[0]
  print(f"K = {k} : {vote}")

K = 1 : Coldplay
K = 3 : LinkinPark
K = 5 : Coldplay
K = 7 : LinkinPark
K = 9 : Coldplay

# NLP

If our text data are unlabelled (as is often the case in NLP), we can use KNN to identify documents that are similar to a given document.  In this example, our documents will be sentences and the given document will be the first sentence.

In [ ]:
%%capture
!python -m textblob.download_corpora

In [ ]:
sentences_orig = [
  'Jen is a good student.',
  'Jen is also a great guitarist.',
  'Good students can sometimes be good guitarists',
]

sentences_orig

['Jen is a good student.',
 'Jen is also a great guitarist.',
 'Good students can sometimes be good guitarists']

# Data Cleaning
We want to singularize guitarists and students.

In [ ]:
sentence_last_tb = TextBlob(sentences_orig[-1]) # Make a textblob so that we can singularize the word
sentence_last_singular = [x.singularize() for x in sentence_last_tb.words] # Singularize each word in the text
sentence_last_clean = ' '.join(sentence_last_singular) # Join it together into a single string
sentence_last_clean

'Good student can sometime be good guitarist'

In [ ]:
sentences_clean = sentences_orig[:2] + [sentence_last_clean]
sentences_clean

['Jen is a good student.',
 'Jen is also a great guitarist.',
 'Good student can sometime be good guitarist']

## Bag of Words Using CountVectorizer

Perform the count transformation

In [ ]:
vectorizer = CountVectorizer(stop_words='english')
bow_matrix = vectorizer.fit_transform(sentences_clean)

In [ ]:
type(bow_matrix), bow_matrix.shape

(scipy.sparse._csr.csr_matrix, (3, 5))

In [ ]:
bow_matrix.toarray()

array([[1, 0, 0, 1, 1],
       [0, 1, 1, 1, 0],
       [2, 0, 1, 0, 1]])

## TF-IDF using BoW

Perform the TF-IDF transformation

In [ ]:
tf_idf_matrix = TfidfTransformer()
tf_idf_jen = tf_idf_matrix.fit_transform(bow_matrix)

In [ ]:
type(tf_idf_jen), tf_idf_jen.shape

(scipy.sparse._csr.csr_matrix, (3, 5))

In [ ]:
tf_idf_jen.toarray()

array([[0.57735027, 0.        , 0.        , 0.57735027, 0.57735027],
       [0.        , 0.68091856, 0.51785612, 0.51785612, 0.        ],
       [0.81649658, 0.        , 0.40824829, 0.        , 0.40824829]])

Print out results in a dataframe

In [ ]:
tf_df = pd.DataFrame(
  data = tf_idf_jen.toarray(),
  columns = vectorizer.get_feature_names_out(),
)

tf_df

       good     great  guitarist       jen   student
0  0.577350  0.000000   0.000000  0.577350  0.577350
1  0.000000  0.680919   0.517856  0.517856  0.000000
2  0.816497  0.000000   0.408248  0.000000  0.408248

> Note: Converting a sparse matrix to a data frame is NOT something you will normally do, especially for large matrices.

## K Nearest Neighbors

Fit nearest neighbors

In [ ]:
nn = NearestNeighbors().fit(tf_idf_jen)

Create the reference matrix from the tf_idf matrix

In [ ]:
sent0 = tf_idf_jen[0]
sent0.shape

(1, 5)

Or ...

Create the reference matrix from the data frame

In [ ]:
sent0 = np.array([tf_df.iloc[0]])
sent0.shape

(1, 5)

Get nearest neighbors distances

In [ ]:
distances, indices = nn.kneighbors(
  X = sent0,
  n_neighbors = 2,
)

In [ ]:
distances

array([[0.        , 0.76536686]])

In [ ]:
indices

array([[0, 2]])

Pull out the original sentences given the indices.

In [ ]:
#Using list comprehension
[x for i,x in enumerate(sentences_orig) if i in indices[0]]

['Jen is a good student.', 'Good students can sometimes be good guitarists']

In [ ]:
#Converting to Numpy array
np.array(sentences_orig)[indices]

array([['Jen is a good student.',
        'Good students can sometimes be good guitarists']], dtype='<U46')

# Another Example - Using Wikipedia API

## Get text and clean

Install Wikipedia API

In [ ]:
%%capture
!pip3 install wikipedia-api

In [ ]:
import wikipediaapi

Pull out page from Wikipedia

In [ ]:
#https://en.wikipedia.org/wiki/Munchkin
topic = 'munchkin'
wikip = wikipediaapi.Wikipedia('foobar')
page_ex = wikip.page(topic)
wiki_text = page_ex.text
wiki_text

'A Munchkin is a native of the fictional Munchkin Country in the Oz books by American author L. Frank Baum. Although a common fixture in Germanic fairy tales, they are introduced to modern audiences with the first appearance in the classic children\'s novel The Wonderful Wizard of Oz (1900) where they welcome Dorothy Gale to their city in Oz. The Munchkins are described as being the same height as Dorothy and they wear only shades of blue clothing, as blue is the Munchkins\' favorite color. Blue is also the predominating color that officially represents the eastern quadrant in the Land of Oz. The Munchkins have appeared in various media, including the 1939 film The Wizard of Oz, as well as in various other films and comedy acts.\n\nConcept\nWhile Baum may have written about it, there are no surviving notes for the composition of The Wonderful Wizard of Oz. The lack of this information has resulted in speculation of the term origins he used in the book, which include the word "Munchkin". Baum researcher Brian Attebery has hypothesized that there might be a connection to the Münchner Kindl (\'Munich child\'), the emblem of the Bavarian city of Munich. The symbol was originally a 13th-century statue of a monk, looking down from the town hall in Munich. Over the years, the image was reproduced many times, for instance as a figure on beer steins, and eventually evolved into a boy wearing a pointed hood. Baum\'s family had German origins, suggesting that Baum could have seen one such reproduction in his childhood.\nIt is also possible that "Munchkin" came from the German word Männchen, which means "mannikin" or "little figure". In 1900, Baum published a book about window displays in which he stressed the importance of mannequins in attracting customers. Another possibility is a connection to Baron Munchausen. This fictional character is based on a real baron who told outrageous tall tales based on his military career. It is also possible that the name is related to Thumbkin, Bumpkin, etc., pet names given to fingers of the hand in nursery rhymes.\nLike the other Oz terms, the word "Munchkin" ends in a diminutive which in this case refers to the size of the natives.\n\nLiterature\nOz Books by Frank Baum\nThe Munchkins are first mentioned (quote shown) in an excerpt from chapter two of The Wonderful Wizard of Oz, titled "The Council with the Munchkins". Dorothy initially meets only three of them, along with the Good Witch of the North. The rest of the Munchkins then come out of hiding and are shown to be grateful towards Dorothy for killing their evil ruler the Wicked Witch of the East. Dorothy later eventually finds the yellow brick road and along the way attends a banquet held by a Munchkin man named Boq. Sometime in the book a background story is also given about a "Munchkin maiden" (named Nimmie Amee in later books), who was the former love interest of the Tin Woodman.\nBaum also included the Munchkin characters in his later works as minor and major individual characters. The Munchkin Jinjur is the main antagonist in Baum\'s second book The Marvelous Land of Oz, where she seeks to overthrow the Scarecrow and take over the Emerald City. Jinjur makes a brief appearance in the next book, entitled Ozma of Oz, and is brought back in Baum\'s twelfth book, The Tin Woodman of Oz. By this time, she is shown to be a more prominent character who is helpful and friendly to Dorothy and her friends. Two other major Munchkin characters also appear in The Tin Woodman of Oz: Tommy Kwikstep and Nimmie Amee. The former appears in the story asking for a wish for running an errand for a witch; the latter is the name given to the mystery "Munchkin maiden" from the first book, who was the former lover of the Tin Woodman. More information is revealed that tells about the Tin Woodman\'s origin and their tragic love story. Lastly, the Munchkin Unc Nunkie appears in Baum\'s seventh book, The Patchwork Girl of Oz, where he is accidentally turned to stone. His Munchkin nephew Ojo successfully goes on a quest in search of an antidote while learning more about himself in the process.\n\nSubsequent Oz books\nL. Frank Baum died on 6 May 1919 after which other writers took up writing additional Oz stories. In some cases these books were written under Baum\'s name and included the Munchkins. There is at least one known Munchkin character that was created after Baum\'s death that appears as a major character. Zif is a Munchkin boy who appears in John R. Neill\'s first adaptation called The Royal Book of Oz. Zif is a student at the College of Art and Athletic Perfection; he is both respectful and resentful towards his teacher Wogglebog who considers Zif a "nobody or a nothing". The Munchkin characters that Baum had created in his lifetime also appear in these additional works.\n\nFilm and musicals\nEarly works (1902–1933)\nWhile the 1939 film is the most well known adaptation (see section below), it was not the first outside work to show the Munchkins in film or musical format. One of the first musical adaptations of Baum\'s books took place in 1902; it was also dubbed The Wizard of Oz. The Munchkins make their appearance in act one, called "The Storm", in which they are shown dancing around their maypole, not noticing that Dorothy\'s house has fallen to earth killing the Wicked Witch of the East. The first film adaptation of Baum\'s works, titled The Wonderful Wizard of Oz, was released in 1910, followed by three sequels. However, it was not until 1914 that Munchkin characters first appeared in film works. Ojo the Lucky and Unc Nunkie both appear in a film titled The Patchwork Girl of Oz (based on the book of the same name). This film stars American actress Violet MacMillan as Ojo and was produced by Baum.\n\n1939 film\nThe 1939 movie musical The Wizard of Oz was loosely based on Baum\'s novel. Notable differences of the Munchkins include their country name of Munchkinland and their clothes of many colors instead of an all-blue attire. In the musical, the Munchkins are portrayed by the thirty-odd members of the Singer Midgets, a European performing troupe made up of adult actors with dwarfism. Their numbers were swelled when a national talent search brought in a further ninety-four little men, women, and teenagers, with a few average-sized children were also included as background extras in order to make up the 124 characters requested by MGM.\nIn the musical, the Munchkins first appear when Dorothy and Toto arrive in the Land of Oz after her house lands on the Wicked Witch of the East. The Munchkins hide from all the commotion until Glinda the Good Witch arrives reassuring them that everything is okay. Dorothy tells them how she arrived in the Land of Oz (through a musical number) and the Munchkins celebrate. To make it official, a Barrister and a number of City Fathers insist to the Mayor of the Munchkin City that they must make sure that the Wicked Witch of the East is really dead before the celebration continues. The Coroner confirms this by saying that the witch is "not only merely dead" but is indeed "most sincerely dead" while showing a Certificate of Death. The Munchkins then celebrate further as Dorothy receives gifts from the "Lullaby League" and the "Lollipop Guild". Near the end of the song, the Wicked Witch of the West arrives, which causes the Munchkins to panic. After the Wicked Witch of the West leaves, Glinda tells Dorothy to follow the yellow brick road to the Emerald City as the Munchkins guide her out of Munchkinland.\n\nThe Munchkin actors have since not avoided controversy with alleged behavior behind the scenes. In a 1967 interview, Judy Garland referred to all of the Munchkins as "little drunks" who got intoxicated every night to the point where they had to be picked up in "butterfly nets". These accusations were denied as fabrications by Munchkin Margaret Pellegrini, who said only "a couple of kids from Germany even drank beer". On 20 November 2007, the Munchkins were given a star on the Hollywood Walk of Fame. Seven of the surviving Munchkin actors from the film were present. As a result of the popularity of the 1939 film, the word "munchkin" has entered the English language as a reference to small children, persons with dwarfism, or anything of diminutive stature.\n\nActors and actresses\nThe following is a list of actors who portrayed the Munchkins in the 1939 film. Most of the dwarfs hired were acquired for MGM by Leo Singer, the proprietor of Singer\'s Midgets. A Daily Variety news story from 17 August 1938, stated 124 dwarves had been signed to play Munchkins; modern sources place the number either at 122 or 124. An additional dozen or so child actors were hired to make up for the shortage of dwarves. At least one Munchkin actor, Dale Paullin (stage name Paul Dale), did not make the final cut for the movie. Only two actors (Joseph Koziel and Frank Cucksey) used their actual voices for the dialogue exchanged with Dorothy where she is given the flowers. The rest of the voices, such as the "Munchkin chorus", were created by Pinto Colvig and Billy Bletcher with their voices recorded at a slow speed, which were subsequently sped-up when played back.\nIn 1989, author Stephen Cox researched, found, and wrote about the surviving Munchkin actors fifty years after they made the film. He wrote about them in his book, The Munchkins Remember (1989, E.P. Dutton), which was later revised as The Munchkins of Oz (Cumberland House), and his book remained in print for nearly two decades. When he wrote the book, 33 of the actors with dwarfism who appeared in the film were still alive and were interviewed. Several of them outlived all the major cast, as well as the original Tin Man Buddy Ebsen. Jerry Maren, who played the green "Lollipop Guild" member, was the last living adult Munchkin actor. Maren was the only Munchkin alive when the film\'s longest living cast member, Shep Houghton, an extra, died in 2016.\n\nNotes: Some of the information presented in the table below may never be complete as Social Security records remain sparse prior to the mid-twentieth century. Other factors such as immigration and foreign citizenship also add to this difficulty. Stage names and/or aliases are present in italics and quotation marks.\n\nChild actresses\nAbout a dozen children of average height were hired so they could be used for background fill. Sources differ on the number of children used for these roles ranging anywhere from 10 to 12. The names used for the women are maiden names with known aliases present in italics and quotation marks.\nPriscilla Ann Montgomery Clark is the earliest born of the Munchkins listed below and the final living Munchkin actress.\n\nLater works (1940–1989)\nThe 1939 film was adapted into a musical that was released in 1942 that includes the Munchkin characters. The events that take place mirror the film including the song "Ding-Dong! The Witch Is Dead". Twenty-seven years later an animated film called The Wonderful Land of Oz was made featuring Jinjur as a main antagonist.\n\nOther works\nThe Munchkins appeared in The Wiz and were played by children and teenagers. (1978)\nThe Munchkins appear at the end of Return to Oz. They are seen celebrating Dorothy\'s return after defeating the Nome King and are present at Princess Ozma\'s coronation. Tommy Kwikstep was also seen there. (1985)\nIn The Muppets\' Wizard of Oz, the Munchkins were played by Rizzo the Rat (as the "Mayor of Munchkinland") and his fellow rats, allowing them to also pull double duty as the Field Mice that rescue Dorothy from the poppies. (2005)\nThe Munchkins appeared in Dorothy and the Witches of Oz. The Munchkins were first seen in the battle against the Wicked Witch of the West\'s forces in Oz. They were later brought to Earth by Glinda in order to combat the forces of the Wicked Witch of the West. (2012)\nThe Munchkins appear in Oz the Great and Powerful. They alongside the Quadlings and the Tinkers as inhabitants of Glinda\'s protectorate. Although the film is not otherwise a musical, the Munchkins sing and dance much as they do in the 1939 film. (2013)\nThe Munchkins appear in Dorothy and the Wizard of Oz with the "Mayor of Munchkinland" voiced by Bill Fagerbakke and the background Munchkins voiced by Steven Blum and Jessica DiCicco. Ojo, Dr. Pipt, the Lollipop Guild, and the Lullaby League are also featured. Also, Smith & Tinker are depicted as Munchkins in this show.\nThe Munchkins appear as a culture of farmers in Wicked. Director Jon M. Chu decided to cast people closer to the book\'s original description being about as tall as Dorothy, rather than the 1939 film\'s cast of much shorter Munchkins. The main Munchkin character in this story, Boq Woodsman, is played by Ethan Slater who stands at 5\'7". Chu also chose to focus more on their culture than their physical appearance.\n\nExplanatory notes\nReferences\nCitations\nWorks cited\nExternal links\n The dictionary definition of munchkin at Wiktionary'

Replace newline chars with spaces before doing any processing. Strip the ' and "s" from possessives.

In [ ]:
wiki_text_clean = (
  wiki_text
  .lower()
  .replace("\n"," ")
  .replace("\'s",'')
  .replace('\'','')
  .replace("(", "")
  .replace(")", "")
  .replace('"', "")
)

wiki_text_clean

'a munchkin is a native of the fictional munchkin country in the oz books by american author l. frank baum. although a common fixture in germanic fairy tales, they are introduced to modern audiences with the first appearance in the classic children novel the wonderful wizard of oz 1900 where they welcome dorothy gale to their city in oz. the munchkins are described as being the same height as dorothy and they wear only shades of blue clothing, as blue is the munchkins favorite color. blue is also the predominating color that officially represents the eastern quadrant in the land of oz. the munchkins have appeared in various media, including the 1939 film the wizard of oz, as well as in various other films and comedy acts.  concept while baum may have written about it, there are no surviving notes for the composition of the wonderful wizard of oz. the lack of this information has resulted in speculation of the term origins he used in the book, which include the word munchkin. baum researcher brian attebery has hypothesized that there might be a connection to the münchner kindl munich child, the emblem of the bavarian city of munich. the symbol was originally a 13th-century statue of a monk, looking down from the town hall in munich. over the years, the image was reproduced many times, for instance as a figure on beer steins, and eventually evolved into a boy wearing a pointed hood. baum family had german origins, suggesting that baum could have seen one such reproduction in his childhood. it is also possible that munchkin came from the german word männchen, which means mannikin or little figure. in 1900, baum published a book about window displays in which he stressed the importance of mannequins in attracting customers. another possibility is a connection to baron munchausen. this fictional character is based on a real baron who told outrageous tall tales based on his military career. it is also possible that the name is related to thumbkin, bumpkin, etc., pet names given to fingers of the hand in nursery rhymes. like the other oz terms, the word munchkin ends in a diminutive which in this case refers to the size of the natives.  literature oz books by frank baum the munchkins are first mentioned quote shown in an excerpt from chapter two of the wonderful wizard of oz, titled the council with the munchkins. dorothy initially meets only three of them, along with the good witch of the north. the rest of the munchkins then come out of hiding and are shown to be grateful towards dorothy for killing their evil ruler the wicked witch of the east. dorothy later eventually finds the yellow brick road and along the way attends a banquet held by a munchkin man named boq. sometime in the book a background story is also given about a munchkin maiden named nimmie amee in later books, who was the former love interest of the tin woodman. baum also included the munchkin characters in his later works as minor and major individual characters. the munchkin jinjur is the main antagonist in baum second book the marvelous land of oz, where she seeks to overthrow the scarecrow and take over the emerald city. jinjur makes a brief appearance in the next book, entitled ozma of oz, and is brought back in baum twelfth book, the tin woodman of oz. by this time, she is shown to be a more prominent character who is helpful and friendly to dorothy and her friends. two other major munchkin characters also appear in the tin woodman of oz: tommy kwikstep and nimmie amee. the former appears in the story asking for a wish for running an errand for a witch; the latter is the name given to the mystery munchkin maiden from the first book, who was the former lover of the tin woodman. more information is revealed that tells about the tin woodman origin and their tragic love story. lastly, the munchkin unc nunkie appears in baum seventh book, the patchwork girl of oz, where he is accidentally turned to stone. his munchkin nephew ojo successfully goes on a quest in search of an antidote while learning more about himself in the process.  subsequent oz books l. frank baum died on 6 may 1919 after which other writers took up writing additional oz stories. in some cases these books were written under baum name and included the munchkins. there is at least one known munchkin character that was created after baum death that appears as a major character. zif is a munchkin boy who appears in john r. neill first adaptation called the royal book of oz. zif is a student at the college of art and athletic perfection; he is both respectful and resentful towards his teacher wogglebog who considers zif a nobody or a nothing. the munchkin characters that baum had created in his lifetime also appear in these additional works.  film and musicals early works 1902–1933 while the 1939 film is the most well known adaptation see section below, it was not the first outside work to show the munchkins in film or musical format. one of the first musical adaptations of baum books took place in 1902; it was also dubbed the wizard of oz. the munchkins make their appearance in act one, called the storm, in which they are shown dancing around their maypole, not noticing that dorothy house has fallen to earth killing the wicked witch of the east. the first film adaptation of baum works, titled the wonderful wizard of oz, was released in 1910, followed by three sequels. however, it was not until 1914 that munchkin characters first appeared in film works. ojo the lucky and unc nunkie both appear in a film titled the patchwork girl of oz based on the book of the same name. this film stars american actress violet macmillan as ojo and was produced by baum.  1939 film the 1939 movie musical the wizard of oz was loosely based on baum novel. notable differences of the munchkins include their country name of munchkinland and their clothes of many colors instead of an all-blue attire. in the musical, the munchkins are portrayed by the thirty-odd members of the singer midgets, a european performing troupe made up of adult actors with dwarfism. their numbers were swelled when a national talent search brought in a further ninety-four little men, women, and teenagers, with a few average-sized children were also included as background extras in order to make up the 124 characters requested by mgm. in the musical, the munchkins first appear when dorothy and toto arrive in the land of oz after her house lands on the wicked witch of the east. the munchkins hide from all the commotion until glinda the good witch arrives reassuring them that everything is okay. dorothy tells them how she arrived in the land of oz through a musical number and the munchkins celebrate. to make it official, a barrister and a number of city fathers insist to the mayor of the munchkin city that they must make sure that the wicked witch of the east is really dead before the celebration continues. the coroner confirms this by saying that the witch is not only merely dead but is indeed most sincerely dead while showing a certificate of death. the munchkins then celebrate further as dorothy receives gifts from the lullaby league and the lollipop guild. near the end of the song, the wicked witch of the west arrives, which causes the munchkins to panic. after the wicked witch of the west leaves, glinda tells dorothy to follow the yellow brick road to the emerald city as the munchkins guide her out of munchkinland.  the munchkin actors have since not avoided controversy with alleged behavior behind the scenes. in a 1967 interview, judy garland referred to all of the munchkins as little drunks who got intoxicated every night to the point where they had to be picked up in butterfly nets. these accusations were denied as fabrications by munchkin margaret pellegrini, who said only a couple of kids from germany even drank beer. on 20 november 2007, the munchkins were given a star on the hollywood walk of fame. seven of the surviving munchkin actors from the film were present. as a result of the popularity of the 1939 film, the word munchkin has entered the english language as a reference to small children, persons with dwarfism, or anything of diminutive stature.  actors and actresses the following is a list of actors who portrayed the munchkins in the 1939 film. most of the dwarfs hired were acquired for mgm by leo singer, the proprietor of singer midgets. a daily variety news story from 17 august 1938, stated 124 dwarves had been signed to play munchkins; modern sources place the number either at 122 or 124. an additional dozen or so child actors were hired to make up for the shortage of dwarves. at least one munchkin actor, dale paullin stage name paul dale, did not make the final cut for the movie. only two actors joseph koziel and frank cucksey used their actual voices for the dialogue exchanged with dorothy where she is given the flowers. the rest of the voices, such as the munchkin chorus, were created by pinto colvig and billy bletcher with their voices recorded at a slow speed, which were subsequently sped-up when played back. in 1989, author stephen cox researched, found, and wrote about the surviving munchkin actors fifty years after they made the film. he wrote about them in his book, the munchkins remember 1989, e.p. dutton, which was later revised as the munchkins of oz cumberland house, and his book remained in print for nearly two decades. when he wrote the book, 33 of the actors with dwarfism who appeared in the film were still alive and were interviewed. several of them outlived all the major cast, as well as the original tin man buddy ebsen. jerry maren, who played the green lollipop guild member, was the last living adult munchkin actor. maren was the only munchkin alive when the film longest living cast member, shep houghton, an extra, died in 2016.  notes: some of the information presented in the table below may never be complete as social security records remain sparse prior to the mid-twentieth century. other factors such as immigration and foreign citizenship also add to this difficulty. stage names and/or aliases are present in italics and quotation marks.  child actresses about a dozen children of average height were hired so they could be used for background fill. sources differ on the number of children used for these roles ranging anywhere from 10 to 12. the names used for the women are maiden names with known aliases present in italics and quotation marks. priscilla ann montgomery clark is the earliest born of the munchkins listed below and the final living munchkin actress.  later works 1940–1989 the 1939 film was adapted into a musical that was released in 1942 that includes the munchkin characters. the events that take place mirror the film including the song ding-dong! the witch is dead. twenty-seven years later an animated film called the wonderful land of oz was made featuring jinjur as a main antagonist.  other works the munchkins appeared in the wiz and were played by children and teenagers. 1978 the munchkins appear at the end of return to oz. they are seen celebrating dorothy return after defeating the nome king and are present at princess ozma coronation. tommy kwikstep was also seen there. 1985 in the muppets wizard of oz, the munchkins were played by rizzo the rat as the mayor of munchkinland and his fellow rats, allowing them to also pull double duty as the field mice that rescue dorothy from the poppies. 2005 the munchkins appeared in dorothy and the witches of oz. the munchkins were first seen in the battle against the wicked witch of the west forces in oz. they were later brought to earth by glinda in order to combat the forces of the wicked witch of the west. 2012 the munchkins appear in oz the great and powerful. they alongside the quadlings and the tinkers as inhabitants of glinda protectorate. although the film is not otherwise a musical, the munchkins sing and dance much as they do in the 1939 film. 2013 the munchkins appear in dorothy and the wizard of oz with the mayor of munchkinland voiced by bill fagerbakke and the background munchkins voiced by steven blum and jessica dicicco. ojo, dr. pipt, the lollipop guild, and the lullaby league are also featured. also, smith & tinker are depicted as munchkins in this show. the munchkins appear as a culture of farmers in wicked. director jon m. chu decided to cast people closer to the book original description being about as tall as dorothy, rather than the 1939 film cast of much shorter munchkins. the main munchkin character in this story, boq woodsman, is played by ethan slater who stands at 57. chu also chose to focus more on their culture than their physical appearance.  explanatory notes references citations works cited external links  the dictionary definition of munchkin at wiktionary'

Convert to textblob

In [ ]:
wiki_blob = TextBlob(wiki_text_clean)
wiki_blob

TextBlob("a munchkin is a native of the fictional munchkin country in the oz books by american author l. frank baum. although a common fixture in germanic fairy tales, they are introduced to modern audiences with the first appearance in the classic children novel the wonderful wizard of oz 1900 where they welcome dorothy gale to their city in oz. the munchkins are described as being the same height as dorothy and they wear only shades of blue clothing, as blue is the munchkins favorite color. blue is also the predominating color that officially represents the eastern quadrant in the land of oz. the munchkins have appeared in various media, including the 1939 film the wizard of oz, as well as in various other films and comedy acts.  concept while baum may have written about it, there are no surviving notes for the composition of the wonderful wizard of oz. the lack of this information has resulted in speculation of the term origins he used in the book, which include the word munchkin. baum researcher brian attebery has hypothesized that there might be a connection to the münchner kindl munich child, the emblem of the bavarian city of munich. the symbol was originally a 13th-century statue of a monk, looking down from the town hall in munich. over the years, the image was reproduced many times, for instance as a figure on beer steins, and eventually evolved into a boy wearing a pointed hood. baum family had german origins, suggesting that baum could have seen one such reproduction in his childhood. it is also possible that munchkin came from the german word männchen, which means mannikin or little figure. in 1900, baum published a book about window displays in which he stressed the importance of mannequins in attracting customers. another possibility is a connection to baron munchausen. this fictional character is based on a real baron who told outrageous tall tales based on his military career. it is also possible that the name is related to thumbkin, bumpkin, etc., pet names given to fingers of the hand in nursery rhymes. like the other oz terms, the word munchkin ends in a diminutive which in this case refers to the size of the natives.  literature oz books by frank baum the munchkins are first mentioned quote shown in an excerpt from chapter two of the wonderful wizard of oz, titled the council with the munchkins. dorothy initially meets only three of them, along with the good witch of the north. the rest of the munchkins then come out of hiding and are shown to be grateful towards dorothy for killing their evil ruler the wicked witch of the east. dorothy later eventually finds the yellow brick road and along the way attends a banquet held by a munchkin man named boq. sometime in the book a background story is also given about a munchkin maiden named nimmie amee in later books, who was the former love interest of the tin woodman. baum also included the munchkin characters in his later works as minor and major individual characters. the munchkin jinjur is the main antagonist in baum second book the marvelous land of oz, where she seeks to overthrow the scarecrow and take over the emerald city. jinjur makes a brief appearance in the next book, entitled ozma of oz, and is brought back in baum twelfth book, the tin woodman of oz. by this time, she is shown to be a more prominent character who is helpful and friendly to dorothy and her friends. two other major munchkin characters also appear in the tin woodman of oz: tommy kwikstep and nimmie amee. the former appears in the story asking for a wish for running an errand for a witch; the latter is the name given to the mystery munchkin maiden from the first book, who was the former lover of the tin woodman. more information is revealed that tells about the tin woodman origin and their tragic love story. lastly, the munchkin unc nunkie appears in baum seventh book, the patchwork girl of oz, where he is accidentally turned to stone. his munchkin nephew ojo successfully goes on a quest in search of an antidote while learning more about himself in the process.  subsequent oz books l. frank baum died on 6 may 1919 after which other writers took up writing additional oz stories. in some cases these books were written under baum name and included the munchkins. there is at least one known munchkin character that was created after baum death that appears as a major character. zif is a munchkin boy who appears in john r. neill first adaptation called the royal book of oz. zif is a student at the college of art and athletic perfection; he is both respectful and resentful towards his teacher wogglebog who considers zif a nobody or a nothing. the munchkin characters that baum had created in his lifetime also appear in these additional works.  film and musicals early works 1902–1933 while the 1939 film is the most well known adaptation see section below, it was not the first outside work to show the munchkins in film or musical format. one of the first musical adaptations of baum books took place in 1902; it was also dubbed the wizard of oz. the munchkins make their appearance in act one, called the storm, in which they are shown dancing around their maypole, not noticing that dorothy house has fallen to earth killing the wicked witch of the east. the first film adaptation of baum works, titled the wonderful wizard of oz, was released in 1910, followed by three sequels. however, it was not until 1914 that munchkin characters first appeared in film works. ojo the lucky and unc nunkie both appear in a film titled the patchwork girl of oz based on the book of the same name. this film stars american actress violet macmillan as ojo and was produced by baum.  1939 film the 1939 movie musical the wizard of oz was loosely based on baum novel. notable differences of the munchkins include their country name of munchkinland and their clothes of many colors instead of an all-blue attire. in the musical, the munchkins are portrayed by the thirty-odd members of the singer midgets, a european performing troupe made up of adult actors with dwarfism. their numbers were swelled when a national talent search brought in a further ninety-four little men, women, and teenagers, with a few average-sized children were also included as background extras in order to make up the 124 characters requested by mgm. in the musical, the munchkins first appear when dorothy and toto arrive in the land of oz after her house lands on the wicked witch of the east. the munchkins hide from all the commotion until glinda the good witch arrives reassuring them that everything is okay. dorothy tells them how she arrived in the land of oz through a musical number and the munchkins celebrate. to make it official, a barrister and a number of city fathers insist to the mayor of the munchkin city that they must make sure that the wicked witch of the east is really dead before the celebration continues. the coroner confirms this by saying that the witch is not only merely dead but is indeed most sincerely dead while showing a certificate of death. the munchkins then celebrate further as dorothy receives gifts from the lullaby league and the lollipop guild. near the end of the song, the wicked witch of the west arrives, which causes the munchkins to panic. after the wicked witch of the west leaves, glinda tells dorothy to follow the yellow brick road to the emerald city as the munchkins guide her out of munchkinland.  the munchkin actors have since not avoided controversy with alleged behavior behind the scenes. in a 1967 interview, judy garland referred to all of the munchkins as little drunks who got intoxicated every night to the point where they had to be picked up in butterfly nets. these accusations were denied as fabrications by munchkin margaret pellegrini, who said only a couple of kids from germany even drank beer. on 20 november 2007, the munchkins were given a star on the hollywood walk of fame. seven of the surviving munchkin actors from the film were present. as a result of the popularity of the 1939 film, the word munchkin has entered the english language as a reference to small children, persons with dwarfism, or anything of diminutive stature.  actors and actresses the following is a list of actors who portrayed the munchkins in the 1939 film. most of the dwarfs hired were acquired for mgm by leo singer, the proprietor of singer midgets. a daily variety news story from 17 august 1938, stated 124 dwarves had been signed to play munchkins; modern sources place the number either at 122 or 124. an additional dozen or so child actors were hired to make up for the shortage of dwarves. at least one munchkin actor, dale paullin stage name paul dale, did not make the final cut for the movie. only two actors joseph koziel and frank cucksey used their actual voices for the dialogue exchanged with dorothy where she is given the flowers. the rest of the voices, such as the munchkin chorus, were created by pinto colvig and billy bletcher with their voices recorded at a slow speed, which were subsequently sped-up when played back. in 1989, author stephen cox researched, found, and wrote about the surviving munchkin actors fifty years after they made the film. he wrote about them in his book, the munchkins remember 1989, e.p. dutton, which was later revised as the munchkins of oz cumberland house, and his book remained in print for nearly two decades. when he wrote the book, 33 of the actors with dwarfism who appeared in the film were still alive and were interviewed. several of them outlived all the major cast, as well as the original tin man buddy ebsen. jerry maren, who played the green lollipop guild member, was the last living adult munchkin actor. maren was the only munchkin alive when the film longest living cast member, shep houghton, an extra, died in 2016.  notes: some of the information presented in the table below may never be complete as social security records remain sparse prior to the mid-twentieth century. other factors such as immigration and foreign citizenship also add to this difficulty. stage names and/or aliases are present in italics and quotation marks.  child actresses about a dozen children of average height were hired so they could be used for background fill. sources differ on the number of children used for these roles ranging anywhere from 10 to 12. the names used for the women are maiden names with known aliases present in italics and quotation marks. priscilla ann montgomery clark is the earliest born of the munchkins listed below and the final living munchkin actress.  later works 1940–1989 the 1939 film was adapted into a musical that was released in 1942 that includes the munchkin characters. the events that take place mirror the film including the song ding-dong! the witch is dead. twenty-seven years later an animated film called the wonderful land of oz was made featuring jinjur as a main antagonist.  other works the munchkins appeared in the wiz and were played by children and teenagers. 1978 the munchkins appear at the end of return to oz. they are seen celebrating dorothy return after defeating the nome king and are present at princess ozma coronation. tommy kwikstep was also seen there. 1985 in the muppets wizard of oz, the munchkins were played by rizzo the rat as the mayor of munchkinland and his fellow rats, allowing them to also pull double duty as the field mice that rescue dorothy from the poppies. 2005 the munchkins appeared in dorothy and the witches of oz. the munchkins were first seen in the battle against the wicked witch of the west forces in oz. they were later brought to earth by glinda in order to combat the forces of the wicked witch of the west. 2012 the munchkins appear in oz the great and powerful. they alongside the quadlings and the tinkers as inhabitants of glinda protectorate. although the film is not otherwise a musical, the munchkins sing and dance much as they do in the 1939 film. 2013 the munchkins appear in dorothy and the wizard of oz with the mayor of munchkinland voiced by bill fagerbakke and the background munchkins voiced by steven blum and jessica dicicco. ojo, dr. pipt, the lollipop guild, and the lullaby league are also featured. also, smith & tinker are depicted as munchkins in this show. the munchkins appear as a culture of farmers in wicked. director jon m. chu decided to cast people closer to the book original description being about as tall as dorothy, rather than the 1939 film cast of much shorter munchkins. the main munchkin character in this story, boq woodsman, is played by ethan slater who stands at 57. chu also chose to focus more on their culture than their physical appearance.  explanatory notes references citations works cited external links  the dictionary definition of munchkin at wiktionary")

Only look at subset of sentences

In [ ]:
size = len(wiki_blob.sentences)
size

102

In [ ]:
my_sentences = wiki_blob.sentences[0:(size//1)]
my_sentences

[Sentence("a munchkin is a native of the fictional munchkin country in the oz books by american author l. frank baum."),
 Sentence("although a common fixture in germanic fairy tales, they are introduced to modern audiences with the first appearance in the classic children novel the wonderful wizard of oz 1900 where they welcome dorothy gale to their city in oz."),
 Sentence("the munchkins are described as being the same height as dorothy and they wear only shades of blue clothing, as blue is the munchkins favorite color."),
 Sentence("blue is also the predominating color that officially represents the eastern quadrant in the land of oz."),
 Sentence("the munchkins have appeared in various media, including the 1939 film the wizard of oz, as well as in various other films and comedy acts."),
 Sentence("concept while baum may have written about it, there are no surviving notes for the composition of the wonderful wizard of oz."),
 Sentence("the lack of this information has resulted in speculation of the term origins he used in the book, which include the word munchkin."),
 Sentence("baum researcher brian attebery has hypothesized that there might be a connection to the münchner kindl munich child, the emblem of the bavarian city of munich."),
 Sentence("the symbol was originally a 13th-century statue of a monk, looking down from the town hall in munich."),
 Sentence("over the years, the image was reproduced many times, for instance as a figure on beer steins, and eventually evolved into a boy wearing a pointed hood."),
 Sentence("baum family had german origins, suggesting that baum could have seen one such reproduction in his childhood."),
 Sentence("it is also possible that munchkin came from the german word männchen, which means mannikin or little figure."),
 Sentence("in 1900, baum published a book about window displays in which he stressed the importance of mannequins in attracting customers."),
 Sentence("another possibility is a connection to baron munchausen."),
 Sentence("this fictional character is based on a real baron who told outrageous tall tales based on his military career."),
 Sentence("it is also possible that the name is related to thumbkin, bumpkin, etc., pet names given to fingers of the hand in nursery rhymes."),
 Sentence("like the other oz terms, the word munchkin ends in a diminutive which in this case refers to the size of the natives."),
 Sentence("literature oz books by frank baum the munchkins are first mentioned quote shown in an excerpt from chapter two of the wonderful wizard of oz, titled the council with the munchkins."),
 Sentence("dorothy initially meets only three of them, along with the good witch of the north."),
 Sentence("the rest of the munchkins then come out of hiding and are shown to be grateful towards dorothy for killing their evil ruler the wicked witch of the east."),
 Sentence("dorothy later eventually finds the yellow brick road and along the way attends a banquet held by a munchkin man named boq."),
 Sentence("sometime in the book a background story is also given about a munchkin maiden named nimmie amee in later books, who was the former love interest of the tin woodman."),
 Sentence("baum also included the munchkin characters in his later works as minor and major individual characters."),
 Sentence("the munchkin jinjur is the main antagonist in baum second book the marvelous land of oz, where she seeks to overthrow the scarecrow and take over the emerald city."),
 Sentence("jinjur makes a brief appearance in the next book, entitled ozma of oz, and is brought back in baum twelfth book, the tin woodman of oz."),
 Sentence("by this time, she is shown to be a more prominent character who is helpful and friendly to dorothy and her friends."),
 Sentence("two other major munchkin characters also appear in the tin woodman of oz: tommy kwikstep and nimmie amee."),
 Sentence("the former appears in the story asking for a wish for running an errand for a witch; the latter is the name given to the mystery munchkin maiden from the first book, who was the former lover of the tin woodman."),
 Sentence("more information is revealed that tells about the tin woodman origin and their tragic love story."),
 Sentence("lastly, the munchkin unc nunkie appears in baum seventh book, the patchwork girl of oz, where he is accidentally turned to stone."),
 Sentence("his munchkin nephew ojo successfully goes on a quest in search of an antidote while learning more about himself in the process."),
 Sentence("subsequent oz books l. frank baum died on 6 may 1919 after which other writers took up writing additional oz stories."),
 Sentence("in some cases these books were written under baum name and included the munchkins."),
 Sentence("there is at least one known munchkin character that was created after baum death that appears as a major character."),
 Sentence("zif is a munchkin boy who appears in john r. neill first adaptation called the royal book of oz."),
 Sentence("zif is a student at the college of art and athletic perfection; he is both respectful and resentful towards his teacher wogglebog who considers zif a nobody or a nothing."),
 Sentence("the munchkin characters that baum had created in his lifetime also appear in these additional works."),
 Sentence("film and musicals early works 1902–1933 while the 1939 film is the most well known adaptation see section below, it was not the first outside work to show the munchkins in film or musical format."),
 Sentence("one of the first musical adaptations of baum books took place in 1902; it was also dubbed the wizard of oz."),
 Sentence("the munchkins make their appearance in act one, called the storm, in which they are shown dancing around their maypole, not noticing that dorothy house has fallen to earth killing the wicked witch of the east."),
 Sentence("the first film adaptation of baum works, titled the wonderful wizard of oz, was released in 1910, followed by three sequels."),
 Sentence("however, it was not until 1914 that munchkin characters first appeared in film works."),
 Sentence("ojo the lucky and unc nunkie both appear in a film titled the patchwork girl of oz based on the book of the same name."),
 Sentence("this film stars american actress violet macmillan as ojo and was produced by baum."),
 Sentence("1939 film the 1939 movie musical the wizard of oz was loosely based on baum novel."),
 Sentence("notable differences of the munchkins include their country name of munchkinland and their clothes of many colors instead of an all-blue attire."),
 Sentence("in the musical, the munchkins are portrayed by the thirty-odd members of the singer midgets, a european performing troupe made up of adult actors with dwarfism."),
 Sentence("their numbers were swelled when a national talent search brought in a further ninety-four little men, women, and teenagers, with a few average-sized children were also included as background extras in order to make up the 124 characters requested by mgm."),
 Sentence("in the musical, the munchkins first appear when dorothy and toto arrive in the land of oz after her house lands on the wicked witch of the east."),
 Sentence("the munchkins hide from all the commotion until glinda the good witch arrives reassuring them that everything is okay."),
 Sentence("dorothy tells them how she arrived in the land of oz through a musical number and the munchkins celebrate."),
 Sentence("to make it official, a barrister and a number of city fathers insist to the mayor of the munchkin city that they must make sure that the wicked witch of the east is really dead before the celebration continues."),
 Sentence("the coroner confirms this by saying that the witch is not only merely dead but is indeed most sincerely dead while showing a certificate of death."),
 Sentence("the munchkins then celebrate further as dorothy receives gifts from the lullaby league and the lollipop guild."),
 Sentence("near the end of the song, the wicked witch of the west arrives, which causes the munchkins to panic."),
 Sentence("after the wicked witch of the west leaves, glinda tells dorothy to follow the yellow brick road to the emerald city as the munchkins guide her out of munchkinland."),
 Sentence("the munchkin actors have since not avoided controversy with alleged behavior behind the scenes."),
 Sentence("in a 1967 interview, judy garland referred to all of the munchkins as little drunks who got intoxicated every night to the point where they had to be picked up in butterfly nets."),
 Sentence("these accusations were denied as fabrications by munchkin margaret pellegrini, who said only a couple of kids from germany even drank beer."),
 Sentence("on 20 november 2007, the munchkins were given a star on the hollywood walk of fame."),
 Sentence("seven of the surviving munchkin actors from the film were present."),
 Sentence("as a result of the popularity of the 1939 film, the word munchkin has entered the english language as a reference to small children, persons with dwarfism, or anything of diminutive stature."),
 Sentence("actors and actresses the following is a list of actors who portrayed the munchkins in the 1939 film."),
 Sentence("most of the dwarfs hired were acquired for mgm by leo singer, the proprietor of singer midgets."),
 Sentence("a daily variety news story from 17 august 1938, stated 124 dwarves had been signed to play munchkins; modern sources place the number either at 122 or 124. an additional dozen or so child actors were hired to make up for the shortage of dwarves."),
 Sentence("at least one munchkin actor, dale paullin stage name paul dale, did not make the final cut for the movie."),
 Sentence("only two actors joseph koziel and frank cucksey used their actual voices for the dialogue exchanged with dorothy where she is given the flowers."),
 Sentence("the rest of the voices, such as the munchkin chorus, were created by pinto colvig and billy bletcher with their voices recorded at a slow speed, which were subsequently sped-up when played back."),
 Sentence("in 1989, author stephen cox researched, found, and wrote about the surviving munchkin actors fifty years after they made the film."),
 Sentence("he wrote about them in his book, the munchkins remember 1989, e.p."),
 Sentence("dutton, which was later revised as the munchkins of oz cumberland house, and his book remained in print for nearly two decades."),
 Sentence("when he wrote the book, 33 of the actors with dwarfism who appeared in the film were still alive and were interviewed."),
 Sentence("several of them outlived all the major cast, as well as the original tin man buddy ebsen."),
 Sentence("jerry maren, who played the green lollipop guild member, was the last living adult munchkin actor."),
 Sentence("maren was the only munchkin alive when the film longest living cast member, shep houghton, an extra, died in 2016.  notes: some of the information presented in the table below may never be complete as social security records remain sparse prior to the mid-twentieth century."),
 Sentence("other factors such as immigration and foreign citizenship also add to this difficulty."),
 Sentence("stage names and/or aliases are present in italics and quotation marks."),
 Sentence("child actresses about a dozen children of average height were hired so they could be used for background fill."),
 Sentence("sources differ on the number of children used for these roles ranging anywhere from 10 to 12. the names used for the women are maiden names with known aliases present in italics and quotation marks."),
 Sentence("priscilla ann montgomery clark is the earliest born of the munchkins listed below and the final living munchkin actress."),
 Sentence("later works 1940–1989 the 1939 film was adapted into a musical that was released in 1942 that includes the munchkin characters."),
 Sentence("the events that take place mirror the film including the song ding-dong!"),
 Sentence("the witch is dead."),
 Sentence("twenty-seven years later an animated film called the wonderful land of oz was made featuring jinjur as a main antagonist."),
 Sentence("other works the munchkins appeared in the wiz and were played by children and teenagers."),
 Sentence("1978 the munchkins appear at the end of return to oz."),
 Sentence("they are seen celebrating dorothy return after defeating the nome king and are present at princess ozma coronation."),
 Sentence("tommy kwikstep was also seen there."),
 Sentence("1985 in the muppets wizard of oz, the munchkins were played by rizzo the rat as the mayor of munchkinland and his fellow rats, allowing them to also pull double duty as the field mice that rescue dorothy from the poppies."),
 Sentence("2005 the munchkins appeared in dorothy and the witches of oz."),
 Sentence("the munchkins were first seen in the battle against the wicked witch of the west forces in oz."),
 Sentence("they were later brought to earth by glinda in order to combat the forces of the wicked witch of the west."),
 Sentence("2012 the munchkins appear in oz the great and powerful."),
 Sentence("they alongside the quadlings and the tinkers as inhabitants of glinda protectorate."),
 Sentence("although the film is not otherwise a musical, the munchkins sing and dance much as they do in the 1939 film."),
 Sentence("2013 the munchkins appear in dorothy and the wizard of oz with the mayor of munchkinland voiced by bill fagerbakke and the background munchkins voiced by steven blum and jessica dicicco."),
 Sentence("ojo, dr. pipt, the lollipop guild, and the lullaby league are also featured."),
 Sentence("also, smith & tinker are depicted as munchkins in this show."),
 Sentence("the munchkins appear as a culture of farmers in wicked."),
 Sentence("director jon m. chu decided to cast people closer to the book original description being about as tall as dorothy, rather than the 1939 film cast of much shorter munchkins."),
 Sentence("the main munchkin character in this story, boq woodsman, is played by ethan slater who stands at 57. chu also chose to focus more on their culture than their physical appearance."),
 Sentence("explanatory notes references citations works cited external links  the dictionary definition of munchkin at wiktionary")]

Singularize and convert back to string

In [ ]:
for i, sentence in enumerate(my_sentences):
  sing = [x.singularize() for x in sentence.words]
  my_sentences[i] = ' '.join(sing)

my_sentences

['a munchkin is a native of the fictional munchkin country in the oz book by american author l frank baum',
 'although a common fixture in germanic fairy tale they are introduced to modern audience with the first appearance in the classic child novel the wonderful wizard of oz 1900 where they welcome dorothy gale to their city in oz',
 'the munchkin are described a being the same height a dorothy and they wear only shade of blue clothing a blue is the munchkin favorite color',
 'blue is also the predominating color that officially represent the eastern quadrant in the land of oz',
 'the munchkin have appeared in variou medium including the 1939 film the wizard of oz a well a in variou other film and comedy act',
 'concept while baum may have written about it there are no surviving note for the composition of the wonderful wizard of oz',
 'the lack of thi information ha resulted in speculation of the term origin he used in the book which include the word munchkin',
 'baum researcher brian attebery ha hypothesized that there might be a connection to the münchner kindl munich child the emblem of the bavarian city of munich',
 'the symbol wa originally a 13th-century statue of a monk looking down from the town hall in munich',
 'over the year the image wa reproduced many time for instance a a figure on beer stein and eventually evolved into a boy wearing a pointed hood',
 'baum family had german origin suggesting that baum could have seen one such reproduction in hi childhood',
 'it is also possible that munchkin came from the german word männchen which mean mannikin or little figure',
 'in 1900 baum published a book about window display in which he stressed the importance of mannequin in attracting customer',
 'another possibility is a connection to baron munchausen',
 'thi fictional character is based on a real baron who told outrageou tall tale based on hi military career',
 'it is also possible that the name is related to thumbkin bumpkin etc pet name given to finger of the hand in nursery rhyme',
 'like the other oz term the word munchkin end in a diminutive which in thi case refer to the size of the native',
 'literature oz book by frank baum the munchkin are first mentioned quote shown in an excerpt from chapter two of the wonderful wizard of oz titled the council with the munchkin',
 'dorothy initially meet only three of them along with the good witch of the north',
 'the rest of the munchkin then come out of hiding and are shown to be grateful toward dorothy for killing their evil ruler the wicked witch of the east',
 'dorothy later eventually find the yellow brick road and along the way attend a banquet held by a munchkin man named boq',
 'sometime in the book a background story is also given about a munchkin maiden named nimmie amee in later book who wa the former love interest of the tin woodman',
 'baum also included the munchkin character in hi later work a minor and major individual character',
 'the munchkin jinjur is the main antagonist in baum second book the marvelou land of oz where she seek to overthrow the scarecrow and take over the emerald city',
 'jinjur make a brief appearance in the next book entitled ozma of oz and is brought back in baum twelfth book the tin woodman of oz',
 'by thi time she is shown to be a more prominent character who is helpful and friendly to dorothy and her friend',
 'two other major munchkin character also appear in the tin woodman of oz tommy kwikstep and nimmie amee',
 'the former appear in the story asking for a wish for running an errand for a witch the latter is the name given to the mystery munchkin maiden from the first book who wa the former lover of the tin woodman',
 'more information is revealed that tell about the tin woodman origin and their tragic love story',
 'lastly the munchkin unc nunkie appear in baum seventh book the patchwork girl of oz where he is accidentally turned to stone',
 'hi munchkin nephew ojo successfully go on a quest in search of an antidote while learning more about himself in the proces',
 'subsequent oz book l frank baum died on 6 may 1919 after which other writer took up writing additional oz story',
 'in some case these book were written under baum name and included the munchkin',
 'there is at least one known munchkin character that wa created after baum death that appear a a major character',
 'zif is a munchkin boy who appear in john r neill first adaptation called the royal book of oz',
 'zif is a student at the college of art and athletic perfection he is both respectful and resentful toward hi teacher wogglebog who consider zif a nobody or a nothing',
 'the munchkin character that baum had created in hi lifetime also appear in these additional work',
 'film and musical early work 1902–1933 while the 1939 film is the most well known adaptation see section below it wa not the first outside work to show the munchkin in film or musical format',
 'one of the first musical adaptation of baum book took place in 1902 it wa also dubbed the wizard of oz',
 'the munchkin make their appearance in act one called the storm in which they are shown dancing around their maypole not noticing that dorothy house ha fallen to earth killing the wicked witch of the east',
 'the first film adaptation of baum work titled the wonderful wizard of oz wa released in 1910 followed by three sequel',
 'however it wa not until 1914 that munchkin character first appeared in film work',
 'ojo the lucky and unc nunkie both appear in a film titled the patchwork girl of oz based on the book of the same name',
 'thi film star american actres violet macmillan a ojo and wa produced by baum',
 '1939 film the 1939 movie musical the wizard of oz wa loosely based on baum novel',
 'notable difference of the munchkin include their country name of munchkinland and their clothe of many color instead of an all-blue attire',
 'in the musical the munchkin are portrayed by the thirty-odd member of the singer midget a european performing troupe made up of adult actor with dwarfism',
 'their number were swelled when a national talent search brought in a further ninety-fmy little man woman and teenager with a few average-sized child were also included a background extra in order to make up the 124 character requested by mgm',
 'in the musical the munchkin first appear when dorothy and toto arrive in the land of oz after her house land on the wicked witch of the east',
 'the munchkin hide from all the commotion until glinda the good witch arrife reassuring them that everything is okay',
 'dorothy tell them how she arrived in the land of oz through a musical number and the munchkin celebrate',
 'to make it official a barrister and a number of city father insist to the mayor of the munchkin city that they must make sure that the wicked witch of the east is really dead before the celebration continue',
 'the coroner confirm thi by saying that the witch is not only merely dead but is indeed most sincerely dead while showing a certificate of death',
 'the munchkin then celebrate further a dorothy receife gift from the lullaby league and the lollipop guild',
 'near the end of the song the wicked witch of the west arrife which cause the munchkin to panic',
 'after the wicked witch of the west leaf glinda tell dorothy to follow the yellow brick road to the emerald city a the munchkin guide her out of munchkinland',
 'the munchkin actor have since not avoided controversy with alleged behavior behind the scene',
 'in a 1967 interview judy garland referred to all of the munchkin a little drunk who got intoxicated every night to the point where they had to be picked up in butterfly net',
 'these accusation were denied a fabrication by munchkin margaret pellegrini who said only a couple of kid from germany even drank beer',
 'on 20 november 2007 the munchkin were given a star on the hollywood walk of fame',
 'seven of the surviving munchkin actor from the film were present',
 'a a result of the popularity of the 1939 film the word munchkin ha entered the english language a a reference to small child person with dwarfism or anything of diminutive stature',
 'actor and actress the following is a list of actor who portrayed the munchkin in the 1939 film',
 'most of the dwarf hired were acquired for mgm by leo singer the proprietor of singer midget',
 'a daily variety news story from 17 august 1938 stated 124 dwarf had been signed to play munchkin modern source place the number either at 122 or 124 an additional dozen or so child actor were hired to make up for the shortage of dwarf',
 'at least one munchkin actor dale paullin stage name paul dale did not make the final cut for the movie',
 'only two actor joseph koziel and frank cucksey used their actual voice for the dialogue exchanged with dorothy where she is given the flower',
 'the rest of the voice such a the munchkin choru were created by pinto colvig and billy bletcher with their voice recorded at a slow speed which were subsequently sped-up when played back',
 'in 1989 author stephen cox researched found and wrote about the surviving munchkin actor fifty year after they made the film',
 'he wrote about them in hi book the munchkin remember 1989 e.p',
 'dutton which wa later revised a the munchkin of oz cumberland house and hi book remained in print for nearly two decade',
 'when he wrote the book 33 of the actor with dwarfism who appeared in the film were still alive and were interviewed',
 'several of them outlived all the major cast a well a the original tin man buddy ebsen',
 'jerry maren who played the green lollipop guild member wa the last living adult munchkin actor',
 'maren wa the only munchkin alive when the film longest living cast member shep houghton an extra died in 2016 note some of the information presented in the table below may never be complete a social security record remain sparse prior to the mid-twentieth century',
 'other factor such a immigration and foreign citizenship also add to thi difficulty',
 'stage name and/or alias are present in italic and quotation mark',
 'child actress about a dozen child of average height were hired so they could be used for background fill',
 'source differ on the number of child used for these role ranging anywhere from 10 to 12 the name used for the woman are maiden name with known alias present in italic and quotation mark',
 'priscilla ann montgomery clark is the earliest born of the munchkin listed below and the final living munchkin actres',
 'later work 1940–1989 the 1939 film wa adapted into a musical that wa released in 1942 that include the munchkin character',
 'the event that take place mirror the film including the song ding-dong',
 'the witch is dead',
 'twenty-seven year later an animated film called the wonderful land of oz wa made featuring jinjur a a main antagonist',
 'other work the munchkin appeared in the wiz and were played by child and teenager',
 '1978 the munchkin appear at the end of return to oz',
 'they are seen celebrating dorothy return after defeating the nome king and are present at princes ozma coronation',
 'tommy kwikstep wa also seen there',
 '1985 in the muppet wizard of oz the munchkin were played by rizzo the rat a the mayor of munchkinland and hi fellow rat allowing them to also pull double duty a the field mouse that rescue dorothy from the poppy',
 '2005 the munchkin appeared in dorothy and the witch of oz',
 'the munchkin were first seen in the battle against the wicked witch of the west force in oz',
 'they were later brought to earth by glinda in order to combat the force of the wicked witch of the west',
 '2012 the munchkin appear in oz the great and powerful',
 'they alongside the quadling and the tinker a inhabitant of glinda protectorate',
 'although the film is not otherwise a musical the munchkin sing and dance much a they do in the 1939 film',
 '2013 the munchkin appear in dorothy and the wizard of oz with the mayor of munchkinland voiced by bill fagerbakke and the background munchkin voiced by steven blum and jessica dicicco',
 'ojo dr pipt the lollipop guild and the lullaby league are also featured',
 'also smith tinker are depicted a munchkin in thi show',
 'the munchkin appear a a culture of farmer in wicked',
 'director jon m chu decided to cast person closer to the book original description being about a tall a dorothy rather than the 1939 film cast of much shorter munchkin',
 'the main munchkin character in thi story boq woodsman is played by ethan slater who stand at 57 chu also chose to focu more on their culture than their physical appearance',
 'explanatory note reference citation work cited external link the dictionary definition of munchkin at wiktionary']

## TF-IDF without using BoW

Perform the TF-IDF Vectorization

In [ ]:
tf_idf_matrix = TfidfVectorizer(stop_words = 'english')
tf_idf = tf_idf_matrix.fit_transform(my_sentences)

In [ ]:
tf_idf.shape

(102, 608)

Print out results in a data frame

In [ ]:
pd.set_option('display.max_rows', 200)

results_df = pd.DataFrame(
  data = tf_idf.toarray(),
  columns = tf_idf_matrix.get_feature_names_out()
)

results_df.transpose()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,...,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101
10,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.250467,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.250467,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.199167,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
124,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.208216,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.365649,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13th,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.316328,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
written,0.0,0.0,0.0,0.0,0.0,0.378109,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.520664,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wrote,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.311535,0.471806,0.0,0.352529,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
year,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.236091,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.311535,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.283585,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
yellow,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.280467,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.277911,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
zif,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.345024,0.493756,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## K Nearest Neighbors

Fit nearest neighbors

In [ ]:
nn = NearestNeighbors().fit(tf_idf)

Get nearest neighbors distances to first sentence

In [ ]:
(tf_idf[0]).toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.37316781, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.37316781, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.22131918, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.22131918,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.37316781, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.37316781, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.33114427, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.24541474,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.37316781,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.18941929, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ]])

In [ ]:
distances, indices = nn.kneighbors(
  X = tf_idf[52],
  n_neighbors = 6,
)

In [ ]:
distances

array([[0.        , 0.98559941, 1.31679593, 1.33950434, 1.3619762 ,
        1.36806268]])

In [ ]:
indices

array([[52, 82, 51, 33, 97, 89]])

In [ ]:
np.array(my_sentences)[indices]

array([['the coroner confirm thi by saying that the witch is not only merely dead but is indeed most sincerely dead while showing a certificate of death',
        'the witch is dead',
        'to make it official a barrister and a number of city father insist to the mayor of the munchkin city that they must make sure that the wicked witch of the east is really dead before the celebration continue',
        'there is at least one known munchkin character that wa created after baum death that appear a a major character',
        'also smith tinker are depicted a munchkin in thi show',
        '2005 the munchkin appeared in dorothy and the witch of oz']],
      dtype='<U263')

In [ ]:
np.array([str(x) for x in wiki_blob.sentences])[indices]

array([['the coroner confirms this by saying that the witch is not only merely dead but is indeed most sincerely dead while showing a certificate of death.',
        'the witch is dead.',
        'to make it official, a barrister and a number of city fathers insist to the mayor of the munchkin city that they must make sure that the wicked witch of the east is really dead before the celebration continues.',
        'there is at least one known munchkin character that was created after baum death that appears as a major character.',
        'also, smith & tinker are depicted as munchkins in this show.',
        '2005 the munchkins appeared in dorothy and the witches of oz.']],
      dtype='<U274')