<a href="https://colab.research.google.com/github/stephanie465337/Data-Science-Portfolio-C21/blob/main/NotebookLM/Module%204/1c_Lambdas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Functions

A function is a [first-class citizen]( https://en.wikipedia.org/wiki/First-class_citizen ).  That is, it is an "entity which supports all the operations generally available to other entities." Those include these characteristics:
- assign to a variable
- pass as an argument to a function or method
- return from a function or method

In [1]:
#Example of setting a function to a variable
foo = print
foo("hello world")

hello world

In [2]:
what_is = type
what_is("hello")

str

In [ ]:
for fooo in [sum, len, min, max]:

# Lambdas
- anonymous/inline functions
- "throw away" functions
- good for passing a function as an argument to another function
- quick and easy
- one line
- expression
- No statements - no assignments (x=3) , some logic - loops, etc.
- 'anonymous functions' - can and should be unnamed

In [3]:
import pandas as pd
from functools import reduce
import numpy as np

# Syntax

`lambda argument(s) : expression`
expression is the return value

**You shouldn't use named lambda functions.  Use def instead.  This is just an example so you can see lambda on it's own**

In [4]:
#DO NOT do this.  It works, but is considered "bad practice", e.g. no type hints, no doc string
multiply_2_lambda = lambda x: x*2
type(multiply_2_lambda)

function

In [5]:
# ... but it does work.
multiply_2_lambda(9)

18

In [6]:
#No dock string
multiply_2_lambda?

In [7]:
#Do this instead. Notice type hints and doc string
def multiply_2_def(x: int) -> int:
  '''Doubles the value of an integer'''
  return x*2
type(multiply_2_def)

function

In [8]:
multiply_2_def(9)

18

In [9]:
multiply_2_def("hello ")

'hello hello '

In [10]:
multiply_2_def?

# A few functions in Python that take lambdas as arguments
Generally, lambdas are used in the context of another function, such as the following:
- map
- reduce
- sort

## Map

In [11]:
#Map allows you to transform all the items in an iterable without using a for loop
#Input to function is a single element at a time
#It is useful when you need to apply a transformation function to each item in an iterable without having to create a named function.

my_list = [2,3,6,7,4,4,9]

list_3 = list(map(lambda x: x*3, my_list))
print(list_3)

[6, 9, 18, 21, 12, 12, 27]

In [12]:
#For python lists, list comprehension is preferred
[ x*3 for x in my_list ]

[6, 9, 18, 21, 12, 12, 27]

In [13]:
#The same using a named function
def times_3( x: int ) -> int:
  '''Triples the value of an integer'''
  return x*3

my_list = [2,3,6,7,4,4,9]

# notice the name of the function is passed without "()"
list_3 = list(map(times_3, my_list))
print(list_3)

[6, 9, 18, 21, 12, 12, 27]

In [14]:
times_3("hi ")

'hi hi hi '

## Reduce

In [15]:
#Reduce will apply a function *cumulatively* to all elements in an interable.
#Input is initial pair folllowed by cumulative value and next element
my_list = [2, 3, 7, 3]
print(reduce(lambda x, y: x * y, my_list))

126

In [16]:
#The same using a named function
def times_xy( x:int, y:int) -> int:
  '''Multiplies X and Y'''
  return x * y

my_list = [2, 3, 7, 3]
print(reduce(times_xy, my_list))

126

In [17]:
print(reduce(lambda x, y: x + y, my_list))

15

In [18]:
print(reduce(lambda x, y: x + y, range(101)))

5050

## Sort

In [19]:
#Key is a parameter used to specify a function used on each list element prior sorting, e.g. with nested lists
words = [['chrysanthemum', 9], ['foo',8], ['blue',-7], ['loo',9], ['barbaric', 5], ['barber',3]]
words.sort() #Sorts by first element (the string)
print(words)

[['barbaric', 5], ['barber', 3], ['blue', -7], ['chrysanthemum', 9], ['foo', 8], ['loo', 9]]

In [20]:
words.sort(key = lambda x: x[1]) #Sorts by second element (the number)
print(words)

[['blue', -7], ['barber', 3], ['barbaric', 5], ['foo', 8], ['chrysanthemum', 9], ['loo', 9]]

In [21]:
words.sort(key = lambda x: abs(x[1])) #Sorts by second element (the number)
print(words)

[['barber', 3], ['barbaric', 5], ['blue', -7], ['foo', 8], ['chrysanthemum', 9], ['loo', 9]]

In [22]:
#Same using a named function
def get_second_item(x):
  return x[1]

words = [['foo',8], ['blue',-7], ['loo',9], ['barbaric', 5], ['barber',3], ['chrysanthemum', 9]]
words.sort(key=get_second_item)
print(words)

[['blue', -7], ['barber', 3], ['barbaric', 5], ['foo', 8], ['loo', 9], ['chrysanthemum', 9]]

In [23]:
get_second_item

# Lambdas in DataFrames

In [24]:
df = pd.DataFrame([[1,2,3],[4,3,6],[7,6,5]])
df

   0  1  2
0  1  2  3
1  4  3  6
2  7  6  5

In [25]:
#Create a new column that is a function of another column
df[3] = df[2].apply(lambda x: x*2)
df

   0  1  2   3
0  1  2  3   6
1  4  3  6  12
2  7  6  5  10

In [26]:
#Same using a named function
df[4] = df[2].apply(multiply_2_def)
df

   0  1  2   3   4
0  1  2  3   6   6
1  4  3  6  12  12
2  7  6  5  10  10

In [27]:
df_foo = pd.DataFrame()
df_foo

Empty DataFrame
Columns: []
Index: []

In [28]:
#Same using a named function
df_foo["func"] = df[2].apply(multiply_2_def)
df_foo

   func
0     6
1    12
2    10

In [29]:
#Create a new column that is a function of another column
df_foo["lambda"] = df[2].apply(lambda x: x*2)
df_foo

   func  lambda
0     6       6
1    12      12
2    10      10

## Your Turn

### Part 1

A data frame, `df`, has been defined for you below. Use lambdas to do the following:

1. Create a fourth column that is the square of the first column.
2. Create a fifth column that is the square root of the second column.


```bash
df = pd.DataFrame([[1,2,3],[4,3,6],[7,6,5]])
df
```

In [30]:
df = pd.DataFrame([[1,2,3],[4,3,6],[7,6,5]])
df

   0  1  2
0  1  2  3
1  4  3  6
2  7  6  5

In [31]:
# Solution 1: Create a fourth column that is the square of the first column.
df[4] = df[1].apply(lambda x: x**2)
df

   0  1  2   4
0  1  2  3   4
1  4  3  6   9
2  7  6  5  36

In [32]:
# Solution 2: Create a fifth column that is the square root of the second column.
df[5] = df[2].apply(lambda x: x**(1/2))
df

   0  1  2   4         5
0  1  2  3   4  1.732051
1  4  3  6   9  2.449490
2  7  6  5  36  2.236068

### Part 2
A data frame, `df`, has been defined for you below. Use lambdas to do the following:

1. Create a column `fname_cap` that has the first letter of `fname` capitalized.
1. Create a column `lname_cap` that has the first letter of `lname` capitalized.
1. Create a column `lfname_cap` that is `lname_cap` and `fname_cap` separated by a comma and a space.

The input data frame:

|    | fname   | lname      |
|---:|:--------|:-----------|
|  0 | GEORGE  | WASHINGTON |
|  1 | JOHN    | ADAMS      |
|  2 | THOMAS  | JEFFERSON  |
|  3 | JAMES   | MADISON    |

In the end, the data frame should look like this:

|    | fname   | lname      | fname_cap   | lname_cap   | lfname_cap         |
|---:|:--------|:-----------|:------------|:------------|:-------------------|
|  0 | GEORGE  | WASHINGTON | George      | Washington  | Washington, George |
|  1 | JOHN    | ADAMS      | John        | Adams       | Adams, John        |
|  2 | THOMAS  | JEFFERSON  | Thomas      | Jefferson   | Jefferson, Thomas  |
|  3 | JAMES   | MADISON    | James       | Madison     | Madison, James     |

A starting point:

```python
names =  ['GEORGE WASHINGTON',
          'JOHN ADAMS',
          'THOMAS JEFFERSON',
          'JAMES MADISON'
]
```

In [33]:
names =  ['GEORGE WASHINGTON',
          'JOHN ADAMS',
          'THOMAS JEFFERSON',
          'JAMES MADISON'
]

In [46]:
df = pd.DataFrame([f.split() for f in names], columns= 'fname lname'.split())
df

    fname       lname
0  GEORGE  WASHINGTON
1    JOHN       ADAMS
2  THOMAS   JEFFERSON
3   JAMES     MADISON

In [48]:
#Solution 1: Create a column fname_cap that has the first letter of fname capitalized.
df['fname_cap'] = df['fname'].apply(lambda x: x.capitalize())
df

    fname       lname fname_cap
0  GEORGE  WASHINGTON    George
1    JOHN       ADAMS      John
2  THOMAS   JEFFERSON    Thomas
3   JAMES     MADISON     James

In [49]:
df['fname'].str.capitalize()

0    George
1      John
2    Thomas
3     James
Name: fname, dtype: object

In [50]:
#Solution 2: Create a column lname_cap that has the first letter of lname capitalized.
df["lname_cap"] = df["lname"].apply(lambda x: x.capitalize())
df

    fname       lname fname_cap   lname_cap
0  GEORGE  WASHINGTON    George  Washington
1    JOHN       ADAMS      John       Adams
2  THOMAS   JEFFERSON    Thomas   Jefferson
3   JAMES     MADISON     James     Madison

In [51]:
df['lname'].str.capitalize()

0    Washington
1         Adams
2     Jefferson
3       Madison
Name: lname, dtype: object

In [52]:
#Solution 3: Create a column lfname_cap that is lname_cap and fname_cap separated by a comma and a space.
df["lfname_cap"] = df.apply(lambda x: f'{x["lname_cap"]}, {x["fname_cap"]}', axis=1)
df

    fname       lname fname_cap   lname_cap          lfname_cap
0  GEORGE  WASHINGTON    George  Washington  Washington, George
1    JOHN       ADAMS      John       Adams         Adams, John
2  THOMAS   JEFFERSON    Thomas   Jefferson   Jefferson, Thomas
3   JAMES     MADISON     James     Madison      Madison, James

In [53]:
df['lname_cap'] + ', ' + df['fname_cap']

0    Washington, George
1           Adams, John
2     Jefferson, Thomas
3        Madison, James
dtype: object

In [54]:
#Does not work
f'{df["lname_cap"]}, {df["fname_cap"]}'

'0    Washington\n1         Adams\n2     Jefferson\n3       Madison\nName: lname_cap, dtype: object, 0    George\n1      John\n2    Thomas\n3     James\nName: fname_cap, dtype: object'