<a href="https://colab.research.google.com/github/stephanie465337/Data-Science-Portfolio-C21/blob/main/3c_Object_Oriented_Programming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics of Object Oriented Programming

## Why we care

Everything in python is an object:
- strings
- ints
- lists
- DataFrames
- Numpy Arrays

We want to cover just enough OOP that you understand certain things about Python syntax.

## Scope

## Manging variables

### global, local, nonlocal

Local scope

In [1]:
x = 5

In [2]:
x

5

In [3]:
def foo():
  # print(x)
  x = 10
  print(x)

In [4]:
foo()

10

In [5]:
x

5

In [6]:
def bar(x):
  print(x)
  x = 10
  print(x)

In [7]:
x = 5
bar(x)

5
10

In [8]:
x

5

Using `global`

In [9]:
def foo():
  global x
  print(x)
  x = 10
  print(x)

In [10]:
x = 5
foo()

5
10

In [11]:
x

10

Enclosed scope, using `nonlocal`

In [12]:
def foo():
  '''this is foo'''
  x = 15
  print(x)

  def bar(n=20):
    '''this is bar'''
    nonlocal x
    print(x)
    x = n
    print(x)

  return bar

In [13]:
x = 5
x

5

In [14]:
type(foo())

15

function

In [15]:
yow = foo()

15

In [16]:
yow?

In [17]:
type(yow)

function

In [18]:
yow(8)

15
8

In [19]:
x

5

In [20]:
yow()

8
20

In [21]:
x

5

In [22]:
asdf = foo
print(asdf)

asdf = foo()
print(asdf)

<function foo at 0x7fb5d0f76de0>
15
<function foo.<locals>.bar at 0x7fb5d0f844a0>

In [23]:
asdf?

In [24]:
x = 5
asdf = foo()
print("===")
asdf()

15
===
15
20

In [25]:
foo()(8)

15
15
8

In [26]:
yow()

20
20

In [27]:
x

5

### Recursive function

A function that calls itself.  It has two parts:
1. the base condition and result
1. the recursive ( or self-referential ) part

Factorial =

n! = n * (n-1) * (n-2) * ... * 1

= n * (n-1)!

= n * (n-1) * (n-2)!

In [28]:
def factorial(x):
  if x <= 1:
    print(f"== {x} == DONE!!!!")
    return 1
  else:
    print(f"== {x}")
    return x * factorial(x-1)

- factorial(1) -> 1
- factorial(2) -> 2 * factorial(1) -> 2 * 1 -> 2
- factorial(3) -> 3 * factorial(2) -> 3 * 2 * factorial(1) -> 3 * 2 * 1 -> 6

In [29]:
factorial(3)

== 3
== 2
== 1 == DONE!!!!

6

### Using a closure

A closure is when a function "encloses" or contains the definition to another function.  Usually, the enclosing ( or outer ) function contains variables that are used to keep state, i.e. are persistent across calls to the enclosed ( or inner ) function.  The outer function returns a reference to the inner function.

Fibonacci =  0, 1, 1, 2, 3, 5, 8, 13, ...

In [30]:
def make_fibonacci():
  #Enclosed variable (closure)
  memo = {}

  #Enclosed function (closure)
  def fibonacci(n):
    if n in memo:
      return memo[n]

    if   n <= 1:
      result = 0
    elif n == 2:
      result = 1
    else:
      result = fibonacci(n - 1) + fibonacci(n - 2)

    memo[n] = result
    return result
  def view():
    return memo

  return fibonacci, memo

In [31]:
fibc, memo = make_fibonacci()

In [32]:
type(fibc)

function

In [33]:
fibc(3)

1

In [34]:
memo

{2: 1, 1: 0, 3: 1}

In [35]:
memo.clear()

In [36]:
memo

{}

## Classes and Objects/Instances

**Classes** are like a blueprint.  They define a type of object and the methods that can be used on that object.  

**Objects/Instances** are specific instances of a class.  For example, an actual house.  You could create as many houses as you wanted from one blueprint.  

For example, DataFrame is a class in Pandas.  But when you create a DataFrame, that specific DataFrame is an object.  

Classes allow us to create functionality that will be available to all objects that we make of that class.  

For example,  you are able to use head() with any DataFrame to get the first few entries.

##  Methods and Attributes
**Methods** are like functions, but they run on an object.  
- For example, when you call head() on a dataframe it's df.head() not head(df).  


**Attributes** are values for variables associated with an object.

In [37]:
import pandas as pd

In [38]:
df = pd.DataFrame([[0,2],[5,6],[9,0]])
df

   0  1
0  0  2
1  5  6
2  9  0

In [39]:
# head() is a method we can call on our dataframe object
df.head(2)

   0  1
0  0  2
1  5  6

In [40]:
# shape is an attribute  - notice how it has no ()
df.shape

(3, 2)

In [41]:
print(df)

   0  1
0  0  2
1  5  6
2  9  0

In [42]:
print(df.__class__)

<class 'pandas.core.frame.DataFrame'>

In [43]:
print(df.__class__.__name__)

DataFrame

##  Making your own class

Animal **Class**

Attributes:
- Sound - What sound does it make?
- Name
- Color
- Species
- \# of legs
- eye color
....

Methods (What can an animal do?  Or what can I do to it?):
- Talk
- Walk
- ...

**Object - Specific instance of the class**

Cat -

Sound - mreeow

Name - Head Cat

Color - White & grey

**Make an animal class & an object of type Animal**

In [44]:
#Class names - first letter of words are capitalized - no spaces - i.e. pd.DataFrame
class Animal:
  """This is the Animal Class"""

  #This is the constructor.  It is called when we make a new Animal.
  #For example, something like
  # head_cat = Animal('Head Cat', 'cat', 'white and grey', 'meow') goes to
  # head_cat = __init__('Head Cat', 'cat', 'white and grey', 'meow')
  def __init__(self, name, species, color, sound):
    #Here we set the attributes based on the input from the constructor
    self.name = name
    self.species = species
    self.color = color
    self.sound = sound
    self.steps = 0

  #This is a dunder method - it returns a string as a representation of the object.
  #Creating a string that will be returned when print is used on the Animal.
  #We'll make it something pretty and human-readable.
  def __repr__(self):
    return(f"{self.__class__.__name__}(name={self.name}, species={self.species}, color={self.color}, sound={self.sound})")

  #This is a method
  def talk(self):  # head_cat.talk()  ->  talk(head_cat)
    """Print the animal's sound"""
    print(self.sound)  # print(head_cat.sound)

  def walk(self, num_steps):
    self.steps = self.steps + num_steps
    return num_steps

In [45]:
our_dog = Animal(name = 'Zeus', species = 'dog', color = 'grey', sound = 'bark')
our_dog

Animal(name=Zeus, species=dog, color=grey, sound=bark)

In [46]:
print(our_dog)

Animal(name=Zeus, species=dog, color=grey, sound=bark)

In [47]:
our_dog.steps

0

In [48]:
our_dog.talk()

bark

In [49]:
our_dog.walk(5)

5

In [50]:
our_dog.steps

5

In [51]:
#Animal?
help(Animal)

Help on class Animal in module __main__:

class Animal(builtins.object)
 |  Animal(name, species, color, sound)
 |
 |  This is the Animal Class
 |
 |  Methods defined here:
 |
 |  __init__(self, name, species, color, sound)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __repr__(self)
 |      Return repr(self).
 |
 |  talk(self)
 |      Print the animal's sound
 |
 |  walk(self, num_steps)
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object

In [52]:
our_dog.__dict__

{'name': 'Zeus',
 'species': 'dog',
 'color': 'grey',
 'sound': 'bark',
 'steps': 5}

In [53]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6]])
df.__dict__

{'_is_copy': None,
 '_mgr': BlockManager
 Items: RangeIndex(start=0, stop=3, step=1)
 Axis 1: RangeIndex(start=0, stop=2, step=1)
 NumpyBlock: slice(0, 3, 1), 3 x 2, dtype: int64,
 '_item_cache': {},
 '_attrs': {},
 '_flags': <Flags(allows_duplicate_labels=True)>}

In [54]:
#Head Cat is an Object of Type Animal.  Animal is the class.
head_cat = Animal('Head Cat', 'cat', 'white and grey', 'mrrrrr')
head_cat

Animal(name=Head Cat, species=cat, color=white and grey, sound=mrrrrr)

In [55]:
head_cat.talk()

mrrrrr

In [ ]:
print(head_cat)

In [56]:
print(head_cat.species)

cat

In [57]:
head_cat.color

'white and grey'

In [58]:
trip = Animal('Tripping Hazzard', 'cat', 'grey', 'purrr')
trip.talk()
print(f"Trip was a {trip.color} cat")

purrr
Trip was a grey cat

In [59]:
print(trip)

Animal(name=Tripping Hazzard, species=cat, color=grey, sound=purrr)

In [60]:
parrot = Animal("Timothy", "parrot", "blue", "Polly want a cracker!")

In [61]:
print(parrot)

Animal(name=Timothy, species=parrot, color=blue, sound=Polly want a cracker!)

In [62]:
parrot.talk()

Polly want a cracker!

In [63]:
parrot.walk(10)
parrot.steps

10

In [64]:
parrot.walk(5)
parrot.steps

15

In [65]:
print(parrot)
print(parrot.color)

Animal(name=Timothy, species=parrot, color=blue, sound=Polly want a cracker!)
blue

##  Making a derived class

### Creating a [Queue]( https://en.wikipedia.org/wiki/Queue_(abstract_data_type) )

"A queue has two ends, the top ( or back/tail/rear ), which is the only position at which the **push** ( or enqueue/enter/add ) operation may occur, and the bottom (or front/head), which is the only position at which the **pop** ( or dequeue/leave/remove ) operation may occur."

![A queue]( https://media.geeksforgeeks.org/wp-content/cdn-uploads/20221213113312/Queue-Data-Structures.png )

Why not use a list?

In [70]:
#Create the list
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [75]:
#Show the size
my_list.size

AttributeError: 'list' object has no attribute 'size'

In [76]:
#Pop from the front
my_list.pop()

3

In [77]:
#Push a value to the back
my_list.push(3)

AttributeError: 'list' object has no attribute 'push'

In [78]:
#Display items in the queue.
my_list.show()

AttributeError: 'list' object has no attribute 'show'

Using a queue.

In [79]:
class Queue(list):
  '''
  Implements a queue data structure with methods push(), pop(), and show(),
  and attribute size.
  '''

  def __init__(self, initial_list=None):
    '''Initialize a Queue given an optional list'''
    if initial_list is not None:
      super().__init__(initial_list)
      self.size = len(initial_list)
    else:
      super().__init__()
      self.size = 0

  def push(self, item):
    '''Push an element onto the Queue'''
    self.append(item)
    self.size += 1

  def pop(self):
    '''Remove an element from the Queue'''
    if self.size > 0:
      self.size -= 1
      return super().pop(0)
    else:
      return None

  def show(self):
    '''Show the elements in the Queue'''
    return(self)

In [80]:
#Example usage:
q = Queue([1, 2, 3])
q

[1, 2, 3]

In [81]:
type(q)

__main__.Queue

In [82]:
print("Initial queue:", q)

Initial queue: [1, 2, 3]

In [83]:
print("Size of the queue:", q.size)

Size of the queue: 3

In [84]:
print("Popped item:", q.pop())

Popped item: 1

In [85]:
print("Queue after popping:", q)

Queue after popping: [2, 3]

In [86]:
print("Size after popping:", q.size)

Size after popping: 2

In [87]:
q.push(100)
q

[2, 3, 100]

In [88]:
print(q.show())
type(q)

[2, 3, 100]

__main__.Queue

In [89]:
q = Queue()
q

[]

In [90]:
q.push("Haji")
q

['Haji']

In [91]:
q.push("Lisa")
q

['Haji', 'Lisa']

In [92]:
q

['Haji', 'Lisa']

In [93]:
q.pop()

'Haji'

In [94]:
q

['Lisa']

In [95]:
q.push("Abe")

In [96]:
q

['Lisa', 'Abe']

In [97]:
q.size

2

In [98]:
q.pop()

'Lisa'

In [99]:
q

['Abe']

In [100]:
q = Queue([1, 2, 3])
q

[1, 2, 3]

In [101]:
l = [1, 2, 3]
l

[1, 2, 3]

In [102]:
q.pop()

1

In [103]:
l.pop()

3

Introspection

In [104]:
dir(Queue)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'push',
 'remove',
 'reverse',
 'show',
 'sort']

In [105]:
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [106]:
dir(q)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'push',
 'remove',
 'reverse',
 'show',
 'size',
 'sort']

In [107]:
Queue.__base__, Queue.__base__.__base__, Queue.__base__.__base__.__base__

(list, object, None)

## Expanding Pandas

In [108]:
@pd.api.extensions.register_dataframe_accessor("rwc")
class DataFrameExtension:
  def __init__(self, pandas_obj):
    self._obj = pandas_obj

  def rows(self):
    return len(self._obj)

In [109]:
dir(DataFrameExtension)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'rows']

In [110]:
# Create a data frame
data = {'col1': [1, 2, 3, 4, 5], 'col2': ['a', 'b', 'c', 'd', 'e']}
df = pd.DataFrame(data)
df

   col1 col2
0     1    a
1     2    b
2     3    c
3     4    d
4     5    e

In [111]:
#Display how many rows
df.rwc.rows()

5

In [112]:
dir(df.rwc)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_obj',
 'rows']

## Your turn
1. Create your own class.
  - List a few attributes (>2)
  - Create at least 3 methods - `__init__`, `__repr__`, and at least 1 method of your own
1. Create a new object of your class
1. Print your object, print your object's attributes, & run your method


---
Ideas:
- Car
- Person
- Plant

In [113]:
#Solution 1

In [114]:
#Solution 2

In [115]:
#Solution 3

## Memoizing

### Persistence with an instance attribute ( variable )

In [116]:
#Solution
class Fibonacci:

  def __init__(self):
    self.memo = {}

  def fibonacci(self, n):
    if n in self.memo:
      return self.memo[n]
    if n <= 1:
      return n
    else:
      result = self.fibonacci(n - 1) + self.fibonacci(n - 2)
      self.memo[n] = result
      return result

In [117]:
fib1a = Fibonacci()

#Output: 55
print(fib1a.fibonacci(10))

55

In [118]:
fib1a.memo

{2: 1, 3: 2, 4: 3, 5: 5, 6: 8, 7: 13, 8: 21, 9: 34, 10: 55}

In [119]:
fib1b = Fibonacci()

In [120]:
fib1b.memo

{}

In [121]:
fib1a.memo

{2: 1, 3: 2, 4: 3, 5: 5, 6: 8, 7: 13, 8: 21, 9: 34, 10: 55}

### Persistence with an class attribute ( variable )

In [122]:
#Solution
class Fibonacci2:
  memo = {}

  def fibonacci(self, n):
    if n in Fibonacci2.memo:
      return Fibonacci2.memo[n]
    if n <= 1:
      return n
    else:
      result = self.fibonacci(n - 1) + self.fibonacci(n - 2)
      Fibonacci2.memo[n] = result
      return result

In [123]:
fib2a = Fibonacci2()

#Output: 55
print(fib2a.fibonacci(10))

55

In [124]:
fib2a.memo

{2: 1, 3: 2, 4: 3, 5: 5, 6: 8, 7: 13, 8: 21, 9: 34, 10: 55}

In [125]:
fib2b = Fibonacci2()

In [126]:
fib2b.memo

{2: 1, 3: 2, 4: 3, 5: 5, 6: 8, 7: 13, 8: 21, 9: 34, 10: 55}

In [127]:
fib2b.fibonacci(20)

6765

In [128]:
fib2a.memo

{2: 1,
 3: 2,
 4: 3,
 5: 5,
 6: 8,
 7: 13,
 8: 21,
 9: 34,
 10: 55,
 11: 89,
 12: 144,
 13: 233,
 14: 377,
 15: 610,
 16: 987,
 17: 1597,
 18: 2584,
 19: 4181,
 20: 6765}

In [129]:
#Solution
class Fibonacci2:
  memo = {1:1}

  def fibonacci(n):
    if n in Fibonacci2.memo:
      return Fibonacci2.memo[n]
    if n <= 1:
      return n
    else:
      result = Fibonacci2.fibonacci(n - 1) + Fibonacci2.fibonacci(n - 2)
      Fibonacci2.memo[n] = result
      return result

In [130]:
fib3 = Fibonacci2()

In [131]:
Fibonacci2.fibonacci(-3)

-3

In [132]:
Fibonacci2.memo

{1: 1}