<a href="https://colab.research.google.com/github/stephanie465337/Data-Science-Portfolio-C21/blob/main/Data_Questions_How_Many%3F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Transaction Predictions

##Data Questions? How Many?

Columns
- identifier columns:
- target columns:
	-  rows with nulls in each:
- feature columns:
	- rows with nulls in each:
- numerical columns:
	- discrete columns:
		- rows with nulls in each:
	-continuous columns:
		- rows with nulls in each:
- categorical columns:
	-nominal columns:
		- rows with nulls in each:
		- categories in each:
	-ordinal columns:
		- rows with nulls in each:
		- categories in each:
- Nested columns:

ROWS
- rows with nulls:
- duplicate rows:
- missing rows:

###Imports

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

###File Path

In [ ]:
url = 'https://ddc-datascience.s3.amazonaws.com/Projects/Project.1-Transactions/Data/Transaction.train.big.csv'
url

'https://ddc-datascience.s3.amazonaws.com/Projects/Project.1-Transactions/Data/Transaction.train.big.csv'

In [ ]:
df = pd.read_csv(url)
df

,Unnamed: 0,ID_code,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,...,var_91,var_92,var_93,var_94,var_95,var_96,var_97,var_98,var_99,var_100
0,0,train_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,train_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,train_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,train_3,0.0,4.6739,22.3915,15.6015,NaN,0.0464,NaN,NaN,...,NaN,11.1077,NaN,-12.6465,NaN,NaN,NaN,NaN,NaN,14.0618
4,4,train_4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1049995,1049995,train_1049995,1.0,11.3251,16.4148,20.5955,NaN,-6.3011,NaN,NaN,...,NaN,1.3921,NaN,-16.4925,NaN,NaN,NaN,NaN,NaN,14.4421
1049996,1049996,train_1049996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1049997,1049997,train_1049997,0.0,8.9941,13.4127,3.9567,NaN,3.5744,NaN,NaN,...,NaN,2.0836,NaN,-18.6168,NaN,NaN,NaN,NaN,NaN,14.0689
1049998,1049998,train_1049998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1049999,1049999,train_1049999,0.0,2.1828,12.3805,17.5654,NaN,8.1795,NaN,NaN,...,NaN,-12.1108,NaN,10.7608,NaN,NaN,NaN,NaN,NaN,14.1690

### Columns

####Identifier columns

In [ ]:
#ID_code is the unique identifier. Each value is different and does not contribute to explain/predict the target.
df.columns

Index(['Unnamed: 0', 'ID_code', 'target', 'var_0', 'var_1', 'var_2', 'var_3',
       'var_4', 'var_5', 'var_6',
       ...
       'var_91', 'var_92', 'var_93', 'var_94', 'var_95', 'var_96', 'var_97',
       'var_98', 'var_99', 'var_100'],
      dtype='object', length=104)

In [ ]:
#Must match len(df)
df['ID_code'].nunique()

1050000

In [ ]:
#Must match df['ID_code'].nunique
len(df)

1050000

####Target columns

In [ ]:
#The 'target' column that I am trying to predict, explain or understand.
#Rows with nulls in each
df['target'].head()

0    NaN
1    NaN
2    NaN
3    0.0
4    NaN
Name: target, dtype: float64

In [ ]:
df['target'].value_counts()
#Separates into two classes:
# 0 = Customer WILL make a transaction
# 1 = Customer will NOT make a transaction

target
0.0    161960
1.0     18040
Name: count, dtype: int64

In [ ]:
#Rows with nulls in target
df['target'].isnull().sum()

np.int64(870000)

####Feature columns

In [ ]:
feature_columns = [col for col in df.columns if col.startswith ('var_')]

df[feature_columns].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050000 entries, 0 to 1049999
Columns: 101 entries, var_0 to var_100
dtypes: float64(101)
memory usage: 809.1 MB

In [ ]:
#Rows with nulls in each
#Minus 3 columns for 2 identifier and 1 target column
df.isnull().sum()

var_0       870000
var_1       870000
var_2       870000
var_3      1050000
var_4       870000
            ...
var_96     1050000
var_97     1050000
var_98     1050000
var_99     1050000
var_100     870000
Length: 101, dtype: int64

####Numerical columns

In [ ]:
len(df.select_dtypes(include = 'number').columns)

103

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050000 entries, 0 to 1049999
Columns: 104 entries, Unnamed: 0 to var_100
dtypes: float64(102), int64(1), object(1)
memory usage: 833.1+ MB

In [ ]:
#Discrete columns (int): is the Unnamed column
df['Unnamed: 0'].isnull().sum()

np.int64(0)

In [ ]:
#Continuous columns (flt): are the 'Var_' columns
df[feature_columns].isnull().sum()

var_0       870000
var_1       870000
var_2       870000
var_3      1050000
var_4       870000
            ...
var_96     1050000
var_97     1050000
var_98     1050000
var_99     1050000
var_100     870000
Length: 101, dtype: int64

####Categorical columns
Nominal columns: none

Ordinal columns: none

The object column is not considered categorical.

In [ ]:
df.select_dtypes(include='object').head()

   ID_code
0  train_0
1  train_1
2  train_2
3  train_3
4  train_4

In [ ]:
df['ID_code'].head()

0    train_0
1    train_1
2    train_2
3    train_3
4    train_4
Name: ID_code, dtype: object

####Nested columns

In [ ]:
df.head()

,Unnamed: 0,ID_code,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,...,var_91,var_92,var_93,var_94,var_95,var_96,var_97,var_98,var_99,var_100
0,0,train_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,train_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,train_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,train_3,0.0,4.6739,22.3915,15.6015,NaN,0.0464,NaN,NaN,...,NaN,11.1077,NaN,-12.6465,NaN,NaN,NaN,NaN,NaN,14.0618
4,4,train_4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

###Rows

In [ ]:
#Rows with nulls
df.isnull().any(axis = 1).sum()

np.int64(1050000)

In [ ]:
#Duplicate rows
df.duplicated().sum()

np.int64(0)

In [ ]:
#Missing rows
df.isnull().sum()

Unnamed: 0          0
ID_code             0
target         870000
var_0          870000
var_1          870000
               ...
var_96        1050000
var_97        1050000
var_98        1050000
var_99        1050000
var_100        870000
Length: 104, dtype: int64