<a href="https://colab.research.google.com/github/stephanie465337/Data-Science-Portfolio-C21/blob/main/NotebookLM/Module%202/1e_Imputation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Missing Data

Imputation is used to fill in missing values in a data set, i.e. fill in the blanks. Missing values are values in a dataset that are missing or have a null value. For example, it could be data that weren't collected or were mistakenly not recorded or were recorded incorrectly.

**Note**: A zero data value is not necessarily a missing value. Zero can be a useful measure, depending on the variable.

Missing values can cause issues in ML because many ML algorithms are not equipped to handle missing data.

## Simple Strategies

There are a few simple strategies for handling missing data:

1) **Drop rows with null values.** We can drop rows if the missing data in the dataset is missing at random, and if the number of null rows is low relative to the total number of rows in our dataset. We have to be careful because dropping too much data can cause bias in our model.

2) **Drop columns that mostly contain null values** We can drop columns if most of the values are null. However, we have to take caution when doing this because we don't want to drop a column that could have been useful for our predictions.

## Imputation

Imputation involves replacing a null value with a different value. There are numerous ways that a null value can be imputed, including:

1. Using the mean or median of the variable (for continuous data).
2. Using the mode of the variable (for categorical data).
3. Using a constant value (e.g., 0)
4. Using machine learning!
5. Many other ways that are beyond the scope of the class.

## Implementation

There are three commonly used ways to perform imputation in Python.

1. pandas `fillna()` - fills in missing values for a single column using a constant or summary statistic. This is particularly useful if you need to fill NA values differently for different columns.
1. sklearn `SimpleImputer` - fills in missing values using a constant or summary statistic. Useful if you want to fill in NA values in different columns using the same constant or the same summary statistic.
1. sklearn `IterativeImputer` - fills in missing values as a function of other variables.

## Example
https://medium.com/analytics-vidhya/a-quick-guide-on-missing-data-imputation-techniques-in-python-2020-5410f3df1c1e

In [ ]:
#Imports
import pandas as pd
import numpy as np

In [ ]:
#Generate Data
np.random.seed(42)
my_df = pd.DataFrame()
my_df["A"] = np.random.randint(1, 10, 10)
my_df["B"] = np.random.random(10)
my_df["C"] = np.random.randint(1, 20, 10)
my_df["D"] = np.random.normal(0, 10, 10)

my_df

   A         B   C          D
0  7  0.142867  17  -5.251229
1  4  0.650888  10  19.127713
2  8  0.056412  16 -20.267196
3  5  0.721999  15  11.194236
4  7  0.938553  15   7.791926
5  3  0.000779  19 -11.010978
6  7  0.992212  12  11.302282
7  8  0.617482   3   3.731189
8  5  0.611653   5  -3.864730
9  4  0.007066  19 -11.587702

In [ ]:
my_df.shape

(10, 4)

In [ ]:
my_df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
A,10.0,5.800000,1.813529,3.000000,4.250000,6.000000,7.000000,8.000000
B,10.0,0.473991,0.386246,0.000779,0.078025,0.614567,0.704221,0.992212
C,10.0,13.100000,5.566766,3.000000,10.500000,15.000000,16.750000,19.000000
D,10.0,0.116551,12.482028,-20.267196,-9.571040,-0.066770,10.343659,19.127713

In [ ]:
my_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       10 non-null     int64
 1   B       10 non-null     float64
 2   C       10 non-null     int64
 3   D       10 non-null     float64
dtypes: float64(2), int64(2)
memory usage: 452.0 bytes

In [ ]:
#Randomly change some values to NA
np.random.seed(11)
rand_Index_A = np.random.randint(0, 9, 3)
rand_Index_B = np.random.randint(0, 9, 4)

(rand_Index_A, rand_Index_B)

(array([0, 1, 7]), array([1, 7, 2, 8]))

In [ ]:
my_df.loc[rand_Index_A, 'A'] = np.nan
my_df.loc[rand_Index_B, 'B'] = np.nan

my_df

     A         B   C          D
0  NaN  0.142867  17  -5.251229
1  NaN       NaN  10  19.127713
2  8.0       NaN  16 -20.267196
3  5.0  0.721999  15  11.194236
4  7.0  0.938553  15   7.791926
5  3.0  0.000779  19 -11.010978
6  7.0  0.992212  12  11.302282
7  NaN       NaN   3   3.731189
8  5.0       NaN   5  -3.864730
9  4.0  0.007066  19 -11.587702

In [ ]:
my_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       7 non-null      float64
 1   B       6 non-null      float64
 2   C       10 non-null     int64
 3   D       10 non-null     float64
dtypes: float64(3), int64(1)
memory usage: 452.0 bytes

In [ ]:
#Calculate the mode of Column A
my_df_clean_1 = my_df.copy()
mode_A = my_df_clean_1['A'].mode(dropna = True)[0]
#mode_A = my_df_clean_1['A'].dropna().mode()[0]  #Alternate way to calc mode
mode_A

np.float64(5.0)

In [ ]:
my_df_clean_1['A'].mode(dropna = True)

0    5.0
1    7.0
Name: A, dtype: float64

In [ ]:
#Fill in A using the mode of Column A
my_df_clean_1.fillna({'A' : mode_A }, inplace = True)
my_df_clean_1

     A         B   C          D
0  5.0  0.142867  17  -5.251229
1  5.0       NaN  10  19.127713
2  8.0       NaN  16 -20.267196
3  5.0  0.721999  15  11.194236
4  7.0  0.938553  15   7.791926
5  3.0  0.000779  19 -11.010978
6  7.0  0.992212  12  11.302282
7  5.0       NaN   3   3.731189
8  5.0       NaN   5  -3.864730
9  4.0  0.007066  19 -11.587702

In [ ]:
#Fill in B using 0
my_df_clean_1.fillna({'B': 0}, inplace = True)
my_df_clean_1

     A         B   C          D
0  5.0  0.142867  17  -5.251229
1  5.0  0.000000  10  19.127713
2  8.0  0.000000  16 -20.267196
3  5.0  0.721999  15  11.194236
4  7.0  0.938553  15   7.791926
5  3.0  0.000779  19 -11.010978
6  7.0  0.992212  12  11.302282
7  5.0  0.000000   3   3.731189
8  5.0  0.000000   5  -3.864730
9  4.0  0.007066  19 -11.587702

In [ ]:
my_df

     A         B   C          D
0  NaN  0.142867  17  -5.251229
1  NaN       NaN  10  19.127713
2  8.0       NaN  16 -20.267196
3  5.0  0.721999  15  11.194236
4  7.0  0.938553  15   7.791926
5  3.0  0.000779  19 -11.010978
6  7.0  0.992212  12  11.302282
7  NaN       NaN   3   3.731189
8  5.0       NaN   5  -3.864730
9  4.0  0.007066  19 -11.587702

In [ ]:
pd.concat([ my_df, my_df_clean_1 ], axis=1)

     A         B   C          D    A         B   C          D
0  NaN  0.142867  17  -5.251229  5.0  0.142867  17  -5.251229
1  NaN       NaN  10  19.127713  5.0  0.000000  10  19.127713
2  8.0       NaN  16 -20.267196  8.0  0.000000  16 -20.267196
3  5.0  0.721999  15  11.194236  5.0  0.721999  15  11.194236
4  7.0  0.938553  15   7.791926  7.0  0.938553  15   7.791926
5  3.0  0.000779  19 -11.010978  3.0  0.000779  19 -11.010978
6  7.0  0.992212  12  11.302282  7.0  0.992212  12  11.302282
7  NaN       NaN   3   3.731189  5.0  0.000000   3   3.731189
8  5.0       NaN   5  -3.864730  5.0  0.000000   5  -3.864730
9  4.0  0.007066  19 -11.587702  4.0  0.007066  19 -11.587702

In [ ]:
#Simple Imputer
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values = np.nan, strategy = 'mean')
my_df_simple_impute = imp.fit_transform(my_df)
#pd.concat([my_df,pd.DataFrame(my_df_simple_impute)], axis = 1)
pd.DataFrame(my_df_simple_impute, columns = my_df.columns)

          A         B     C          D
0  5.571429  0.142867  17.0  -5.251229
1  5.571429  0.467246  10.0  19.127713
2  8.000000  0.467246  16.0 -20.267196
3  5.000000  0.721999  15.0  11.194236
4  7.000000  0.938553  15.0   7.791926
5  3.000000  0.000779  19.0 -11.010978
6  7.000000  0.992212  12.0  11.302282
7  5.571429  0.467246   3.0   3.731189
8  5.000000  0.467246   5.0  -3.864730
9  4.000000  0.007066  19.0 -11.587702

In [ ]:
#Iterative Imputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

imp = IterativeImputer(max_iter=10, random_state = 4)
my_df_iter_impute = imp.fit_transform(my_df)
pd.DataFrame(my_df_iter_impute, columns = my_df.columns)

          A         B     C          D
0  5.569097  0.142867  17.0  -5.251229
1  5.583886  1.215860  10.0  19.127713
2  8.000000 -0.171245  16.0 -20.267196
3  5.000000  0.721999  15.0  11.194236
4  7.000000  0.938553  15.0   7.791926
5  3.000000  0.000779  19.0 -11.010978
6  7.000000  0.992212  12.0  11.302282
7  5.578266  0.802860   3.0   3.731189
8  5.000000  0.496488   5.0  -3.864730
9  4.000000  0.007066  19.0 -11.587702

In [ ]:
my_df_iter_impute[:,0].reshape(-1,1)

array([[5.56909701],
       [5.58388612],
       [8.        ],
       [5.        ],
       [7.        ],
       [3.        ],
       [7.        ],
       [5.57826587],
       [5.        ],
       [4.        ]])

In [ ]:
my_df

     A         B   C          D
0  NaN  0.142867  17  -5.251229
1  NaN       NaN  10  19.127713
2  8.0       NaN  16 -20.267196
3  5.0  0.721999  15  11.194236
4  7.0  0.938553  15   7.791926
5  3.0  0.000779  19 -11.010978
6  7.0  0.992212  12  11.302282
7  NaN       NaN   3   3.731189
8  5.0       NaN   5  -3.864730
9  4.0  0.007066  19 -11.587702

In [ ]:
m, s = (my_df["A"].mean(), my_df["A"].std())
m,s

(np.float64(5.571428571428571), 1.8126539343499315)

In [ ]:
np.random.normal(m, s, 3)

array([5.55641141, 4.99204752, 4.59870525])