# Project SQL: Data Discovery with the Chinook Database

Welcome to your first major hands-on data exploration project. In this assignment, you will be stepping into the role of a data analyst querying the Chinook database: a sample dataset representing a digital media store, complete with information about artists, albums, tracks, customers, and business sales.

The core objective of this project is to transition you from simply writing code to thinking like a data scientist. To do that, our journey follows a deliberate, four-fold progression:

## Phase 1. Master the Mechanics (Get Familiar with SQL)

### Chinook data set

See the lecture on SQLite3 using the Chinook data set to set up the software, database, and tables, as well as for the links to ancillary information about the data set.

Before you can extract deep insights, you need to speak the language. You will start by practicing the fundamental mechanics of SQL using the SQL statements below: learning how to filter data, join tables, group metrics, and aggregate numbers. Think of this as learning how to move around the data environment smoothly.  As a starting point, pick a single table and answer the "How many ...?" questions using SQL.  Then repeat the process for each table.

In [1]:
# Install the sqlite package for Ubuntu
# Download the Chinook sqlite database

In [2]:
#Imports sqlite3 and pandas
import sqlite3 as db
import pandas as pd

In [3]:
#Prevents the code from being printed to keep notebook clean.
#Runs the subsiding lines as terminal commands and not Python.
#Get the latest version.
#Install SQLite
%%capture
%%bash
apt-get update
apt-get install -y sqlite3

In [4]:
#Use as needed
!sqlite3 --help

Usage: sqlite3 [OPTIONS] FILENAME [SQL]
FILENAME is the name of an SQLite database. A new database is created
if the file does not previously exist.
OPTIONS include:
   -A ARGS...           run ".archive ARGS" and exit
   -append              append the database to the end of the file
   -ascii               set output mode to 'ascii'
   -bail                stop after hitting an error
   -batch               force batch I/O
   -box                 set output mode to 'box'
   -column              set output mode to 'column'
   -cmd COMMAND         run "COMMAND" before reading stdin
   -csv                 set output mode to 'csv'
   -deserialize         open the database using sqlite3_deserialize()
   -echo                print commands before execution
   -init FILENAME       read/process named file
   -[no]header          turn headers on or off
   -help                show this message
   -html                set output mode to HTML
   -interactive         force interactive I/O
   -json                set output mode to 'json'
   -line                set output mode to 'line'
   -list                set output mode to 'list'
   -lookaside SIZE N    use N entries of SZ bytes for lookaside memory
   -markdown            set output mode to 'markdown'
   -maxsize N           maximum size for a --deserialize database
   -memtrace            trace all memory allocations and deallocations
   -mmap N              default mmap size set to N
   -newline SEP         set output row separator. Default: '\n'
   -nofollow            refuse to open symbolic links to database files
   -nonce STRING        set the safe-mode escape nonce
   -nullvalue TEXT      set text string for NULL values. Default ''
   -pagecache SIZE N    use N slots of SZ bytes each for page cache memory
   -quote               set output mode to 'quote'
   -readonly            open the database read-only
   -safe                enable safe-mode
   -separator SEP       set output column separator. Default: '|'
   -stats               print memory stats before each finalize
   -table               set output mode to 'table'
   -tabs                set output mode to 'tabs'
   -version             show SQLite version
   -vfs NAME            use NAME as the default VFS
   -zip                 open the file as a ZIP Archive

In [5]:
#Verify version
!sqlite3 --version

3.37.2 2022-01-06 13:25:41 872ba256cbf61d9290b571c0e6d82a20c224ca3ad82971edc46b29818d5dalt1

In [6]:
%%bash
#Check if [] already exists. || is an OR operator.
[ -f chinook.zip ] ||
#Curl transfers data from a URL.
# -s Hides progress when downloading file.
# -O Saves file using original URL: chinook.zip.
  curl -s -O https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
#Command to extract files
# -l lists files to verify.
unzip -l chinook.zip

Archive:  chinook.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
   884736  2015-11-29 10:53   chinook.db
---------                     -------
   884736                     1 file

In [7]:
#Delete file to ensure you are starting from a clean slate
# !rm command to 'remove
# -f = 'force'
!rm -f chinook.db

In [8]:
# ! uses terminal and not Python
# -u = update
!unzip -u chinook.zip

Archive:  chinook.zip
  inflating: chinook.db

In [9]:
# ls = list
# -l =long format
!ls -la

total 1180
drwxr-xr-x 1 root root   4096 Jul  8 03:42 .
drwxr-xr-x 1 root root   4096 Jul  8 03:40 ..
-rw-r--r-- 1 root root 884736 Nov 29  2015 chinook.db
-rw-r--r-- 1 root root 305596 Jul  8 03:42 chinook.zip
drwxr-xr-x 4 root root   4096 Jun  4 13:32 .config
drwxr-xr-x 1 root root   4096 Jun  4 13:32 sample_data

In [10]:
#Connect to a sqlite database and load a result set into a data frame
db_con = db.connect("chinook.db")

In [11]:
#Explicitly close the connection
db_con.close()

### Use SQL queries to pull specific information

Do NOT pull all the data and then filter using DataFrame methods.  The initial purpose is to get familiar with SQL.

### Basic Queries

#### SELECT (with * and with column names)

In [12]:
query = '''
  SELECT *
  FROM employees
'''

with db.connect("chinook.db") as db_con:
  df = pd.read_sql_query( query , db_con )
df

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,1,Adams,Andrew,General Manager,NaN,1962-02-18 00:00:00,2002-08-14 00:00:00,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,1958-12-08 00:00:00,2002-05-01 00:00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29 00:00:00,2002-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03 00:00:00,2003-10-17 00:00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com
5,6,Mitchell,Michael,IT Manager,1.0,1973-07-01 00:00:00,2003-10-17 00:00:00,5827 Bowness Road NW,Calgary,AB,Canada,T3B 0C5,+1 (403) 246-9887,+1 (403) 246-9899,michael@chinookcorp.com
6,7,King,Robert,IT Staff,6.0,1970-05-29 00:00:00,2004-01-02 00:00:00,590 Columbia Boulevard West,Lethbridge,AB,Canada,T1K 5N8,+1 (403) 456-9986,+1 (403) 456-8485,robert@chinookcorp.com
7,8,Callahan,Laura,IT Staff,6.0,1968-01-09 00:00:00,2004-03-04 00:00:00,923 7 ST NW,Lethbridge,AB,Canada,T1H 1Y8,+1 (403) 467-3351,+1 (403) 467-8772,laura@chinookcorp.com

#### WHERE

In [13]:
query = '''
  SELECT *
  FROM employees
  WHERE employeeid = 3
'''

with db.connect("chinook.db") as db_con:
  df = pd.read_sql_query( query , db_con )
df

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,3,Peacock,Jane,Sales Support Agent,2,1973-08-29 00:00:00,2002-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com

#### AND

In [14]:
query = '''
  SELECT *
  FROM employees
  WHERE employeeid > 3
    AND State = 'AB'
'''

with db.connect("chinook.db") as db_con:
  df = pd.read_sql_query( query , db_con )
df

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,4,Park,Margaret,Sales Support Agent,2,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
1,5,Johnson,Steve,Sales Support Agent,2,1965-03-03 00:00:00,2003-10-17 00:00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com
2,6,Mitchell,Michael,IT Manager,1,1973-07-01 00:00:00,2003-10-17 00:00:00,5827 Bowness Road NW,Calgary,AB,Canada,T3B 0C5,+1 (403) 246-9887,+1 (403) 246-9899,michael@chinookcorp.com
3,7,King,Robert,IT Staff,6,1970-05-29 00:00:00,2004-01-02 00:00:00,590 Columbia Boulevard West,Lethbridge,AB,Canada,T1K 5N8,+1 (403) 456-9986,+1 (403) 456-8485,robert@chinookcorp.com
4,8,Callahan,Laura,IT Staff,6,1968-01-09 00:00:00,2004-03-04 00:00:00,923 7 ST NW,Lethbridge,AB,Canada,T1H 1Y8,+1 (403) 467-3351,+1 (403) 467-8772,laura@chinookcorp.com

#### OR

In [15]:
query = '''
  SELECT *
  FROM employees
  WHERE City = 'Calgary'
    OR City = 'Lethbridge'
'''

with db.connect("chinook.db") as db_con:
  df = pd.read_sql_query( query , db_con )
df

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,2,Edwards,Nancy,Sales Manager,1,1958-12-08 00:00:00,2002-05-01 00:00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
1,3,Peacock,Jane,Sales Support Agent,2,1973-08-29 00:00:00,2002-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
2,4,Park,Margaret,Sales Support Agent,2,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
3,5,Johnson,Steve,Sales Support Agent,2,1965-03-03 00:00:00,2003-10-17 00:00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com
4,6,Mitchell,Michael,IT Manager,1,1973-07-01 00:00:00,2003-10-17 00:00:00,5827 Bowness Road NW,Calgary,AB,Canada,T3B 0C5,+1 (403) 246-9887,+1 (403) 246-9899,michael@chinookcorp.com
5,7,King,Robert,IT Staff,6,1970-05-29 00:00:00,2004-01-02 00:00:00,590 Columbia Boulevard West,Lethbridge,AB,Canada,T1K 5N8,+1 (403) 456-9986,+1 (403) 456-8485,robert@chinookcorp.com
6,8,Callahan,Laura,IT Staff,6,1968-01-09 00:00:00,2004-03-04 00:00:00,923 7 ST NW,Lethbridge,AB,Canada,T1H 1Y8,+1 (403) 467-3351,+1 (403) 467-8772,laura@chinookcorp.com

#### LIKE (with % or _ wildcard)

In [16]:
query = '''
  SELECT *
  FROM employees
  WHERE FirstName LIKE 'M%'
'''

with db.connect("chinook.db") as db_con:
  df = pd.read_sql_query( query , db_con )
df

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,4,Park,Margaret,Sales Support Agent,2,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
1,6,Mitchell,Michael,IT Manager,1,1973-07-01 00:00:00,2003-10-17 00:00:00,5827 Bowness Road NW,Calgary,AB,Canada,T3B 0C5,+1 (403) 246-9887,+1 (403) 246-9899,michael@chinookcorp.com

#### BETWEEN

In [17]:
query = '''
  SELECT *
  FROM employees
  WHERE EmployeeId BETWEEN 4 AND 7
'''

with db.connect("chinook.db") as db_con:
  df = pd.read_sql_query( query , db_con )
df

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,4,Park,Margaret,Sales Support Agent,2,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
1,5,Johnson,Steve,Sales Support Agent,2,1965-03-03 00:00:00,2003-10-17 00:00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com
2,6,Mitchell,Michael,IT Manager,1,1973-07-01 00:00:00,2003-10-17 00:00:00,5827 Bowness Road NW,Calgary,AB,Canada,T3B 0C5,+1 (403) 246-9887,+1 (403) 246-9899,michael@chinookcorp.com
3,7,King,Robert,IT Staff,6,1970-05-29 00:00:00,2004-01-02 00:00:00,590 Columbia Boulevard West,Lethbridge,AB,Canada,T1K 5N8,+1 (403) 456-9986,+1 (403) 456-8485,robert@chinookcorp.com

#### LIMIT

In [18]:
query = '''
  SELECT *
  FROM employees
  WHERE City LIKE 'C%'
  LIMIT 3
'''

with db.connect("chinook.db") as db_con:
  df = pd.read_sql_query( query , db_con )
df

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,2,Edwards,Nancy,Sales Manager,1,1958-12-08 00:00:00,2002-05-01 00:00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
1,3,Peacock,Jane,Sales Support Agent,2,1973-08-29 00:00:00,2002-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
2,4,Park,Margaret,Sales Support Agent,2,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com

In [19]:
query = '''
  SELECT *
  FROM playlists AS p1
  INNER JOIN playlist_track AS p2
  ON p1.PlaylistId = p2.PlaylistId
  WHERE Name = 'Music'
    AND p1.PlaylistId = 1
'''

with db.connect("chinook.db") as db_con:
  df = pd.read_sql_query( query , db_con )
df

      PlaylistId   Name  PlaylistId  TrackId
0              1  Music           1        1
1              1  Music           1        2
2              1  Music           1        3
3              1  Music           1        4
4              1  Music           1        5
...          ...    ...         ...      ...
3285           1  Music           1     3499
3286           1  Music           1     3500
3287           1  Music           1     3501
3288           1  Music           1     3502
3289           1  Music           1     3503

[3290 rows x 4 columns]

### Sorting and Grouping

#### ORDER BY

In [20]:
query = '''
  SELECT *
  FROM employees
  ORDER By FirstName DESC
'''

with db.connect("chinook.db") as db_con:
  df = pd.read_sql_query( query , db_con )
df

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03 00:00:00,2003-10-17 00:00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com
1,7,King,Robert,IT Staff,6.0,1970-05-29 00:00:00,2004-01-02 00:00:00,590 Columbia Boulevard West,Lethbridge,AB,Canada,T1K 5N8,+1 (403) 456-9986,+1 (403) 456-8485,robert@chinookcorp.com
2,2,Edwards,Nancy,Sales Manager,1.0,1958-12-08 00:00:00,2002-05-01 00:00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
3,6,Mitchell,Michael,IT Manager,1.0,1973-07-01 00:00:00,2003-10-17 00:00:00,5827 Bowness Road NW,Calgary,AB,Canada,T3B 0C5,+1 (403) 246-9887,+1 (403) 246-9899,michael@chinookcorp.com
4,4,Park,Margaret,Sales Support Agent,2.0,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
5,8,Callahan,Laura,IT Staff,6.0,1968-01-09 00:00:00,2004-03-04 00:00:00,923 7 ST NW,Lethbridge,AB,Canada,T1H 1Y8,+1 (403) 467-3351,+1 (403) 467-8772,laura@chinookcorp.com
6,3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29 00:00:00,2002-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
7,1,Adams,Andrew,General Manager,NaN,1962-02-18 00:00:00,2002-08-14 00:00:00,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com

#### DISTINCT

In [35]:
query = '''
  SELECT DISTINCT Title
  FROM employees
'''

with db.connect("chinook.db") as db_con:
  df = pd.read_sql_query( query , db_con )
df

                 Title
0      General Manager
1        Sales Manager
2  Sales Support Agent
3           IT Manager
4             IT Staff

#### GROUP BY

In [42]:
query = '''
  SELECT Country, COUNT(*)
  FROM employees
  GROUP BY Country
'''

with db.connect("chinook.db") as db_con:
  df = pd.read_sql_query( query , db_con )
df

  Country  COUNT(*)
0  Canada         8

### Aggregates

#### MAX

In [43]:
query = '''
  SELECT MAX(Total)
  FROM invoices
'''

with db.connect("chinook.db") as db_con:
  df = pd.read_sql_query( query , db_con )
df

   MAX(Total)
0       25.86

#### MIN

In [45]:
query = '''
  SELECT MIN(Total)
  FROM invoices
'''

with db.connect("chinook.db") as db_con:
  df = pd.read_sql_query( query , db_con )
df

   MIN(Total)
0        0.99

#### SUM

In [46]:
query = '''
  SELECT SUM(Total)
  FROM invoices
'''

with db.connect("chinook.db") as db_con:
  df = pd.read_sql_query( query , db_con )
df

   SUM(Total)
0      2328.6

#### AVG

In [47]:
query = '''
  SELECT AVG(Total)
  FROM invoices
'''

with db.connect("chinook.db") as db_con:
  df = pd.read_sql_query( query , db_con )
df

   AVG(Total)
0    5.651942

#### COUNT

In [48]:
query = '''
  SELECT COUNT(EmployeeId)
  FROM employees
'''

with db.connect("chinook.db") as db_con:
  df = pd.read_sql_query( query , db_con )
df

   COUNT(EmployeeId)
0                  8

## Phase 2. Map the Terrain (Get Familiar with the Data)

Data never exists in a vacuum. By writing queries, you will uncover the shape, structure, and quirks of the Chinook dataset. Again, using the SQL statements below, you'll learn how the tables relate to one another, what a single row represents in different contexts, and where specific types of information live.  Here's where you should get familiar with the ERD and join tables in various ways.

In [ ]:
with db.connect('chinook.db') as db_con:

  query = '''
    SELECT name
    FROM sqlite_master
    WHERE type = 'table';
  '''

  tables = pd.read_sql_query(query, db_con)

  for table in tables ['name']:

    query = f'''
      SELECT COUNT(1)
      FROM "{table}";
    '''
    row_count = pd.read_sql_query(query, db_con).iloc[0,0]

    query = f'''
      PRAGMA table_info("{table}");
    '''
    columns = pd.read_sql_query(query, db_con)

    print('=' * 60)
    print(f'Table: {table}')
    print('=' * 60)
    print(f'Rows: {row_count}')
    print(f'Columns: {len(columns)}')
    print()

    summary = []

    for _, col in columns.iterrows():

      column = col['name']
      dtype = col['type']

      identifier = 'YES' if col['pk'] == 1 else 'NO'

      query = f'''
        SELECT COUNT(1)
        FROM "{table}"
        WHERE "{column}" IS NULL;
      '''
      nulls = pd.read_sql_query(query, db_con).iloc[0,0]

      query = f'''
        SELECT COUNT(DISTINCT "{column}")
        FROM "{table}";
      '''
      distinct = pd.read_sql_query(query, db_con).iloc[0,0]

      summary.append({
        'Column': column,
        'Type': dtype,
        'Identifier': identifier,
        'Nulls': nulls,
        'Distinct': distinct
      })

    summary_df = pd.DataFrame(summary)

    print(summary_df.to_string(index=False))
    print('\n')

In [50]:
#Opens SQLite database so Python can send the SQL queries to it and close the connection when finished.
with db.connect('chinook.db') as db_con:

  #Tables
  # sqlite_master is built into every SQLite db. (Table of Contents)
  # SELECTs the name of the column
  # FROM the catalog
  # WHERE only returns the tables (not indexes or views)?
  query = '''
    SELECT name
    FROM sqlite_master
    WHERE type = 'table';
  '''

  tables = pd.read_sql_query(query, db_con)

  #Loop through each table
  for table in tables ['name']:

    #Rows
    # .iloc[0,0] is to extract the actual value instead of returning the DataFrame.
    #Use "" around {}
    query = f'''
      SELECT COUNT(1)
      FROM "{table}";
    '''
    row_count = pd.read_sql_query(query, db_con).iloc[0,0]

    #Columns
    #PRAGMA table_info() is a SQLite command that tells you everything about the columns.
    #Use "" around {}
    query = f'''
      PRAGMA table_info("{table}");
    '''
    columns = pd.read_sql_query(query, db_con)

    print('=' * 60) #Prints top border
    print(f'Table: {table}') #Prints table name
    print('=' * 60) #Prints bottom border
    print(f'Rows: {row_count}') #Labels row count
    print(f'Columns: {len(columns)}') #Labels column count
    print()

    #This will store a dict for every column.
    #The list will turn into a DataFrame at the end.
    summary = []

    #Loop through every column
    #Each row has 2 pieces of info (index, row). _ removes the index.
    for _, col in columns.iterrows():

      #Pulls the name of the column
      column = col['name']
      #Pulls the dtype (referred to as type) ex INTEGER
      dtype = col['type']

      #Identifiers
      #If pk = 1 it is a primary key (pk comes from SQLite/DO NOT change)
      identifier = 'YES' if col['pk'] == 1 else 'NO'

      #NULLs
      #Use "" around {}
      query = f'''
        SELECT COUNT(1)
        FROM "{table}"
        WHERE "{column}" IS NULL;
      '''
      nulls = pd.read_sql_query(query, db_con).iloc[0,0]

      #Distinct values
      #Produces a value to show how many unique values are in the column.
      #Could be an indicator of a categorical
      #Use "" around {}
      query = f'''
        SELECT COUNT(DISTINCT "{column}")
        FROM "{table}";
      '''
      distinct = pd.read_sql_query(query, db_con).iloc[0,0]

      #Creates a dictionary to store everything.
      summary.append({
        'Column': column,
        'Type': dtype,
        'Identifier': identifier,
        'Nulls': nulls,
        'Distinct': distinct
      })

    #Turns the summary list from above into a DataFrame
    summary_df = pd.DataFrame(summary)

    #Using to_string(index=False) prints each table immediate
    print(summary_df.to_string(index=False)) #index=False removes the added row numbers from Pandas
    print('\n') #Enters the line for space

============================================================
Table: albums
============================================================
Rows: 347
Columns: 3

  Column          Type Identifier  Nulls  Distinct
 AlbumId       INTEGER        YES      0       347
   Title NVARCHAR(160)         NO      0       347
ArtistId       INTEGER         NO      0       204


============================================================
Table: sqlite_sequence
============================================================
Rows: 10
Columns: 2

Column Type Identifier  Nulls  Distinct
  name              NO      0        10
   seq              NO      0        10


============================================================
Table: artists
============================================================
Rows: 275
Columns: 2

  Column          Type Identifier  Nulls  Distinct
ArtistId       INTEGER        YES      0       275
    Name NVARCHAR(120)         NO      0       275


============================================================
Table: customers
============================================================
Rows: 59
Columns: 13

      Column         Type Identifier  Nulls  Distinct
  CustomerId      INTEGER        YES      0        59
   FirstName NVARCHAR(40)         NO      0        57
    LastName NVARCHAR(20)         NO      0        59
     Company NVARCHAR(80)         NO     49        10
     Address NVARCHAR(70)         NO      0        59
        City NVARCHAR(40)         NO      0        53
       State NVARCHAR(40)         NO     29        25
     Country NVARCHAR(40)         NO      0        24
  PostalCode NVARCHAR(10)         NO      4        55
       Phone NVARCHAR(24)         NO      1        58
         Fax NVARCHAR(24)         NO     47        12
       Email NVARCHAR(60)         NO      0        59
SupportRepId      INTEGER         NO      0         3


============================================================
Table: employees
============================================================
Rows: 8
Columns: 15

    Column         Type Identifier  Nulls  Distinct
EmployeeId      INTEGER        YES      0         8
  LastName NVARCHAR(20)         NO      0         8
 FirstName NVARCHAR(20)         NO      0         8
     Title NVARCHAR(30)         NO      0         5
 ReportsTo      INTEGER         NO      1         3
 BirthDate     DATETIME         NO      0         8
  HireDate     DATETIME         NO      0         7
   Address NVARCHAR(70)         NO      0         8
      City NVARCHAR(40)         NO      0         3
     State NVARCHAR(40)         NO      0         1
   Country NVARCHAR(40)         NO      0         1
PostalCode NVARCHAR(10)         NO      0         8
     Phone NVARCHAR(24)         NO      0         7
       Fax NVARCHAR(24)         NO      0         8
     Email NVARCHAR(60)         NO      0         8


============================================================
Table: genres
============================================================
Rows: 25
Columns: 2

 Column          Type Identifier  Nulls  Distinct
GenreId       INTEGER        YES      0        25
   Name NVARCHAR(120)         NO      0        25


============================================================
Table: invoices
============================================================
Rows: 412
Columns: 9

           Column          Type Identifier  Nulls  Distinct
        InvoiceId       INTEGER        YES      0       412
       CustomerId       INTEGER         NO      0        59
      InvoiceDate      DATETIME         NO      0       354
   BillingAddress  NVARCHAR(70)         NO      0        59
      BillingCity  NVARCHAR(40)         NO      0        53
     BillingState  NVARCHAR(40)         NO    202        25
   BillingCountry  NVARCHAR(40)         NO      0        24
BillingPostalCode  NVARCHAR(10)         NO     28        55
            Total NUMERIC(10,2)         NO      0        23


============================================================
Table: invoice_items
============================================================
Rows: 2240
Columns: 5

       Column          Type Identifier  Nulls  Distinct
InvoiceLineId       INTEGER        YES      0      2240
    InvoiceId       INTEGER         NO      0       412
      TrackId       INTEGER         NO      0      1984
    UnitPrice NUMERIC(10,2)         NO      0         2
     Quantity       INTEGER         NO      0         1


============================================================
Table: media_types
============================================================
Rows: 5
Columns: 2

     Column          Type Identifier  Nulls  Distinct
MediaTypeId       INTEGER        YES      0         5
       Name NVARCHAR(120)         NO      0         5


============================================================
Table: playlists
============================================================
Rows: 18
Columns: 2

    Column          Type Identifier  Nulls  Distinct
PlaylistId       INTEGER        YES      0        18
      Name NVARCHAR(120)         NO      0        14


============================================================
Table: playlist_track
============================================================
Rows: 8715
Columns: 2

    Column    Type Identifier  Nulls  Distinct
PlaylistId INTEGER        YES      0        14
   TrackId INTEGER         NO      0      3503


============================================================
Table: tracks
============================================================
Rows: 3503
Columns: 9

      Column          Type Identifier  Nulls  Distinct
     TrackId       INTEGER        YES      0      3503
        Name NVARCHAR(200)         NO      0      3257
     AlbumId       INTEGER         NO      0       347
 MediaTypeId       INTEGER         NO      0         5
     GenreId       INTEGER         NO      0        25
    Composer NVARCHAR(220)         NO    978       852
Milliseconds       INTEGER         NO      0      3080
       Bytes       INTEGER         NO      0      3501
   UnitPrice NUMERIC(10,2)         NO      0         2


============================================================
Table: sqlite_stat1
============================================================
Rows: 15
Columns: 3

Column Type Identifier  Nulls  Distinct
   tbl              NO      0        11
   idx              NO      4        11
  stat              NO      0        15

## Phase 3. Answer Guided Questions

Once you know the syntax and understand the data structure, you will put your skills to work solving specific business problems. Below are sets of explicit questions to answer using SQL. This phase mimics standard reporting: you are handed a specific prompt, and your job is to translate that prompt into an accurate, data-driven answer.

Here are some practice questions:
- https://github.com/LucasMcL/15-sql_queries_02-chinook/blob/master/README.md
- [Using the R language]( https://rpubs.com/enext777/636199 )
- [Search Google]( https://www.google.com/search?q=chinook+database+questions )
- Ask AI to generate some questions for you.  Be sure to mention the Chinook data set.

## Phase 4. Ask and Answer Your Own Questions

This final phase is the most critical part of the project. The true hallmark of a great data scientist isn't just answering the questions you're handed; it's having the curiosity and intuition to formulate your own questions.

You are tasked with looking at the Chinook dataset, generating your own original hypotheses or business questions, and writing the SQL required to answer them.

Demonstrate that you know SQL fundamentals by posting a question for each SQL statement below and then using the SQL statement to answer you question.

You will use the material from this phase for the presentation.

## Why This Matters: The Path to Your Capstone

Learning to ask your own questions is the exact skill you will rely on for your final capstone project. In your capstone, you will choose a dataset from your own field of interest. No one will hand you a list of prompts or a guide telling you what to look for.

Use this project as your sandbox. Mastering the ability to interrogate a database now will give you the framework you need to discover meaningful, independent insights in your capstone later.

## Make some plots

Make some cool plots to go with your data. Write SQL queries to get ONLY the information you need for each plot. (Don't pull ALL the data and then just plot a few columns.)

## EXTRA CREDIT:
* Use a CTE
* Use a query that joins two or more tables.
* Make a model to see if you can predict something ( e.g. GNB classifier, linear regression )
* Come up with something else cool to do with your data