<a href="https://colab.research.google.com/github/stephanie465337/Data-Science-Portfolio-C21/blob/main/NotebookLM/Module%203/1e_Metadata_DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exploring the Metadata of Data Frames

## What is metadata?

It is data about data.  Or as [Wikipedia says]( https://en.wikipedia.org/wiki/Metadata ):

> "data that provides information about other data", but not the content of the data itself, such as the text of a message or the image itself.

For example, given a file, the data are the contents of the file.  The metadata is the data about the file: the size, date, ownership, group membership, permissions, the file type, etc.

A sound track will contain audio, but the metadata would include the length of the recording, the recording date, the author's name, any copyright info, the performers names, etc.

An digital photo will contain the image with the metadata containing the date, time, exposure settings, GPS info, camera make/model, etc.  Usually this information is stored in the [EXIF portion]( https://en.wikipedia.org/wiki/Exif ) of the digital image.



For a data frame, the metadata is the number of rows and columns, the column names, the column data types, the row indices, the value counts of categorical data, the min/median/mean/max of continuous data, etc.

For a web resource ( e.g. file ), the metadata is what is in the headers of the response to an HTTP request, e.g. the server type, the last update date, the content-length, the content-type, etc.

Metadata is useful for understanding the data itself.  For ML algorithms it is important to understand the metadata to determine what types of ML algorithms are appropriate for the data and if any transformations need to happen if the data is not appropriate.

## Exploring dataframes

In [ ]:
%%capture
%%bash
apt-get update
apt-get install -y tree

In [ ]:
import pandas as pd

In [ ]:
url = "https://ddc-datascience.s3.amazonaws.com/Projects/Project.2-Housing/Data/Housing.Data.csv"
housing = pd.read_csv( url )

Getting the shape ( rows, columns ) of a Data Frame

In [ ]:
housing.shape

(2637, 81)

In [ ]:
type(housing.shape)

tuple

In [ ]:
rows, columns = housing.shape
{
  "Rows": rows,
  "Columns" : columns
}

{'Rows': 2637, 'Columns': 81}

### Data types and nulls

#### Data from `.info()` ... or not

In [ ]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2637 entries, 0 to 2636
Data columns (total 81 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PID              2637 non-null   int64
 1   MS SubClass      2637 non-null   int64
 2   MS Zoning        2637 non-null   object
 3   Lot Frontage     2188 non-null   float64
 4   Lot Area         2637 non-null   int64
 5   Street           2637 non-null   object
 6   Alley            180 non-null    object
 7   Lot Shape        2637 non-null   object
 8   Land Contour     2637 non-null   object
 9   Utilities        2637 non-null   object
 10  Lot Config       2637 non-null   object
 11  Land Slope       2637 non-null   object
 12  Neighborhood     2637 non-null   object
 13  Condition 1      2637 non-null   object
 14  Condition 2      2637 non-null   object
 15  Bldg Type        2637 non-null   object
 16  House Style      2637 non-null   object
 17  Overall Qual     2637 non-null   int64
 18  Overall Cond     2637 non-null   int64
 19  Year Built       2637 non-null   int64
 20  Year Remod/Add   2637 non-null   int64
 21  Roof Style       2637 non-null   object
 22  Roof Matl        2637 non-null   object
 23  Exterior 1st     2637 non-null   object
 24  Exterior 2nd     2637 non-null   object
 25  Mas Vnr Type     1030 non-null   object
 26  Mas Vnr Area     2614 non-null   float64
 27  Exter Qual       2637 non-null   object
 28  Exter Cond       2637 non-null   object
 29  Foundation       2637 non-null   object
 30  Bsmt Qual        2564 non-null   object
 31  Bsmt Cond        2564 non-null   object
 32  Bsmt Exposure    2561 non-null   object
 33  BsmtFin Type 1   2564 non-null   object
 34  BsmtFin SF 1     2636 non-null   float64
 35  BsmtFin Type 2   2563 non-null   object
 36  BsmtFin SF 2     2636 non-null   float64
 37  Bsmt Unf SF      2636 non-null   float64
 38  Total Bsmt SF    2636 non-null   float64
 39  Heating          2637 non-null   object
 40  Heating QC       2637 non-null   object
 41  Central Air      2637 non-null   object
 42  Electrical       2637 non-null   object
 43  1st Flr SF       2637 non-null   int64
 44  2nd Flr SF       2637 non-null   int64
 45  Low Qual Fin SF  2637 non-null   int64
 46  Gr Liv Area      2637 non-null   int64
 47  Bsmt Full Bath   2635 non-null   float64
 48  Bsmt Half Bath   2635 non-null   float64
 49  Full Bath        2637 non-null   int64
 50  Half Bath        2637 non-null   int64
 51  Bedroom AbvGr    2637 non-null   int64
 52  Kitchen AbvGr    2637 non-null   int64
 53  Kitchen Qual     2637 non-null   object
 54  TotRms AbvGrd    2637 non-null   int64
 55  Functional       2637 non-null   object
 56  Fireplaces       2637 non-null   int64
 57  Fireplace Qu     1353 non-null   object
 58  Garage Type      2492 non-null   object
 59  Garage Yr Blt    2490 non-null   float64
 60  Garage Finish    2490 non-null   object
 61  Garage Cars      2636 non-null   float64
 62  Garage Area      2636 non-null   float64
 63  Garage Qual      2490 non-null   object
 64  Garage Cond      2490 non-null   object
 65  Paved Drive      2637 non-null   object
 66  Wood Deck SF     2637 non-null   int64
 67  Open Porch SF    2637 non-null   int64
 68  Enclosed Porch   2637 non-null   int64
 69  3Ssn Porch       2637 non-null   int64
 70  Screen Porch     2637 non-null   int64
 71  Pool Area        2637 non-null   int64
 72  Pool QC          11 non-null     object
 73  Fence            528 non-null    object
 74  Misc Feature     96 non-null     object
 75  Misc Val         2637 non-null   int64
 76  Mo Sold          2637 non-null   int64
 77  Yr Sold          2637 non-null   int64
 78  Sale Type        2637 non-null   object
 79  Sale Condition   2637 non-null   object
 80  SalePrice        2637 non-null   int64
dtypes: float64(11), int64(27), object(43)
memory usage: 1.6+ MB

Notice `.info()` provides five kinds of information:
- the number of rows and columns
- the number of rows of each column that are not-nulls
- the data type of the column
- summary counts of column data types
- the amount of memory used by the Data Frame

How can I extract that information to work with it?  For example, how can I use the data from `.info()` to list all columns that have nulls?

In [ ]:
type(housing.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2637 entries, 0 to 2636
Data columns (total 81 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PID              2637 non-null   int64
 1   MS SubClass      2637 non-null   int64
 2   MS Zoning        2637 non-null   object
 3   Lot Frontage     2188 non-null   float64
 4   Lot Area         2637 non-null   int64
 5   Street           2637 non-null   object
 6   Alley            180 non-null    object
 7   Lot Shape        2637 non-null   object
 8   Land Contour     2637 non-null   object
 9   Utilities        2637 non-null   object
 10  Lot Config       2637 non-null   object
 11  Land Slope       2637 non-null   object
 12  Neighborhood     2637 non-null   object
 13  Condition 1      2637 non-null   object
 14  Condition 2      2637 non-null   object
 15  Bldg Type        2637 non-null   object
 16  House Style      2637 non-null   object
 17  Overall Qual     2637 non-null   int64
 18  Overall Cond     2637 non-null   int64
 19  Year Built       2637 non-null   int64
 20  Year Remod/Add   2637 non-null   int64
 21  Roof Style       2637 non-null   object
 22  Roof Matl        2637 non-null   object
 23  Exterior 1st     2637 non-null   object
 24  Exterior 2nd     2637 non-null   object
 25  Mas Vnr Type     1030 non-null   object
 26  Mas Vnr Area     2614 non-null   float64
 27  Exter Qual       2637 non-null   object
 28  Exter Cond       2637 non-null   object
 29  Foundation       2637 non-null   object
 30  Bsmt Qual        2564 non-null   object
 31  Bsmt Cond        2564 non-null   object
 32  Bsmt Exposure    2561 non-null   object
 33  BsmtFin Type 1   2564 non-null   object
 34  BsmtFin SF 1     2636 non-null   float64
 35  BsmtFin Type 2   2563 non-null   object
 36  BsmtFin SF 2     2636 non-null   float64
 37  Bsmt Unf SF      2636 non-null   float64
 38  Total Bsmt SF    2636 non-null   float64
 39  Heating          2637 non-null   object
 40  Heating QC       2637 non-null   object
 41  Central Air      2637 non-null   object
 42  Electrical       2637 non-null   object
 43  1st Flr SF       2637 non-null   int64
 44  2nd Flr SF       2637 non-null   int64
 45  Low Qual Fin SF  2637 non-null   int64
 46  Gr Liv Area      2637 non-null   int64
 47  Bsmt Full Bath   2635 non-null   float64
 48  Bsmt Half Bath   2635 non-null   float64
 49  Full Bath        2637 non-null   int64
 50  Half Bath        2637 non-null   int64
 51  Bedroom AbvGr    2637 non-null   int64
 52  Kitchen AbvGr    2637 non-null   int64
 53  Kitchen Qual     2637 non-null   object
 54  TotRms AbvGrd    2637 non-null   int64
 55  Functional       2637 non-null   object
 56  Fireplaces       2637 non-null   int64
 57  Fireplace Qu     1353 non-null   object
 58  Garage Type      2492 non-null   object
 59  Garage Yr Blt    2490 non-null   float64
 60  Garage Finish    2490 non-null   object
 61  Garage Cars      2636 non-null   float64
 62  Garage Area      2636 non-null   float64
 63  Garage Qual      2490 non-null   object
 64  Garage Cond      2490 non-null   object
 65  Paved Drive      2637 non-null   object
 66  Wood Deck SF     2637 non-null   int64
 67  Open Porch SF    2637 non-null   int64
 68  Enclosed Porch   2637 non-null   int64
 69  3Ssn Porch       2637 non-null   int64
 70  Screen Porch     2637 non-null   int64
 71  Pool Area        2637 non-null   int64
 72  Pool QC          11 non-null     object
 73  Fence            528 non-null    object
 74  Misc Feature     96 non-null     object
 75  Misc Val         2637 non-null   int64
 76  Mo Sold          2637 non-null   int64
 77  Yr Sold          2637 non-null   int64
 78  Sale Type        2637 non-null   object
 79  Sale Condition   2637 non-null   object
 80  SalePrice        2637 non-null   int64
dtypes: float64(11), int64(27), object(43)
memory usage: 1.6+ MB

NoneType

In [ ]:
housing.info().transpose()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2637 entries, 0 to 2636
Data columns (total 81 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PID              2637 non-null   int64
 1   MS SubClass      2637 non-null   int64
 2   MS Zoning        2637 non-null   object
 3   Lot Frontage     2188 non-null   float64
 4   Lot Area         2637 non-null   int64
 5   Street           2637 non-null   object
 6   Alley            180 non-null    object
 7   Lot Shape        2637 non-null   object
 8   Land Contour     2637 non-null   object
 9   Utilities        2637 non-null   object
 10  Lot Config       2637 non-null   object
 11  Land Slope       2637 non-null   object
 12  Neighborhood     2637 non-null   object
 13  Condition 1      2637 non-null   object
 14  Condition 2      2637 non-null   object
 15  Bldg Type        2637 non-null   object
 16  House Style      2637 non-null   object
 17  Overall Qual     2637 non-null   int64
 18  Overall Cond     2637 non-null   int64
 19  Year Built       2637 non-null   int64
 20  Year Remod/Add   2637 non-null   int64
 21  Roof Style       2637 non-null   object
 22  Roof Matl        2637 non-null   object
 23  Exterior 1st     2637 non-null   object
 24  Exterior 2nd     2637 non-null   object
 25  Mas Vnr Type     1030 non-null   object
 26  Mas Vnr Area     2614 non-null   float64
 27  Exter Qual       2637 non-null   object
 28  Exter Cond       2637 non-null   object
 29  Foundation       2637 non-null   object
 30  Bsmt Qual        2564 non-null   object
 31  Bsmt Cond        2564 non-null   object
 32  Bsmt Exposure    2561 non-null   object
 33  BsmtFin Type 1   2564 non-null   object
 34  BsmtFin SF 1     2636 non-null   float64
 35  BsmtFin Type 2   2563 non-null   object
 36  BsmtFin SF 2     2636 non-null   float64
 37  Bsmt Unf SF      2636 non-null   float64
 38  Total Bsmt SF    2636 non-null   float64
 39  Heating          2637 non-null   object
 40  Heating QC       2637 non-null   object
 41  Central Air      2637 non-null   object
 42  Electrical       2637 non-null   object
 43  1st Flr SF       2637 non-null   int64
 44  2nd Flr SF       2637 non-null   int64
 45  Low Qual Fin SF  2637 non-null   int64
 46  Gr Liv Area      2637 non-null   int64
 47  Bsmt Full Bath   2635 non-null   float64
 48  Bsmt Half Bath   2635 non-null   float64
 49  Full Bath        2637 non-null   int64
 50  Half Bath        2637 non-null   int64
 51  Bedroom AbvGr    2637 non-null   int64
 52  Kitchen AbvGr    2637 non-null   int64
 53  Kitchen Qual     2637 non-null   object
 54  TotRms AbvGrd    2637 non-null   int64
 55  Functional       2637 non-null   object
 56  Fireplaces       2637 non-null   int64
 57  Fireplace Qu     1353 non-null   object
 58  Garage Type      2492 non-null   object
 59  Garage Yr Blt    2490 non-null   float64
 60  Garage Finish    2490 non-null   object
 61  Garage Cars      2636 non-null   float64
 62  Garage Area      2636 non-null   float64
 63  Garage Qual      2490 non-null   object
 64  Garage Cond      2490 non-null   object
 65  Paved Drive      2637 non-null   object
 66  Wood Deck SF     2637 non-null   int64
 67  Open Porch SF    2637 non-null   int64
 68  Enclosed Porch   2637 non-null   int64
 69  3Ssn Porch       2637 non-null   int64
 70  Screen Porch     2637 non-null   int64
 71  Pool Area        2637 non-null   int64
 72  Pool QC          11 non-null     object
 73  Fence            528 non-null    object
 74  Misc Feature     96 non-null     object
 75  Misc Val         2637 non-null   int64
 76  Mo Sold          2637 non-null   int64
 77  Yr Sold          2637 non-null   int64
 78  Sale Type        2637 non-null   object
 79  Sale Condition   2637 non-null   object
 80  SalePrice        2637 non-null   int64
dtypes: float64(11), int64(27), object(43)
memory usage: 1.6+ MB

AttributeError: 'NoneType' object has no attribute 'transpose'

It's a "none" data type.  Hmmm.  `.info()` does not return any data.  It only displays it on the screen.

That means that you cannot do anything ( easily ) with the information that it is giving to you.


Let's put this aside for the moment.

### Some basic statistics

In [ ]:
housing.describe()

,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
count,2.637000e+03,2637.000000,2188.000000,2637.000000,2637.000000,2637.000000,2637.000000,2637.000000,2614.000000,2636.000000,...,2637.000000,2637.000000,2637.000000,2637.000000,2637.000000,2637.000000,2637.000000,2637.000000,2637.000000,2637.000000
mean,7.141301e+08,57.349261,69.166819,10044.694729,6.097459,5.569966,1971.288586,1984.202882,101.887911,438.441199,...,94.305271,46.984452,22.813424,2.368601,15.775123,2.130072,42.014031,6.243838,2007.795601,179986.230186
std,1.887527e+08,42.499091,23.356779,6742.549521,1.411522,1.118262,30.306986,20.913077,179.578232,449.602326,...,126.927272,66.564333,61.177638,23.160600,55.783751,35.140140,393.158781,2.722093,1.306403,78309.251522
min,5.263011e+08,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000
25%,5.284770e+08,20.000000,58.000000,7436.000000,5.000000,5.000000,1954.000000,1965.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129500.000000
50%,5.354530e+08,50.000000,68.000000,9450.000000,6.000000,5.000000,1973.000000,1993.000000,0.000000,368.000000,...,0.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,160000.000000
75%,9.071870e+08,70.000000,80.000000,11526.000000,7.000000,6.000000,2001.000000,2004.000000,164.000000,732.000000,...,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,213000.000000
max,1.007100e+09,190.000000,313.000000,164660.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,1424.000000,742.000000,584.000000,407.000000,576.000000,800.000000,12500.000000,12.000000,2010.000000,745000.000000

In [ ]:
type(housing.describe())

pandas.core.frame.DataFrame

A data frame.  I can work with that using all the methods that a data frame has.

List the columns.

In [ ]:
housing.describe().columns

Index(['PID', 'MS SubClass', 'Lot Frontage', 'Lot Area', 'Overall Qual',
       'Overall Cond', 'Year Built', 'Year Remod/Add', 'Mas Vnr Area',
       'BsmtFin SF 1', 'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF',
       '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area',
       'Bsmt Full Bath', 'Bsmt Half Bath', 'Full Bath', 'Half Bath',
       'Bedroom AbvGr', 'Kitchen AbvGr', 'TotRms AbvGrd', 'Fireplaces',
       'Garage Yr Blt', 'Garage Cars', 'Garage Area', 'Wood Deck SF',
       'Open Porch SF', 'Enclosed Porch', '3Ssn Porch', 'Screen Porch',
       'Pool Area', 'Misc Val', 'Mo Sold', 'Yr Sold', 'SalePrice'],
      dtype='object')

Count the number of columns.

In [ ]:
housing.describe().columns.size

38

Discover more columns.

In [ ]:
housing.describe(include = "all").columns.size

81

Use method chaining to customize the output.

In [ ]:
(
  housing
  .describe( include = "all" )
  .transpose()
  .astype({"count": int})
)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
PID,2637,NaN,NaN,NaN,714130147.70383,188752674.750322,526301100.0,528477010.0,535453040.0,907187010.0,1007100110.0
MS SubClass,2637,NaN,NaN,NaN,57.349261,42.499091,20.0,20.0,50.0,70.0,190.0
MS Zoning,2637,7,RL,2043,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lot Frontage,2188,NaN,NaN,NaN,69.166819,23.356779,21.0,58.0,68.0,80.0,313.0
Lot Area,2637,NaN,NaN,NaN,10044.694729,6742.549521,1300.0,7436.0,9450.0,11526.0,164660.0
...,...,...,...,...,...,...,...,...,...,...,...
Mo Sold,2637,NaN,NaN,NaN,6.243838,2.722093,1.0,4.0,6.0,8.0,12.0
Yr Sold,2637,NaN,NaN,NaN,2007.795601,1.306403,2006.0,2007.0,2008.0,2009.0,2010.0
Sale Type,2637,10,WD,2286,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sale Condition,2637,6,Normal,2166,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SalePrice,2637,NaN,NaN,NaN,179986.230186,78309.251522,12789.0,129500.0,160000.0,213000.0,745000.0

Notice that the names of the columns from the original data frame are the named index for the rows.

### Nulls

In [ ]:
housing.isnull()

,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,False,False,False,False,False,False,True,False,False,False,...,False,True,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,True,False,False,False,...,False,True,True,False,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False,...,False,True,True,True,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,...,False,True,True,True,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,...,False,True,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2632,False,False,False,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
2633,False,False,False,False,False,False,True,False,False,False,...,False,True,True,True,False,False,False,False,False,False
2634,False,False,False,False,False,False,True,False,False,False,...,False,True,True,True,False,False,False,False,False,False
2635,False,False,False,False,False,False,True,False,False,False,...,False,True,False,True,False,False,False,False,False,False
2636,False,False,False,False,False,False,True,False,False,False,...,False,True,True,True,False,False,False,False,False,False

In [ ]:
type(housing.isnull())

pandas.core.frame.DataFrame

In [ ]:
housing.isnull().sum()

PID                 0
MS SubClass         0
MS Zoning           0
Lot Frontage      449
Lot Area            0
                 ...
Mo Sold             0
Yr Sold             0
Sale Type           0
Sale Condition      0
SalePrice           0
Length: 81, dtype: int64

In [ ]:
type(housing.isnull().sum())

pandas.core.series.Series

Again, notice that the names of the columns from the original data frame are the named index for the rows.

#### Calculate proportion of nulls

In [ ]:
nulls = housing.isnull().sum()
filter = nulls > 0
(nulls[filter].sort_values(ascending=False) / housing.shape[0] * 100).round(1)

Pool QC           99.6
Misc Feature      96.4
Alley             93.2
Fence             80.0
Mas Vnr Type      60.9
Fireplace Qu      48.7
Lot Frontage      17.0
Garage Cond        5.6
Garage Yr Blt      5.6
Garage Finish      5.6
Garage Qual        5.6
Garage Type        5.5
Bsmt Exposure      2.9
BsmtFin Type 2     2.8
Bsmt Qual          2.8
BsmtFin Type 1     2.8
Bsmt Cond          2.8
Mas Vnr Area       0.9
Bsmt Half Bath     0.1
Bsmt Full Bath     0.1
BsmtFin SF 1       0.0
Total Bsmt SF      0.0
Bsmt Unf SF        0.0
BsmtFin SF 2       0.0
Garage Area        0.0
Garage Cars        0.0
dtype: float64

Again, notice that the names of the columns from the original data frame are the named index for the rows.

### Data types

In [ ]:
housing.dtypes

PID                 int64
MS SubClass         int64
MS Zoning          object
Lot Frontage      float64
Lot Area            int64
                   ...
Mo Sold             int64
Yr Sold             int64
Sale Type          object
Sale Condition     object
SalePrice           int64
Length: 81, dtype: object

In [ ]:
type(housing.dtypes)

pandas.core.series.Series

Again, notice that the names of the columns from the original data frame are the named index for the rows.

### Memory usage

In [ ]:
housing.memory_usage(deep=False, index = False)

PID               21096
MS SubClass       21096
MS Zoning         21096
Lot Frontage      21096
Lot Area          21096
                  ...
Mo Sold           21096
Yr Sold           21096
Sale Type         21096
Sale Condition    21096
SalePrice         21096
Length: 81, dtype: int64

In [ ]:
housing.memory_usage(deep=False, index = False).sum()

np.int64(1708776)

In [ ]:
housing.memory_usage(deep=True, index = False).sum()

np.int64(6504555)

In [ ]:
type(housing.memory_usage(deep=True, index = False))

pandas.core.series.Series

Again, notice that the names of the columns from the original data frame are the named index for the rows.

## Automate: first pass

Each of the above processes created either data frames or data series where the named index for the rows was the names of the columns from the original data frame.  That means that all these data sets can be concatenated together into a single data frame.

In [ ]:
#Assign current data frame to a generic name
df = housing

#Build a data frame to contain the metadata, using the generic name
df_info = pd.concat([
  pd.DataFrame([ df.isna().sum().to_dict()], index = ["Nulls"]).transpose().astype({"Nulls":int}),
  pd.DataFrame([ df.dtypes.to_dict()], index = ["Data_Types"]).transpose().astype({"Data_Types":'category'}),
  pd.DataFrame([ df.memory_usage(deep=True, index = False).to_dict()], index = ["Memory"]).transpose(),
  df.describe(include = "all").transpose().astype({"count":int}).rename(columns = {"50%":"median"}),
], axis = "columns")
df_info

,Nulls,Data_Types,Memory,count,unique,top,freq,mean,std,min,25%,median,75%,max
PID,0,int64,21096,2637,NaN,NaN,NaN,714130147.70383,188752674.750322,526301100.0,528477010.0,535453040.0,907187010.0,1007100110.0
MS SubClass,0,int64,21096,2637,NaN,NaN,NaN,57.349261,42.499091,20.0,20.0,50.0,70.0,190.0
MS Zoning,0,object,134632,2637,7,RL,2043,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lot Frontage,449,float64,21096,2188,NaN,NaN,NaN,69.166819,23.356779,21.0,58.0,68.0,80.0,313.0
Lot Area,0,int64,21096,2637,NaN,NaN,NaN,10044.694729,6742.549521,1300.0,7436.0,9450.0,11526.0,164660.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Mo Sold,0,int64,21096,2637,NaN,NaN,NaN,6.243838,2.722093,1.0,4.0,6.0,8.0,12.0
Yr Sold,0,int64,21096,2637,NaN,NaN,NaN,2007.795601,1.306403,2006.0,2007.0,2008.0,2009.0,2010.0
Sale Type,0,object,137192,2637,10,WD,2286,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sale Condition,0,object,145441,2637,6,Normal,2166,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SalePrice,0,int64,21096,2637,NaN,NaN,NaN,179986.230186,78309.251522,12789.0,129500.0,160000.0,213000.0,745000.0

In [ ]:
df_info["IRQ"] = df_info["75%"] - df_info["25%"]
df_info["range"] = df_info["max"] - df_info["min"]
df_info["sum"] = df_info["mean"] * df_info["count"]
df_info.insert(1, "Nulls_pct" , round(df_info["Nulls"] / df_info.shape[0],2))
df_info

,Nulls,Nulls_pct,Data_Types,Memory,count,unique,top,freq,mean,std,min,25%,median,75%,max,IRQ,range,sum
PID,0,0.00,int64,21096,2637,NaN,NaN,NaN,714130147.70383,188752674.750322,526301100.0,528477010.0,535453040.0,907187010.0,1007100110.0,378710000.0,480799010.0,1883161199495.0
MS SubClass,0,0.00,int64,21096,2637,NaN,NaN,NaN,57.349261,42.499091,20.0,20.0,50.0,70.0,190.0,50.0,170.0,151230.0
MS Zoning,0,0.00,object,134632,2637,7,RL,2043,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lot Frontage,449,5.54,float64,21096,2188,NaN,NaN,NaN,69.166819,23.356779,21.0,58.0,68.0,80.0,313.0,22.0,292.0,151337.0
Lot Area,0,0.00,int64,21096,2637,NaN,NaN,NaN,10044.694729,6742.549521,1300.0,7436.0,9450.0,11526.0,164660.0,4090.0,163360.0,26487860.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Mo Sold,0,0.00,int64,21096,2637,NaN,NaN,NaN,6.243838,2.722093,1.0,4.0,6.0,8.0,12.0,4.0,11.0,16465.0
Yr Sold,0,0.00,int64,21096,2637,NaN,NaN,NaN,2007.795601,1.306403,2006.0,2007.0,2008.0,2009.0,2010.0,2.0,4.0,5294557.0
Sale Type,0,0.00,object,137192,2637,10,WD,2286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sale Condition,0,0.00,object,145441,2637,6,Normal,2166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SalePrice,0,0.00,int64,21096,2637,NaN,NaN,NaN,179986.230186,78309.251522,12789.0,129500.0,160000.0,213000.0,745000.0,83500.0,732211.0,474623689.0

In [ ]:
# Display some info from the meta data
print(f"Memory: { (df_info['Memory'].sum() / 1000 / 1000):_} MB")
print(df_info["Data_Types"].value_counts().to_json())
df_info.sort_values(by = ["Data_Types", "max"], ascending=[1,0])

Memory: 6.504555 MB
{"object":43,"int64":27,"float64":11}

,Nulls,Nulls_pct,Data_Types,Memory,count,unique,top,freq,mean,std,min,25%,median,75%,max,IRQ,range,sum
PID,0,0.00,int64,21096,2637,NaN,NaN,NaN,714130147.70383,188752674.750322,526301100.0,528477010.0,535453040.0,907187010.0,1007100110.0,378710000.0,480799010.0,1883161199495.0
SalePrice,0,0.00,int64,21096,2637,NaN,NaN,NaN,179986.230186,78309.251522,12789.0,129500.0,160000.0,213000.0,745000.0,83500.0,732211.0,474623689.0
Lot Area,0,0.00,int64,21096,2637,NaN,NaN,NaN,10044.694729,6742.549521,1300.0,7436.0,9450.0,11526.0,164660.0,4090.0,163360.0,26487860.0
Misc Val,0,0.00,int64,21096,2637,NaN,NaN,NaN,42.014031,393.158781,0.0,0.0,0.0,0.0,12500.0,0.0,12500.0,110791.0
Gr Liv Area,0,0.00,int64,21096,2637,NaN,NaN,NaN,1496.98521,495.209631,334.0,1128.0,1441.0,1740.0,5642.0,612.0,5308.0,3947550.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Pool QC,2626,32.42,object,84593,11,4,Gd,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fence,2109,26.04,object,95886,528,4,MnPrv,306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Misc Feature,2541,31.37,object,86400,96,4,Shed,87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sale Type,0,0.00,object,137192,2637,10,WD,2286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sale Condition,0,0.00,object,145441,2637,6,Normal,2166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Notes:
- remove columns with 20% or more of null values


- remove rows with 5% or fewer null values

In [ ]:
for dt in df_info["Data_Types"].unique():
  print(dt)

int64
object
float64

In [ ]:
df_info["Data_Types"].value_counts()

Data_Types
object     43
int64      27
float64    11
Name: count, dtype: int64

In [ ]:
for dt in df_info["Data_Types"].unique():
  filter = df_info["Data_Types"] == dt
  cols = df_info[ filter ].index
  housing[ cols ].info()

In [ ]:
filter = df_info["Data_Types"] == "object"
filter.sum()
# cols = df_info[ filter ].index
# housing[cols].nunique().sort_values(ascending = False)

np.int64(43)

## Automate: second pass

### Blank data frame

In [ ]:
metatdata_df = pd.DataFrame()
metatdata_df

Empty DataFrame
Columns: []
Index: []

### Append data type info

In [ ]:
metatdata_df["Data_types"] = housing.dtypes
metatdata_df

               Data_types
PID                 int64
MS SubClass         int64
MS Zoning          object
Lot Frontage      float64
Lot Area            int64
...                   ...
Mo Sold             int64
Yr Sold             int64
Sale Type          object
Sale Condition     object
SalePrice           int64

[81 rows x 1 columns]

### Append Null stats

In [ ]:
metatdata_df["Nulls"] = housing.isnull().sum()
metatdata_df

               Data_types  Nulls
PID                 int64      0
MS SubClass         int64      0
MS Zoning          object      0
Lot Frontage      float64    449
Lot Area            int64      0
...                   ...    ...
Mo Sold             int64      0
Yr Sold             int64      0
Sale Type          object      0
Sale Condition     object      0
SalePrice           int64      0

[81 rows x 2 columns]

In [ ]:
metatdata_df["Nulls_pct"] = ( metatdata_df["Nulls"] / housing.shape[0] * 100 ).round(1)
metatdata_df

               Data_types  Nulls  Nulls_pct
PID                 int64      0        0.0
MS SubClass         int64      0        0.0
MS Zoning          object      0        0.0
Lot Frontage      float64    449       17.0
Lot Area            int64      0        0.0
...                   ...    ...        ...
Mo Sold             int64      0        0.0
Yr Sold             int64      0        0.0
Sale Type          object      0        0.0
Sale Condition     object      0        0.0
SalePrice           int64      0        0.0

[81 rows x 3 columns]

### Append memory usage

In [ ]:
metatdata_df["Memory"] = housing.memory_usage( deep = True)
metatdata_df

               Data_types  Nulls  Nulls_pct  Memory
PID                 int64      0        0.0   21096
MS SubClass         int64      0        0.0   21096
MS Zoning          object      0        0.0  134632
Lot Frontage      float64    449       17.0   21096
Lot Area            int64      0        0.0   21096
...                   ...    ...        ...     ...
Mo Sold             int64      0        0.0   21096
Yr Sold             int64      0        0.0   21096
Sale Type          object      0        0.0  137192
Sale Condition     object      0        0.0  145441
SalePrice           int64      0        0.0   21096

[81 rows x 4 columns]

### Append unique counts and percentage

In [ ]:
metatdata_df["NUnique"] = housing.nunique()
metatdata_df

               Data_types  Nulls  Nulls_pct  Memory  NUnique
PID                 int64      0        0.0   21096     2637
MS SubClass         int64      0        0.0   21096       16
MS Zoning          object      0        0.0  134632        7
Lot Frontage      float64    449       17.0   21096      126
Lot Area            int64      0        0.0   21096     1799
...                   ...    ...        ...     ...      ...
Mo Sold             int64      0        0.0   21096       12
Yr Sold             int64      0        0.0   21096        5
Sale Type          object      0        0.0  137192       10
Sale Condition     object      0        0.0  145441        6
SalePrice           int64      0        0.0   21096      983

[81 rows x 5 columns]

In [ ]:
metatdata_df["NUnique_pct"] = (housing.nunique()/len(housing)*100).round(1)
metatdata_df

               Data_types  Nulls  Nulls_pct  Memory  NUnique  NUnique_pct
PID                 int64      0        0.0   21096     2637        100.0
MS SubClass         int64      0        0.0   21096       16          0.6
MS Zoning          object      0        0.0  134632        7          0.3
Lot Frontage      float64    449       17.0   21096      126          4.8
Lot Area            int64      0        0.0   21096     1799         68.2
...                   ...    ...        ...     ...      ...          ...
Mo Sold             int64      0        0.0   21096       12          0.5
Yr Sold             int64      0        0.0   21096        5          0.2
Sale Type          object      0        0.0  137192       10          0.4
Sale Condition     object      0        0.0  145441        6          0.2
SalePrice           int64      0        0.0   21096      983         37.3

[81 rows x 6 columns]

### Append descriptive stats

Use .join() instead of .concatenate().  This ensures the named index is used to match values.

In [ ]:
metatdata_df = metatdata_df.join(housing.describe(include = "all").transpose())
metatdata_df

,Data_types,Nulls,Nulls_pct,Memory,NUnique,NUnique_pct,count,unique,top,freq,mean,std,min,25%,50%,75%,max
PID,int64,0,0.0,21096,2637,100.0,2637.0,NaN,NaN,NaN,714130147.70383,188752674.750322,526301100.0,528477010.0,535453040.0,907187010.0,1007100110.0
MS SubClass,int64,0,0.0,21096,16,0.6,2637.0,NaN,NaN,NaN,57.349261,42.499091,20.0,20.0,50.0,70.0,190.0
MS Zoning,object,0,0.0,134632,7,0.3,2637,7,RL,2043,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lot Frontage,float64,449,17.0,21096,126,4.8,2188.0,NaN,NaN,NaN,69.166819,23.356779,21.0,58.0,68.0,80.0,313.0
Lot Area,int64,0,0.0,21096,1799,68.2,2637.0,NaN,NaN,NaN,10044.694729,6742.549521,1300.0,7436.0,9450.0,11526.0,164660.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Mo Sold,int64,0,0.0,21096,12,0.5,2637.0,NaN,NaN,NaN,6.243838,2.722093,1.0,4.0,6.0,8.0,12.0
Yr Sold,int64,0,0.0,21096,5,0.2,2637.0,NaN,NaN,NaN,2007.795601,1.306403,2006.0,2007.0,2008.0,2009.0,2010.0
Sale Type,object,0,0.0,137192,10,0.4,2637,10,WD,2286,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sale Condition,object,0,0.0,145441,6,0.2,2637,6,Normal,2166,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SalePrice,int64,0,0.0,21096,983,37.3,2637.0,NaN,NaN,NaN,179986.230186,78309.251522,12789.0,129500.0,160000.0,213000.0,745000.0

### Adjust format of data frame

In [ ]:
metatdata_df = metatdata_df.astype({"count":int}).rename(columns = {"50%": "median"})
metatdata_df

,Data_types,Nulls,Nulls_pct,Memory,NUnique,NUnique_pct,count,unique,top,freq,mean,std,min,25%,median,75%,max
PID,int64,0,0.0,21096,2637,100.0,2637,NaN,NaN,NaN,714130147.70383,188752674.750322,526301100.0,528477010.0,535453040.0,907187010.0,1007100110.0
MS SubClass,int64,0,0.0,21096,16,0.6,2637,NaN,NaN,NaN,57.349261,42.499091,20.0,20.0,50.0,70.0,190.0
MS Zoning,object,0,0.0,134632,7,0.3,2637,7,RL,2043,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lot Frontage,float64,449,17.0,21096,126,4.8,2188,NaN,NaN,NaN,69.166819,23.356779,21.0,58.0,68.0,80.0,313.0
Lot Area,int64,0,0.0,21096,1799,68.2,2637,NaN,NaN,NaN,10044.694729,6742.549521,1300.0,7436.0,9450.0,11526.0,164660.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Mo Sold,int64,0,0.0,21096,12,0.5,2637,NaN,NaN,NaN,6.243838,2.722093,1.0,4.0,6.0,8.0,12.0
Yr Sold,int64,0,0.0,21096,5,0.2,2637,NaN,NaN,NaN,2007.795601,1.306403,2006.0,2007.0,2008.0,2009.0,2010.0
Sale Type,object,0,0.0,137192,10,0.4,2637,10,WD,2286,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sale Condition,object,0,0.0,145441,6,0.2,2637,6,Normal,2166,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SalePrice,int64,0,0.0,21096,983,37.3,2637,NaN,NaN,NaN,179986.230186,78309.251522,12789.0,129500.0,160000.0,213000.0,745000.0

### Redo as a Function

In [ ]:
def metadata( dataframe ):
  '''Given a dataframe, returns a dataframe of metadata about the dataframe'''
  metadata_df = pd.DataFrame()
  metadata_df["Data_types"] = dataframe.dtypes
  metadata_df["Count"] = len(dataframe)
  metadata_df["Nulls"] = dataframe.isnull().sum()
  metadata_df["Nulls_pct"] = ( metadata_df["Nulls"] / metadata_df["Count"] * 100 ).round(1)
  metadata_df["Memory"] = dataframe.memory_usage( deep = True)
  metadata_df["NUnique"] = dataframe.nunique()
  metadata_df["NUnique_pct"] = (dataframe.nunique() / metadata_df["Count"] * 100).round(1)
  metadata_df = metadata_df.join( dataframe.describe(include = "all").transpose())
  metadata_df["IRQ"] = metadata_df["75%"] - metadata_df["25%"]
  metadata_df["range"] = metadata_df["max"] - metadata_df["min"]
  metadata_df["sum"] = metadata_df["mean"] * metadata_df["count"]
  metadata_df = (
    metadata_df
    .astype({ "count" : int })
    .rename(columns = {
      "25%" : "Q1_25%",
      "50%" : "Q2_median",
      "75%" : "Q3_75%",
      }
    )
  )
  return metadata_df

In [ ]:
md = metadata(housing)
md

,Data_types,Count,Nulls,Nulls_pct,Memory,NUnique,NUnique_pct,count,unique,top,...,mean,std,min,Q1_25%,Q2_median,Q3_75%,max,IRQ,range,sum
PID,int64,2637,0,0.0,21096,2637,100.0,2637,NaN,NaN,...,714130147.70383,188752674.750322,526301100.0,528477010.0,535453040.0,907187010.0,1007100110.0,378710000.0,480799010.0,1883161199495.0
MS SubClass,int64,2637,0,0.0,21096,16,0.6,2637,NaN,NaN,...,57.349261,42.499091,20.0,20.0,50.0,70.0,190.0,50.0,170.0,151230.0
MS Zoning,object,2637,0,0.0,134632,7,0.3,2637,7,RL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lot Frontage,float64,2637,449,17.0,21096,126,4.8,2188,NaN,NaN,...,69.166819,23.356779,21.0,58.0,68.0,80.0,313.0,22.0,292.0,151337.0
Lot Area,int64,2637,0,0.0,21096,1799,68.2,2637,NaN,NaN,...,10044.694729,6742.549521,1300.0,7436.0,9450.0,11526.0,164660.0,4090.0,163360.0,26487860.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Mo Sold,int64,2637,0,0.0,21096,12,0.5,2637,NaN,NaN,...,6.243838,2.722093,1.0,4.0,6.0,8.0,12.0,4.0,11.0,16465.0
Yr Sold,int64,2637,0,0.0,21096,5,0.2,2637,NaN,NaN,...,2007.795601,1.306403,2006.0,2007.0,2008.0,2009.0,2010.0,2.0,4.0,5294557.0
Sale Type,object,2637,0,0.0,137192,10,0.4,2637,10,WD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sale Condition,object,2637,0,0.0,145441,6,0.2,2637,6,Normal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SalePrice,int64,2637,0,0.0,21096,983,37.3,2637,NaN,NaN,...,179986.230186,78309.251522,12789.0,129500.0,160000.0,213000.0,745000.0,83500.0,732211.0,474623689.0

A count of columns with each data type.

In [ ]:
md["Data_types"].value_counts()

Data_types
object     43
int64      27
float64    11
Name: count, dtype: int64

All columns with more than some threshold of nulls.

In [ ]:
filter = (md["Nulls_pct"] > 10)
md["Nulls_pct"][filter].sort_values(ascending = False)

Pool QC         99.6
Misc Feature    96.4
Alley           93.2
Fence           80.0
Mas Vnr Type    60.9
Fireplace Qu    48.7
Lot Frontage    17.0
Name: Nulls_pct, dtype: float64

Identifier columns

In [ ]:
filter = (md["NUnique_pct"] > 95)
md[["count", "NUnique","NUnique_pct"]][filter].sort_values(by = ["NUnique_pct"], ascending = False)

     count  NUnique  NUnique_pct
PID   2637     2637        100.0

Skew

In [ ]:
(md["mean"] > md["Q2_median"]).sum()

np.int64(29)

## Automate: import

### Just one python file

In [ ]:
%%writefile metadata01.py
import pandas as pd

def metadata( dataframe ):
  '''Given a dataframe, returns a dataframe of metadata about the dataframe'''
  metadata_df = pd.DataFrame()
  metadata_df["Data_types"] = dataframe.dtypes
  metadata_df["Count"] = len(dataframe)
  metadata_df["Nulls"] = dataframe.isnull().sum()
  metadata_df["Nulls_pct"] = ( metadata_df["Nulls"] / metadata_df["Count"] * 100 ).round(1)
  metadata_df["Memory"] = dataframe.memory_usage( deep = True)
  metadata_df["NUnique"] = dataframe.nunique()
  metadata_df["NUnique_pct"] = (dataframe.nunique() / metadata_df["Count"] * 100).round(1)
  metadata_df = metadata_df.join( dataframe.describe( include = "all" ).transpose() )
  metadata_df = metadata_df.astype( { "count" : int } )
  if dataframe.select_dtypes(include=['number']).shape[1] :
    metadata_df["IRQ"] = metadata_df["75%"] - metadata_df["25%"]
    metadata_df["range"] = metadata_df["max"] - metadata_df["min"]
    metadata_df["sum"] = metadata_df["mean"] * metadata_df["count"]
    metadata_df = (
      metadata_df
      .rename( columns = {
        "25%" : "Q1_25%",
        "50%" : "Q2_median",
        "75%" : "Q3_75%",
        }
      )
    )
  return metadata_df

def cols_to_drop( dataframe ):
  '''Given a dataframe, returns columns that should likely be dropped'''
  md = metadata( dataframe )
  filter = md["Nulls_pct"] >= 40
  return md[ filter ]["Nulls_pct"].to_dict()

def likely_ids( dataframe ):
  '''Given a dataframe, returns a dictionary of likely ID columns'''
  md = metadata( dataframe )
  return md["NUnique_pct"][ md["NUnique_pct"] > 95 ].sort_values( ascending = False )

Writing metadata01.py

In [ ]:
!ls -la m*

-rw-r--r-- 1 root root 1607 Jun 29 20:24 metadata01.py

In [ ]:
!cat -n metadata01.py

     1	import pandas as pd
     2
     3	def metadata( dataframe ):
     4	  '''Given a dataframe, returns a dataframe of metadata about the dataframe'''
     5	  metadata_df = pd.DataFrame()
     6	  metadata_df["Data_types"] = dataframe.dtypes
     7	  metadata_df["Count"] = len(dataframe)
     8	  metadata_df["Nulls"] = dataframe.isnull().sum()
     9	  metadata_df["Nulls_pct"] = ( metadata_df["Nulls"] / metadata_df["Count"] * 100 ).round(1)
    10	  metadata_df["Memory"] = dataframe.memory_usage( deep = True)
    11	  metadata_df["NUnique"] = dataframe.nunique()
    12	  metadata_df["NUnique_pct"] = (dataframe.nunique() / metadata_df["Count"] * 100).round(1)
    13	  metadata_df = metadata_df.join( dataframe.describe( include = "all" ).transpose() )
    14	  metadata_df = metadata_df.astype( { "count" : int } )
    15	  if dataframe.select_dtypes(include=['number']).shape[1] :
    16	    metadata_df["IRQ"] = metadata_df["75%"] - metadata_df["25%"]
    17	    metadata_df["range"] = metadata_df["max"] - metadata_df["min"]
    18	    metadata_df["sum"] = metadata_df["mean"] * metadata_df["count"]
    19	    metadata_df = (
    20	      metadata_df
    21	      .rename( columns = {
    22	        "25%" : "Q1_25%",
    23	        "50%" : "Q2_median",
    24	        "75%" : "Q3_75%",
    25	        }
    26	      )
    27	    )
    28	  return metadata_df
    29
    30	def cols_to_drop( dataframe ):
    31	  '''Given a dataframe, returns columns that should likely be dropped'''
    32	  md = metadata( dataframe )
    33	  filter = md["Nulls_pct"] >= 40
    34	  return md[ filter ]["Nulls_pct"].to_dict()
    35
    36	def likely_ids( dataframe ):
    37	  '''Given a dataframe, returns a dictionary of likely ID columns'''
    38	  md = metadata( dataframe )
    39	  return md["NUnique_pct"][ md["NUnique_pct"] > 95 ].sort_values( ascending = False )

In [ ]:
import metadata01

In [ ]:
metadata01.metadata(df)

,Data_types,Count,Nulls,Nulls_pct,Memory,NUnique,NUnique_pct,count,unique,top,...,mean,std,min,Q1_25%,Q2_median,Q3_75%,max,IRQ,range,sum
PID,int64,2637,0,0.0,21096,2637,100.0,2637,NaN,NaN,...,714130147.70383,188752674.750322,526301100.0,528477010.0,535453040.0,907187010.0,1007100110.0,378710000.0,480799010.0,1883161199495.0
MS SubClass,int64,2637,0,0.0,21096,16,0.6,2637,NaN,NaN,...,57.349261,42.499091,20.0,20.0,50.0,70.0,190.0,50.0,170.0,151230.0
MS Zoning,object,2637,0,0.0,134632,7,0.3,2637,7,RL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lot Frontage,float64,2637,449,17.0,21096,126,4.8,2188,NaN,NaN,...,69.166819,23.356779,21.0,58.0,68.0,80.0,313.0,22.0,292.0,151337.0
Lot Area,int64,2637,0,0.0,21096,1799,68.2,2637,NaN,NaN,...,10044.694729,6742.549521,1300.0,7436.0,9450.0,11526.0,164660.0,4090.0,163360.0,26487860.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Mo Sold,int64,2637,0,0.0,21096,12,0.5,2637,NaN,NaN,...,6.243838,2.722093,1.0,4.0,6.0,8.0,12.0,4.0,11.0,16465.0
Yr Sold,int64,2637,0,0.0,21096,5,0.2,2637,NaN,NaN,...,2007.795601,1.306403,2006.0,2007.0,2008.0,2009.0,2010.0,2.0,4.0,5294557.0
Sale Type,object,2637,0,0.0,137192,10,0.4,2637,10,WD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sale Condition,object,2637,0,0.0,145441,6,0.2,2637,6,Normal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SalePrice,int64,2637,0,0.0,21096,983,37.3,2637,NaN,NaN,...,179986.230186,78309.251522,12789.0,129500.0,160000.0,213000.0,745000.0,83500.0,732211.0,474623689.0

In [ ]:
import metadata01 as md01

In [ ]:
md01.metadata(df)

,Data_types,Count,Nulls,Nulls_pct,Memory,NUnique,NUnique_pct,count,unique,top,...,mean,std,min,Q1_25%,Q2_median,Q3_75%,max,IRQ,range,sum
PID,int64,2637,0,0.0,21096,2637,100.0,2637,NaN,NaN,...,714130147.70383,188752674.750322,526301100.0,528477010.0,535453040.0,907187010.0,1007100110.0,378710000.0,480799010.0,1883161199495.0
MS SubClass,int64,2637,0,0.0,21096,16,0.6,2637,NaN,NaN,...,57.349261,42.499091,20.0,20.0,50.0,70.0,190.0,50.0,170.0,151230.0
MS Zoning,object,2637,0,0.0,134632,7,0.3,2637,7,RL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lot Frontage,float64,2637,449,17.0,21096,126,4.8,2188,NaN,NaN,...,69.166819,23.356779,21.0,58.0,68.0,80.0,313.0,22.0,292.0,151337.0
Lot Area,int64,2637,0,0.0,21096,1799,68.2,2637,NaN,NaN,...,10044.694729,6742.549521,1300.0,7436.0,9450.0,11526.0,164660.0,4090.0,163360.0,26487860.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Mo Sold,int64,2637,0,0.0,21096,12,0.5,2637,NaN,NaN,...,6.243838,2.722093,1.0,4.0,6.0,8.0,12.0,4.0,11.0,16465.0
Yr Sold,int64,2637,0,0.0,21096,5,0.2,2637,NaN,NaN,...,2007.795601,1.306403,2006.0,2007.0,2008.0,2009.0,2010.0,2.0,4.0,5294557.0
Sale Type,object,2637,0,0.0,137192,10,0.4,2637,10,WD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sale Condition,object,2637,0,0.0,145441,6,0.2,2637,6,Normal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SalePrice,int64,2637,0,0.0,21096,983,37.3,2637,NaN,NaN,...,179986.230186,78309.251522,12789.0,129500.0,160000.0,213000.0,745000.0,83500.0,732211.0,474623689.0

### GitHub

Upload your code to GitHub:
1. login to GitHub
1. create a repo, e.g. ds-toolbox
1. click Add file > Upload files
1. commit to the repository

Get the "raw" link:
1. click on the file
1. click Raw
1. copy the link in the address bar

( alternatively, right click on Raw and copy the link.  Use -L when using curl )

Download your toolkit file from GitHub.

In [ ]:
!ls -l

total 12
-rw-r--r-- 1 root root 1607 Jun 29 20:24 metadata01.py
drwxr-xr-x 2 root root 4096 Jun 29 20:24 __pycache__
drwxr-xr-x 1 root root 4096 Jun  4 13:32 sample_data

In [ ]:
# !curl -s -O https://raw.githubusercontent.com/rwcitek/ddc-example-repo/refs/heads/main/python_modules/metadata.py
# !curl -s -L -O https://github.com/rwcitek/ddc-example-repo/raw/refs/heads/main/python_modules/metadata.py

!curl -s -L -o metadata02.py https://github.com/rwcitek/ddc-example-repo/raw/refs/heads/main/python_modules/metadata.py

In [ ]:
!ls -l

total 16
-rw-r--r-- 1 root root 1607 Jun 29 20:24 metadata01.py
-rw-r--r-- 1 root root 1614 Jun 29 20:25 metadata02.py
drwxr-xr-x 2 root root 4096 Jun 29 20:24 __pycache__
drwxr-xr-x 1 root root 4096 Jun  4 13:32 sample_data

In [ ]:
import metadata02

In [ ]:
md = metadata02.metadata(housing)
md

,Data_types,Count,Nulls,Nulls_pct,Memory,NUnique,NUnique_pct,count,unique,top,...,mean,std,min,Q1_25%,Q2_median,Q3_75%,max,IRQ,range,sum
PID,int64,2637,0,0.0,21096,2637,100.0,2637,NaN,NaN,...,714130147.70383,188752674.750322,526301100.0,528477010.0,535453040.0,907187010.0,1007100110.0,378710000.0,480799010.0,1883161199495.0
MS SubClass,int64,2637,0,0.0,21096,16,0.6,2637,NaN,NaN,...,57.349261,42.499091,20.0,20.0,50.0,70.0,190.0,50.0,170.0,151230.0
MS Zoning,object,2637,0,0.0,134632,7,0.3,2637,7,RL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lot Frontage,float64,2637,449,17.0,21096,126,4.8,2188,NaN,NaN,...,69.166819,23.356779,21.0,58.0,68.0,80.0,313.0,22.0,292.0,151337.0
Lot Area,int64,2637,0,0.0,21096,1799,68.2,2637,NaN,NaN,...,10044.694729,6742.549521,1300.0,7436.0,9450.0,11526.0,164660.0,4090.0,163360.0,26487860.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Mo Sold,int64,2637,0,0.0,21096,12,0.5,2637,NaN,NaN,...,6.243838,2.722093,1.0,4.0,6.0,8.0,12.0,4.0,11.0,16465.0
Yr Sold,int64,2637,0,0.0,21096,5,0.2,2637,NaN,NaN,...,2007.795601,1.306403,2006.0,2007.0,2008.0,2009.0,2010.0,2.0,4.0,5294557.0
Sale Type,object,2637,0,0.0,137192,10,0.4,2637,10,WD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sale Condition,object,2637,0,0.0,145441,6,0.2,2637,6,Normal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SalePrice,int64,2637,0,0.0,21096,983,37.3,2637,NaN,NaN,...,179986.230186,78309.251522,12789.0,129500.0,160000.0,213000.0,745000.0,83500.0,732211.0,474623689.0

In [ ]:
metadata02.cols_to_drop(housing)

{'Alley': 93.2,
 'Mas Vnr Type': 60.9,
 'Fireplace Qu': 48.7,
 'Pool QC': 99.6,
 'Fence': 80.0,
 'Misc Feature': 96.4}

In [ ]:
metadata02?

In [ ]:
metadata02??

### Clone GitHub repo

How many packages are pre-installed in the CoLab environment?

In [ ]:
%%capture
pip = !pip3 list

In [ ]:
pip[:5], "...", pip[-5:]

(['Package                                  Version',
  '---------------------------------------- ------------------',
  'absl-py                                  1.4.0',
  'accelerate                               1.14.0',
  'access                                   1.1.10.post3'],
 '...',
 ['ydf_tf                                   2.20.0',
  'yellowbrick                              1.5',
  'yfinance                                 0.2.66',
  'zipp                                     4.1.0',
  'zstandard                                0.25.0'])

In [ ]:
len(pip[2:])

666

In [ ]:
for i in pip:
  if "module" in i:
    print(i)

pyasn1_modules                           0.4.2

In [ ]:
!git clone https://github.com/rwcitek/ddc-example-repo.git

Cloning into 'ddc-example-repo'...
remote: Enumerating objects: 123, done.
remote: Counting objects: 100% (123/123), done.
remote: Compressing objects: 100% (109/109), done.
remote: Total 123 (delta 46), reused 3 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (123/123), 33.96 KiB | 1.21 MiB/s, done.
Resolving deltas: 100% (46/46), done.

In [ ]:
ls -lF

total 20
drwxr-xr-x 4 root root 4096 Jun 29 20:25 ddc-example-repo/
-rw-r--r-- 1 root root 1607 Jun 29 20:24 metadata01.py
-rw-r--r-- 1 root root 1614 Jun 29 20:25 metadata02.py
drwxr-xr-x 2 root root 4096 Jun 29 20:25 __pycache__/
drwxr-xr-x 1 root root 4096 Jun  4 13:32 sample_data/

In [ ]:
!tree ddc-example-repo

ddc-example-repo
├── hw.txt
├── LICENSE
├── pip+github.md
├── python_modules
│   ├── foobar.py
│   ├── __init__.py
│   ├── metadata.py
│   └── my_module.py
├── README.md
└── setup.py

1 directory, 9 files

In [ ]:
cat -n ddc-example-repo/setup.py

In [ ]:
!pip install ./ddc-example-repo/

Processing ./ddc-example-repo
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: python_modules
  Building wheel for python_modules (setup.py) ... done
  Created wheel for python_modules: filename=python_modules-0.1-py3-none-any.whl size=7121 sha256=93bac0746b049cb127fa3a06025b7a13b7a119f15c90b79717949f6dbc2254be
  Stored in directory: /root/.cache/pip/wheels/a2/b3/7c/527291c06a92b91626a07aa8e33cf39ddc70409b43c09fa1e3
Successfully built python_modules
Installing collected packages: python_modules
Successfully installed python_modules-0.1

Now, how many packages are installed in the CoLab environment?

In [ ]:
pip = !pip3 list
len(pip[2:])

In [ ]:
for i in pip:
  if "module" in i:
    print(i)

In [ ]:
import python_modules as pm03

In [ ]:
pm03??

In [ ]:
cat -n /usr/local/lib/python3.12/dist-packages/python_modules/__init__.py

In [ ]:
pm03.metadata??

In [ ]:
ls -lF /usr/local/lib/python3.12/dist-packages/python_modules/

### Using pip and GitHub

In [ ]:
!pip install git+https://github.com/rwcitek/ddc-example-repo.git

In [ ]:
!pip list | grep module

In [ ]:
import python_modules as pm04

In [ ]:
pm04.hw()

In [ ]:
pm04.metadata(housing)

In [ ]:
pm04.foobar()