<a href="https://colab.research.google.com/github/stephanie465337/Data-Science-Portfolio-C21/blob/main/NotebookLM/Module%203/2b_Pandas_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Demonstrating SQL on Pandas DataFrames using DuckDB
This notebook demonstrates how to perform common SQL operations on a pandas DataFrame using DuckDB,
comparing native pandas syntax with its equivalent SQL syntax.

In [ ]:
import pandas as pd
import duckdb

In [ ]:
#Load the Boston housing dataset
url = 'http://ddc-datascience.s3.amazonaws.com/boston.csv'
url

'http://ddc-datascience.s3.amazonaws.com/boston.csv'

In [ ]:
df = pd.read_csv(url, index_col=0)
df.shape

(490, 13)

## 1. SELECT *
Select all columns and all rows from the dataset.

In [ ]:
#Pandas
df

,per_cap_crime,res_zoning_prop,business_prop,river_front,nitric_oxide_conc,num_rooms,units_before_1940,distance_to_employment,distance_to_hwy,prop_tax,pupil_teacher_ratio,perc_lower_status,med_home_value
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,7.88,11.9

In [ ]:
#SQL
#duckdb.query("SELECT * FROM df").df()
duckdb.query('''
  SELECT *
  FROM df
''').df()

,per_cap_crime,res_zoning_prop,business_prop,river_front,nitric_oxide_conc,num_rooms,units_before_1940,distance_to_employment,distance_to_hwy,prop_tax,pupil_teacher_ratio,perc_lower_status,med_home_value
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,9.67,22.4
486,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,9.08,20.6
487,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,5.64,23.9
488,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,6.48,22.0
489,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,7.88,11.9

## 2. SELECT - One Column
Select only the `med_home_value` column.

In [ ]:
#Pandas
df[['med_home_value']]

     med_home_value
0              24.0
1              21.6
2              34.7
3              33.4
4              36.2
..              ...
501            22.4
502            20.6
503            23.9
504            22.0
505            11.9

[490 rows x 1 columns]

In [ ]:
#SQL
duckdb.query('''
  SELECT med_home_value
  FROM df
''').df()

     med_home_value
0              24.0
1              21.6
2              34.7
3              33.4
4              36.2
..              ...
485            22.4
486            20.6
487            23.9
488            22.0
489            11.9

[490 rows x 1 columns]

## 3. SELECT - Multiple Columns
Select the `num_rooms`, `prop_tax`, and `med_home_value` columns.

In [ ]:
#Pandas
df[['num_rooms', 'prop_tax', 'med_home_value']]

     num_rooms  prop_tax  med_home_value
0        6.575     296.0            24.0
1        6.421     242.0            21.6
2        7.185     242.0            34.7
3        6.998     222.0            33.4
4        7.147     222.0            36.2
..         ...       ...             ...
501      6.593     273.0            22.4
502      6.120     273.0            20.6
503      6.976     273.0            23.9
504      6.794     273.0            22.0
505      6.030     273.0            11.9

[490 rows x 3 columns]

In [ ]:
#SQL
duckdb.query('''
  SELECT num_rooms, prop_tax, med_home_value
  FROM df
''').df()

     num_rooms  prop_tax  med_home_value
0        6.575     296.0            24.0
1        6.421     242.0            21.6
2        7.185     242.0            34.7
3        6.998     222.0            33.4
4        7.147     222.0            36.2
..         ...       ...             ...
485      6.593     273.0            22.4
486      6.120     273.0            20.6
487      6.976     273.0            23.9
488      6.794     273.0            22.0
489      6.030     273.0            11.9

[490 rows x 3 columns]

## 4. WHERE - Single Conditional (Numeric)
Filter rows where the number of rooms (`num_rooms`) is greater than 8.

In [ ]:
#Pandas
df[df['num_rooms'] > 8]

,per_cap_crime,res_zoning_prop,business_prop,river_front,nitric_oxide_conc,num_rooms,units_before_1940,distance_to_employment,distance_to_hwy,prop_tax,pupil_teacher_ratio,perc_lower_status,med_home_value
97,0.12083,0.0,2.89,0.0,0.445,8.069,76.0,3.4952,2.0,276.0,18.0,4.21,38.7
224,0.31533,0.0,6.20,0.0,0.504,8.266,78.3,2.8944,8.0,307.0,17.4,4.14,44.8
226,0.38214,0.0,6.20,0.0,0.504,8.040,86.5,3.2157,8.0,307.0,17.4,3.13,37.6
232,0.57529,0.0,6.20,0.0,0.507,8.337,73.3,3.8384,8.0,307.0,17.4,2.47,41.7
233,0.33147,0.0,6.20,0.0,0.507,8.247,70.4,3.6519,8.0,307.0,17.4,3.95,48.3
253,0.36894,22.0,5.86,0.0,0.431,8.259,8.4,8.9067,7.0,330.0,19.1,3.54,42.8
262,0.52014,20.0,3.97,0.0,0.647,8.398,91.5,2.2885,5.0,264.0,13.0,5.91,48.8
364,3.47428,0.0,18.10,1.0,0.718,8.780,82.9,1.9047,24.0,666.0,20.2,5.29,21.9

In [ ]:
#SQL
duckdb.query('''
  SELECT *
  FROM df
  WHERE num_rooms > 8
''').df()

,per_cap_crime,res_zoning_prop,business_prop,river_front,nitric_oxide_conc,num_rooms,units_before_1940,distance_to_employment,distance_to_hwy,prop_tax,pupil_teacher_ratio,perc_lower_status,med_home_value
0,0.12083,0.0,2.89,0.0,0.445,8.069,76.0,3.4952,2.0,276.0,18.0,4.21,38.7
1,0.31533,0.0,6.20,0.0,0.504,8.266,78.3,2.8944,8.0,307.0,17.4,4.14,44.8
2,0.38214,0.0,6.20,0.0,0.504,8.040,86.5,3.2157,8.0,307.0,17.4,3.13,37.6
3,0.57529,0.0,6.20,0.0,0.507,8.337,73.3,3.8384,8.0,307.0,17.4,2.47,41.7
4,0.33147,0.0,6.20,0.0,0.507,8.247,70.4,3.6519,8.0,307.0,17.4,3.95,48.3
5,0.36894,22.0,5.86,0.0,0.431,8.259,8.4,8.9067,7.0,330.0,19.1,3.54,42.8
6,0.52014,20.0,3.97,0.0,0.647,8.398,91.5,2.2885,5.0,264.0,13.0,5.91,48.8
7,3.47428,0.0,18.10,1.0,0.718,8.780,82.9,1.9047,24.0,666.0,20.2,5.29,21.9

## 5. WHERE - Single Conditional (Binary/Flag)
Filter rows where the property limits the Charles River (`river_front` equals 1).

In [ ]:
#Pandas
df[df['river_front'] == 1]

,per_cap_crime,res_zoning_prop,business_prop,river_front,nitric_oxide_conc,num_rooms,units_before_1940,distance_to_employment,distance_to_hwy,prop_tax,pupil_teacher_ratio,perc_lower_status,med_home_value
142,3.32105,0.0,19.58,1.0,0.8710,5.403,100.0,1.3216,5.0,403.0,14.7,26.82,13.4
152,1.12658,0.0,19.58,1.0,0.8710,5.012,88.0,1.6102,5.0,403.0,14.7,12.12,15.3
154,1.41385,0.0,19.58,1.0,0.8710,6.129,96.0,1.7494,5.0,403.0,14.7,15.12,17.0
155,3.53501,0.0,19.58,1.0,0.8710,6.152,82.6,1.7455,5.0,403.0,14.7,15.02,15.6
160,1.27346,0.0,19.58,1.0,0.6050,6.250,92.6,1.7984,5.0,403.0,14.7,5.50,27.0
208,0.13587,0.0,10.59,1.0,0.4890,6.064,59.1,4.2392,4.0,277.0,18.6,14.66,24.4
209,0.43571,0.0,10.59,1.0,0.4890,5.344,100.0,3.8750,4.0,277.0,18.6,23.09,20.0
210,0.17446,0.0,10.59,1.0,0.4890,5.960,92.1,3.8771,4.0,277.0,18.6,17.27,21.7
211,0.37578,0.0,10.59,1.0,0.4890,5.404,88.6,3.6650,4.0,277.0,18.6,23.98,19.3
212,0.21719,0.0,10.59,1.0,0.4890,5.807,53.8,3.6526,4.0,277.0,18.6,16.03,22.4
216,0.04560,0.0,13.89,1.0,0.5500,5.888,56.0,3.1121,5.0,276.0,16.4,13.51,23.3
218,0.11069,0.0,13.89,1.0,0.5500,5.951,93.8,2.8893,5.0,276.0,16.4,17.92,21.5
219,0.11425,0.0,13.89,1.0,0.5500,6.373,92.4,3.3633,5.0,276.0,16.4,10.50,23.0
220,0.35809,0.0,6.20,1.0,0.5070,6.951,88.5,2.8617,8.0,307.0,17.4,9.71,26.7
221,0.40771,0.0,6.20,1.0,0.5070,6.164,91.3,3.0480,8.0,307.0,17.4,21.46,21.7
222,0.62356,0.0,6.20,1.0,0.5070,6.879,77.7,3.2721,8.0,307.0,17.4,9.93,27.5
234,0.44791,0.0,6.20,1.0,0.5070,6.726,66.5,3.6519,8.0,307.0,17.4,8.05,29.0
236,0.52058,0.0,6.20,1.0,0.5070,6.631,76.5,4.1480,8.0,307.0,17.4,9.54,25.1
269,0.09065,20.0,6.96,1.0,0.4640,5.920,61.5,3.9175,3.0,223.0,18.6,13.65,20.7
273,0.22188,20.0,6.96,1.0,0.4640,7.691,51.8,4.3665,3.0,223.0,18.6,6.58,35.2
274,0.05644,40.0,6.41,1.0,0.4470,6.758,32.9,4.0776,4.0,254.0,17.6,3.53,32.4
276,0.10469,40.0,6.41,1.0,0.4470,7.267,49.0,4.7872,4.0,254.0,17.6,6.05,33.2
277,0.06127,40.0,6.41,1.0,0.4470,6.826,27.6,4.8628,4.0,254.0,17.6,4.16,33.1
282,0.06129,20.0,3.33,1.0,0.4429,7.645,49.7,5.2119,5.0,216.0,14.9,3.01,46.0
356,8.98296,0.0,18.10,1.0,0.7700,6.212,97.4,2.1222,24.0,666.0,20.2,17.60,17.8
357,3.84970,0.0,18.10,1.0,0.7700,6.395,91.0,2.5052,24.0,666.0,20.2,13.27,21.7
358,5.20177,0.0,18.10,1.0,0.7700,6.127,83.4,2.7227,24.0,666.0,20.2,11.48,22.7
363,4.22239,0.0,18.10,1.0,0.7700,5.803,89.0,1.9047,24.0,666.0,20.2,14.64,16.8
364,3.47428,0.0,18.10,1.0,0.7180,8.780,82.9,1.9047,24.0,666.0,20.2,5.29,21.9

In [ ]:
#SQL
duckdb.query('''
  SELECT *
  FROM df
  WHERE river_front = 1
''').df()

,per_cap_crime,res_zoning_prop,business_prop,river_front,nitric_oxide_conc,num_rooms,units_before_1940,distance_to_employment,distance_to_hwy,prop_tax,pupil_teacher_ratio,perc_lower_status,med_home_value
0,3.32105,0.0,19.58,1.0,0.8710,5.403,100.0,1.3216,5.0,403.0,14.7,26.82,13.4
1,1.12658,0.0,19.58,1.0,0.8710,5.012,88.0,1.6102,5.0,403.0,14.7,12.12,15.3
2,1.41385,0.0,19.58,1.0,0.8710,6.129,96.0,1.7494,5.0,403.0,14.7,15.12,17.0
3,3.53501,0.0,19.58,1.0,0.8710,6.152,82.6,1.7455,5.0,403.0,14.7,15.02,15.6
4,1.27346,0.0,19.58,1.0,0.6050,6.250,92.6,1.7984,5.0,403.0,14.7,5.50,27.0
5,0.13587,0.0,10.59,1.0,0.4890,6.064,59.1,4.2392,4.0,277.0,18.6,14.66,24.4
6,0.43571,0.0,10.59,1.0,0.4890,5.344,100.0,3.8750,4.0,277.0,18.6,23.09,20.0
7,0.17446,0.0,10.59,1.0,0.4890,5.960,92.1,3.8771,4.0,277.0,18.6,17.27,21.7
8,0.37578,0.0,10.59,1.0,0.4890,5.404,88.6,3.6650,4.0,277.0,18.6,23.98,19.3
9,0.21719,0.0,10.59,1.0,0.4890,5.807,53.8,3.6526,4.0,277.0,18.6,16.03,22.4
10,0.04560,0.0,13.89,1.0,0.5500,5.888,56.0,3.1121,5.0,276.0,16.4,13.51,23.3
11,0.11069,0.0,13.89,1.0,0.5500,5.951,93.8,2.8893,5.0,276.0,16.4,17.92,21.5
12,0.11425,0.0,13.89,1.0,0.5500,6.373,92.4,3.3633,5.0,276.0,16.4,10.50,23.0
13,0.35809,0.0,6.20,1.0,0.5070,6.951,88.5,2.8617,8.0,307.0,17.4,9.71,26.7
14,0.40771,0.0,6.20,1.0,0.5070,6.164,91.3,3.0480,8.0,307.0,17.4,21.46,21.7
15,0.62356,0.0,6.20,1.0,0.5070,6.879,77.7,3.2721,8.0,307.0,17.4,9.93,27.5
16,0.44791,0.0,6.20,1.0,0.5070,6.726,66.5,3.6519,8.0,307.0,17.4,8.05,29.0
17,0.52058,0.0,6.20,1.0,0.5070,6.631,76.5,4.1480,8.0,307.0,17.4,9.54,25.1
18,0.09065,20.0,6.96,1.0,0.4640,5.920,61.5,3.9175,3.0,223.0,18.6,13.65,20.7
19,0.22188,20.0,6.96,1.0,0.4640,7.691,51.8,4.3665,3.0,223.0,18.6,6.58,35.2
20,0.05644,40.0,6.41,1.0,0.4470,6.758,32.9,4.0776,4.0,254.0,17.6,3.53,32.4
21,0.10469,40.0,6.41,1.0,0.4470,7.267,49.0,4.7872,4.0,254.0,17.6,6.05,33.2
22,0.06127,40.0,6.41,1.0,0.4470,6.826,27.6,4.8628,4.0,254.0,17.6,4.16,33.1
23,0.06129,20.0,3.33,1.0,0.4429,7.645,49.7,5.2119,5.0,216.0,14.9,3.01,46.0
24,8.98296,0.0,18.10,1.0,0.7700,6.212,97.4,2.1222,24.0,666.0,20.2,17.60,17.8
25,3.84970,0.0,18.10,1.0,0.7700,6.395,91.0,2.5052,24.0,666.0,20.2,13.27,21.7
26,5.20177,0.0,18.10,1.0,0.7700,6.127,83.4,2.7227,24.0,666.0,20.2,11.48,22.7
27,4.22239,0.0,18.10,1.0,0.7700,5.803,89.0,1.9047,24.0,666.0,20.2,14.64,16.8
28,3.47428,0.0,18.10,1.0,0.7180,8.780,82.9,1.9047,24.0,666.0,20.2,5.29,21.9

## 6. WHERE - Two Conditionals with AND
Filter rows where `num_rooms` is greater than 7 AND `med_home_value` is greater than 40.

In [ ]:
#Pandas
df[(df['num_rooms'] > 7) & (df['med_home_value'] > 40)]

,per_cap_crime,res_zoning_prop,business_prop,river_front,nitric_oxide_conc,num_rooms,units_before_1940,distance_to_employment,distance_to_hwy,prop_tax,pupil_teacher_ratio,perc_lower_status,med_home_value
98,0.08187,0.0,2.89,0.0,0.4450,7.820,36.9,3.4952,2.0,276.0,18.0,3.57,43.8
202,0.02177,82.5,2.03,0.0,0.4150,7.610,15.7,6.2700,2.0,348.0,14.7,3.11,42.3
203,0.03510,95.0,2.68,0.0,0.4161,7.853,33.2,5.1180,4.0,224.0,14.7,3.81,48.5
224,0.31533,0.0,6.20,0.0,0.5040,8.266,78.3,2.8944,8.0,307.0,17.4,4.14,44.8
228,0.29819,0.0,6.20,0.0,0.5040,7.686,17.0,3.3751,8.0,307.0,17.4,3.92,46.7
232,0.57529,0.0,6.20,0.0,0.5070,8.337,73.3,3.8384,8.0,307.0,17.4,2.47,41.7
233,0.33147,0.0,6.20,0.0,0.5070,8.247,70.4,3.6519,8.0,307.0,17.4,3.95,48.3
253,0.36894,22.0,5.86,0.0,0.4310,8.259,8.4,8.9067,7.0,330.0,19.1,3.54,42.8
256,0.01538,90.0,3.75,0.0,0.3940,7.454,34.2,6.3361,3.0,244.0,15.9,3.11,44.0
261,0.53412,20.0,3.97,0.0,0.6470,7.520,89.4,2.1398,5.0,264.0,13.0,7.26,43.1
262,0.52014,20.0,3.97,0.0,0.6470,8.398,91.5,2.2885,5.0,264.0,13.0,5.91,48.8
268,0.54050,20.0,3.97,0.0,0.5750,7.470,52.6,2.8720,5.0,264.0,13.0,3.16,43.5
280,0.03578,20.0,3.33,0.0,0.4429,7.820,64.5,4.6947,5.0,216.0,14.9,3.76,45.4
282,0.06129,20.0,3.33,1.0,0.4429,7.645,49.7,5.2119,5.0,216.0,14.9,3.01,46.0

In [ ]:
#SQL
duckdb.query('''
  SELECT *
  FROM df
  WHERE
      num_rooms > 7
    AND
      med_home_value > 40
''').df()

,per_cap_crime,res_zoning_prop,business_prop,river_front,nitric_oxide_conc,num_rooms,units_before_1940,distance_to_employment,distance_to_hwy,prop_tax,pupil_teacher_ratio,perc_lower_status,med_home_value
0,0.08187,0.0,2.89,0.0,0.4450,7.820,36.9,3.4952,2.0,276.0,18.0,3.57,43.8
1,0.02177,82.5,2.03,0.0,0.4150,7.610,15.7,6.2700,2.0,348.0,14.7,3.11,42.3
2,0.03510,95.0,2.68,0.0,0.4161,7.853,33.2,5.1180,4.0,224.0,14.7,3.81,48.5
3,0.31533,0.0,6.20,0.0,0.5040,8.266,78.3,2.8944,8.0,307.0,17.4,4.14,44.8
4,0.29819,0.0,6.20,0.0,0.5040,7.686,17.0,3.3751,8.0,307.0,17.4,3.92,46.7
5,0.57529,0.0,6.20,0.0,0.5070,8.337,73.3,3.8384,8.0,307.0,17.4,2.47,41.7
6,0.33147,0.0,6.20,0.0,0.5070,8.247,70.4,3.6519,8.0,307.0,17.4,3.95,48.3
7,0.36894,22.0,5.86,0.0,0.4310,8.259,8.4,8.9067,7.0,330.0,19.1,3.54,42.8
8,0.01538,90.0,3.75,0.0,0.3940,7.454,34.2,6.3361,3.0,244.0,15.9,3.11,44.0
9,0.53412,20.0,3.97,0.0,0.6470,7.520,89.4,2.1398,5.0,264.0,13.0,7.26,43.1
10,0.52014,20.0,3.97,0.0,0.6470,8.398,91.5,2.2885,5.0,264.0,13.0,5.91,48.8
11,0.54050,20.0,3.97,0.0,0.5750,7.470,52.6,2.8720,5.0,264.0,13.0,3.16,43.5
12,0.03578,20.0,3.33,0.0,0.4429,7.820,64.5,4.6947,5.0,216.0,14.9,3.76,45.4
13,0.06129,20.0,3.33,1.0,0.4429,7.645,49.7,5.2119,5.0,216.0,14.9,3.01,46.0

## 7. WHERE - Two Conditionals with OR
Filter rows where `per_cap_crime` is extremely high (> 50) OR `perc_lower_status` is extremely high (> 30).

In [ ]:
#Pandas
df[(df['per_cap_crime'] > 50) | (df['perc_lower_status'] > 30)]

,per_cap_crime,res_zoning_prop,business_prop,river_front,nitric_oxide_conc,num_rooms,units_before_1940,distance_to_employment,distance_to_hwy,prop_tax,pupil_teacher_ratio,perc_lower_status,med_home_value
48,0.25387,0.0,6.91,0.0,0.448,5.399,95.3,5.8700,3.0,233.0,17.9,30.81,14.4
141,1.62864,0.0,21.89,0.0,0.624,5.019,100.0,1.4394,4.0,437.0,21.2,34.41,14.4
373,11.10810,0.0,18.10,0.0,0.668,4.906,100.0,1.1742,24.0,666.0,20.2,34.77,13.8
374,18.49820,0.0,18.10,0.0,0.668,4.138,100.0,1.1370,24.0,666.0,20.2,37.97,13.8
380,88.97620,0.0,18.10,0.0,0.671,6.968,91.9,1.4165,24.0,666.0,20.2,17.21,10.4
384,20.08490,0.0,18.10,0.0,0.700,4.368,91.2,1.4395,24.0,666.0,20.2,30.63,8.8
385,16.81180,0.0,18.10,0.0,0.700,5.277,98.1,1.4261,24.0,666.0,20.2,30.81,7.2
387,22.59710,0.0,18.10,0.0,0.700,5.000,89.5,1.5184,24.0,666.0,20.2,31.99,7.4
388,14.33370,0.0,18.10,0.0,0.700,4.880,100.0,1.5895,24.0,666.0,20.2,30.62,10.2
398,38.35180,0.0,18.10,0.0,0.693,5.453,100.0,1.4896,24.0,666.0,20.2,30.59,5.0
405,67.92080,0.0,18.10,0.0,0.693,5.683,100.0,1.4254,24.0,666.0,20.2,22.98,5.0
410,51.13580,0.0,18.10,0.0,0.597,5.757,100.0,1.4130,24.0,666.0,20.2,10.11,15.0
412,18.81100,0.0,18.10,0.0,0.597,4.628,100.0,1.5539,24.0,666.0,20.2,34.37,17.9
414,45.74610,0.0,18.10,0.0,0.693,4.519,100.0,1.6582,24.0,666.0,20.2,36.98,7.0
418,73.53410,0.0,18.10,0.0,0.679,5.957,100.0,1.8026,24.0,666.0,20.2,20.62,8.8
438,13.67810,0.0,18.10,0.0,0.740,5.935,87.9,1.8206,24.0,666.0,20.2,34.02,8.4

In [ ]:
#SQL
duckdb.query('''
  SELECT *
  FROM df
  WHERE
      per_cap_crime > 50
    OR
      perc_lower_status > 30
''').df()

,per_cap_crime,res_zoning_prop,business_prop,river_front,nitric_oxide_conc,num_rooms,units_before_1940,distance_to_employment,distance_to_hwy,prop_tax,pupil_teacher_ratio,perc_lower_status,med_home_value
0,0.25387,0.0,6.91,0.0,0.448,5.399,95.3,5.8700,3.0,233.0,17.9,30.81,14.4
1,1.62864,0.0,21.89,0.0,0.624,5.019,100.0,1.4394,4.0,437.0,21.2,34.41,14.4
2,11.10810,0.0,18.10,0.0,0.668,4.906,100.0,1.1742,24.0,666.0,20.2,34.77,13.8
3,18.49820,0.0,18.10,0.0,0.668,4.138,100.0,1.1370,24.0,666.0,20.2,37.97,13.8
4,88.97620,0.0,18.10,0.0,0.671,6.968,91.9,1.4165,24.0,666.0,20.2,17.21,10.4
5,20.08490,0.0,18.10,0.0,0.700,4.368,91.2,1.4395,24.0,666.0,20.2,30.63,8.8
6,16.81180,0.0,18.10,0.0,0.700,5.277,98.1,1.4261,24.0,666.0,20.2,30.81,7.2
7,22.59710,0.0,18.10,0.0,0.700,5.000,89.5,1.5184,24.0,666.0,20.2,31.99,7.4
8,14.33370,0.0,18.10,0.0,0.700,4.880,100.0,1.5895,24.0,666.0,20.2,30.62,10.2
9,38.35180,0.0,18.10,0.0,0.693,5.453,100.0,1.4896,24.0,666.0,20.2,30.59,5.0
10,67.92080,0.0,18.10,0.0,0.693,5.683,100.0,1.4254,24.0,666.0,20.2,22.98,5.0
11,51.13580,0.0,18.10,0.0,0.597,5.757,100.0,1.4130,24.0,666.0,20.2,10.11,15.0
12,18.81100,0.0,18.10,0.0,0.597,4.628,100.0,1.5539,24.0,666.0,20.2,34.37,17.9
13,45.74610,0.0,18.10,0.0,0.693,4.519,100.0,1.6582,24.0,666.0,20.2,36.98,7.0
14,73.53410,0.0,18.10,0.0,0.679,5.957,100.0,1.8026,24.0,666.0,20.2,20.62,8.8
15,13.67810,0.0,18.10,0.0,0.740,5.935,87.9,1.8206,24.0,666.0,20.2,34.02,8.4

## 8. WHERE - Mixed Conditionals (AND + OR)
Filter rows next to the river where either the crime rate is low (< 0.1) OR rooms are many (> 7).

In [ ]:
#Pandas
df[(df['river_front'] == 1) & ((df['per_cap_crime'] < 0.1) | (df['num_rooms'] > 7))]

,per_cap_crime,res_zoning_prop,business_prop,river_front,nitric_oxide_conc,num_rooms,units_before_1940,distance_to_employment,distance_to_hwy,prop_tax,pupil_teacher_ratio,perc_lower_status,med_home_value
216,0.04560,0.0,13.89,1.0,0.5500,5.888,56.0,3.1121,5.0,276.0,16.4,13.51,23.3
269,0.09065,20.0,6.96,1.0,0.4640,5.920,61.5,3.9175,3.0,223.0,18.6,13.65,20.7
273,0.22188,20.0,6.96,1.0,0.4640,7.691,51.8,4.3665,3.0,223.0,18.6,6.58,35.2
274,0.05644,40.0,6.41,1.0,0.4470,6.758,32.9,4.0776,4.0,254.0,17.6,3.53,32.4
276,0.10469,40.0,6.41,1.0,0.4470,7.267,49.0,4.7872,4.0,254.0,17.6,6.05,33.2
277,0.06127,40.0,6.41,1.0,0.4470,6.826,27.6,4.8628,4.0,254.0,17.6,4.16,33.1
282,0.06129,20.0,3.33,1.0,0.4429,7.645,49.7,5.2119,5.0,216.0,14.9,3.01,46.0
364,3.47428,0.0,18.10,1.0,0.7180,8.780,82.9,1.9047,24.0,666.0,20.2,5.29,21.9

In [ ]:
#SQL
duckdb.query('''
  SELECT *
  FROM df
  WHERE
      river_front = 1
    AND
      (per_cap_crime < 0.1 OR num_rooms > 7)
''').df()

,per_cap_crime,res_zoning_prop,business_prop,river_front,nitric_oxide_conc,num_rooms,units_before_1940,distance_to_employment,distance_to_hwy,prop_tax,pupil_teacher_ratio,perc_lower_status,med_home_value
0,0.04560,0.0,13.89,1.0,0.5500,5.888,56.0,3.1121,5.0,276.0,16.4,13.51,23.3
1,0.09065,20.0,6.96,1.0,0.4640,5.920,61.5,3.9175,3.0,223.0,18.6,13.65,20.7
2,0.22188,20.0,6.96,1.0,0.4640,7.691,51.8,4.3665,3.0,223.0,18.6,6.58,35.2
3,0.05644,40.0,6.41,1.0,0.4470,6.758,32.9,4.0776,4.0,254.0,17.6,3.53,32.4
4,0.10469,40.0,6.41,1.0,0.4470,7.267,49.0,4.7872,4.0,254.0,17.6,6.05,33.2
5,0.06127,40.0,6.41,1.0,0.4470,6.826,27.6,4.8628,4.0,254.0,17.6,4.16,33.1
6,0.06129,20.0,3.33,1.0,0.4429,7.645,49.7,5.2119,5.0,216.0,14.9,3.01,46.0
7,3.47428,0.0,18.10,1.0,0.7180,8.780,82.9,1.9047,24.0,666.0,20.2,5.29,21.9

## 9. WHERE - BETWEEN
Filter rows where `med_home_value` is BETWEEN 25 and 30 (inclusive).

In [ ]:
#Pandas
df[df['med_home_value'].between(25, 30)]

,per_cap_crime,res_zoning_prop,business_prop,river_front,nitric_oxide_conc,num_rooms,units_before_1940,distance_to_employment,distance_to_hwy,prop_tax,pupil_teacher_ratio,perc_lower_status,med_home_value
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3.0,222.0,18.7,5.21,28.7
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,19.15,27.1
41,0.12744,0.0,6.91,0.0,0.448,6.770,2.9,5.7209,3.0,233.0,17.9,4.84,26.6
42,0.14150,0.0,6.91,0.0,0.448,6.169,6.6,5.7209,3.0,233.0,17.9,5.81,25.3
52,0.05360,21.0,5.64,0.0,0.439,6.511,21.1,6.8147,4.0,243.0,16.8,5.28,25.0
63,0.12650,25.0,5.13,0.0,0.453,6.762,43.4,7.9809,8.0,284.0,19.7,9.50,25.0
80,0.04113,25.0,4.86,0.0,0.426,6.727,33.5,5.4007,4.0,281.0,19.0,5.29,28.0
85,0.05735,0.0,4.49,0.0,0.449,6.630,56.1,4.4377,3.0,247.0,18.5,6.53,26.6
89,0.05302,0.0,3.41,0.0,0.489,7.079,63.1,3.4145,2.0,270.0,17.8,5.70,28.7
93,0.02875,28.0,15.04,0.0,0.464,6.211,28.9,3.6659,4.0,270.0,18.2,6.21,25.0
95,0.12204,0.0,2.89,0.0,0.445,6.625,57.8,3.4952,2.0,276.0,18.0,6.65,28.4
100,0.14866,0.0,8.56,0.0,0.520,6.727,79.9,2.7778,5.0,384.0,20.9,9.42,27.5
101,0.11432,0.0,8.56,0.0,0.520,6.781,71.3,2.8561,5.0,384.0,20.9,7.67,26.5
160,1.27346,0.0,19.58,1.0,0.605,6.250,92.6,1.7984,5.0,403.0,14.7,5.50,27.0
165,2.92400,0.0,19.58,0.0,0.605,6.101,93.0,2.2834,5.0,403.0,14.7,9.81,25.0
175,0.06664,0.0,4.05,0.0,0.510,6.546,33.1,3.1323,5.0,296.0,16.6,5.33,29.4
178,0.06642,0.0,4.05,0.0,0.510,6.860,74.4,2.9153,5.0,296.0,16.6,6.92,29.9
184,0.08308,0.0,2.46,0.0,0.488,5.604,89.8,2.9879,3.0,193.0,17.8,13.98,26.4
185,0.06047,0.0,2.46,0.0,0.488,6.153,68.8,3.2797,3.0,193.0,17.8,13.15,29.6
188,0.12579,45.0,3.44,0.0,0.437,6.556,29.1,4.5667,5.0,398.0,15.2,4.56,29.8
194,0.01439,60.0,2.93,0.0,0.401,6.604,18.8,6.2196,1.0,265.0,15.6,4.38,29.1
213,0.14052,0.0,10.59,0.0,0.489,6.375,32.3,3.9454,4.0,277.0,18.6,9.38,28.1
215,0.19802,0.0,10.59,0.0,0.489,6.182,42.4,3.9454,4.0,277.0,18.6,9.47,25.0
217,0.07013,0.0,13.89,0.0,0.550,6.642,85.1,3.4211,5.0,276.0,16.4,9.69,28.7
220,0.35809,0.0,6.20,1.0,0.507,6.951,88.5,2.8617,8.0,307.0,17.4,9.71,26.7
222,0.62356,0.0,6.20,1.0,0.507,6.879,77.7,3.2721,8.0,307.0,17.4,9.93,27.5
234,0.44791,0.0,6.20,1.0,0.507,6.726,66.5,3.6519,8.0,307.0,17.4,8.05,29.0
236,0.52058,0.0,6.20,1.0,0.507,6.631,76.5,4.1480,8.0,307.0,17.4,9.54,25.1
249,0.19073,22.0,5.86,0.0,0.431,6.718,17.5,7.8265,7.0,330.0,19.1,6.56,26.2
252,0.08221,22.0,5.86,0.0,0.431,6.957,6.8,8.9067,7.0,330.0,19.1,3.53,29.6
271,0.16211,20.0,6.96,0.0,0.464,6.240,16.3,4.4290,3.0,223.0,18.6,6.59,25.2
278,0.07978,40.0,6.41,0.0,0.447,6.482,32.1,4.1403,4.0,254.0,17.6,7.19,29.1
290,0.03502,80.0,4.95,0.0,0.411,6.861,27.9,5.1167,4.0,245.0,19.2,3.33,28.5
292,0.03615,80.0,4.95,0.0,0.411,6.630,23.4,5.1167,4.0,245.0,19.2,4.70,27.9
295,0.12932,0.0,13.92,0.0,0.437,6.678,31.1,5.9604,4.0,289.0,16.0,6.27,28.6
296,0.05372,0.0,13.92,0.0,0.437,6.549,51.0,5.9604,4.0,289.0,16.0,7.39,27.1
299,0.05561,70.0,2.24,0.0,0.400,7.041,10.0,7.8278,5.0,358.0,14.8,4.74,29.0
302,0.09266,34.0,6.09,0.0,0.433,6.495,18.4,5.4917,7.0,329.0,16.1,8.67,26.4
305,0.05479,33.0,2.18,0.0,0.472,6.616,58.1,3.3700,7.0,222.0,18.4,8.93,28.4
307,0.04932,33.0,2.18,0.0,0.472,6.849,70.3,3.1827,7.0,222.0,18.4,7.53,28.2
324,0.34109,0.0,7.38,0.0,0.493,6.415,40.1,4.7211,5.0,287.0,19.6,6.12,25.0
349,0.02899,40.0,1.25,0.0,0.429,6.939,34.5,8.7921,1.0,335.0,19.7,5.89,26.6
360,4.54192,0.0,18.10,0.0,0.770,6.398,88.0,2.5182,24.0,666.0,20.2,7.79,25.0
365,4.55587,0.0,18.10,0.0,0.718,3.561,87.9,1.6132,24.0,666.0,20.2,7.12,27.5
407,11.95110,0.0,18.10,0.0,0.659,5.608,100.0,1.2852,24.0,666.0,20.2,12.13,27.9
409,14.43830,0.0,18.10,0.0,0.597,6.852,100.0,1.4655,24.0,666.0,20.2,19.78,27.5
473,4.64689,0.0,18.10,0.0,0.614,6.980,67.6,2.5329,24.0,666.0,20.2,11.66,29.8
482,5.73116,0.0,18.10,0.0,0.532,7.061,77.0,3.4106,24.0,666.0,20.2,7.01,25.0

In [ ]:
#SQL
duckdb.query('''
  SELECT *
  FROM df
    WHERE
        med_home_value BETWEEN 25 AND 30
''').df()

,per_cap_crime,res_zoning_prop,business_prop,river_front,nitric_oxide_conc,num_rooms,units_before_1940,distance_to_employment,distance_to_hwy,prop_tax,pupil_teacher_ratio,perc_lower_status,med_home_value
0,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3.0,222.0,18.7,5.21,28.7
1,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,19.15,27.1
2,0.12744,0.0,6.91,0.0,0.448,6.770,2.9,5.7209,3.0,233.0,17.9,4.84,26.6
3,0.14150,0.0,6.91,0.0,0.448,6.169,6.6,5.7209,3.0,233.0,17.9,5.81,25.3
4,0.05360,21.0,5.64,0.0,0.439,6.511,21.1,6.8147,4.0,243.0,16.8,5.28,25.0
5,0.12650,25.0,5.13,0.0,0.453,6.762,43.4,7.9809,8.0,284.0,19.7,9.50,25.0
6,0.04113,25.0,4.86,0.0,0.426,6.727,33.5,5.4007,4.0,281.0,19.0,5.29,28.0
7,0.05735,0.0,4.49,0.0,0.449,6.630,56.1,4.4377,3.0,247.0,18.5,6.53,26.6
8,0.05302,0.0,3.41,0.0,0.489,7.079,63.1,3.4145,2.0,270.0,17.8,5.70,28.7
9,0.02875,28.0,15.04,0.0,0.464,6.211,28.9,3.6659,4.0,270.0,18.2,6.21,25.0
10,0.12204,0.0,2.89,0.0,0.445,6.625,57.8,3.4952,2.0,276.0,18.0,6.65,28.4
11,0.14866,0.0,8.56,0.0,0.520,6.727,79.9,2.7778,5.0,384.0,20.9,9.42,27.5
12,0.11432,0.0,8.56,0.0,0.520,6.781,71.3,2.8561,5.0,384.0,20.9,7.67,26.5
13,1.27346,0.0,19.58,1.0,0.605,6.250,92.6,1.7984,5.0,403.0,14.7,5.50,27.0
14,2.92400,0.0,19.58,0.0,0.605,6.101,93.0,2.2834,5.0,403.0,14.7,9.81,25.0
15,0.06664,0.0,4.05,0.0,0.510,6.546,33.1,3.1323,5.0,296.0,16.6,5.33,29.4
16,0.06642,0.0,4.05,0.0,0.510,6.860,74.4,2.9153,5.0,296.0,16.6,6.92,29.9
17,0.08308,0.0,2.46,0.0,0.488,5.604,89.8,2.9879,3.0,193.0,17.8,13.98,26.4
18,0.06047,0.0,2.46,0.0,0.488,6.153,68.8,3.2797,3.0,193.0,17.8,13.15,29.6
19,0.12579,45.0,3.44,0.0,0.437,6.556,29.1,4.5667,5.0,398.0,15.2,4.56,29.8
20,0.01439,60.0,2.93,0.0,0.401,6.604,18.8,6.2196,1.0,265.0,15.6,4.38,29.1
21,0.14052,0.0,10.59,0.0,0.489,6.375,32.3,3.9454,4.0,277.0,18.6,9.38,28.1
22,0.19802,0.0,10.59,0.0,0.489,6.182,42.4,3.9454,4.0,277.0,18.6,9.47,25.0
23,0.07013,0.0,13.89,0.0,0.550,6.642,85.1,3.4211,5.0,276.0,16.4,9.69,28.7
24,0.35809,0.0,6.20,1.0,0.507,6.951,88.5,2.8617,8.0,307.0,17.4,9.71,26.7
25,0.62356,0.0,6.20,1.0,0.507,6.879,77.7,3.2721,8.0,307.0,17.4,9.93,27.5
26,0.44791,0.0,6.20,1.0,0.507,6.726,66.5,3.6519,8.0,307.0,17.4,8.05,29.0
27,0.52058,0.0,6.20,1.0,0.507,6.631,76.5,4.1480,8.0,307.0,17.4,9.54,25.1
28,0.19073,22.0,5.86,0.0,0.431,6.718,17.5,7.8265,7.0,330.0,19.1,6.56,26.2
29,0.08221,22.0,5.86,0.0,0.431,6.957,6.8,8.9067,7.0,330.0,19.1,3.53,29.6
30,0.16211,20.0,6.96,0.0,0.464,6.240,16.3,4.4290,3.0,223.0,18.6,6.59,25.2
31,0.07978,40.0,6.41,0.0,0.447,6.482,32.1,4.1403,4.0,254.0,17.6,7.19,29.1
32,0.03502,80.0,4.95,0.0,0.411,6.861,27.9,5.1167,4.0,245.0,19.2,3.33,28.5
33,0.03615,80.0,4.95,0.0,0.411,6.630,23.4,5.1167,4.0,245.0,19.2,4.70,27.9
34,0.12932,0.0,13.92,0.0,0.437,6.678,31.1,5.9604,4.0,289.0,16.0,6.27,28.6
35,0.05372,0.0,13.92,0.0,0.437,6.549,51.0,5.9604,4.0,289.0,16.0,7.39,27.1
36,0.05561,70.0,2.24,0.0,0.400,7.041,10.0,7.8278,5.0,358.0,14.8,4.74,29.0
37,0.09266,34.0,6.09,0.0,0.433,6.495,18.4,5.4917,7.0,329.0,16.1,8.67,26.4
38,0.05479,33.0,2.18,0.0,0.472,6.616,58.1,3.3700,7.0,222.0,18.4,8.93,28.4
39,0.04932,33.0,2.18,0.0,0.472,6.849,70.3,3.1827,7.0,222.0,18.4,7.53,28.2
40,0.34109,0.0,7.38,0.0,0.493,6.415,40.1,4.7211,5.0,287.0,19.6,6.12,25.0
41,0.02899,40.0,1.25,0.0,0.429,6.939,34.5,8.7921,1.0,335.0,19.7,5.89,26.6
42,4.54192,0.0,18.10,0.0,0.770,6.398,88.0,2.5182,24.0,666.0,20.2,7.79,25.0
43,4.55587,0.0,18.10,0.0,0.718,3.561,87.9,1.6132,24.0,666.0,20.2,7.12,27.5
44,11.95110,0.0,18.10,0.0,0.659,5.608,100.0,1.2852,24.0,666.0,20.2,12.13,27.9
45,14.43830,0.0,18.10,0.0,0.597,6.852,100.0,1.4655,24.0,666.0,20.2,19.78,27.5
46,4.64689,0.0,18.10,0.0,0.614,6.980,67.6,2.5329,24.0,666.0,20.2,11.66,29.8
47,5.73116,0.0,18.10,0.0,0.532,7.061,77.0,3.4106,24.0,666.0,20.2,7.01,25.0

## 10. LIMIT
Select the first 5 rows of the dataset.

In [ ]:
#Pandas
df.head(5)

,per_cap_crime,res_zoning_prop,business_prop,river_front,nitric_oxide_conc,num_rooms,units_before_1940,distance_to_employment,distance_to_hwy,prop_tax,pupil_teacher_ratio,perc_lower_status,med_home_value
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,5.33,36.2

In [ ]:
#SQL
duckdb.query('''
  SELECT *
  FROM df
  LIMIT 5
''').df()

,per_cap_crime,res_zoning_prop,business_prop,river_front,nitric_oxide_conc,num_rooms,units_before_1940,distance_to_employment,distance_to_hwy,prop_tax,pupil_teacher_ratio,perc_lower_status,med_home_value
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,5.33,36.2

## 11. WHERE with LIMIT
Select the first 3 rows where `distance_to_hwy` is 24.

In [ ]:
#Pandas
df[df['distance_to_hwy'] == 24].head(3)

,per_cap_crime,res_zoning_prop,business_prop,river_front,nitric_oxide_conc,num_rooms,units_before_1940,distance_to_employment,distance_to_hwy,prop_tax,pupil_teacher_ratio,perc_lower_status,med_home_value
356,8.98296,0.0,18.1,1.0,0.77,6.212,97.4,2.1222,24.0,666.0,20.2,17.60,17.8
357,3.84970,0.0,18.1,1.0,0.77,6.395,91.0,2.5052,24.0,666.0,20.2,13.27,21.7
358,5.20177,0.0,18.1,1.0,0.77,6.127,83.4,2.7227,24.0,666.0,20.2,11.48,22.7

In [ ]:
#SQL
duckdb.query('''
  SELECT *
  FROM df
  WHERE distance_to_hwy = 24
--  LIMIT 3
''').df().head(3)

,per_cap_crime,res_zoning_prop,business_prop,river_front,nitric_oxide_conc,num_rooms,units_before_1940,distance_to_employment,distance_to_hwy,prop_tax,pupil_teacher_ratio,perc_lower_status,med_home_value
0,8.98296,0.0,18.1,1.0,0.77,6.212,97.4,2.1222,24.0,666.0,20.2,17.60,17.8
1,3.84970,0.0,18.1,1.0,0.77,6.395,91.0,2.5052,24.0,666.0,20.2,13.27,21.7
2,5.20177,0.0,18.1,1.0,0.77,6.127,83.4,2.7227,24.0,666.0,20.2,11.48,22.7

## 12. GROUP BY - COUNT
Count the number of properties grouped by their accessibility index to highways (`distance_to_hwy`).

In [ ]:
#Pandas
df.groupby('distance_to_hwy').size().reset_index(name='count')

   distance_to_hwy  count
0              1.0     19
1              2.0     24
2              3.0     37
3              4.0    108
4              5.0    109
5              6.0     26
6              7.0     17
7              8.0     23
8             24.0    127

In [ ]:
#SQL
duckdb.query('''
  SELECT distance_to_hwy, COUNT(*) as count
  FROM df
  GROUP BY distance_to_hwy --all
''').df()

   distance_to_hwy  count
0              4.0    108
1             24.0    127
2              1.0     19
3              2.0     24
4              3.0     37
5              5.0    109
6              8.0     23
7              6.0     26
8              7.0     17

## 13. GROUP BY - AVG
Find the average home value (`med_home_value`) grouped by whether they are on the river front (`river_front`).

In [ ]:
#Pandas
df.groupby('river_front')['med_home_value'].mean().reset_index(name='avg_value')

   river_front  avg_value
0          0.0  21.488503
1          1.0  23.979310

In [ ]:
#SQL
duckdb.query('''
  SELECT river_front, AVG(med_home_value) as avg_value
  FROM df
  GROUP BY river_front
''').df()

   river_front  avg_value
0          0.0  21.488503
1          1.0  23.979310

## 14. GROUP BY - SUM
Find the total proportion of non-retail business acres (`business_prop`) grouped by highway accessibility.

In [ ]:
#Pandas
df.groupby('distance_to_hwy')['business_prop'].sum().reset_index(name='total_business_prop')

   distance_to_hwy  total_business_prop
0              1.0               100.11
1              2.0               231.14
2              3.0               165.46
3              4.0              1178.99
4              5.0              1036.12
5              6.0               213.15
6              7.0                85.59
7              8.0               136.18
8             24.0              2298.70

In [ ]:
#SQL
duckdb.query('''
  SELECT distance_to_hwy, SUM(business_prop) as total_business_prop
  FROM df
  GROUP BY distance_to_hwy
''').df()

   distance_to_hwy  total_business_prop
0              1.0               100.11
1              2.0               231.14
2              3.0               165.46
3              5.0              1036.12
4              8.0               136.18
5              6.0               213.15
6              7.0                85.59
7              4.0              1178.99
8             24.0              2298.70

## 15. GROUP BY - MIN & MAX
Find the minimum and maximum room counts grouped by highway accessibility.

In [ ]:
#Pandas
df.groupby('distance_to_hwy')['num_rooms'].agg(min_rooms='min', max_rooms='max').reset_index()

   distance_to_hwy  min_rooms  max_rooms
0              1.0      5.706      7.241
1              2.0      5.613      8.069
2              3.0      5.399      7.765
3              4.0      4.973      7.853
4              5.0      4.903      8.398
5              6.0      5.390      6.897
6              7.0      5.593      8.259
7              8.0      5.741      8.337
8             24.0      3.561      8.780

In [ ]:
#SQL
duckdb.query('''
  SELECT
    distance_to_hwy,
    MIN(num_rooms) as min_rooms,
    MAX(num_rooms) as max_rooms
  FROM df
  GROUP BY distance_to_hwy
''').df()

   distance_to_hwy  min_rooms  max_rooms
0              4.0      4.973      7.853
1             24.0      3.561      8.780
2              1.0      5.706      7.241
3              2.0      5.613      8.069
4              3.0      5.399      7.765
5              5.0      4.903      8.398
6              8.0      5.741      8.337
7              6.0      5.390      6.897
8              7.0      5.593      8.259

## 16. GROUP BY - Multiple Columns
Group by both `river_front` and `distance_to_hwy` to get the average `nitric_oxide_conc`.

In [ ]:
#Pandas
df.groupby(['river_front', 'distance_to_hwy'])['nitric_oxide_conc'].mean().reset_index(name='avg_nox')

    river_front  distance_to_hwy   avg_nox
0           0.0              1.0  0.466147
1           0.0              2.0  0.484917
2           0.0              3.0  0.450746
3           0.0              4.0  0.508501
4           0.0              5.0  0.558277
5           0.0              6.0  0.514846
6           0.0              7.0  0.441000
7           0.0              8.0  0.487833
8           0.0             24.0  0.670238
9           1.0              3.0  0.464000
10          1.0              4.0  0.473250
11          1.0              5.0  0.686878
12          1.0              8.0  0.507000
13          1.0             24.0  0.759600

In [ ]:
#SQL
duckdb.query('''
  SELECT river_front, distance_to_hwy, AVG(nitric_oxide_conc) as avg_nox
  FROM df
  GROUP BY river_front, distance_to_hwy
  --GROUP BY-- specific to duckdb
''').df()

    river_front  distance_to_hwy   avg_nox
0           0.0              4.0  0.508501
1           1.0              4.0  0.473250
2           1.0             24.0  0.759600
3           0.0             24.0  0.670238
4           0.0              1.0  0.466147
5           0.0              2.0  0.484917
6           0.0              3.0  0.450746
7           0.0              5.0  0.558277
8           0.0              8.0  0.487833
9           0.0              6.0  0.514846
10          1.0              5.0  0.686878
11          1.0              8.0  0.507000
12          0.0              7.0  0.441000
13          1.0              3.0  0.464000

## 17. HAVING - Filter Group COUNT
Group by `distance_to_hwy` and only return groups that have more than 30 properties.

In [ ]:
#Pandas
grouped = df.groupby('distance_to_hwy').size().reset_index(name='count')
grouped[grouped['count'] > 30]

   distance_to_hwy  count
2              3.0     37
3              4.0    108
4              5.0    109
8             24.0    127

In [ ]:
#SQL
duckdb.query('''
  SELECT distance_to_hwy, COUNT(*) as count
  FROM df
  GROUP BY distance_to_hwy
  HAVING COUNT(*) > 30 --WHERE clause for a GROUP
''').df()

   distance_to_hwy  count
0              3.0     37
1              5.0    109
2              4.0    108
3             24.0    127

## 18. HAVING - Filter Group AVG
Group by `distance_to_hwy` and only return groups where the average `med_home_value` is greater than 25.

In [ ]:
#Pandas
grouped = df.groupby('distance_to_hwy')['med_home_value'].mean().reset_index(name='avg_value')
grouped[grouped['avg_value'] > 25]

   distance_to_hwy  avg_value
1              2.0  26.833333
2              3.0  27.332432
6              7.0  27.105882
7              8.0  29.504348

In [ ]:
#SQL
duckdb.query('''
  SELECT distance_to_hwy, AVG(med_home_value) as avg_value
  FROM df
  GROUP BY distance_to_hwy
  HAVING AVG(med_home_value) > 25
''').df()

   distance_to_hwy  avg_value
0              2.0  26.833333
1              3.0  27.332432
2              8.0  29.504348
3              7.0  27.105882

## 19. HAVING - Filter Group MIN
Group by `river_front` and only return groups where the absolute cheapest home (`MIN(med_home_value)`) is greater than 6.

In [ ]:
#Pandas
grouped = df.groupby('river_front')['med_home_value'].min().reset_index(name='min_value')
grouped[grouped['min_value'] > 6]

   river_front  min_value
1          1.0       13.4

In [ ]:
#SQL
duckdb.query('''
  SELECT river_front, MIN(med_home_value) as min_value
  FROM df
  GROUP BY river_front
  HAVING MIN(med_home_value) > 6
''').df()

   river_front  min_value
0          1.0       13.4

## 20. Complex Combination (SELECT, WHERE, GROUP BY, HAVING, LIMIT)
Select `distance_to_hwy` and average `med_home_value` for properties built before 1940 (`units_before_1940` > 80), group by highway distance, keep groups with an average value > 15, and limit to the top 3 results.

In [ ]:
#Pandas
filtered_df = df[df['units_before_1940'] > 80]
grouped = filtered_df.groupby('distance_to_hwy')['med_home_value'].mean().reset_index(name='avg_value')
result = grouped[grouped['avg_value'] > 15].head(3)
result

   distance_to_hwy  avg_value
0              1.0  19.266667
1              2.0  19.657143
2              3.0  27.933333

In [ ]:
#SQL
duckdb.query('''
  SELECT distance_to_hwy, AVG(med_home_value) as avg_value
  FROM df
  WHERE units_before_1940 > 80
  GROUP BY distance_to_hwy
  HAVING AVG(med_home_value) > 15
  LIMIT 3
''').df()

   distance_to_hwy  avg_value
0              4.0  16.726667
1              5.0  22.521569
2              3.0  27.933333