<a href="https://colab.research.google.com/github/stephanie465337/Data-Science-Portfolio-C21/blob/main/NotebookLM/Module%203/2f_sqlite3_chinook_db.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Using a DB in sqlite3

## SQL in sqlite3

In [ ]:
import sqlite3 as db
import pandas as pd

In [ ]:
%%capture
%%bash
apt-get update
apt-get install -y sqlite3

In [ ]:
#Use as needed
!sqlite3 --help

Usage: sqlite3 [OPTIONS] FILENAME [SQL]
FILENAME is the name of an SQLite database. A new database is created
if the file does not previously exist.
OPTIONS include:
   -A ARGS...           run ".archive ARGS" and exit
   -append              append the database to the end of the file
   -ascii               set output mode to 'ascii'
   -bail                stop after hitting an error
   -batch               force batch I/O
   -box                 set output mode to 'box'
   -column              set output mode to 'column'
   -cmd COMMAND         run "COMMAND" before reading stdin
   -csv                 set output mode to 'csv'
   -deserialize         open the database using sqlite3_deserialize()
   -echo                print commands before execution
   -init FILENAME       read/process named file
   -[no]header          turn headers on or off
   -help                show this message
   -html                set output mode to HTML
   -interactive         force interactive I/O
   -json                set output mode to 'json'
   -line                set output mode to 'line'
   -list                set output mode to 'list'
   -lookaside SIZE N    use N entries of SZ bytes for lookaside memory
   -markdown            set output mode to 'markdown'
   -maxsize N           maximum size for a --deserialize database
   -memtrace            trace all memory allocations and deallocations
   -mmap N              default mmap size set to N
   -newline SEP         set output row separator. Default: '\n'
   -nofollow            refuse to open symbolic links to database files
   -nonce STRING        set the safe-mode escape nonce
   -nullvalue TEXT      set text string for NULL values. Default ''
   -pagecache SIZE N    use N slots of SZ bytes each for page cache memory
   -quote               set output mode to 'quote'
   -readonly            open the database read-only
   -safe                enable safe-mode
   -separator SEP       set output column separator. Default: '|'
   -stats               print memory stats before each finalize
   -table               set output mode to 'table'
   -tabs                set output mode to 'tabs'
   -version             show SQLite version
   -vfs NAME            use NAME as the default VFS
   -zip                 open the file as a ZIP Archive

In [ ]:
!sqlite3 --version

3.37.2 2022-01-06 13:25:41 872ba256cbf61d9290b571c0e6d82a20c224ca3ad82971edc46b29818d5dalt1

## Sample database

The [Chinook sample](https://www.sqlitetutorial.net/sqlite-sample-database/)

- Zip file of [sqlite DB](https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip)

- [ER diagram](https://www.sqlitetutorial.net/wp-content/uploads/2018/03/sqlite-sample-database-diagram-color.pdf)

- [ER symbols/meanings](https://d2slcw3kip6qmk.cloudfront.net/marketing/pages/chart/erd-symbols/ERD-Notation.PNG)

- [Draw IO](https://app.diagrams.net/) for creating ER diagrams, flowcharts, etc.

In [ ]:
%%bash
[ -f chinook.zip ] ||
  curl -s -O https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
unzip -l chinook.zip

Archive:  chinook.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
   884736  2015-11-29 10:53   chinook.db
---------                     -------
   884736                     1 file

In [ ]:
!rm -f chinook.db

In [ ]:
!unzip -u chinook.zip

Archive:  chinook.zip
  inflating: chinook.db

In [ ]:
!ls -la

total 1180
drwxr-xr-x 1 root root   4096 Jul  2 14:14 .
drwxr-xr-x 1 root root   4096 Jul  2 13:49 ..
-rw-r--r-- 1 root root 884736 Nov 29  2015 chinook.db
-rw-r--r-- 1 root root 305596 Jul  2 14:14 chinook.zip
drwxr-xr-x 4 root root   4096 Jun  4 13:32 .config
drwxr-xr-x 1 root root   4096 Jun  4 13:32 sample_data

## Query using Python

### Without using a context manager

In [ ]:
#Connect to a sqlite database and load a result set into a data frame
db_con = db.connect("chinook.db")

In [ ]:
#Select the first 10 entries from the employees table
query = '''
  SELECT *
  FROM employees
  LIMIT 10
'''

employees = pd.read_sql_query(query, db_con)
employees

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,1,Adams,Andrew,General Manager,NaN,1962-02-18 00:00:00,2002-08-14 00:00:00,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,1958-12-08 00:00:00,2002-05-01 00:00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29 00:00:00,2002-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03 00:00:00,2003-10-17 00:00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com
5,6,Mitchell,Michael,IT Manager,1.0,1973-07-01 00:00:00,2003-10-17 00:00:00,5827 Bowness Road NW,Calgary,AB,Canada,T3B 0C5,+1 (403) 246-9887,+1 (403) 246-9899,michael@chinookcorp.com
6,7,King,Robert,IT Staff,6.0,1970-05-29 00:00:00,2004-01-02 00:00:00,590 Columbia Boulevard West,Lethbridge,AB,Canada,T1K 5N8,+1 (403) 456-9986,+1 (403) 456-8485,robert@chinookcorp.com
7,8,Callahan,Laura,IT Staff,6.0,1968-01-09 00:00:00,2004-03-04 00:00:00,923 7 ST NW,Lethbridge,AB,Canada,T1H 1Y8,+1 (403) 467-3351,+1 (403) 467-8772,laura@chinookcorp.com

In [ ]:
employees.shape

(8, 15)

In [ ]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeId  8 non-null      int64
 1   LastName    8 non-null      object
 2   FirstName   8 non-null      object
 3   Title       8 non-null      object
 4   ReportsTo   7 non-null      float64
 5   BirthDate   8 non-null      object
 6   HireDate    8 non-null      object
 7   Address     8 non-null      object
 8   City        8 non-null      object
 9   State       8 non-null      object
 10  Country     8 non-null      object
 11  PostalCode  8 non-null      object
 12  Phone       8 non-null      object
 13  Fax         8 non-null      object
 14  Email       8 non-null      object
dtypes: float64(1), int64(1), object(13)
memory usage: 1.1+ KB

In [ ]:
#Explicitly close the connection
db_con.close()

### Using a context manager

List of all table in the database using SQL

In [ ]:
query = '''
  SELECT
    name
  FROM
    sqlite_master
  WHERE
    type='table' AND
    name not like "sqlite_%"
;
'''

print(query)

  SELECT
    name
  FROM
    sqlite_master
  WHERE
    type='table' AND
    name not like "sqlite_%"
;

In [ ]:
with db.connect("chinook.db") as db_con:
  tables = pd.read_sql_query(query, db_con)

tables

              name
0           albums
1          artists
2        customers
3        employees
4           genres
5         invoices
6    invoice_items
7      media_types
8        playlists
9   playlist_track
10          tracks

In [ ]:
#Select the first 10 entries from the employees table
query = '''
  SELECT *
  FROM employees
 employees
  LIMIT 10
'''

print(query)

  SELECT *
  FROM employees
 employees
  LIMIT 10

In [ ]:
#Connect to a sqlite database, load a result set into a data frame, and close the connection
with db.connect("chinook.db") as db_con:
  employees = pd.read_sql_query( query , db_con)

employees

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,1,Adams,Andrew,General Manager,NaN,1962-02-18 00:00:00,2002-08-14 00:00:00,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,1958-12-08 00:00:00,2002-05-01 00:00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29 00:00:00,2002-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03 00:00:00,2003-10-17 00:00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com
5,6,Mitchell,Michael,IT Manager,1.0,1973-07-01 00:00:00,2003-10-17 00:00:00,5827 Bowness Road NW,Calgary,AB,Canada,T3B 0C5,+1 (403) 246-9887,+1 (403) 246-9899,michael@chinookcorp.com
6,7,King,Robert,IT Staff,6.0,1970-05-29 00:00:00,2004-01-02 00:00:00,590 Columbia Boulevard West,Lethbridge,AB,Canada,T1K 5N8,+1 (403) 456-9986,+1 (403) 456-8485,robert@chinookcorp.com
7,8,Callahan,Laura,IT Staff,6.0,1968-01-09 00:00:00,2004-03-04 00:00:00,923 7 ST NW,Lethbridge,AB,Canada,T1H 1Y8,+1 (403) 467-3351,+1 (403) 467-8772,laura@chinookcorp.com

In [ ]:
employees.shape

(8, 15)

In [ ]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeId  8 non-null      int64
 1   LastName    8 non-null      object
 2   FirstName   8 non-null      object
 3   Title       8 non-null      object
 4   ReportsTo   7 non-null      float64
 5   BirthDate   8 non-null      object
 6   HireDate    8 non-null      object
 7   Address     8 non-null      object
 8   City        8 non-null      object
 9   State       8 non-null      object
 10  Country     8 non-null      object
 11  PostalCode  8 non-null      object
 12  Phone       8 non-null      object
 13  Fax         8 non-null      object
 14  Email       8 non-null      object
dtypes: float64(1), int64(1), object(13)
memory usage: 1.1+ KB

In [ ]:
query

'\n  SELECT *\n  FROM employees\n employees\n  LIMIT 10\n'

In [ ]:
pd.read_sql_query( query , db_con)

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,1,Adams,Andrew,General Manager,NaN,1962-02-18 00:00:00,2002-08-14 00:00:00,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,1958-12-08 00:00:00,2002-05-01 00:00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29 00:00:00,2002-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03 00:00:00,2003-10-17 00:00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com
5,6,Mitchell,Michael,IT Manager,1.0,1973-07-01 00:00:00,2003-10-17 00:00:00,5827 Bowness Road NW,Calgary,AB,Canada,T3B 0C5,+1 (403) 246-9887,+1 (403) 246-9899,michael@chinookcorp.com
6,7,King,Robert,IT Staff,6.0,1970-05-29 00:00:00,2004-01-02 00:00:00,590 Columbia Boulevard West,Lethbridge,AB,Canada,T1K 5N8,+1 (403) 456-9986,+1 (403) 456-8485,robert@chinookcorp.com
7,8,Callahan,Laura,IT Staff,6.0,1968-01-09 00:00:00,2004-03-04 00:00:00,923 7 ST NW,Lethbridge,AB,Canada,T1H 1Y8,+1 (403) 467-3351,+1 (403) 467-8772,laura@chinookcorp.com

In [ ]:
db_con.close()

In [ ]:
pd.read_sql_query( query , db_con)

ProgrammingError: Cannot operate on a closed database.

## Query using SQLite3

Using Jupyter magics

In [ ]:
#Get a list of the tables in the database
%%script sqlite3 --column --header chinook.db
.tables

albums          employees       invoices        playlists
artists         genres          media_types     tracks
customers       invoice_items   playlist_track

In [ ]:
#Show the schema for the entire database
%%script sqlite3 --column --header chinook.db
.schema

CREATE TABLE IF NOT EXISTS "albums"
(
    [AlbumId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    [Title] NVARCHAR(160)  NOT NULL,
    [ArtistId] INTEGER  NOT NULL,
    FOREIGN KEY ([ArtistId]) REFERENCES "artists" ([ArtistId])
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "artists"
(
    [ArtistId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    [Name] NVARCHAR(120)
);
CREATE TABLE IF NOT EXISTS "customers"
(
    [CustomerId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    [FirstName] NVARCHAR(40)  NOT NULL,
    [LastName] NVARCHAR(20)  NOT NULL,
    [Company] NVARCHAR(80),
    [Address] NVARCHAR(70),
    [City] NVARCHAR(40),
    [State] NVARCHAR(40),
    [Country] NVARCHAR(40),
    [PostalCode] NVARCHAR(10),
    [Phone] NVARCHAR(24),
    [Fax] NVARCHAR(24),
    [Email] NVARCHAR(60)  NOT NULL,
    [SupportRepId] INTEGER,
    FOREIGN KEY ([SupportRepId]) REFERENCES "employees" ([EmployeeId])
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "employees"
(
    [EmployeeId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    [LastName] NVARCHAR(20)  NOT NULL,
    [FirstName] NVARCHAR(20)  NOT NULL,
    [Title] NVARCHAR(30),
    [ReportsTo] INTEGER,
    [BirthDate] DATETIME,
    [HireDate] DATETIME,
    [Address] NVARCHAR(70),
    [City] NVARCHAR(40),
    [State] NVARCHAR(40),
    [Country] NVARCHAR(40),
    [PostalCode] NVARCHAR(10),
    [Phone] NVARCHAR(24),
    [Fax] NVARCHAR(24),
    [Email] NVARCHAR(60),
    FOREIGN KEY ([ReportsTo]) REFERENCES "employees" ([EmployeeId])
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "genres"
(
    [GenreId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    [Name] NVARCHAR(120)
);
CREATE TABLE IF NOT EXISTS "invoices"
(
    [InvoiceId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    [CustomerId] INTEGER  NOT NULL,
    [InvoiceDate] DATETIME  NOT NULL,
    [BillingAddress] NVARCHAR(70),
    [BillingCity] NVARCHAR(40),
    [BillingState] NVARCHAR(40),
    [BillingCountry] NVARCHAR(40),
    [BillingPostalCode] NVARCHAR(10),
    [Total] NUMERIC(10,2)  NOT NULL,
    FOREIGN KEY ([CustomerId]) REFERENCES "customers" ([CustomerId])
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "invoice_items"
(
    [InvoiceLineId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    [InvoiceId] INTEGER  NOT NULL,
    [TrackId] INTEGER  NOT NULL,
    [UnitPrice] NUMERIC(10,2)  NOT NULL,
    [Quantity] INTEGER  NOT NULL,
    FOREIGN KEY ([InvoiceId]) REFERENCES "invoices" ([InvoiceId])
		ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY ([TrackId]) REFERENCES "tracks" ([TrackId])
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "media_types"
(
    [MediaTypeId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    [Name] NVARCHAR(120)
);
CREATE TABLE IF NOT EXISTS "playlists"
(
    [PlaylistId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    [Name] NVARCHAR(120)
);
CREATE TABLE IF NOT EXISTS "playlist_track"
(
    [PlaylistId] INTEGER  NOT NULL,
    [TrackId] INTEGER  NOT NULL,
    CONSTRAINT [PK_PlaylistTrack] PRIMARY KEY  ([PlaylistId], [TrackId]),
    FOREIGN KEY ([PlaylistId]) REFERENCES "playlists" ([PlaylistId])
		ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY ([TrackId]) REFERENCES "tracks" ([TrackId])
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "tracks"
(
    [TrackId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    [Name] NVARCHAR(200)  NOT NULL,
    [AlbumId] INTEGER,
    [MediaTypeId] INTEGER  NOT NULL,
    [GenreId] INTEGER,
    [Composer] NVARCHAR(220),
    [Milliseconds] INTEGER  NOT NULL,
    [Bytes] INTEGER,
    [UnitPrice] NUMERIC(10,2)  NOT NULL,
    FOREIGN KEY ([AlbumId]) REFERENCES "albums" ([AlbumId])
		ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY ([GenreId]) REFERENCES "genres" ([GenreId])
		ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY ([MediaTypeId]) REFERENCES "media_types" ([MediaTypeId])
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE INDEX [IFK_AlbumArtistId] ON "albums" ([ArtistId]);
CREATE INDEX [IFK_CustomerSupportRepId] ON "customers" ([SupportRepId]);
CREATE INDEX [IFK_EmployeeReportsTo] ON "employees" ([ReportsTo]);
CREATE INDEX [IFK_InvoiceCustomerId] ON "invoices" ([CustomerId]);
CREATE INDEX [IFK_InvoiceLineInvoiceId] ON "invoice_items" ([InvoiceId]);
CREATE INDEX [IFK_InvoiceLineTrackId] ON "invoice_items" ([TrackId]);
CREATE INDEX [IFK_PlaylistTrackTrackId] ON "playlist_track" ([TrackId]);
CREATE INDEX [IFK_TrackAlbumId] ON "tracks" ([AlbumId]);
CREATE INDEX [IFK_TrackGenreId] ON "tracks" ([GenreId]);
CREATE INDEX [IFK_TrackMediaTypeId] ON "tracks" ([MediaTypeId]);
CREATE TABLE sqlite_stat1(tbl,idx,stat);

In [ ]:
#Select the first 10 entries from the employees table
%%script sqlite3 --column --header chinook.db
SELECT *
FROM employees
LIMIT 10

EmployeeId  LastName  FirstName  Title                ReportsTo  BirthDate            HireDate             Address                      City        State  Country  PostalCode  Phone              Fax                Email
----------  --------  ---------  -------------------  ---------  -------------------  -------------------  ---------------------------  ----------  -----  -------  ----------  -----------------  -----------------  ------------------------
1           Adams     Andrew     General Manager                 1962-02-18 00:00:00  2002-08-14 00:00:00  11120 Jasper Ave NW          Edmonton    AB     Canada   T5K 2N1     +1 (780) 428-9482  +1 (780) 428-3457  andrew@chinookcorp.com
2           Edwards   Nancy      Sales Manager        1          1958-12-08 00:00:00  2002-05-01 00:00:00  825 8 Ave SW                 Calgary     AB     Canada   T2P 2T3     +1 (403) 262-3443  +1 (403) 262-3322  nancy@chinookcorp.com
3           Peacock   Jane       Sales Support Agent  2          1973-08-29 00:00:00  2002-04-01 00:00:00  1111 6 Ave SW                Calgary     AB     Canada   T2P 5M5     +1 (403) 262-3443  +1 (403) 262-6712  jane@chinookcorp.com
4           Park      Margaret   Sales Support Agent  2          1947-09-19 00:00:00  2003-05-03 00:00:00  683 10 Street SW             Calgary     AB     Canada   T2P 5G3     +1 (403) 263-4423  +1 (403) 263-4289  margaret@chinookcorp.com
5           Johnson   Steve      Sales Support Agent  2          1965-03-03 00:00:00  2003-10-17 00:00:00  7727B 41 Ave                 Calgary     AB     Canada   T3B 1Y7     1 (780) 836-9987   1 (780) 836-9543   steve@chinookcorp.com
6           Mitchell  Michael    IT Manager           1          1973-07-01 00:00:00  2003-10-17 00:00:00  5827 Bowness Road NW         Calgary     AB     Canada   T3B 0C5     +1 (403) 246-9887  +1 (403) 246-9899  michael@chinookcorp.com
7           King      Robert     IT Staff             6          1970-05-29 00:00:00  2004-01-02 00:00:00  590 Columbia Boulevard West  Lethbridge  AB     Canada   T1K 5N8     +1 (403) 456-9986  +1 (403) 456-8485  robert@chinookcorp.com
8           Callahan  Laura      IT Staff             6          1968-01-09 00:00:00  2004-03-04 00:00:00  923 7 ST NW                  Lethbridge  AB     Canada   T1H 1Y8     +1 (403) 467-3351  +1 (403) 467-8772  laura@chinookcorp.com

In [ ]:
#Count the number of unique albums
%%script sqlite3 --column --header chinook.db
SELECT count(distinct AlbumID)
FROM tracks

count(distinct AlbumID)
-----------------------
347

In [ ]:
#Select the first 10 entries from the albums table
%%script sqlite3 --column --header chinook.db
SELECT *
FROM albums
LIMIT 10

AlbumId  Title                                  ArtistId
-------  -------------------------------------  --------
1        For Those About To Rock We Salute You  1
2        Balls to the Wall                      2
3        Restless and Wild                      2
4        Let There Be Rock                      1
5        Big Ones                               3
6        Jagged Little Pill                     4
7        Facelift                               5
8        Warner 25 Anos                         6
9        Plays Metallica By Four Cellos         7
10       Audioslave                             8

In [ ]:
#Select the first 10 entries from the artists table
%%script sqlite3 --column --header chinook.db
SELECT *
FROM artists
LIMIT 10

ArtistId  Name
--------  --------------------
1         AC/DC
2         Accept
3         Aerosmith
4         Alanis Morissette
5         Alice In Chains
6         Antônio Carlos Jobim
7         Apocalyptica
8         Audioslave
9         BackBeat
10        Billy Cobham

In [ ]:
#Select the first 10 entries from joining the artists and albums tables
%%script sqlite3 --column --header chinook.db
SELECT *
FROM artists
JOIN albums
ON artists.ArtistID = albums.ArtistID
LIMIT 10

ArtistId  Name                  AlbumId  Title                                  ArtistId
--------  --------------------  -------  -------------------------------------  --------
1         AC/DC                 1        For Those About To Rock We Salute You  1
2         Accept                2        Balls to the Wall                      2
2         Accept                3        Restless and Wild                      2
1         AC/DC                 4        Let There Be Rock                      1
3         Aerosmith             5        Big Ones                               3
4         Alanis Morissette     6        Jagged Little Pill                     4
5         Alice In Chains       7        Facelift                               5
6         Antônio Carlos Jobim  8        Warner 25 Anos                         6
7         Apocalyptica          9        Plays Metallica By Four Cellos         7
8         Audioslave            10       Audioslave                             8

In [ ]:
#Select albums by AC/DC
%%script sqlite3 --column --header chinook.db
SELECT *
FROM artists
JOIN albums
ON artists.ArtistID = albums.ArtistID
WHERE Name = 'AC/DC'
LIMIT 10

ArtistId  Name   AlbumId  Title                                  ArtistId
--------  -----  -------  -------------------------------------  --------
1         AC/DC  1        For Those About To Rock We Salute You  1
1         AC/DC  4        Let There Be Rock                      1

In [ ]:
#Select some fields from the employees table
%%script sqlite3 --column --header chinook.db
SELECT EmployeeId, LastName, FirstName, Title, ReportsTo
FROM employees

EmployeeId  LastName  FirstName  Title                ReportsTo
----------  --------  ---------  -------------------  ---------
1           Adams     Andrew     General Manager
2           Edwards   Nancy      Sales Manager        1
3           Peacock   Jane       Sales Support Agent  2
4           Park      Margaret   Sales Support Agent  2
5           Johnson   Steve      Sales Support Agent  2
6           Mitchell  Michael    IT Manager           1
7           King      Robert     IT Staff             6
8           Callahan  Laura      IT Staff             6

In [ ]:
#Select employees and their bosses
%%script sqlite3 --column --header chinook.db
SELECT emp1.EmployeeId, emp1.LastName, emp1.FirstName, emp1.Title, emp1.ReportsTo, emp2.EmployeeId, emp2.LastName, emp2.FirstName, emp2.ReportsTo
FROM employees as emp1
JOIN employees as emp2
ON emp1.ReportsTo = emp2.EmployeeID

EmployeeId  LastName  FirstName  Title                ReportsTo  EmployeeId  LastName  FirstName  ReportsTo
----------  --------  ---------  -------------------  ---------  ----------  --------  ---------  ---------
2           Edwards   Nancy      Sales Manager        1          1           Adams     Andrew
3           Peacock   Jane       Sales Support Agent  2          2           Edwards   Nancy      1
4           Park      Margaret   Sales Support Agent  2          2           Edwards   Nancy      1
5           Johnson   Steve      Sales Support Agent  2          2           Edwards   Nancy      1
6           Mitchell  Michael    IT Manager           1          1           Adams     Andrew
7           King      Robert     IT Staff             6          6           Mitchell  Michael    1
8           Callahan  Laura      IT Staff             6          6           Mitchell  Michael    1

In [ ]:
#The first three entries from a self cross join of employees
%%script sqlite3 --column --header chinook.db
SELECT *
FROM employees as emp1
JOIN employees as emp2
LIMIT 3

EmployeeId  LastName  FirstName  Title            ReportsTo  BirthDate            HireDate             Address              City      State  Country  PostalCode  Phone              Fax                Email                   EmployeeId  LastName  FirstName  Title                ReportsTo  BirthDate            HireDate             Address              City      State  Country  PostalCode  Phone              Fax                Email
----------  --------  ---------  ---------------  ---------  -------------------  -------------------  -------------------  --------  -----  -------  ----------  -----------------  -----------------  ----------------------  ----------  --------  ---------  -------------------  ---------  -------------------  -------------------  -------------------  --------  -----  -------  ----------  -----------------  -----------------  ----------------------
1           Adams     Andrew     General Manager             1962-02-18 00:00:00  2002-08-14 00:00:00  11120 Jasper Ave NW  Edmonton  AB     Canada   T5K 2N1     +1 (780) 428-9482  +1 (780) 428-3457  andrew@chinookcorp.com  1           Adams     Andrew     General Manager                 1962-02-18 00:00:00  2002-08-14 00:00:00  11120 Jasper Ave NW  Edmonton  AB     Canada   T5K 2N1     +1 (780) 428-9482  +1 (780) 428-3457  andrew@chinookcorp.com
1           Adams     Andrew     General Manager             1962-02-18 00:00:00  2002-08-14 00:00:00  11120 Jasper Ave NW  Edmonton  AB     Canada   T5K 2N1     +1 (780) 428-9482  +1 (780) 428-3457  andrew@chinookcorp.com  2           Edwards   Nancy      Sales Manager        1          1958-12-08 00:00:00  2002-05-01 00:00:00  825 8 Ave SW         Calgary   AB     Canada   T2P 2T3     +1 (403) 262-3443  +1 (403) 262-3322  nancy@chinookcorp.com
1           Adams     Andrew     General Manager             1962-02-18 00:00:00  2002-08-14 00:00:00  11120 Jasper Ave NW  Edmonton  AB     Canada   T5K 2N1     +1 (780) 428-9482  +1 (780) 428-3457  andrew@chinookcorp.com  3           Peacock   Jane       Sales Support Agent  2          1973-08-29 00:00:00  2002-04-01 00:00:00  1111 6 Ave SW        Calgary   AB     Canada   T2P 5M5     +1 (403) 262-3443  +1 (403) 262-6712  jane@chinookcorp.com

In [ ]:
#Select a few columns from a self cross joins of employees
%%script sqlite3 --column --header chinook.db
SELECT emp1.EmployeeID, emp1.FirstName, emp1.ReportsTo, emp2.EmployeeID, emp2.FirstName
FROM employees as emp1
JOIN employees as emp2

EmployeeId  FirstName  ReportsTo  EmployeeId  FirstName
----------  ---------  ---------  ----------  ---------
1           Andrew                1           Andrew
1           Andrew                2           Nancy
1           Andrew                3           Jane
1           Andrew                4           Margaret
1           Andrew                5           Steve
1           Andrew                6           Michael
1           Andrew                7           Robert
1           Andrew                8           Laura
2           Nancy      1          1           Andrew
2           Nancy      1          2           Nancy
2           Nancy      1          3           Jane
2           Nancy      1          4           Margaret
2           Nancy      1          5           Steve
2           Nancy      1          6           Michael
2           Nancy      1          7           Robert
2           Nancy      1          8           Laura
3           Jane       2          1           Andrew
3           Jane       2          2           Nancy
3           Jane       2          3           Jane
3           Jane       2          4           Margaret
3           Jane       2          5           Steve
3           Jane       2          6           Michael
3           Jane       2          7           Robert
3           Jane       2          8           Laura
4           Margaret   2          1           Andrew
4           Margaret   2          2           Nancy
4           Margaret   2          3           Jane
4           Margaret   2          4           Margaret
4           Margaret   2          5           Steve
4           Margaret   2          6           Michael
4           Margaret   2          7           Robert
4           Margaret   2          8           Laura
5           Steve      2          1           Andrew
5           Steve      2          2           Nancy
5           Steve      2          3           Jane
5           Steve      2          4           Margaret
5           Steve      2          5           Steve
5           Steve      2          6           Michael
5           Steve      2          7           Robert
5           Steve      2          8           Laura
6           Michael    1          1           Andrew
6           Michael    1          2           Nancy
6           Michael    1          3           Jane
6           Michael    1          4           Margaret
6           Michael    1          5           Steve
6           Michael    1          6           Michael
6           Michael    1          7           Robert
6           Michael    1          8           Laura
7           Robert     6          1           Andrew
7           Robert     6          2           Nancy
7           Robert     6          3           Jane
7           Robert     6          4           Margaret
7           Robert     6          5           Steve
7           Robert     6          6           Michael
7           Robert     6          7           Robert
7           Robert     6          8           Laura
8           Laura      6          1           Andrew
8           Laura      6          2           Nancy
8           Laura      6          3           Jane
8           Laura      6          4           Margaret
8           Laura      6          5           Steve
8           Laura      6          6           Michael
8           Laura      6          7           Robert
8           Laura      6          8           Laura

In [ ]:
#Select the first 10 entries from a self cross joins of employees
%%script sqlite3 --column --header chinook.db
SELECT emp1.EmployeeID, emp1.FirstName, emp1.ReportsTo, emp2.EmployeeID, emp2.FirstName
FROM employees as emp1
JOIN employees as emp2
LIMIT 10

EmployeeId  FirstName  ReportsTo  EmployeeId  FirstName
----------  ---------  ---------  ----------  ---------
1           Andrew                1           Andrew
1           Andrew                2           Nancy
1           Andrew                3           Jane
1           Andrew                4           Margaret
1           Andrew                5           Steve
1           Andrew                6           Michael
1           Andrew                7           Robert
1           Andrew                8           Laura
2           Nancy      1          1           Andrew
2           Nancy      1          2           Nancy

In [ ]:
#Select employees and their supervisors
%%script sqlite3 --column --header chinook.db
SELECT emp1.EmployeeID, emp1.FirstName, emp1.ReportsTo, emp2.EmployeeID, emp2.FirstName
FROM employees as emp1
JOIN employees as emp2
WHERE emp1.ReportsTo = emp2.EmployeeID
ORDER by emp1.EmployeeID

EmployeeId  FirstName  ReportsTo  EmployeeId  FirstName
----------  ---------  ---------  ----------  ---------
2           Nancy      1          1           Andrew
3           Jane       2          2           Nancy
4           Margaret   2          2           Nancy
5           Steve      2          2           Nancy
6           Michael    1          1           Andrew
7           Robert     6          6           Michael
8           Laura      6          6           Michael

### Building a complex join using a CTE

In [ ]:
#Select customers, their rep, and the rep's supervisor
# Uses CTEs
%%script sqlite3 --column --header chinook.db

with
emp as (
  SELECT EmployeeID, FirstName, Lastname, ReportsTo
  FROM employees
)

SELECT *
FROM emp
LIMIT 10

EmployeeID  FirstName  Lastname  ReportsTo
----------  ---------  --------  ---------
1           Andrew     Adams
2           Nancy      Edwards   1
3           Jane       Peacock   2
4           Margaret   Park      2
5           Steve      Johnson   2
6           Michael    Mitchell  1
7           Robert     King      6
8           Laura      Callahan  6

In [ ]:
#Select customers, their rep, and the rep's supervisor
# Uses CTEs
%%script sqlite3 --column --header chinook.db

with
emp as (
  SELECT EmployeeID, FirstName, Lastname, ReportsTo
  FROM employees
),
reps as (
  SELECT *
  FROM emp
)

SELECT *
FROM reps

EmployeeID  FirstName  Lastname  ReportsTo
----------  ---------  --------  ---------
1           Andrew     Adams
2           Nancy      Edwards   1
3           Jane       Peacock   2
4           Margaret   Park      2
5           Steve      Johnson   2
6           Michael    Mitchell  1
7           Robert     King      6
8           Laura      Callahan  6

In [ ]:
#Select customers, their rep, and the rep's supervisor
# Uses CTEs
%%script sqlite3 --column --header chinook.db

with
emp as (
  SELECT EmployeeID, FirstName, Lastname, ReportsTo
  FROM employees
),
reps as (
  SELECT EmployeeID, FirstName, Lastname, ReportsTo
  FROM emp
),
supervisors as (
  SELECT EmployeeID, FirstName, Lastname
  FROM emp
)

SELECT *
FROM supervisors

EmployeeID  FirstName  Lastname
----------  ---------  --------
1           Andrew     Adams
2           Nancy      Edwards
3           Jane       Peacock
4           Margaret   Park
5           Steve      Johnson
6           Michael    Mitchell
7           Robert     King
8           Laura      Callahan

In [ ]:
#Select customers, their rep, and the rep's supervisor
# Uses CTEs
%%script sqlite3 --column --header chinook.db

with
emp as (
  SELECT EmployeeID, FirstName, Lastname, ReportsTo
  FROM employees
),
reps as (
  SELECT EmployeeID, FirstName, Lastname, ReportsTo
  FROM emp
),
supervisors as (
  SELECT EmployeeID, FirstName, Lastname
  FROM emp
),
workers as (
  SELECT r.EmployeeID as "EmpID", r.Firstname as "Rep", r.ReportsTo as "ReportID", s.EmployeeID as "SuperID", s.FirstName as "Supervisor"
  FROM reps as r
  JOIN supervisors as s
  WHERE r.ReportsTo = s.EmployeeID
)

SELECT *
FROM workers

EmpID  Rep       ReportID  SuperID  Supervisor
-----  --------  --------  -------  ----------
2      Nancy     1         1        Andrew
3      Jane      2         2        Nancy
4      Margaret  2         2        Nancy
5      Steve     2         2        Nancy
6      Michael   1         1        Andrew
7      Robert    6         6        Michael
8      Laura     6         6        Michael

In [ ]:
#Select customers, their rep, and the rep's supervisor
# Uses CTEs
%%script sqlite3 --column --header chinook.db

with
emp as (
  SELECT EmployeeID, FirstName, Lastname, ReportsTo
  FROM employees
),
reps as (
  SELECT EmployeeID, FirstName, Lastname, ReportsTo
  FROM emp
),
supervisors as (
  SELECT EmployeeID, FirstName, Lastname
  FROM emp
),
workers as (
  SELECT r.EmployeeID as "EmpID", r.Firstname as "Rep", r.ReportsTo as "ReportID", s.EmployeeID as "SuperID", s.FirstName as "Supervisor"
  FROM reps as r
  JOIN supervisors as s
  WHERE r.ReportsTo = s.EmployeeID
),
cust as (
  SELECT CustomerID, FirstName as "Customer", SupportRepID
  FROM customers
)

SELECT *
FROM cust
LIMIT 10

CustomerID  Customer   SupportRepID
----------  ---------  ------------
1           Luís       3
2           Leonie     5
3           François   3
4           Bjørn      4
5           František  4
6           Helena     5
7           Astrid     5
8           Daan       4
9           Kara       4
10          Eduardo    4

In [ ]:
#Select customers, their rep, and the rep's supervisor
# Uses CTEs
%%script sqlite3 --column --header chinook.db

with
emp as (
  SELECT EmployeeID, FirstName, Lastname, ReportsTo, Title
  FROM employees
),
reps as (
  SELECT EmployeeID, FirstName, Lastname, ReportsTo
  FROM emp
  WHERE Title = "Sales Support Agent"
),
supervisors as (
  SELECT EmployeeID, FirstName, Lastname
  FROM emp
  WHERE Title != "Sales Support Agent"
),
workers as (
  SELECT r.EmployeeID as "EmpID", r.Firstname as "Rep", r.ReportsTo as "ReportID", s.EmployeeID as "SuperID", s.FirstName as "Supervisor"
  FROM reps as r
  JOIN supervisors as s
  WHERE r.ReportsTo = s.EmployeeID
),
cust as (
  SELECT CustomerID, FirstName as "Customer", SupportRepID
  FROM customers
),
cust_rep_super as (
  SELECT Customer, Rep, Supervisor
  -- SELECT *
  FROM cust
  JOIN workers
  WHERE SupportRepID = EmpID
)

SELECT *
FROM cust_rep_super
-- LIMIT 10

Customer   Rep       Supervisor
---------  --------  ----------
Luís       Jane      Nancy
François   Jane      Nancy
Roberto    Jane      Nancy
Jennifer   Jane      Nancy
Michelle   Jane      Nancy
Tim        Jane      Nancy
Frank      Jane      Nancy
Robert     Jane      Nancy
Edward     Jane      Nancy
Ellie      Jane      Nancy
Fynn       Jane      Nancy
Niklas     Jane      Nancy
Wyatt      Jane      Nancy
Isabelle   Jane      Nancy
Terhi      Jane      Nancy
Ladislav   Jane      Nancy
Hugh       Jane      Nancy
Emma       Jane      Nancy
Phil       Jane      Nancy
Manoj      Jane      Nancy
Puja       Jane      Nancy
Bjørn      Margaret  Nancy
František  Margaret  Nancy
Daan       Margaret  Nancy
Kara       Margaret  Nancy
Eduardo    Margaret  Nancy
Fernanda   Margaret  Nancy
Frank      Margaret  Nancy
Dan        Margaret  Nancy
Heather    Margaret  Nancy
John       Margaret  Nancy
Richard    Margaret  Nancy
Patrick    Margaret  Nancy
Aaron      Margaret  Nancy
João       Margaret  Nancy
Madalena   Margaret  Nancy
Camille    Margaret  Nancy
Dominique  Margaret  Nancy
Stanisław  Margaret  Nancy
Mark       Margaret  Nancy
Diego      Margaret  Nancy
Leonie     Steve     Nancy
Helena     Steve     Nancy
Astrid     Steve     Nancy
Alexandre  Steve     Nancy
Mark       Steve     Nancy
Jack       Steve     Nancy
Kathy      Steve     Nancy
Victor     Steve     Nancy
Julia      Steve     Nancy
Martha     Steve     Nancy
Hannah     Steve     Nancy
Marc       Steve     Nancy
Lucas      Steve     Nancy
Johannes   Steve     Nancy
Enrique    Steve     Nancy
Joakim     Steve     Nancy
Steve      Steve     Nancy
Luis       Steve     Nancy

## Your Turn

- How many unique albums are in the Tracks table?
- How many tracks are on the album with AlbumID 1?
- Do the totals in the Invoices table add up to the lineitems in the Invoice_Items table?

Don't forget to add this magic to the top of your code cell or use Python with a sqlite connection.

```bash
%%script sqlite3 --column --header chinook.db
```

```bash
import sqlite3 as db
import pandas as pd

query = '''
  SELECT ...
'''

with db.connect("chinook.db") as db_con:
  df = pd.read_sql_query( query , db_con )
df

```

In [ ]:
import sqlite3 as db
import pandas as pd

In [ ]:
#How many unique albums are in the Tracks table?
%%script sqlite3 --column --header chinook.db
SELECT count(distinct AlbumID)
FROM tracks

count(distinct AlbumID)
-----------------------
347

In [ ]:
#How many tracks are on the album with AlbumID 1?
%%script sqlite3 --column --header chinook.db
SELECT AlbumId, count(1) as 'number of tracks'
FROM tracks
WHERE AlbumId = 1
group by AlbumId

AlbumId  number of tracks
-------  ----------------
1        10

In [ ]:
#Do the totals in the Invoices table add up to the lineitems in the Invoice_Items table?
%%script sqlite3 --column --header chinook.db
WITH
  invs as(
    select sum(UnitPrice)
  from
    invoice_items
  )

SELECT *
FROM invs
LIMIT 10

sum(UnitPrice)
----------------
2328.59999999996

In [ ]:
%%script sqlite3 --column --header chinook.db
WITH
  invs as(
    select sum(UnitPrice)
  from
    invoices
  )

SELECT *
FROM invs

Error: near line 1: in prepare, no such column: UnitPrice (1)

CalledProcessError: Command 'b'WITH\n  invs as(\n    select sum(UnitPrice)\n  from\n    invoices\n  )\n\nSELECT *\nFROM invs\n'' returned non-zero exit status 1.

## Calculating some descriptive statistics using CTEs

In [ ]:
%%script sqlite3 --column --header chinook.db

WITH
  -- vals       as ( SELECT unitprice as value                 FROM Invoice_items ),
  vals       as ( SELECT Total as value                        FROM Invoices ),

  -- calculate descriptive statistics
  count_mean as ( SELECT count(1) as n, max(value) as max, min(value) as min, AVG(value) as mean     from vals ),
  delta      as ( SELECT value, n, mean, value - mean as delta FROM vals, count_mean ),
  delta2     as ( SELECT power(delta, 2) as delta2             FROM delta ),
  delta2sum  as ( SELECT sum(delta2) as delta2sum              FROM delta2 ),
  variance   as ( SELECT delta2sum/(n-1) as variance           FROM delta2sum, count_mean ),
  stdev      as ( SELECT power(variance, 0.5) as stdev         FROM variance ),
  desc_stats as ( SELECT *                                     FROM count_mean, stdev, delta2sum, variance )

SELECT
  *
FROM
  desc_stats
;