<a href="https://colab.research.google.com/github/stephanie465337/Data-Science-Portfolio-C21/blob/main/NotebookLM/Module1/6a_More_Indexing_in_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# More Indexing in Pandas

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Create a data frame
my_dict = {
    'Name': ['Mary', 'Joe', 'Roger', 'Sarah', 'Mike', 'Phil'],
    'Age': [20, 45, 32, 58, 39, 42],
    'City': ['Albuquerque', 'Rio Rancho', 'Santa Fe', 'Taos', 'Albuquerque', 'Placitas'],
'Occupation': ['student', 'doctor', 'data scientist', 'general contractor', 'student', 'manager']
}
people_df = pd.DataFrame(my_dict)
people_df

    Name  Age         City          Occupation
0   Mary   20  Albuquerque             student
1    Joe   45   Rio Rancho              doctor
2  Roger   32     Santa Fe      data scientist
3  Sarah   58         Taos  general contractor
4   Mike   39  Albuquerque             student
5   Phil   42     Placitas             manager

## Review of column and row indexing

### Using column names

In [ ]:
#Column indexing
people_df['Name']
#This is a DataSeries

0     Mary
1      Joe
2    Roger
3    Sarah
4     Mike
5     Phil
Name: Name, dtype: object

In [ ]:
#Column indexing
people_df[['Name']]
#This is a DataFrame recognized by the table icon in the top right corner

    Name
0   Mary
1    Joe
2  Roger
3  Sarah
4   Mike
5   Phil

In [ ]:
list_of_columns = ['Name']
people_df[ list_of_columns ]

    Name
0   Mary
1    Joe
2  Roger
3  Sarah
4   Mike
5   Phil

In [ ]:
#people_df['Name', 'Age']
people_df[['Name', 'Age', 'Name']]

    Name  Age   Name
0   Mary   20   Mary
1    Joe   45    Joe
2  Roger   32  Roger
3  Sarah   58  Sarah
4   Mike   39   Mike
5   Phil   42   Phil

In [ ]:
#Multiple column indexing
people_df[['Name', 'Age']]

    Name  Age
0   Mary   20
1    Joe   45
2  Roger   32
3  Sarah   58
4   Mike   39
5   Phil   42

In [ ]:
#Multiple column indexing
people_df[['Name', 'Age', 'Name']]

    Name  Age   Name
0   Mary   20   Mary
1    Joe   45    Joe
2  Roger   32  Roger
3  Sarah   58  Sarah
4   Mike   39   Mike
5   Phil   42   Phil

In [ ]:
name_index = people_df.columns[::-2]
name_index

Index(['Occupation', 'Age'], dtype='object')

In [ ]:
people_df[name_index]

           Occupation  Age         City
0             student   20  Albuquerque
1              doctor   45   Rio Rancho
2      data scientist   32     Santa Fe
3  general contractor   58         Taos
4             student   39  Albuquerque
5             manager   42     Placitas

In [ ]:
name_index = pd.Series(people_df.columns).sample(n=3)
name_index

3    Occupation
0          Name
2          City
dtype: object

In [ ]:
people_df[name_index]

           Occupation   Name         City
0             student   Mary  Albuquerque
1              doctor    Joe   Rio Rancho
2      data scientist  Roger     Santa Fe
3  general contractor  Sarah         Taos
4             student   Mike  Albuquerque
5             manager   Phil     Placitas

### Columns with iloc indices

iloc = interger locations

In [ ]:
#Column indexing using .iloc - indexing
people_df.iloc[:,0]

0     Mary
1      Joe
2    Roger
3    Sarah
4     Mike
5     Phil
Name: Name, dtype: object

In [ ]:
#Column indexing using .iloc - slicing
people_df.iloc[:,0::2]

    Name         City
0   Mary  Albuquerque
1    Joe   Rio Rancho
2  Roger     Santa Fe
3  Sarah         Taos
4   Mike  Albuquerque
5   Phil     Placitas

In [ ]:
for i in list(enumerate(people_df.columns)):
  print(i)

(0, 'Name')
(1, 'Age')
(2, 'City')
(3, 'Occupation')

In [ ]:
# Column indexing using .iloc - list
people_df.iloc[ : , [1,0,3,2,3]]

   Age   Name          Occupation         City          Occupation
0   20   Mary             student  Albuquerque             student
1   45    Joe              doctor   Rio Rancho              doctor
2   32  Roger      data scientist     Santa Fe      data scientist
3   58  Sarah  general contractor         Taos  general contractor
4   39   Mike             student  Albuquerque             student
5   42   Phil             manager     Placitas             manager

### Rows with indices

In [ ]:
#Reassign index
people_df.index =  list("abcdef")
people_df

    Name  Age         City          Occupation
a   Mary   20  Albuquerque             student
b    Joe   45   Rio Rancho              doctor
c  Roger   32     Santa Fe      data scientist
d  Sarah   58         Taos  general contractor
e   Mike   39  Albuquerque             student
f   Phil   42     Placitas             manager

In [ ]:
#Row indexing using .loc
people_df.loc["b"]

Name                 Joe
Age                   45
City          Rio Rancho
Occupation        doctor
Name: b, dtype: object

In [ ]:
#Row indexing using .iloc
people_df.iloc[1]

Name                 Joe
Age                   45
City          Rio Rancho
Occupation        doctor
Name: b, dtype: object

In [ ]:
#Multiple rows - slicing
people_df.loc["a":"c"]

    Name  Age         City      Occupation
a   Mary   20  Albuquerque         student
b    Joe   45   Rio Rancho          doctor
c  Roger   32     Santa Fe  data scientist

In [ ]:
people_df.iloc[0:2]

   Name  Age         City Occupation
a  Mary   20  Albuquerque    student
b   Joe   45   Rio Rancho     doctor

In [ ]:
#Selecting rows in any order - list
people_df.loc[["a","d","d","c","b"]]

    Name  Age         City          Occupation
a   Mary   20  Albuquerque             student
d  Sarah   58         Taos  general contractor
d  Sarah   58         Taos  general contractor
c  Roger   32     Santa Fe      data scientist
b    Joe   45   Rio Rancho              doctor

In [ ]:
idx = [0,3,3,2,1]
idx

[0, 3, 3, 2, 1]

In [ ]:
people_df.iloc[idx, :]

    Name  Age         City          Occupation
a   Mary   20  Albuquerque             student
d  Sarah   58         Taos  general contractor
d  Sarah   58         Taos  general contractor
c  Roger   32     Santa Fe      data scientist
b    Joe   45   Rio Rancho              doctor

### Indexing for a single entry

In [ ]:
#Row and column indexing
people_df['Name'].iloc[0]

'Mary'

In [ ]:
#Another way
people_df['Name'].loc["a"]

'Mary'

In [ ]:
#Another way
people_df.loc["a"]['Name']

'Mary'

In [ ]:
#Another way
people_df.loc["a"].loc['Name']

'Mary'

In [ ]:
#Another way
people_df.loc["a",'Name']

'Mary'

In [ ]:
#Another way
people_df.iloc[0,0]

'Mary'

In [ ]:
#Another way
people_df.iloc[0].iloc[0]

'Mary'

In [ ]:
#Another way
people_df.iloc[0].loc["Name"]

'Mary'

## Attribute Access

> WARNING: Do Not Use This

You can access columns in a dataframe as attributes. Note: there are a few cases when the attribute will not work, such as if your column is named a number (e.g., 1) or if it is named after an existing method (e.g., min).

In [ ]:
people_df

    Name  Age         City          Occupation
a   Mary   20  Albuquerque             student
b    Joe   45   Rio Rancho              doctor
c  Roger   32     Santa Fe      data scientist
d  Sarah   58         Taos  general contractor
e   Mike   39  Albuquerque             student
f   Phil   42     Placitas             manager

In [ ]:
people_df.Name

a     Mary
b      Joe
c    Roger
d    Sarah
e     Mike
f     Phil
Name: Name, dtype: object

In [ ]:
people_df.Name.loc["a"]

'Mary'

In [ ]:
people_df["shape"] = 10
people_df

    Name  Age         City          Occupation  shape
a   Mary   20  Albuquerque             student     10
b    Joe   45   Rio Rancho              doctor     10
c  Roger   32     Santa Fe      data scientist     10
d  Sarah   58         Taos  general contractor     10
e   Mike   39  Albuquerque             student     10
f   Phil   42     Placitas             manager     10

In [ ]:
people_df.shape

(6, 5)

In [ ]:
people_df["shape"]

a    10
b    10
c    10
d    10
e    10
f    10
Name: shape, dtype: int64

## Boolean Indexing

In [ ]:
filter = (people_df['Age'] > 40) #Create a filter
filter

a    False
b     True
c    False
d     True
e    False
f     True
Name: Age, dtype: bool

In [ ]:
people_df[filter] #Use that filter to index

    Name  Age        City          Occupation  shape
b    Joe   45  Rio Rancho              doctor     10
d  Sarah   58        Taos  general contractor     10
f   Phil   42    Placitas             manager     10

In [ ]:
#Another example - people from Albuquerque
filter = (people_df['City'] == 'Albuquerque')
filter

a     True
b    False
c    False
d    False
e     True
f    False
Name: City, dtype: bool

In [ ]:
people_df[filter] #Use that filter to index

   Name  Age         City Occupation  shape
a  Mary   20  Albuquerque    student     10
e  Mike   39  Albuquerque    student     10

In [ ]:
#A third example! People from albuquerque or people who are doctors
filter1 = (people_df['City'] == 'Albuquerque')
filter1

a     True
b    False
c    False
d    False
e     True
f    False
Name: City, dtype: bool

In [ ]:
filter2 = (people_df['Occupation'] == 'doctor')
filter2

a    False
b     True
c    False
d    False
e    False
f    False
Name: Occupation, dtype: bool

In [ ]:
filter = filter1 | filter2
filter

a     True
b     True
c    False
d    False
e     True
f    False
dtype: bool

In [ ]:
#Verify
pd.concat([filter1, filter2, filter, people_df], axis='columns')

    City Occupation      0   Name  Age         City          Occupation  shape
a   True      False   True   Mary   20  Albuquerque             student     10
b  False       True   True    Joe   45   Rio Rancho              doctor     10
c  False      False  False  Roger   32     Santa Fe      data scientist     10
d  False      False  False  Sarah   58         Taos  general contractor     10
e   True      False   True   Mike   39  Albuquerque             student     10
f  False      False  False   Phil   42     Placitas             manager     10

In [ ]:
people_df[filter] #Use that filter to index

   Name  Age         City Occupation  shape
a  Mary   20  Albuquerque    student     10
b   Joe   45   Rio Rancho     doctor     10
e  Mike   39  Albuquerque    student     10

In [ ]:
#Negating
filter = (people_df['Name'] == 'Mary')
filter

a     True
b    False
c    False
d    False
e    False
f    False
Name: Name, dtype: bool

In [ ]:
#Verify
pd.concat([filter, ~filter, people_df], axis='columns')

    Name   Name   Name  Age         City          Occupation  shape
a   True  False   Mary   20  Albuquerque             student     10
b  False   True    Joe   45   Rio Rancho              doctor     10
c  False   True  Roger   32     Santa Fe      data scientist     10
d  False   True  Sarah   58         Taos  general contractor     10
e  False   True   Mike   39  Albuquerque             student     10
f  False   True   Phil   42     Placitas             manager     10

In [ ]:
people_df[~filter] #Use that filter to index

    Name  Age         City          Occupation  shape
b    Joe   45   Rio Rancho              doctor     10
c  Roger   32     Santa Fe      data scientist     10
d  Sarah   58         Taos  general contractor     10
e   Mike   39  Albuquerque             student     10
f   Phil   42     Placitas             manager     10

In [ ]:
people_df[people_df['Name'] != 'Mary']

    Name  Age         City          Occupation  shape
b    Joe   45   Rio Rancho              doctor     10
c  Roger   32     Santa Fe      data scientist     10
d  Sarah   58         Taos  general contractor     10
e   Mike   39  Albuquerque             student     10
f   Phil   42     Placitas             manager     10

## Indexing w/ Isin

In [ ]:
people_df['City']

a    Albuquerque
b     Rio Rancho
c       Santa Fe
d           Taos
e    Albuquerque
f       Placitas
Name: City, dtype: object

In [ ]:
filter = (people_df['City'].isin(['Rio Rancho', 'Santa Fe', 'Taos'])) #Create a filter
filter

a    False
b     True
c     True
d     True
e    False
f    False
Name: City, dtype: bool

In [ ]:
#Verify
pd.concat([filter, people_df], axis='columns')

    City   Name  Age         City          Occupation  shape
a  False   Mary   20  Albuquerque             student     10
b   True    Joe   45   Rio Rancho              doctor     10
c   True  Roger   32     Santa Fe      data scientist     10
d   True  Sarah   58         Taos  general contractor     10
e  False   Mike   39  Albuquerque             student     10
f  False   Phil   42     Placitas             manager     10

In [ ]:
people_df[filter] #Use that filter to index

    Name  Age        City          Occupation  shape
b    Joe   45  Rio Rancho              doctor     10
c  Roger   32    Santa Fe      data scientist     10
d  Sarah   58        Taos  general contractor     10

## Numpy Where
The numpy where method can be useful to find rows that correspond to a particular conditional statement.

In [ ]:
import numpy as np

In [ ]:
filter = (people_df['City'] == 'Albuquerque')
filter

a     True
b    False
c    False
d    False
e     True
f    False
Name: City, dtype: bool

In [ ]:
where_index = np.where(filter)
where_index, where_index[0]

((array([0, 4]),), array([0, 4]))

In [ ]:
where_index[0][1]

np.int64(4)

In [ ]:
people_df

    Name  Age         City          Occupation  shape
a   Mary   20  Albuquerque             student     10
b    Joe   45   Rio Rancho              doctor     10
c  Roger   32     Santa Fe      data scientist     10
d  Sarah   58         Taos  general contractor     10
e   Mike   39  Albuquerque             student     10
f   Phil   42     Placitas             manager     10

In [ ]:
people_df.iloc[where_index[0]]

   Name  Age         City Occupation  shape
a  Mary   20  Albuquerque    student     10
e  Mike   39  Albuquerque    student     10

In [ ]:
people_df.drop(people_df.index[where_index[0]])

    Name  Age        City          Occupation  shape
b    Joe   45  Rio Rancho              doctor     10
c  Roger   32    Santa Fe      data scientist     10
d  Sarah   58        Taos  general contractor     10
f   Phil   42    Placitas             manager     10

In [ ]:
people_df_no_abq = people_df.drop(people_df.index[where_index[0]])
people_df_no_abq

    Name  Age        City          Occupation  shape
b    Joe   45  Rio Rancho              doctor     10
c  Roger   32    Santa Fe      data scientist     10
d  Sarah   58        Taos  general contractor     10
f   Phil   42    Placitas             manager     10

In [ ]:
where_index[0][0]

np.int64(0)

In [ ]:
people_df

    Name  Age         City          Occupation  shape
a   Mary   20  Albuquerque             student     10
b    Joe   45   Rio Rancho              doctor     10
c  Roger   32     Santa Fe      data scientist     10
d  Sarah   58         Taos  general contractor     10
e   Mike   39  Albuquerque             student     10
f   Phil   42     Placitas             manager     10

In [ ]:
people_df.iloc[where_index[0][0]]

Name                 Mary
Age                    20
City          Albuquerque
Occupation        student
shape                  10
Name: a, dtype: object

In [ ]:
people_df_no_abq

    Name  Age        City          Occupation  shape
b    Joe   45  Rio Rancho              doctor     10
c  Roger   32    Santa Fe      data scientist     10
d  Sarah   58        Taos  general contractor     10
f   Phil   42    Placitas             manager     10

In [ ]:
people_df_no_abq.iloc[where_index[0][0]]

Name                 Joe
Age                   45
City          Rio Rancho
Occupation        doctor
shape                 10
Name: b, dtype: object

In [ ]:
people_df_no_abq.reset_index()

  index   Name  Age        City          Occupation  shape
0     b    Joe   45  Rio Rancho              doctor     10
1     c  Roger   32    Santa Fe      data scientist     10
2     d  Sarah   58        Taos  general contractor     10
3     f   Phil   42    Placitas             manager     10

In [ ]:
people_df_no_abq

    Name  Age        City          Occupation  shape
b    Joe   45  Rio Rancho              doctor     10
c  Roger   32    Santa Fe      data scientist     10
d  Sarah   58        Taos  general contractor     10
f   Phil   42    Placitas             manager     10

In [ ]:
people_df_no_abq.reset_index(drop = True)

    Name  Age        City          Occupation  shape
0    Joe   45  Rio Rancho              doctor     10
1  Roger   32    Santa Fe      data scientist     10
2  Sarah   58        Taos  general contractor     10
3   Phil   42    Placitas             manager     10

In [ ]:
people_df_no_abq

    Name  Age        City          Occupation  shape
b    Joe   45  Rio Rancho              doctor     10
c  Roger   32    Santa Fe      data scientist     10
d  Sarah   58        Taos  general contractor     10
f   Phil   42    Placitas             manager     10

In [ ]:
people_df_no_abq.reset_index(drop = True, inplace = True)
people_df_no_abq

    Name  Age        City          Occupation  shape
0    Joe   45  Rio Rancho              doctor     10
1  Roger   32    Santa Fe      data scientist     10
2  Sarah   58        Taos  general contractor     10
3   Phil   42    Placitas             manager     10

## Random Sampling in Pandas

In [ ]:
people_df

    Name  Age         City          Occupation  shape
a   Mary   20  Albuquerque             student     10
b    Joe   45   Rio Rancho              doctor     10
c  Roger   32     Santa Fe      data scientist     10
d  Sarah   58         Taos  general contractor     10
e   Mike   39  Albuquerque             student     10
f   Phil   42     Placitas             manager     10

In [ ]:
#Take a random sample of size 3
people_df.sample(n = 3)

   Name  Age         City Occupation  shape
e  Mike   39  Albuquerque    student     10
a  Mary   20  Albuquerque    student     10
f  Phil   42     Placitas    manager     10

In [ ]:
#Take a random proportion
people_df.sample(frac = 1/3)

    Name  Age         City          Occupation  shape
e   Mike   39  Albuquerque             student     10
d  Sarah   58         Taos  general contractor     10

In [ ]:
people_df.groupby('City').sample(n = 1)

    Name  Age         City          Occupation  shape
a   Mary   20  Albuquerque             student     10
f   Phil   42     Placitas             manager     10
b    Joe   45   Rio Rancho              doctor     10
c  Roger   32     Santa Fe      data scientist     10
d  Sarah   58         Taos  general contractor     10

In [ ]:
#Take a randoom sample but set the seed for reproducibility
people_df.sample(n = 3, random_state = 42)

   Name  Age         City Occupation  shape
a  Mary   20  Albuquerque    student     10
b   Joe   45   Rio Rancho     doctor     10
f  Phil   42     Placitas    manager     10

In [ ]:
people_df.sample(n=2, axis="columns")

          City  Age
a  Albuquerque   20
b   Rio Rancho   45
c     Santa Fe   32
d         Taos   58
e  Albuquerque   39
f     Placitas   42

In [ ]:
people_df.sample(n=2, axis="columns").sample(n=2)

   Age Occupation
b   45     doctor
f   42    manager